- src/index.js
> Drag to move selection

- src/index.js
Fix #11 
The selection wasn't working properly after resolving conflct for the merge of [this PR](https://github.com/vjeux/excalibur/pull/28).
> Fixes selecting an element

- src/index.tsx
> Copy paste

- src/index.tsx
Instead of just checking if the click is within the bounds, this check if the click is within 10 pixels of a segment that defines the shape. This should give better hit detection.
Note: the ellipsis one is not good. But I'm not motivated enough to find a good approximation for the distance between a point and ellipsis
Fixed #9
> Path-dependent hit test

- src/index.tsx
This PR is the first step towards getting closer to making elements not a global anymore.
This moves the logic of drawing to the canvas to componentDidUpdate and instead of calling drawScene, we can just do this.forceUpdate() to trigger a re-render and therefore a componentDidUpdate.
The previous PR broke copy and paste, I fixed it by putting the handler in the div above.
I made sure that export to png was still working. I tried a bunch of edge cases and everything seems to be working fine.
> Remove drawScene

- src/index.tsx
The new feature that allows setting canvas BG resulted in regression for export, where it always exported the bg even if unchecked.
In this PR I've factored out the canvas rendering function from `componentDidUpdate` so that we can easily call it in the export helper.
The fix hacks it by doing 2 extra rerenders.
> fix regression of always exporting bg

- src/index.tsx
As @vjeux identified an unexpected behavior with each element's color(see comment here: https://github.com/excalidraw/excalibur/pull/53#discussion_r362700722), this PR fixes this bug by making the stroke and the background color properties of the item itself instead of being global.
> Fix Global Item Colors

- src/styles.css
Removes the margin from body and adds it to the controls' container to add some whitespace.
> Fixes body margin

- .gitignore
- src/index.tsx
- Adds support for deleting elements by pressing the 'delete' key
- Assigns 'magic numbers' and key names to named variables/properties
> Add support for 'delete' key

- src/index.tsx
Since we can already choose colors for the shapes, I think it'd be cool to make it possible to pick a color for the text too.
Actually, this should be introduced by https://github.com/excalidraw/excalibur/pull/54
> Add Text Colors

- public/index.html
- src/index.tsx
Due to the project renaming, this PR also renames some parts of the code that was using the old name
> Rename Excalibur to Excalidraw

- public/index.html
- src/styles.css
> Add preload to font

- .gitignore
- src/index.tsx
- src/styles.css
> Add shortcuts

- README.md
This PR adds a minimal readme 
https://github.com/excalidraw/excalidraw/issues/61
> [WIP] Adding README

- public/index.html
Happy to give access to whoever wants to see the data :)
All the formatting changes are due to saving with prettier.
> Add google analytics tag

- src/index.tsx
Don't ask me how it works, but it does :p
> Distance between point and ellipsis

- public/index.html
This adds a link to the github repo at the top right of the screen. I'm not 100% convinced but I feel like it's worth shipping for now. Thoughts welcome!
Fixes #77
> Add github corner

- src/index.tsx
> Update on resize

- package-lock.json
- package.json
- src/index.tsx
- src/styles.css
> Side panel

- src/index.tsx
- src/zindex.test.ts
- src/zindex.ts
> Send to back

- src/zindex.test.ts
- src/zindex.ts
This just adds the raw logic. We'll need to wire it up to the UI afterwards.
> Add support for forward

- src/index.tsx
> Wire up forward

- src/index.tsx
Fixes #91 
I think we react only on left mouse button
> Fix: right clicking while on the canvas messes up selection

- src/index.tsx
fixes https://github.com/excalidraw/excalidraw/issues/32
Fixes dragging issues like:
> ensure mouse drag doesn't select texts (#32)

- src/styles.css
Just a little bit of ux enhacement
> Improve Buttons UX

- src/index.tsx
This needs to be done from front to back instead of back to front
Fixes #115
> Fix hit testing

- src/index.tsx
This way we can make it const and people can accidentally make a stale reference to it.
> Prevent re-assignment of elements

- src/index.tsx
fixes https://github.com/excalidraw/excalidraw/issues/118
changes as per issue:
- make bg export by default
- removed padding option (defaults to `10px`)
- removed `exportVisibleOnly` option since it no longer makes sense
additional:
- instead of `context`, we're now passing `canvas` to the `renderScene`
- made `renderScene` more configurable so that we can use it in export
If anything doesn't work, or changes request, I won't be available for next ~12-14 hrs (feel free to modify).
> fix export to support scrolling

- package.json
- src/index.tsx
- src/styles.scss
> Inline font-awesome icons

- package-lock.json
- package.json
> Removed lodash

- src/index.tsx
> Resize with negative width or height

- src/index.tsx
The quality is muuuch better on my macbook pro!
Note that this doesn't increase the size of the exported canvas, only the visible one.
Fixes #105
> Use device pixel ratio

- src/index.tsx
The joys of event handling :(
Fixes #140
> Fix missing mouseup

- src/index.tsx
And reset it back to default on mouse up.
Fixes #102
> Set the cursor to 'crosshair' when expected to draw

- public/index.html
This got hidden after the layout change
> Move octocat to the front

- src/index.tsx
> Square selection should work in all directions

- src/index.tsx
> Adjust arrow start/end points

- package-lock.json
- package.json
- src/index.tsx
- src/styles.scss
Disgusting POC of Sketch-like color pickers. Lmk if I should keep going and refactor
> Improved color picker

- src/index.tsx
- src/roundRect.ts
Little improvements for scrollbars
> Better scrollbars

- src/index.tsx
- src/styles.scss
> Adding diamond shape

- src/index.tsx
- src/styles.scss
Option to change some styles from the elements, like stroke width, fill style, roughness, and update the stroke color and background color.
> Change styles

- src/index.tsx
> Double click to add text

- src/index.tsx
- src/styles.scss
Sadly there's currently a bug with codesandbox that doesn't let me update a PR. This is #189 being rebased.
> Improve Color Picker *2

- src/index.tsx
> Implement redo

- .gitignore
- src/element/bounds.ts
- src/element/collision.ts
- src/element/generateDraw.ts
- src/element/handlerRectangles.ts
- src/element/index.ts
- src/element/newElement.ts
- src/element/resizeTest.ts
- src/element/typeChecks.ts
- src/element/types.ts
- src/index.tsx
- src/math.ts
- src/scene/types.ts
This is one part of the PR regarding extracting element functions into their respective modules: #204. For the time being please keep the other PR open.
> Extract element functions into modules

- src/index.tsx
- src/scene/comparisons.ts
- src/scene/createScene.ts
- src/scene/data.ts
- src/scene/index.ts
- src/scene/render.ts
- src/scene/roundRect.ts
- src/scene/scrollbars.ts
- src/scene/selection.ts
- src/scene/types.ts
- src/types.ts
- src/utils.ts
This is the second extraction based on #204. In this PR, I am also changing the signatures of the functions by adding `elements` as an argument; so that, these functions do not rely on the global `elements` array.
> Extract scene functions and small utilities to their respective modules

- src/components/ButtonSelect.tsx
- src/components/ColorPicker.tsx
- src/components/EditableText.tsx
- src/index.tsx
- src/shapes.tsx
Part of the extraction process related to #202 and #204
> Extract components and shapes into their respective modules

- src/index.tsx
#164  added in the commit. 
- Copy something
- Scroll far enough left and/or down so you don't see the original thing
- Paste it
Now it paste in the viewport.
> paste inside the viewport

- src/index.tsx
> implement shift+resize for all sides

- src/index.tsx
Fixes https://github.com/excalidraw/excalidraw/issues/209
> Copy and paste styles

- src/components/ColorPicker.tsx
- src/components/ContextMenu.css
- src/components/ContextMenu.tsx
- src/components/Popover.tsx
- src/index.tsx
- src/styles.scss
Fixes #193 
Note, **paste** command can not be called programmatically in safari and firefox (without setting the corresponding flag).
> Context menu with some commands

- src/element/index.ts
- src/element/textWysiwyg.tsx
- src/index.tsx
> Wysiwyg text

- src/index.tsx
- src/scene/data.ts
- src/scene/index.ts
Fixes #203 
I had to debounce saving function, because it was too slow =( 
[Here is an example](https://excalidraw-5hp6n0em8.now.sh/#W3sidHlwZSI6ImVsbGlwc2UiLCJ4IjotMjEwLCJ5IjoxMjksIndpZHRoIjozMTUsImhlaWdodCI6MjU2LCJpc1NlbGVjdGVkIjpmYWxzZSwic3Ryb2tlQ29sb3IiOiIjMDAwMDAwIiwiYmFja2dyb3VuZENvbG9yIjoiI2ZjYjkwMCIsInNlZWQiOjcwOTU1MDQwNCwiZmlsbFN0eWxlIjoiaGFjaHVyZSIsInN0cm9rZVdpZHRoIjoxLCJyb3VnaG5lc3MiOjEsIm9wYWNpdHkiOjEwMH0seyJ0eXBlIjoiZWxsaXBzZSIsIngiOi0xNjksInkiOjI1Mywid2lkdGgiOjMzLCJoZWlnaHQiOi0zMiwiaXNTZWxlY3RlZCI6ZmFsc2UsInN0cm9rZUNvbG9yIjoiIzAwMDAwMCIsImJhY2tncm91bmRDb2xvciI6IiMwNjkzZTMiLCJzZWVkIjo0Mzc4MTk1MDYsImZpbGxTdHlsZSI6ImhhY2h1cmUiLCJzdHJva2VXaWR0aCI6MSwicm91Z2huZXNzIjoxLCJvcGFjaXR5IjoxMDB9LHsidHlwZSI6InJlY3RhbmdsZSIsIngiOi05NiwieSI6Mjc1LCJ3aWR0aCI6LTEwMiwiaGVpZ2h0IjotNjUsImlzU2VsZWN …
> Save scene in URL

- package-lock.json
- package.json
- src/components/panels/PanelCanvas.tsx
- src/components/panels/PanelColor.tsx
- src/components/panels/PanelExport.tsx
- src/components/panels/PanelSelection.tsx
- src/components/panels/PanelTools.tsx
- src/index.tsx
Extract the following panels into their respective components:
* Tools -> Tool Selector
* PanelColor -> Stroke and Background Color picker picker
* Selection -> Bring forward etc buttons
* Canvas -> View background color and clear canvas
* Export -> All export functionality
Additional Housekeeping: added Jest TS types
> Extract Sidebar panels into separate components

- src/index.tsx
- src/scene/data.ts
- src/scene/index.ts
Reverts excalidraw/excalidraw#220
It does not work well. URLs are to huge, practically no one url shortener can handle it. Also it caused an issue #228
> Revert "Save scene in URL"

- src/element/index.ts
- src/element/textWysiwyg.tsx
- src/index.tsx
- src/types.ts
> Wysiwyg text 2.0

- src/index.tsx
> Fixed: Copy + Paste moves text inside rectangle #229

- src/element/textWysiwyg.tsx
- src/element/types.ts
- src/index.tsx
- src/renderer/renderElement.ts
- src/utils.ts
> Fixes text jumping on creation

- src/index.tsx
- src/renderer/renderElement.ts
- src/scene/comparisons.ts
- src/scene/index.ts
> Creating a text near the center of a shape should put it in the center

- .github/FUNDING.yml
I just created an open collective for the project.
> Adding open collective sponsor

- src/element/textWysiwyg.tsx
- src/utils.ts
Fixes #271
I've found one problem: it allows to paste multiline text which is not supported yet
> Contenteditable wysiwyg

- src/components/Panel.tsx
- src/components/panels/PanelCanvas.tsx
- src/components/panels/PanelExport.tsx
- src/components/panels/PanelSelection.tsx
- src/components/panels/PanelTools.tsx
- src/index.tsx
- src/styles.scss
This PR adds a new feature to collapse contents of a panel.
Referencing issue: #237
> Make panels collapsible

- src/index.tsx
- src/scene/comparisons.ts
- src/scene/index.ts
@vjeux @paulomenezes 
New PR from the last master.
Add editable font size and font familly on select text
> Add font size and font familly option for selection

- CONTRIBUTING.md
> Add contributing md

- src/index.tsx
> Clear active tool on escape

- src/index.tsx
Fix for recent regression of copy/paste introduced in #283 
@Fausto95 Can you check if all fixed now? Sorry about the regression, we really need to set up tests :).
> fix copy/paste regression

- src/components/SidePanel.tsx
- src/element/index.ts
- src/element/textElement.ts
- src/index.tsx
I am separating side panel from app component to make it easier navigating the codebase. SidePanel component's props is a bit messy now but the the extraction is 100% working. I am going to spend some time trying to clean up the API, hence the Draft PR.
> Extract Side Panel from App component

- src/index.tsx
> Command clicking should "xor" selection

- src/renderer/renderElement.ts
- src/renderer/renderScene.ts
`context.translate` was used to render every element. Moved it to `renderScene`
> Removed SceneState from renderElement

- src/actions/actionDeleteSelected.tsx
Now that we have context menu, we don't need it there
> Remove Delete from panel

- src/components/SidePanel.tsx
> Export to canvas only selected elements

- src/actions/actionCanvas.tsx
- src/appState.ts
- src/index.tsx
Also makes "Clear canvas" reset the entire app state
Fixes #79
Fixes #226
> Set shape background to be transparent by default

- src/history.ts
- src/index.tsx
I just pasted @enzoferey's implementation and it fixed the bug reported by @dwelle
Fixes #307
> Fix undoOnce

- src/index.tsx
Hopefully it should resolve the copy pasting issues
Fixes #249
> Move copy paste handler to document

- src/element/collision.ts
fixes #104 
Alright, this one is crazy, but it kinda works. I have no idea what I'm doing exactly around the ellipse, so don't ask me.
Also, the algo for `diamond` shape could in theory be factored out and used for any rectangle, but I kept a simpler one for regular `rectangle` due to perf.
Related, there's an issue how we handle coordinates when we flip shapes horizontally/vertically. I hacked-normalized it when detecting hitbox for diamond shape, but in the long run we need to normalize globally, because this results in several other bugs. Will create an issue for this, soon.
Also, for perf, I'd probably make `backgroundColor` `null` to indicate no bg is present, instead of `"transparent"`, so that we don't need to compare strings.
Also note, that when we implement #15, all the code in …
> select filled elements by clicking inside

- src/index.tsx
Fixes https://github.com/excalidraw/excalidraw/issues/348
> fix selecting elem inside already selected element

- src/index.tsx
- src/scene/index.ts
- src/scene/selection.ts
> Shift drag to add to selection

- package-lock.json
- package.json
This fixes issue reported by @dwelle here: https://github.com/excalidraw/excalidraw/pull/363#issuecomment-573819741
> Bump rough.js one more time. 

- package-lock.json
- package.json
- src/renderer/renderElement.ts
fixes #370 
Thanks @pshihn again, for swift fix in roughjs!
> enable curveFitting & bump roughjs

- src/index.tsx
- src/shapes.tsx
Hello!
I used excalidraw and I loved it. One thing I found counterintuitive is the hotkeys. I added functionality to make them work numerically, too!
> Add numeric hotkeys

- src/index.tsx
> Fix #360 prevent creating invisibly small elements

- src/element/index.ts
- src/element/sizeChecks.ts
- src/index.tsx
> Remove resized element if it is invisibly small

- src/components/ColorPicker.css
- src/components/ToolIcon.scss
- src/styles.scss
- src/theme.css
https://yeun.github.io/open-color/
> Update colors from open colors

- src/components/ExportDialog.css
- src/components/ExportDialog.tsx
- src/components/Stack.tsx
- src/components/ToolIcon.scss
- src/components/ToolIcon.tsx
- src/index.tsx
- src/scene/data.ts
This PR adds feature that allows to scale exporting images
> Set scale for exporting images

- src/components/ExportDialog.css
- src/components/ExportDialog.tsx
- src/components/Stack.tsx
- src/components/ToolIcon.scss
- src/components/ToolIcon.tsx
- src/index.tsx
- src/scene/data.ts
Reverts excalidraw/excalidraw#416
Caused issue #419
> Revert "Set scale for exporting images"

- package.json
> Test only the app.. lint is separate

- src/appState.ts
- src/element/textWysiwyg.tsx
- src/index.tsx
- src/types.ts
Fixes https://github.com/excalidraw/excalidraw/issues/399
> Render text actions panel on double click

- src/index.tsx
- src/utils.ts
> flush autosave on unload

- src/appState.ts
- src/components/LockIcon.tsx
- src/components/ToolIcon.scss
- src/index.tsx
- src/types.ts
Adding a lock icon to lock the current shape selection (from https://github.com/excalidraw/excalidraw/pull/384).
Demo:
> Introduce Shapelock

- src/bug-issue-template.js
- src/index.tsx
- src/styles.scss
fixes #471 
This is not the end state we wanna arrive to, but I've had some issues that I couldn't debug. Maybe as a hotfix it suffices.
> add top error boundary & reset localStorage on error

- src/components/ToolIcon.scss
> Pointer for Tool icons

- package.json
- src/element/collision.ts
> Allow dragging transparent elements when selected

- .github/workflows/lint.yml
- .github/workflows/test.yml
Note sure if this helps with https://github.com/excalidraw/excalidraw/issues/424, we'll see.
> update events for GH actions to include PRs

- src/renderer/renderScene.ts
> Render only visible elements

- public/locales/en/translation.json
- public/locales/es/translation.json
- src/actions/actionProperties.tsx
- src/components/ExportDialog.tsx
- src/components/LanguageList.tsx
- src/i18n.ts
- src/index.tsx
- src/scene/data.ts
- src/styles.scss
This PR follow this issue:
https://github.com/excalidraw/excalidraw/issues/453
- add menu list to select languages
- add Spanish translations
> Internationalization followup

- src/element/index.ts
- src/element/sizeChecks.ts
- src/element/sizeHelpers.ts
- src/index.tsx
> Draw horizontal/vertical lines/arrows when shift pressed

- src/index.tsx
Related to https://github.com/excalidraw/excalidraw/pull/522
> Don't use translated value for shortcut

- src/components/LanguageList.tsx
- src/index.tsx
- src/styles.scss
Fixes: https://github.com/excalidraw/excalidraw/issues/530
> Enhance language selection

- src/index.tsx
- src/scene/data.ts
- https://excalidraw.com?id=4794773428764672
- https://deploy-preview-554--excalidraw.netlify.com?id=4794773428764672
-----
- https://excalidraw.com?id=4846349744865280
- https://deploy-preview-554--excalidraw.netlify.com?id=4846349744865280
-----
- https://excalidraw.com?id=5184813602439168
- https://deploy-preview-554--excalidraw.netlify.com?id=5184813602439168
-----
- https://excalidraw.com?id=5641665683390464
- https://deploy-preview-554--excalidraw.netlify.com?id=5641665683390464
-----
- https://excalidraw.com?id=6310713509281792
- https://deploy-preview-554--excalidraw.netlify.com?id=6310713509281792
-----
- https://excalidraw.com/?id=5193297203036160
- https://deploy-preview-554--excalidraw.netlify.com?id=5193297203036160
------
Fixes #306
> Scroll content to the center when loading from backend or file

- src/components/ColorPicker.tsx
By changing from a `<div>` to a `<button>`, it's now possible to use the space key in order to select it
> Make color selection accessible

- src/components/ExportDialog.tsx
Right now we're running useEffect block which runs getExportCanvasPreview on every state update, even if the modal is not visible (eg: when moving the mouse around!). This puts the modal code in its own component so that it doesn't trigger useEffect when not visible.
The code isn't very elegant as we're forwarding all the props, there's likely a better way to handle it (if anyone is interested, PR would be appreciated), but at least now it no longer double renders the scene.
Fixes #559
> Do not trigger modal actions when not visible

- src/components/ContextMenu.css
- src/components/ContextMenu.tsx
> Adjust context menu and use open colors

- src/components/LockIcon.tsx
- src/components/ToolIcon.scss
- src/index.tsx
The lock is a different type as the rest of the shapes, so we should visually separate it.
> Add a gap between shapes and lock

- src/index.tsx
When we are scrolling, resizing, or moving elements, we already disable the history. Since those actions do not change the state of the UI, we can also avoid re-drawing it and save ~10ms per frame.
I had to change all the forceUpdate() to setState({}), otherwise it would bypass shouldComponentUpdate.
Fixes #558
> Disable UI rendering when history is skipped

- public/locales/es/translation.json
Tiny PR to fix a Spanish translation
> Fix translation

- src/index.tsx
Hack fix for https://github.com/excalidraw/excalidraw/issues/592. Not closing the issue because this is not a long-term fix, but I do't want to split the `<App/>` compo right now because it'd create really bad merge conflicts for long-standing PRs.
> temp hack fix for state updates

- src/components/ColorPicker.css
- src/components/ColorPicker.tsx
Fixes: https://github.com/excalidraw/excalidraw/issues/590
> lowercase pasted color

- src/index.tsx
> Fix: refreshing the page while selecting saves the selection element

- .lintstagedrc.js
- package-lock.json
- package.json
No need for that.. we format then using Prettier
> Remove eslint-plugin-json-format

- src/components/ToolButton.tsx
Reverts #587 due to https://github.com/excalidraw/excalidraw/issues/615#issuecomment-580167049.
fixes #615
/cc @muzakparov
> Revert "Fix keyboard shortcut (#587)"

- src/scene/data.ts
- https://deploy-preview-608--excalidraw.netlify.com/?id=1234
- https://excalidraw.com/?id=1234
> Better handling of 404 errors when loading from backend

- src/components/ColorPicker.css
- src/components/ColorPicker.tsx
This adds the ability to navigate using left/right/bottom/up keys and shows key bindings for all the different colors. This is only optimized for the qwerty keyboard layout, but unfortunately it's not possible to detect other keyboard layouts :(
> Add keybindings for color picker

- src/index.tsx
- src/scene/data.ts
- src/scene/index.ts
> Drag and drop JSON exports to canvas loads the scene

- src/scene/data.ts
Fixes: https://github.com/excalidraw/excalidraw/issues/677
> Load only valid excalidraw json when drag&drop

- src/actions/actionProperties.tsx
Instead of freeform, let's only support 10 increments of opacity. Should help keep things consistent
> Add step for opacity slider

- src/actions/actionProperties.tsx
I think it could be convenient to be able to change the opacity with the scroll wheel, no need to click and drag of opacity slider every time
> Allow changing opacity with scroll wheel

- src/actions/actionFinalize.tsx
- src/appState.ts
- src/index.tsx
- src/scene/data.ts
This PR implements real-time multi arrow feature. Currently, everything works but there is something that I am not satisfied with. When finalizing multi arrows, should we remove the "uncommitted" point or should we keep it? 
#669
> Add points to multi arrows in real time

- src/components/ColorPicker.tsx
> Remove select color input on click

- src/element/bounds.ts
> Set arrow cap size based on length of the entire arrow

- src/index.tsx
> fix restoring from localStorage

- src/index.tsx
It seems #479 regressed again.
> fix hotkeys not working when non-writable input focused

- src/appState.ts
- src/index.tsx
- src/types.ts
Hints on the tools don't display in the selected language initially when we change the language.
> Fix language selection

- src/locales/pl.json
Polish is a very complicated language, and it's even more complicated when you try to write it using the English keyboard.
This PR contains few language fixes. This time every word/sentence has been check by my wife, so it's fine :D
> Fix grammar problems in Polish translation 🇵🇱🐛

- src/scene/data.ts
Because it looks more secure ;)
> Add lock icon

- src/element/bounds.ts
Fixes #710
Previously, arrow caps were aligned based on the stored points. This misaligned the arrow caps when we had an "abrupt" curve in the arrow because the "midpoint" of the bezier curve was not stored in the points array (red points are the points that are stored):
I change the implemention so that the direction on the curve is calculated by the end point and a point **on the curve** that is closer to the end point. The point is calculated using cubic bezier formula.
> Align arrow caps based on bezier curve instead of stored points

- src/element/newElement.ts
Wouldn't let me sleep if I let it like this :).
> fix cloning element.points

- src/actions/actionFinalize.tsx
- src/index.tsx
- src/utils.ts
> fix some element types reset to selection when the lock is active

- package-lock.json
- package.json
browser-nativefs has moved from tomayac to GoogleChromeLabs
https://github.com/GoogleChromeLabs/browser-nativefs
> Update browser-nativefs dep after repo move

- src/actions/actionCanvas.tsx
- src/index.tsx
- src/scene/index.ts
- src/scene/zoom.ts
Borrowed the idea from figma (:
> Use meta key + wheel to zoom in/out

- src/index.tsx
Clamps zoom from top.
@nanot1m please check if it works well for you.
> fix wheel zoom step

- src/actions/actionCanvas.tsx
- src/actions/index.ts
- src/index.tsx
- <kbd>shift/meta</kbd> + <kbd>-</kbd> — zoom out
- <kbd>shift/meta</kbd> + <kbd>+</kbd> — zoom in
- <kbd>shift/meta</kbd> + <kbd>0</kbd> — reset zoom
> Shortcuts to zoom in/out and to reset zoom

- src/components/HintViewer.css
- src/components/HintViewer.tsx
- src/index.tsx
> Show hint under toolbar

- public/index.html
https://www.google.com/appserve/mkt/p/AFnwnKUwZ7ofhCQhlxxDNFZMdDCdf9b9v3EYRD8U6SxPpY6Gbc8IcdhhPYia7pyqXB0waaDtEdbu3BGQhWGJKb_4NRgdzKr8MYmeYyrl3fsI7lY-Hlt_S7jKMtXl1uW41XuN2DfK3xfwxfKATuePkyy5Dfk
> Update expiring origin trial token

- src/actions/actionFinalize.tsx
- src/index.tsx
> Don't render bounding box for multi-point lines during creation

- src/components/ProjectName.tsx
> Fix error on export

- src/actions/actionStyles.ts
- src/element/index.ts
- src/element/typeChecks.ts
Fixes: https://github.com/excalidraw/excalidraw/issues/814
> fix style pasting

- src/renderer/renderElement.ts
fixes https://github.com/excalidraw/excalidraw/issues/835
> fix exporting lines as svg

- src/renderer/renderElement.ts
> fix svg export

- src/scene/data.ts
fixes https://github.com/excalidraw/excalidraw/issues/843
> ensure restored elements are normalized before filter

- src/scene/data.ts
Reverts excalidraw/excalidraw#846
> json.excalidraw is back

- package-lock.json
- package.json
- scripts/build-version.js
------
- https://excalidraw-git-version.excalidraw-team.now.sh/version.json
- https://excalidraw-git-version.excalidraw-team.now.sh/excalidraw-2020-02-28-21-42-03.asar
Fixes #853
> Add version to build and the archived asar app

- src/actions/actionExport.tsx
- src/actions/actionProperties.tsx
- src/actions/actionZindex.tsx
- src/clipboard.ts
- src/components/ColorPicker.tsx
- src/components/ContextMenu.tsx
- src/components/ExportDialog.tsx
- src/components/Modal.tsx
- src/components/Popover.tsx
- src/components/ProjectName.tsx
- src/element/textWysiwyg.tsx
- src/gesture.ts
- src/index.tsx
- src/scene/data.ts
Let's make it more clear.. because sometimes it's error sometimes it's event.. there is no point of abbreviating them :)
> Refactor: e -> event or error, err -> error, p -> pointer

- src/index.tsx
- src/renderer/renderScene.ts
- src/scene/scrollbars.ts
- src/scene/types.ts
- Don't create a new element when clicking a scrollbar. In master shapes create a 0 sized element when clicking a scrollbar, and multi-step arrows create another point.
- Show default cursor when hovering or dragging a scrollbar
Double clicking a scrollbar still creates a text element, not sure if we want it to happen .
> Improve scrollbar-mouse interaction

- src/actions/actionHistory.tsx
How could I have gotten this so wrong?
Fixes #872
> Fix Undo/Redo

- src/components/App.tsx
These methods are really huge and a bit unwieldy in the editor, so I pulled them into instance methods. There should be no functional changes in this diff.
> Pull onPointerDown, onDoubleClick, onPointerMove into instance methods

- src/renderer/renderElement.ts
We merged #880 too quickly. It broke the ability to add new shapes to the canvas.
Test plan:
* npm t
* add new shape to canvas, it works
* drag a shape around
* resize a shape
* add text
* view export preview
> Fix a bug introduced by #880

- src/components/App.tsx
Fixes pinch zoom regression introduced in #784.
> fix pinch zoom

- package-lock.json
- src/renderer/renderScene.ts
> Fill the resize handles with white so they are visible on dark backgrounds

- src/actions/actionFinalize.tsx
- src/actions/actionStyles.ts
- src/components/App.tsx
- src/element/mutateElement.ts
- src/element/newElement.ts
- src/element/sizeHelpers.ts
- src/element/textElement.ts
- src/element/types.ts
@petehunt this borrows heavily from your work on https://github.com/petehunt/excalidraw/commit/57ac7b7d3ca30a2f5ae77ff68b313aa3df9f5a73
This can be tested here: https://excalidraw-test.now.sh/#room=828c67e1019d89ed1bf2,s3Zb_ph9F-2PACFl0r1eBw
Basically, it adds version bumping and does some lossy reconciliation so users can edit different elements at the same time. It doesn't address simultaneous creation and deletion of elements but it's an improvement.
> enable version bumping for collaboration

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
- src/components/RoomDialog.scss
- src/components/RoomDialog.tsx
- src/components/ToolButton.tsx
fixes https://github.com/excalidraw/excalidraw/issues/911
Btw, anyone has any idea how to prevent this weird outline encompassing the number? `outline: none` on the child doesn't work:
Also, currently, count of `1` indicates yourself. Should we stop counting ourselves into the counter at all?
> Collab ui tweaks

- src/data/restore.ts
> fix zero-coalescing roughness

- src/actions/actionFinalize.tsx
- src/element/textWysiwyg.tsx
- fixes https://github.com/excalidraw/excalidraw/issues/919
- made `esc` confirm text to align with desktop apps/Figma...
> Text esc fixes

- src/appState.ts
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
- src/components/RoomDialog.tsx
- src/data/localStorage.ts
- src/types.ts
fix for https://github.com/excalidraw/excalidraw/issues/910
The backend PR is at https://github.com/excalidraw/excalidraw-room/pull/5
> remove remote pointers on client disconnect

- src/utils.ts
fixes https://github.com/excalidraw/excalidraw/issues/929
> fix calculating text width for indented text

- src/renderer/renderScene.ts
Instead of a crude circle, this makes it look more like a pointer. I manually tweaked the numbers until it looked like a pointer :)
> Better looking pointer

- .github/workflows/lint.yml
- package.json
- src/element/newElement.test.ts
> [easy] run typechecking on CI

- src/renderer/renderScene.ts
When the background is solid and has that arrow it's not visible at the moment :)
> Different color for the stroke of the collaborator's arrow

- src/actions/actionDuplicateSelection.ts
- src/actions/index.ts
- src/locales/en.json
Adds support for: https://github.com/excalidraw/excalidraw/issues/981
> CMD + D to Duplicate Selection

- src/components/Dialog.scss
- src/components/MobileMenu.tsx
- src/components/ToolIcon.scss
- src/locales/en.json
- src/scene/scrollbars.ts
- src/styles.scss
- src/utils.ts
> Restyle the mobile UI a bit

- src/actions/actionFinalize.tsx
- src/actions/manager.tsx
- src/components/App.tsx
- src/constants.ts
- src/element/newElement.ts
- src/element/types.ts
- src/locales/en.json
10px delta too big?
Also tends to create text right after (https://github.com/excalidraw/excalidraw/issues/740), but that's for another time.
Fixes #673
> confirm arrow on doubleclick

- src/components/App.tsx
Fixes: https://github.com/excalidraw/excalidraw/issues/1012
> Fix SpaceBar pan

- src/data/index.ts
- src/renderer/renderScene.ts
Fixes: https://github.com/excalidraw/excalidraw/issues/1019
> Remove deleted elements from svg export

- src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1022
reverts #1017 (this is one me @cyan33. We'll need to rewrite the handling a bit because it's pretty convoluted)
> revert #1017

- src/components/App.tsx
Hotfix for deleted elements causing multiple issues. Note, this doesn't fix everything, and may introduce issues of its own, but as as interim solution, it'll do.
fixes https://github.com/excalidraw/excalidraw/issues/1019
> don't pass deleted elements to UI

- src/components/App.tsx
App is too big. I'm preparing it for splitting by putting the related parts together.
Please check my Git history. I'm afraid it may still be messed up.
> App mitosis begins

- src/actions/actionProperties.tsx
To follow the rest of the options..
> Change order of the fill options

- src/components/App.tsx
- src/element/handlerRectangles.ts
The logic to support it was not implemented. This is not the prettiest way to solve it in the world but it does work. Some more refactoring here is probably warranted.
Fixes #1039
> Fix corner resize for multi-point arrows

- src/components/App.tsx
- src/data/index.ts
Resolves #907 
Added `SCENE_INIT` type to update current scene only for new users.
> Add `SCENE_INIT` broadcast type for new user

- src/components/App.tsx
Fixes #1115
The issue is that replaceAllElements calls a render synchronously, preventing lastBroadcastedOrReceivedSceneVersion from being set correctly.
I tried using batchUpdate but it only takes a single argument ( https://github.com/facebook/react/blob/c5d2fc7127654e43de59fff865b74765a103c4a5/packages/react-reconciler/src/ReactFiberWorkLoop.js#L1088 ) whereas the callback takes two.
Test Plan:
- Add a console.log before `this.broadcastScene("SCENE_UPDATE");` in App.tsx
- Connect a bunch of clients
- Have one move a shape
- Make sure that this client has the console logged
- Make sure the other clients don't have it
> Avoid broadcasting what was just received

- README.md
This is what you get when you're not signed in:
Updated readme:
And tested that this flow works.
> Note that codesandbox requires sign-in

- src/element/textWysiwyg.tsx
Fixes #1158
This will add a new line on Enter
> Add new line on Enter

- src/components/App.tsx
Sorry to revert but this is completely breaking zooming in/out with two fingers as it creates a text node.
Reverts excalidraw/excalidraw#1155
> Revert "Insert text on double tap [hacky solution]"

- src/components/App.tsx
One second feels way too long. Let's try 300ms
> Update zoom refresh

- src/element/textWysiwyg.tsx
> Add support for committing a text entry on cmd/shift click

- now.json
> Create now.json for redirects

- now.json
> Add content policy

- src/components/App.tsx
Fixes regression where we no longer scroll to content on collab room join.
> scroll to content on collab scene init

- src/components/App.tsx
Fixes: https://github.com/excalidraw/excalidraw/pull/1179
Tap twice to insert text.
Try zooming and make sure there's no text insertion
> Insert text on double tap

- src/element/handlerRectangles.ts
> Position rotation handle properly with zoom

- src/components/ShortcutsDialog.tsx
- src/locales/en.json
> Add curved lines/arrows shortcuts

- public/index.html
> Better title, for better look in search results, SEO

- src/actions/actionExport.tsx
- src/keys.ts
Re #1239, simplest thing to do.
> Save on CTRL/CMD + S

- src/components/TopErrorBoundary.tsx
- src/data/localStorage.ts
Fixes https://github.com/excalidraw/excalidraw/issues/1240
Wrapped localStorage in try-catch to avoid throwing the exception.
> Wrap localStorage API Access in try-catch

- public/index.html
> Shorter title

- package-lock.json
- package.json
There was a bug where solid ellipses were not being filled properly, caused by evenodd filling rule used to fill curves
> bump roughjs version

- public/index.html
- src/components/GitHubCorner.tsx
- src/components/LayerUI.tsx
- src/styles.scss
> Move GitHub corner and visually-hidden class

- src/components/ShortcutsDialog.tsx
- src/locales/en.json
- src/utils.ts
- Undo
- Redo
- Multiple line text
- How to stop editing
I'm open to suggestions about the copy.
> Add more shortcuts and minor refactor

- src/actions/actionExport.tsx
- src/components/App.tsx
- src/data/blob.ts
> Allow opening empty excalidraw file

- src/components/Modal.scss
- src/components/Modal.tsx
> Fix mobile dialog styling

- package-lock.json
- package.json
Fixes #1368
[Duh :-/](https://github.com/GoogleChromeLabs/browser-nativefs/commit/69667256e307dc0223087a5b1d4fb03b1549633f#diff-eb473a7019959911314d4a7f611503a6)
> Handle the createWriter situation correctly

- public/index.html
Fixes the Content Security Policy Warning in Excalidraw Desktop - https://github.com/excalidraw/excalidraw-desktop/issues/82
> Add Content Security Policy Header Tag

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
- src/data/localStorage.ts
Fixes #1361, store username **for each room** on local storage.
> Store username for every room

- src/components/App.tsx
- src/constants.ts
- src/time_constants.ts
use constants instead of hardcoded strings for better readability
don't use an inline function as it will create a new reference every time
I have made some minor refactoring in the code for better readability. 
Please let me know if this is acceptable.
> some refactoring in app.tsx 

- src/components/App.tsx
- src/components/Portal.tsx
- src/constants.ts
- src/index.tsx
- src/tests/dragCreate.test.tsx
- src/tests/move.test.tsx
- src/tests/multiPointCreate.test.tsx
- src/tests/regressionTests.test.tsx
- src/tests/resize.test.tsx
- src/tests/selection.test.tsx
- src/tests/zindex.test.tsx
- src/types.ts
App.tsx is growing very big so moved the Portal code to a new file, Since Portal is not a component, so this might not be the correct directory. 
Should I create a new directory Helpers for this?
> refactor(app.tsx): move Portal to new file and some refactoring

- public/index.html
attemps to fix https://github.com/excalidraw/excalidraw/issues/1400
> CSP: fix codesandbox

- src/components/App.tsx
Proposal to fix #1383.
I propose to fix the extra middle click paste event only on linux by preventing the next paste event only when user pan the view.
> Prevent next paste on middle clic with linux

- src/element/bounds.test.ts
- src/element/bounds.ts
https://github.com/excalidraw/excalidraw/pull/1394#issuecomment-612545935
> Add test for getElementBounds

- public/index.html
Sign us up for Native File System API v2 Origin Trial.
> Sign us up for Native File System API v2 Origin Trial

- src/components/Island.css
- src/css/theme.scss
Shamelessly ripping this idea from Miro, but I feel this helps
reinforce the infinite canvas feeling.
> Improve UI continuity behind panels

- src/data/json.ts
> Use application/vnd.excalidraw+json and .excalidraw

- src/components/RoomDialog.tsx
> Close sharing dialog on Enter when changing the username

- package-lock.json
- package.json
> Update to browser-nativefs v0.7.0

- .gitignore
- src/components/App.tsx
- src/components/LayerUI.tsx
* Pass named function to react.memo so that in dev tools the name shows up instead of showing anonymous 
* Make LayerUI default export
* Break the functional component into multiple render methods
> Refactor LayerUI

- src/components/ColorPicker.tsx
Implementation proposition for #1478.
> Support different color inputs

- .eslintrc
- package.json
just a quick PR to get eslint rules out of package.json
> extract eslint rules from package.json

- src/components/ColorPicker.tsx
Following #1478, a bug was found related to transparent backgrounds. As Excalidraw only supports `transparent` as a valid transparent color, this commits generalizes the use of canvas to normalize color values.
It changes a few details:
- `rgba()` or `hsla()` syntaxes are not accepted anymore
- pasting values goes through the same normalization step, avoiding invalid values
- color validation is not regex-based anymore
- any CSS-valid black color is now accepted (e.g. previously, `rgb(0,0,0)` was rejected)
> Generalize color normalization

- src/actions/actionExport.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1482
> ignore fileOpen error when user cancels

- src/components/ToolButton.tsx
tool icons were not showing up when an element is selected
> fix tool icon button on mobile

- src/element/handlerRectangles.ts
- src/element/resizeElements.ts
- src/math.ts
- Extract refactored code from #1427, that will likely to conflict with others
- Fix negative flicker bug (#1443)
> Fix resize logic (partly)

- src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1518
> scroll horizontally on shift-scroll

- README.md
[ZEIT is now Vercel](https://vercel.com/blog/zeit-is-now-vercel), so it can be updated in the README.
> Update ZEIT Now -> Vercel

- src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1527
> fix horizontal scroll via shift+wheel on mac

- src/components/LayerUI.scss
> #1529 Rtl ui broken in zen mode

- src/components/LayerUI.scss
- src/components/LayerUI.tsx
- src/components/LockIcon.tsx
- src/components/ToolIcon.scss
- src/css/styles.scss
Fixes https://github.com/excalidraw/excalidraw/issues/1522
> show reset icon with zoom percentage during zen mode

- src/renderer/renderElement.ts
> preserve spaces in text blocks in svg export

- src/locales/en.json
> fixed typo: loose ==> lose

- src/i18n.ts
> Add Catalan translation

- src/element/bounds.ts
- src/renderer/renderElement.ts
possibly fix #1606 
@lusingander can confirm?
@dwelle any idea for keeping the logic in sync?
> fix: resize non solid lines/arrows/draws

- src/locales/en.json
> Typo fix in desc_exitSession en.json

- src/element/collision.ts
- src/renderer/renderElement.ts
Fixes https://github.com/excalidraw/excalidraw/issues/1614
> Ensure arrows are not draggable from inside

- src/constants.ts
- src/element/sizeHelpers.test.ts
> 15-degree rotation locking

- src/actions/actionGroup.ts
> Fix zindex in groups

- src/actions/actionProperties.tsx
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/tests/queries/toolQueries.ts
- src/tests/regressionTests.test.tsx
fix https://github.com/excalidraw/excalidraw/issues/1678
> fix fontFamily state updating

- src/actions/actionCanvas.tsx
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
- src/data/index.ts
- src/data/localStorage.ts
- src/data/restore.ts
- src/element/bounds.ts
- src/element/index.ts
- src/scene/scroll.ts
fixes https://github.com/excalidraw/excalidraw/issues/1260
cc @lipis
> scroll the closest element to center

- src/css/styles.scss
> Hide the UI elements when printing the page

- .github/workflows/publish-docker.yml
fix https://github.com/excalidraw/excalidraw/issues/1621
> Add Docker Hub publish workflow

- src/data/index.ts
- src/renderer/renderElement.ts
- src/scene/export.ts
- src/utils.ts
revert #1687 to fix https://github.com/excalidraw/excalidraw/issues/1704
> Revert "Fix RTL text direction rendering (#1687)"

- src/element/newElement.ts
- src/global.d.ts
fixes https://github.com/excalidraw/excalidraw/issues/1708
> fix text constructor groupIds & improve type safety

- src/components/App.tsx
- src/element/index.ts
- src/element/resizeElements.ts
- src/renderer/renderScene.ts
> support resizing multiple elements including texts

- public/manifest.json
- src/actions/actionCanvas.tsx
- src/index.tsx
On supporting operating systems (I think right now this is just Chrome OS), this PR adds the capability to open `.excalidraw` and `.json` files with Excalidraw.
https://github.com/WICG/file-handling/blob/master/explainer.md#example
> Add file handling

- README.md
Remove Docker information till we resolve the issue with our Docker organization.
Ref:
- https://github.com/excalidraw/excalidraw/issues/1764
- https://github.com/excalidraw/excalidraw/pull/1713
> Remove docker info

- .github/workflows/publish-docker.yml
- Dockerfile
- README.md
- docker-compose.yml
- package.json
- public/index.html
* set the final Docker namespace
* setup docker-compose for local development only
* add instructions and more information about the Docker image
Also addresses:
- https://github.com/excalidraw/excalidraw/issues/1768
- https://github.com/excalidraw/excalidraw/issues/1764
> Prepare for Docker publishing

- src/actions/actionStyles.ts
https://github.com/excalidraw/excalidraw/issues/1716
> Include stroke style when copy/paste styles

- src/components/ShortcutsDialog.tsx
- src/locales/en.json
https://github.com/excalidraw/excalidraw/issues/1712
> Hint for shortcut for moving the visible area

- src/renderer/renderScene.ts
> fix visibility check on rotated elements

- src/css/styles.scss
I ran the SVG through [SVGOMG](https://jakearchibald.github.io/svgomg/) to make it as small (in bytes) as possible without sacrificing image quality.
> Inline the dropdown icon

- src/renderer/renderScene.ts
- src/scene/export.ts
> do not render grid on export

- src/i18n.ts
Resolves https://github.com/excalidraw/excalidraw/pull/1793#discussion_r447067827
> Refactor CJS require to ESM

- src/global.d.ts
- src/index.tsx
- src/react-app-env.d.ts
https://github.com/excalidraw/excalidraw/issues/1665
> Expose Git SHA to window

- public/app.css
- src/components/FixedSideContainer.css
- src/components/LayerUI.tsx
- src/css/styles.scss
All the elements are position: fixed in excalidraw App. This. makes it difficult to render when used inside the host App. So. I changed it to absolute so it's positioned relative to its parent instead of viewport
cc @dwelle
> use absolute positioning instead of fixed

- .env
- src/data/index.ts
- src/global.d.ts
This PR doesn't actually introduce self-hosting yet but it does make it easier.
See https://github.com/excalidraw/excalidraw/issues/1772#issuecomment-651709992 for context.
> Extract backend URLs into environment variables (#1772)

- public/index.html
Resolves https://github.com/excalidraw/excalidraw/pull/1075#issuecomment-653567022
> Parameterise socket preconnect

- src/actions/actionDuplicateSelection.tsx
- src/actions/types.ts
- src/components/App.tsx
- src/locales/en.json
fixes #1742
Somewhat of a cop-out, the underlying problem discussed in the issue still stands, but the solution for that particular bug should actually be more on the note of this PR.
> duplicate point on cmd+d

- src/actions/actionCanvas.tsx
- src/actions/actionNavigate.tsx
- src/appState.ts
- src/components/App.tsx
- src/element/types.ts
- src/index.tsx
- src/scene/scroll.ts
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/types.ts
Width and height are received as props.
cc @dwelle
> feat: add width, height as props to App.tsx

- src/components/App.tsx
- src/element/resizeTest.ts
- src/scene/scrollbars.ts
This handler is now at 1000 LOC. I tried to simplify it by pulling things out. I'll follow up with further refactor later.
Reviewing each commit should be easy.
> Refactoring in pointer down event handler

- src/components/App.tsx
- src/utils.ts
This is a PR on top PR #1880 but it's 2020, the world is on fire, and Github still doesn't have a [stacked PR workflow](https://github.com/isaacs/github/issues/867) 🤦 .
We're down to 600 LOC from 1000 for this function.
Once the first PR gets merged I'll update this one so it's mergeable.
Reviewing each commit should be easy.
> Refactoring in pointer down event handler, step 2

- src/actions/actionDeleteSelected.tsx
fix https://github.com/excalidraw/excalidraw/issues/1891
> fix deleting multi-point elem during edit

- src/components/App.tsx
- src/scene/scrollbars.ts
PR on top PR #1887
This handler is now 90 LOC down from a 1000. Not bad ⛳ . A reader might even be able to tell what this thing does.
Once the second PR gets merged I'll update this one so it's mergeable.
Reviewing each commit should be easy.
> Refactoring in pointer down event handler, step 3

- src/actions/actionProperties.tsx
- src/components/App.tsx
- src/element/textWysiwyg.tsx
I'm checking if the element version is 3 and if it is we use the state.
I don't know if this is the ideal solution but it worked. let me know if there is a better way to handle this.
> Choosing color before entering text does not update the swatch (Fixes #1897)

- src/actions/actionExport.tsx
Lots of sentry hits for this one (we forgot to handle the saving)
> mute FS abort errors

- src/components/Actions.tsx
- src/components/LayerUI.tsx
- src/components/LibraryUnit.scss
- src/components/LibraryUnit.tsx
- src/components/LockIcon.tsx
- src/components/MobileMenu.tsx
- src/components/ToolButton.tsx
- src/components/ToolIcon.scss
Fixes some issues mentioned in #1904
- Resize library items and show more.
- Show library menu on mobile
- Resize icons on mobile
> Library improvements

- src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1919
Not sure if this is 100% tight and won't cause issues elsewhere.
~~Someone please test on Safari using the steps outlined in the issue https://github.com/excalidraw/excalidraw/issues/1919~~ this can't actually be tested in the preview because share links aren't supported there.
@tomayac thoughts?
> delay scene init until document active

- src/data/index.ts
> Make sure extension gets set correctly for exports

- src/element/linearElementEditor.ts
- src/renderer/renderScene.ts
fix https://github.com/excalidraw/excalidraw/issues/1966 + improve type safety
> ensure editingLinearElement handles are rendered on top

- src/components/App.tsx
- src/element/linearElementEditor.ts
> feat: grid mode for line editing

- src/element/collision.ts
In retrospect I abstracted this code away too much.
> Fix text selection broken by #1899

- src/components/App.tsx
This `setState()` didn't trigger any update.
> add explanation for why we mutate collaborators state

- src/actions/actionCanvas.tsx
fix https://github.com/excalidraw/excalidraw/issues/2031
> don't reset dark mode on canvas clear

- src/components/App.tsx
- src/components/Portal.tsx
- src/data/index.ts
Please review #2028 first, as PRs are dependent.
> 🎨 Use consistent naming

- src/components/HintViewer.tsx
- src/locales/en.json
> feat: Add hint for double click to insert text

- src/components/App.tsx
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/tests/binding.test.tsx
- src/tests/helpers/ui.ts
fix https://github.com/excalidraw/excalidraw/issues/2095
For absence of tests around binding I'm not sure if my changes didn't break anything.
> rebind arrow on rotation

- src/components/App.tsx
This PR solves #1927 Sticking to grid when pasting an element
close #1927
> allowed for sticking to grid when pasting an element

- src/charts.ts
- src/clipboard.ts
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
- src/components/RoomDialog.tsx
- src/data/index.ts
fix https://github.com/excalidraw/excalidraw/issues/859
Quickly hacked together, not sure if correct. Play with it and report, esp on browsers that don't support async clipboard API (firefox, safari?), and copy/paste between tabs/browsers, using various APIs (keyboard cmd-c/v, contextmenu...).
I'll tighten up the code and write tests later.
> System clipboard

- package-lock.json
- package.json
- src/data/index.ts
- src/data/json.ts
> Pass file extensions with leading dot after API change

- src/components/App.tsx
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/tests/binding.test.tsx
fix https://github.com/excalidraw/excalidraw/issues/2103
> Arrows binds/unbinds to bindable elements when moved with arrow keys (Issue #2103)

- src/components/App.tsx
- src/data/blob.ts
- src/data/index.ts
- src/data/localStorage.ts
- src/data/restore.ts
- src/data/types.ts
- src/index.tsx
- src/types.ts
When restoring `appState`, ensure we merge with `defaultAppState` in case we're supplied a partial state.
Tweaked the typings when I was at it.
> fix restoring appState

- src/components/App.tsx
- src/data/firebase.ts
Save to firebase on unload (if user stays on site), or portal close. Also, do not prevent unload if scene already saved to firebase.
Test plan:
1. create some elements
2. create room and copy the link
3. close room
4. open the room's link again
5. should have the latest scene
and
1. create some elements
2. create room 
3. try to close tab/window
4. will prevent
5. stay on site
6. try to close again after 1-2 sec
7. should allow you to close since the scene was saved
8. load the link again to see latest data
> save room to firebase on unload or portal close

- src/components/ExportDialog.tsx
- src/locales/en.json
- src/scene/export.ts
> add titles with width/height to scale buttons in ExportDialog

- src/components/Modal.tsx
We shouldn't do I/O outside `useEffect`. We haven't noticed this because we're not using strict mode.
> don't touch DOM outside useEffect

- src/components/TopErrorBoundary.tsx
- src/data/blob.ts
- src/data/firebase.ts
- src/data/index.ts
- src/excalidraw-embed/package-lock.json
- src/excalidraw-embed/package.json
- src/excalidraw-embed/webpack.prod.config.js
- src/i18n.ts
>  enable code splitting and add chunk names to dynamic import and create separate chunk vendor for all node modules

- src/components/ColorPicker.scss
- src/components/ColorPicker.tsx
> enable ColorPicker keyboard shortcuts if using custom color

- .gitignore
- src/actions/actionAddToLibrary.ts
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/constants.ts
- src/data/blob.ts
- src/data/json.ts
- src/data/library.ts
- src/data/localStorage.ts
- src/tests/appState.test.tsx
- src/tests/collab.test.tsx
- src/tests/export.test.tsx
- src/tests/fixtures/fixture_library.excalidrawlib
- src/tests/helpers/api.ts
- src/tests/history.test.tsx
- src/tests/library.test.tsx
A [one-line fix](https://github.com/excalidraw/excalidraw/commit/7d151184c5fc5c0e2ac02c9ce3857a5507e11ad8) that turned into a bit of a refactor.
> Fix library dnd

- src/components/ExportDialog.tsx
fix https://github.com/excalidraw/excalidraw/issues/2333
Hack. If anyone has a better idea for preventing flicker due to unmount in effect teardown and waiting on subsequent async render, have at it.
> fix export preview flicker

- .lintstagedrc.js
- src/actions/actionProperties.tsx
- src/clipboard.ts
- src/components/App.tsx
- src/components/Portal.tsx
- src/data/blob.ts
- src/data/firebase.ts
- src/data/library.ts
- src/data/restore.ts
- src/element/linearElementEditor.ts
- src/element/newElement.ts
- src/element/textWysiwyg.tsx
- src/renderer/renderElement.ts
- src/renderer/renderScene.ts
- src/scene/Scene.ts
- src/serviceWorker.tsx
- src/tests/binding.test.tsx
- src/tests/export.test.tsx
- src/tests/regressionTests.test.tsx
- src/types.ts
- src/utils.ts
- src/zindex.ts
I would also suggest `i` -> `index` but I guess we don't want that :)
> Keep errors, elements and comments consistent

- src/components/Dialog.tsx
> fix modal island ref init

- scripts/build-node.js
- src/actions/actionAlign.tsx
- src/actions/actionDeleteSelected.tsx
- src/align.ts
- src/charts.ts
- src/components/LayerUI.tsx
- src/data/firebase.ts
- src/element/newElement.ts
- src/element/textWysiwyg.tsx
- src/ga.ts
- src/gadirections.ts
- src/galines.ts
- src/gapoints.ts
- src/gatransforms.ts
- src/groups.ts
- src/renderer/renderScene.ts
- src/scene/scroll.ts
- src/tests/align.test.tsx
- src/utils.ts
> Prefer arrow functions

- .gitignore
to allow to customize local dev environment
> add `.env.local` to `.gitignore`

- src/actions/actionCanvas.tsx
> don't reset specific appState props on canvas clear

- src/components/App.tsx
- src/data/library.ts
- src/types.ts
- `restore` library items on import
> Fix library import

- package-lock.json
- package.json
fix https://github.com/excalidraw/excalidraw/issues/2362 by reverting https://github.com/excalidraw/excalidraw/pull/2350
> revert socketIO to 2.3.1

- docker-compose.yml
Hello, thanks for this nice project :)
This is a fix for the `docker-compose` command which doesn't work.
The Dockerfile seems to have changed recently but docker-compose.yml hasn't been updated to reflect the changes.
So I've updated the file and it works again now.
> Fix docker-compose 

- src/actions/actionNavigate.tsx
- src/components/Avatar.tsx
> Add border to the Avatars

- analytics.md
- src/components/App.tsx
- src/components/ExportDialog.tsx
- src/data/index.ts
- Text on double click
- Export actions (backend, png, svg, etc)
> More export events

- analytics.md
- src/actions/actionAlign.tsx
- src/actions/actionCanvas.tsx
- src/actions/actionDistribute.tsx
- src/actions/actionProperties.tsx
- src/analytics.ts
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
- src/scene/scroll.ts
- src/zindex.ts
- Stroke style
- Layers
- Align
- Colors (showing picker id)
- Swap name with category
> More events for layers, align, colors and swap name <=> category

- src/components/App.tsx
This was very annoying when you would zoom on mobile and the context menu would appear.
The problem was the following:
- You put a finger in, it creates a timeout
- You put a second finger in, it creates another timeout
- 300ms elapsed, which is not that much
- The context menu opens
- Now you move your fingers, which works, but the context menu is still open
The fix is to invalidate the context menu if a second finger is added even if the first one hasn't moved.
> Don't open context menu when multi-touch

- src/packages/excalidraw/package.json
- src/packages/utils/package.json
https://docs.npmjs.com/cli/v6/using-npm/config#access
> chore(package.json): set public access for npm packages

- src/actions/actionDuplicateSelection.tsx
- src/components/LayerUI.scss
- src/components/LayerUI.tsx
- src/locales/en.json
Fixes #2466 
The design is not the best.. open for ideas :)
> Add link to the public libraries

- README.md
This adds some awareness about https://libraries.excalidraw.com/ to promote and grow the list of libraries.
> Add https://libraries.excalidraw.com/ to README.md

- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/2470
> fix misaligning on grid paste

- src/packages/excalidraw/CHANGELOG.MD
- src/packages/excalidraw/package.json
Version bump needed so that read me gets updated :D
> docs(readme.md): update the homepage url so it redirects to correct readme

- src/excalidraw-app/data/localStorage.ts
> Don't throw error when localStorage is null

- src/components/LayerUI.scss
- src/components/LayerUI.tsx
> Fix Library Menu Layout

- src/components/Stats.scss
> RTL support for the stats dialog

- src/packages/utils.ts
- src/packages/utils/index.js
Tested with a local build for my app, if that makes any sense.
> feat: export exportToCanvas in utils

- src/actions/actionDeleteSelected.tsx
- src/components/ContextMenu.scss
- src/components/ContextMenu.tsx
> Enhance delete button in context menu

- .github/workflows/build-docker.yml
> chore: Don't run docker build on PRs

- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.MD
- src/packages/excalidraw/README.md
- src/packages/excalidraw/index.tsx
- src/utils.ts
- Partial https://github.com/excalidraw/excalidraw/issues/2588, the second part (`exportToBackend`) will take more work.
- plus readme tweaks
> fix: hide collab button when onCollabButtonClick not supplied

- src/components/IconPicker.scss
> fix: Dropdown for Arrowheads overflow

- .github/workflows/semantic-pr-title.yml
Tested the semantic PR title and works fine, supports these [types](https://github.com/excalidraw/excalidraw/runs/1572923930)
> ci: Add semantic pr title action

- src/appState.ts
- src/packages/excalidraw/CHANGELOG.MD
fixes https://sentry.io/share/issue/88e9af4430024029a3b82ebf3df8e809/
> fix(appstate.ts): Remove unnecessary console.error as it was polluting Sentry

- src/components/App.tsx
- src/constants.ts
- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/index.tsx
Fixes #1442
- Changing the `<title>` to `Excalidraw` after 10 sec
- Introduced `constatnas.APP_NAME = "Excalidraw"`
- Using that variable in all places it's used
> feat: Change title to Excalidraw after a timeout

- package-lock.json
- package.json
> chore: update Sentry

- src/element/types.ts
- src/packages/excalidraw/CHANGELOG.md
fix https://github.com/excalidraw/excalidraw/discussions/2672
> docs: add tsdoc for certain element props

- .env
> chore: Update portal URL

- src/actions/actionExport.tsx
- src/keys.ts
- src/packages/excalidraw/CHANGELOG.md
fix https://github.com/excalidraw/excalidraw/issues/2729
> feat: Add cmd+o shortcut to load scene

- .prettierrc
- CONTRIBUTING.md
- README.md
- src/locales/README.md
- src/packages/excalidraw/README.md
- src/packages/utils/CHANGELOG.md
- src/packages/utils/README.md
I recently made my first contribution and through the process learned what was required in each PR.  This PR hopes to help future contributors in following the same guidelines.
> docs: adding PR guidelines for contributors

- .github/workflows/semantic-pr-title.yml
Fixes https://github.com/amannn/action-semantic-pull-request/issues/72
> ci(semantic-pr-title.yml): update version to 3.0.0 so that action doesn't run twice

- README.md
> fix: broken Individuals link

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/package.json
Since readme will get updated so we releasing this version
> docs: update changelog and readme and release 0.2.1

- package-lock.json
- package.json
- src/data/index.ts
- src/data/json.ts
- src/global.d.ts
- src/types.ts
Renamed to reflect Google's efforts to make our language more inclusive: https://developers.google.com/style/inclusive-documentation#features-and-users.
> refactor: Rename browser-nativefs to browser-fs-access

- .github/workflows/build-docker.yml
- .github/workflows/build-packages.yml
- .github/workflows/cancel.yml
- .github/workflows/lint.yml
- .github/workflows/locales-coverage.yml
- .github/workflows/semantic-pr-title.yml
- .github/workflows/sentry-production.yml
- .github/workflows/test.yml
And made them a bit more consistent
> chore: Update workflows to use the latest Node

- src/components/App.tsx
> fix(app.tsx): show correct state of Nerd stats in context menu when nerd stats dialog closed

- vercel.json
Source: https://vercel.com/docs/configuration
> refactor: Use the latest vercel configuration instead of now

- src/components/LayerUI.tsx
fix https://github.com/excalidraw/excalidraw/issues/2907
Also fixes a case where drawing multi-point lines *didn't* disable pointer-events.
Still may turn out buggy. Competing ideas welcome.
> fix: pointer-events being disabled on free-draw

- src/scene/export.ts
fix exporting in non-1x scales
Thanks @wietsevenema  for report
> fix: mistakenly hardcoding scale

- README.md
> docs: Add open collective in readme

- package-lock.json
- package.json
> chore(deps): bump @sentry/* from 6.0.3 to 6.1.0

- src/actions/manager.tsx
- src/components/App.tsx
- src/constants.ts
> fix: allow to toggle between modes when view only mode to make UI consistent

- src/data/restore.ts
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/index.tsx
fixes https://github.com/excalidraw/excalidraw/issues/2692
TODOS
> feat: export restore API's from Excalidraw package

- src/packages/excalidraw/CHANGELOG.md
- src/renderer/renderScene.ts
> fix: show user state only when passed from host

- .dockerignore
- .github/workflows/build-docker.yml
- .github/workflows/build-packages.yml
- .github/workflows/lint.yml
- .github/workflows/locales-coverage.yml
- .github/workflows/sentry-production.yml
- .github/workflows/test.yml
- docker-compose.yml
> chore: Update action versions and docker build

- src/components/App.tsx
- src/data/restore.ts
- src/data/types.ts
- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/tests/scroll.test.tsx
> feat: Add support for scrollToCenter in initialData so host can control whether to scroll to center on mount

- .prettierrc
- package.json
- yarn.lock
- https://github.com/excalidraw/prettier-config/network/dependents
- https://www.npmjs.com/package/@excalidraw/prettier-config
> chore: Use @excalidraw/prettier-config

- public/index.html
Though this should (also) be fixed be fixed alongside #3143
> fix: hide scrollbars in zenMode

- src/actions/actionClipboard.tsx
- src/components/Toast.scss
- src/locales/en.json
> feat: Add export info on copy PNG to clipboard toast message

- src/css/theme.scss
- src/packages/excalidraw/CHANGELOG.md
> fix: scope css variables so that host css vars don't clash with excalidraw

- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/collab/Portal.tsx
- src/excalidraw-app/index.tsx
> chore: Track collaboration

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/package.json
> docs: release patch version 0.4.3

- src/components/Modal.scss
> fix: double scrollbar on modals

- src/actions/actionClipboard.tsx
- src/components/App.tsx
- src/keys.ts
Reverts https://github.com/excalidraw/excalidraw/pull/3206 (#3205) to fix https://github.com/excalidraw/excalidraw/issues/3267
We'll need to come up with a different solution
> fix: Revert `906faaf0` #3206

- CONTRIBUTING.md
- src/packages/utils/package.json
Fixed a typo that remained after changing npm to yarn
> chore: fix npm to yarn in contributing.md and package.json

- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/3282
> fix: state continuously updated when holding ctrl/cmd

- src/components/icons.tsx
- src/excalidraw-app/collab/RoomDialog.tsx
> fix: Show Windows share icon for Windows users

- src/components/HelpIcon.tsx
- src/css/styles.scss
> fix: Make help toggle tabbable

- src/components/App.tsx
> fix: disallow create text in viewMode on mobile

- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/3332
> fix: state selection state on opening contextMenu

- public/index.html
> chore: Remove duplicate Twitter og:image

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/data/json.ts
> feat: reopen library menu on import from file

- src/css/styles.scss
> fix: export dialog canvas positioning

- src/components/App.tsx
> feat: enable drop event on the whole component

- src/components/ErrorDialog.tsx
- src/data/blob.ts
fix https://github.com/excalidraw/excalidraw/issues/3402
> fix: incorrectly caching png file handle

- src/element/textWysiwyg.test.tsx
- src/element/textWysiwyg.tsx
> feat: support tab in text Wyswig

- src/components/App.tsx
- src/element/index.ts
- src/scene/scroll.ts
@ad1992 this is most likely the cause of the bug I was talking about in chat a while back
> fix: scrollToContent only on visible elements

- README.md
fixes https://github.com/excalidraw/excalidraw/issues/3445
> docs: update local installation instructions in readme

- src/components/App.tsx
- src/packages/excalidraw/CHANGELOG.md
fixes https://github.com/excalidraw/excalidraw/issues/3475
try [here](https://y0ld3.csb.app/)
> fix: only handle cut/paste events inside excalidraw

- src/components/App.tsx
- src/components/FixedSideContainer.scss
- src/components/LayerUI.scss
- src/components/LayerUI.tsx
- src/components/UserList.scss
- src/css/styles.scss
- src/css/theme.scss
- src/excalidraw-app/components/GitHubCorner.tsx
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
- src/types.ts
fix https://github.com/excalidraw/excalidraw/issues/3101
> feat: add `renderTopRight` prop & remove GH corner from core

- src/excalidraw-app/index.tsx
Adds Excalidraw+ promo link, swapping the GH logo for a while.
> feat: add temporary Excalidraw+ promo

- src/components/icons.tsx
- src/locales/en.json
- src/renderer/renderElement.ts
- src/tests/scene/__snapshots__/export.test.ts.snap
Unsure if I've resolved the conflicts correctly because the commit ~~depended on~~ contained some code from https://github.com/excalidraw/excalidraw/pull/3512 (these conflicts will likely arise again when merging this branch into it).
[![round_caps_small](https://user-images.githubusercontent.com/5153846/116792299-089ece00-aac0-11eb-91a3-fd4f907e9b33.png)](https://user-images.githubusercontent.com/5153846/116792110-f6706000-aabe-11eb-913f-f89512fe75ac.png)
```
{"type":"excalidraw/clipboard","elements":[{"id":"L4X_XkeeHpMW7pdZm-OuC","type":"rectangle","x":870.0203155402489,"y":-113.28920947628681,"width":94.00000000000003,"height":81,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":0,"opacity":100,"groupI …
```
> feat: Adds rounded icons, joins and caps.

- src/actions/actionCanvas.tsx
- src/actions/index.ts
- src/actions/types.ts
- src/components/BackgroundPickerAndDarkModeToggle.tsx
- src/components/HelpDialog.tsx
- src/keys.ts
- src/locales/en.json
> feat: Add shortcut for dark mode

- src/components/App.tsx
- src/data/library.ts
ensure we restore on library import & pasting
> fix: restore on paste or lib import

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
- src/types.ts
> refactor: rename renderTopRight prop to renderTopRightUI

- src/components/App.tsx
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/README_NEXT.md
fixes https://github.com/excalidraw/excalidraw/issues/3176, https://github.com/excalidraw/excalidraw/issues/3485
> feat: support updating appState in updateScene API

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/package.json
> docs: release @excalidraw/excalidraw@0.8.0 🎉 

- src/element/bounds.ts
making it proportional to the length of the last segment of the arrow
> perf: Improve arrow head sizing

- src/components/LayerUI.tsx
for https://github.com/excalidraw/excalidraw-libraries/pull/106
Can be merged in any order.
> feat: pass current `theme` when installing libraries

- src/components/App.tsx
- src/components/Dialog.tsx
- src/components/ErrorDialog.tsx
- src/components/LockIcon.tsx
- src/components/Modal.tsx
- src/components/ProjectName.tsx
- src/components/Section.tsx
- src/components/ToolButton.tsx
- src/css/styles.scss
- src/packages/excalidraw/CHANGELOG.md
- src/setupTests.ts
- src/tests/packages/__snapshots__/excalidraw.test.tsx.snap
- src/tests/packages/excalidraw.test.tsx
Remove id where it wasn't needed
fixes #3683
> fix: use excal id so every element has unique id 

- src/actions/actionToggleViewMode.tsx
- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/3739
Elements weren't deselected when viewMode toggled programmatically.
> fix: deselect elements on viewMode toggle

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
- src/packages/utils.ts
fixes https://github.com/excalidraw/excalidraw/issues/3634
> feat: expose getFreeDrawSvg, loadFromBlob and loadLibraryFromBlob from excalidraw package

- package.json
- src/actions/actionExport.tsx
- yarn.lock
> chore: bump browser-fs-access

- scripts/updateChangelog.js
Script to update the changelog for library updates before stable release
> build: Add script to update changelog before stable release

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
* Added missing pr links in the changelog
* Tweaked docs as per the feedback received from users.
* Move to discussions
> docs: tweak changelog and readme

- scripts/release.js
- scripts/updateChangelog.js
- scripts/updateReadme.js
We will try this script for the next few releases and once this works out well we can automate publish via gh action as well so the release will be fully automated.
> build: Add script to update package.json and commit for next release

- Dockerfile
> chore: Bump nginx version to newest

- src/components/App.tsx
- src/constants.ts
- src/tests/viewMode.test.tsx
Fix for issue #3783. Changes cursor to pointer after turning on view mode, add keeps it through clicks, pressing space, and movement.
> fix: view mode cursor adjustments

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/package.json
feels 🥳 when the release process is automated :D
> docs: release @excalidraw/excalidraw@0.9.0  🎉

- public/index.html
- public/manifest.json
Add origin trial tokens for File Handling and Declarative Link Capturing.
We supported both features for a long time, but people had to have the "experimental web platform features" flag set. This PR makes it so that everyone will be able to use those features.
> feat: Add origin trial tokens

- .github/dependabot.yml
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit
> chore: Update dependabot limits

- .env
- .env.production
Waiting for https://json-dev.excalidraw.com
> feat: Use separate json backend for `development` environment

- package.json
- yarn.lock
fix https://github.com/excalidraw/excalidraw/issues/3906
before/after:
> fix: ellipse roughness when `0`

- .github/workflows/publish-docker.yml
> chore: Update docker action to v2

- src/components/App.tsx
> fix: account for libraries v2 when prompting

- src/actions/actionAddToLibrary.ts
> fix: prevent adding images to library via contextMenu

- package.json
- src/packages/excalidraw/package.json
- src/packages/excalidraw/yarn.lock
- tsconfig-types.json
- tsconfig.json
- yarn.lock
fix https://github.com/excalidraw/excalidraw/issues/4282
> chore: bump typescript@4.5.2

- src/scene/zoom.ts
> feat: allow zooming up to 3000%

- src/renderer/renderElement.ts
- src/scene/comparisons.ts
Fixes #4266 
PS: This PR might needs a few more changes to support edge selection for diamond
> feat: Add support for rounded corners in diamond

- src/excalidraw-app/data/firebase.ts
fix https://github.com/excalidraw/excalidraw/issues/4355
> fix: make firebase config parsing not fail on undefined env

- .husky/pre-commit
> fix: husky not able to execute pre-commit on windows

- src/components/App.tsx
- src/element/textWysiwyg.tsx
fixes #4412 
Try in https://1m7pt.csb.app/
> fix: update viewport coords correctly when editing text

- src/element/textWysiwyg.tsx
Introduced as a regression in #4444 
fixes https://github.com/excalidraw/excalidraw/issues/4455
> fix: update height correctly when updating text properties in binded text

- src/element/textWysiwyg.tsx
> fix: vertically align single line when deleting text in bounded container

- src/components/App.tsx
- src/element/dragElements.ts
fixes https://github.com/excalidraw/excalidraw/issues/4456
> fix: support dragging binded text in container selected in a group

- src/actions/actionGroup.tsx
> fix: don't select binded text when ungrouping

- src/components/App.tsx
- src/element/collision.ts
- src/element/textElement.ts
- src/scene/comparisons.ts
The review fixes for https://github.com/excalidraw/excalidraw/pull/4343
> fix: pending review fixes for sticky notes

- src/actions/actionProperties.tsx
- src/actions/actionStyles.ts
- src/element/textElement.ts
- src/element/textWysiwyg.tsx
- src/scene/selection.ts
> feat: Support updating text properties of bounded text by selecting the container

- src/components/HelpDialog.tsx
- src/components/HintViewer.tsx
- src/locales/en.json
> feat: hints and shortcuts help around deep selection

- src/constants.ts
- src/element/textElement.test.ts
- src/element/textElement.ts
fixes https://github.com/excalidraw/excalidraw/issues/4498
> fix: Reduce padding to 5px for bounded text

- src/actions/actionProperties.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4520
> feat: update stroke color of bounded text along with container

- src/components/App.tsx
- src/constants.ts
- src/excalidraw-app/data/localStorage.ts
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/example/App.js
- src/types.ts
> feat: support updating library in updateScene API

- src/components/App.tsx
> fix: prevent canvas drag while editing text

- .env.development
- README.md
Related PR https://github.com/excalidraw/excalidraw-room/pull/305
> fix: port for collab server

- src/data/restore.ts
fix https://github.com/excalidraw/excalidraw/issues/4579
> fix: support collaboration in bounded text

- src/components/App.tsx
- src/element/newElement.ts
- src/element/textWysiwyg.tsx
- src/packages/excalidraw/index.tsx
- src/tests/binding.test.tsx
- src/types.ts
fixes https://github.com/excalidraw/excalidraw/issues/4564
https://user-images.githubusercontent.com/11256141/149111470-ca4d77fe-86bf-46ca-8ed5-a08f47038212.mov
> fix: support collaboration in bound text

- src/components/App.tsx
Fix for Apple Pen Scribble
fix #3502 fix #3955
> fix: Apple Pen missing strokes

- src/components/Actions.tsx
- src/element/Hyperlink.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4697
> feat: show group/group and link action in mobile

- src/element/resizeElements.ts
https://user-images.githubusercontent.com/11256141/154932547-65e728bc-90ac-426d-b739-e417a9f6d1ba.mp4
fixes https://github.com/excalidraw/excalidraw/issues/4805
> fix: support resizing multiple bound text containers

- src/actions/actionStyles.ts
fixes https://github.com/excalidraw/excalidraw/issues/4841
> fix: redraw text bounding box when pasting styles

- package.json
- yarn.lock
> chore: remove `firebase-tools`

- src/actions/actionDistribute.tsx
- src/actions/actionStyles.test.tsx
- src/actions/manager.tsx
- src/tests/contextmenu.test.tsx
- src/tests/helpers/ui.ts
- src/tests/regressionTests.test.tsx
fix https://github.com/excalidraw/excalidraw/issues/4884
the fix is 2 lines (`actionDistribute.tsx`). The rest are tests.
> fix: paste styles shortcut

- .env.development
- .env.production
- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/data/index.ts
added optional REACT_APP_WS_SERVER_URL to be able to set collaboration ws server url easily from enviro vars
> feat: added optional REACT_APP_WS_SERVER_URL for forks usecases

- src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4903
https://user-images.githubusercontent.com/11256141/158141070-7e7db9c9-a5b7-4b2e-a60e-bf6d40e3ca31.mp4
> fix: undo when erasing elements by clicking

- src/components/LayerUI.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4928
> fix: Hide eraser in view mode in desktop

- src/components/App.tsx
- src/element/textWysiwyg.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4895
https://user-images.githubusercontent.com/11256141/159300607-57c97096-a576-4658-bcc8-3744d46cea37.mp4
> fix: don't bind text to container if already present

- src/components/App.tsx
- src/constants.ts
- src/types.ts
https://user-images.githubusercontent.com/11256141/159440279-6487dfcd-c0ad-4a20-8656-1eb5ee698fe0.mp4
> fix: restore original opacities when alt pressed while erasing

- src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4949
> fix: cancel erase elements on pointer up if eraser is not active on pointer up

- src/components/Actions.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4959
> fix: show link icon for bound text containers

- src/element/textWysiwyg.tsx
- src/scene/Scene.ts
> fix: updateWysiwygStyle updatedElement is undefined TypeError

- src/actions/actionCanvas.tsx
- src/actions/actionFinalize.tsx
- src/types.ts
> feat: Eraser toggle to switch back to the previous tool

- src/element/image.ts
fix https://github.com/excalidraw/excalidraw/issues/5043
> fix: ensure svg image dimensions are always set

- src/components/Actions.tsx
> fix: Add image button not working on iPad

- src/actions/manager.tsx
- src/components/App.tsx
Doesn't handle all cases, but the most common.
> feat: stop event propagation when key handled

- src/element/textWysiwyg.tsx
attempt to fix https://github.com/excalidraw/excalidraw/issues/5134, https://github.com/excalidraw/excalidraw/issues/4822
> fix: jumping of text when typing single line in bound text

- src/actions/actionProperties.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5106
https://user-images.githubusercontent.com/11256141/166634455-52640c4c-08b6-4d51-85ef-d5d67c0aa9f6.mp4
> fix: update opacity of bound text when opacity of container updated

- src/components/LibraryMenuItems.tsx
- src/components/PublishLibrary.scss
- src/components/PublishLibrary.tsx
- src/components/SingleLibraryItem.scss
- src/components/SingleLibraryItem.tsx
- src/locales/en.json
> feat: support resubmitting published library items

- .env.production
- src/constants.ts
- src/excalidraw-app/index.scss
- src/excalidraw-app/index.tsx
- feat: added for signed in excalidraw plus user button to easily go to  app.excalidraw.com
- second part of the auto-redirect feat
> feat: go-to-excalidrawplus button

- src/components/App.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/example/App.js
- src/types.ts
- src/utils.ts
https://user-images.githubusercontent.com/11256141/169529720-6b3535a2-26a0-434a-9ca5-d62036cd2a84.mp4
> feat: support setting/resetting cursor from host

- src/components/InitializeApp.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5339
> fix: delay loading until language imported

- src/components/ColorPicker.tsx
- src/components/Dialog.tsx
- src/components/Popover.tsx
- src/utils.ts
fixed tabbing focus trap not working correctly in color picker, and not implemented at all for other popovers
> fix: focus traps inside popovers

- src/data/json.ts
fix https://github.com/excalidraw/excalidraw/issues/5371
> fix: file handle not persisted when importing excalidraw files

- src/i18n.ts
> build: extract all i18n files into locales folder

- src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5214
> fix: prevent browser zoom inside Excalidraw

- src/packages/excalidraw/package.json
To make sure whenever PR is merged the types are working fine
> fix: generate types when building example

- .github/workflows/publish-docker.yml
Fixing push to DockerHub
Updating build and push to the latest version
> fix: Fixing push to DockerHub

- src/components/Popover.tsx
fixes #5519 (issue was introduced with #4030)
https://user-images.githubusercontent.com/14358394/182214660-ab094ee9-ee60-478d-8689-14f6b68774ed.mp4
> fix: Context menu positioning when component has offsets

- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/5539
> fix: line deselected when shift-dragging point outside editor

- src/components/App.tsx
- src/element/collision.ts
- src/element/transformHandles.ts
- src/renderer/renderScene.ts
for https://github.com/excalidraw/excalidraw/issues/5535
https://user-images.githubusercontent.com/11256141/183853657-d3c561d0-d0df-482e-ad6f-08ef28fac4a7.mp4
> fix: show bounding box for 3 or more linear point elements

- src/components/App.tsx
> fix: check if hitting link in handleSelectionOnPointerDown

- src/components/App.tsx
- src/element/collision.ts
- src/element/transformHandles.ts
- src/renderer/renderScene.ts
fixes https://github.com/excalidraw/excalidraw/issues/5576
> fix: allow box selection of points when inside editor

- src/element/linearElementEditor.ts
> fix: Crash when adding a new point in the line editor #5602

- src/components/Footer.tsx
fix https://github.com/excalidraw/excalidraw/issues/5630
> fix: reintroduce help dialog button

- src/components/LayerUI.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5637
> fix: library actions inside the sidebar

- package.json
- src/components/LibraryMenuItems.tsx
- src/excalidraw-app/collab/Portal.tsx
- yarn.lock
before installed them, following errors were appearing:
```
Failed to resolve import "pica" from "../../packages/excalidraw/src/data/blob.ts"
Failed to resolve import "lodash" from "../../packages/excalidraw/src/components/LibraryMenuItems.tsx".
```
> build: add missing dependencies: pica, lodash

- src/components/Actions.tsx
- src/components/Footer.tsx
fix https://github.com/excalidraw/excalidraw/issues/5675
> fix: zen-mode exit button not working

- src/data/blob.ts
> chore: fix typo in blob.ts

- src/packages/excalidraw/example/App.tsx
> chore: fix typo in clipboard alert

- src/components/App.tsx
- src/element/newElement.ts
- src/element/textElement.ts
- src/element/textWysiwyg.tsx
This will be useful later in the future PRs as the dimensions will need to be computed based on shape
> refactor: create a util to compute container dimensions for bound text container

- src/element/textElement.ts
- src/element/textWysiwyg.test.tsx
- src/tests/resize.test.tsx
- src/tests/utils.ts
> fix: horizontal text alignment for bound text when resizing

- src/components/Actions.tsx
- src/components/App.tsx
- src/components/LockButton.tsx
- src/tests/queries/toolQueries.ts
- src/tests/selection.test.tsx
~~https://github.com/excalidraw/excalidraw/issues/5776~~ actually turns out that was a different issue
> fix: incorrectly selecting linear elements on creation while tool-locked

- src/excalidraw-app/collab/Collab.tsx
- src/excalidraw-app/index.tsx
fix https://github.com/excalidraw/excalidraw/issues/5831
> feat: refetch errored/pending images on collab room init load

- src/element/textWysiwyg.test.tsx
- src/element/textWysiwyg.tsx
> fix: Paste clipboard contents into unbound text elements

- src/element/textWysiwyg.test.tsx
- src/element/textWysiwyg.tsx
> fix: merge existing text with new when pasted

- src/components/icons.tsx
> fix: SVG element attributes in icons.tsx

- src/components/App.tsx
- src/components/ContextMenu.tsx
- src/components/ImageExportDialog.tsx
fix https://github.com/excalidraw/excalidraw/issues/5551
> fix: remove legacy React.render() from the editor

- src/actions/shortcuts.ts
- src/components/HelpDialog.tsx
- src/utils.ts
fix https://github.com/excalidraw/excalidraw/issues/5889
fix https://github.com/excalidraw/excalidraw/issues/5734
> fix: stop replacing `del` word with `Delete`

- src/element/resizeElements.ts
- src/element/textWysiwyg.test.tsx
- src/element/typeChecks.ts
https://user-images.githubusercontent.com/11256141/204752715-0e0334a2-4335-4f67-af1a-fde2ed243680.mp4
fixes https://github.com/excalidraw/excalidraw/issues/5842
> fix: scale font correctly when using shift

- src/data/restore.ts
hot fix https://github.com/excalidraw/excalidraw/issues/5953
tests tomorrow
> fix: repair element bindings on restore

- src/components/LayerUI.scss
- src/excalidraw-app/index.scss
- src/packages/excalidraw/example/App.scss
- src/packages/excalidraw/example/App.tsx
Partially https://github.com/excalidraw/excalidraw/issues/5960
> fix: renderFooter styling

- src/components/App.tsx
- src/components/HelpDialog.tsx
- src/keys.ts
- src/locales/en.json
- src/tests/scroll.test.tsx
Fixes #5765.  Includes a test.
> feat: Scroll using PageUp and PageDown

- src/renderer/renderElement.ts
- src/scene/scroll.ts
- src/utils.ts
editor (reference):
export, before fix:
export, after fix:
> fix: png-exporting does not preserve angles correctly for flipped images

- src/components/LayerUI.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/utils.ts
fix https://github.com/excalidraw/excalidraw/issues/6089
> feat: render unknown supplied children to UI

- src/components/ExportDialog.scss
> style: change in ExportButton style (#6147)

- src/element/textElement.test.ts
- src/element/textElement.ts
- Fixes issue #6145 
Array.from() split a string into characters without break emojis.
> fix: :bug: broken emojis when wrap text

- src/components/dropdownMenu/DropdownMenuItem.tsx
- src/components/dropdownMenu/DropdownMenuItemLink.tsx
- src/components/dropdownMenu/common.ts
change getDrodownMenuItemClassName to getDropdownMenuItemClassName
> fix: quick typo fix 

- src/element/textElement.ts
- src/element/textWysiwyg.test.tsx
- src/tests/__snapshots__/linearElementEditor.test.tsx.snap
- src/tests/data/__snapshots__/restore.test.ts.snap
- src/tests/linearElementEditor.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/6173
> fix: add 1px width to the container to calculate more accurately

- src/element/textElement.ts
- src/element/textWysiwyg.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/6179
Introduced as a regression in #5723
> fix: horizontal padding when aligning bound text containers

- dev-docs/docusaurus.config.js
> docs: show last updated time and author

- src/clients.ts
- src/excalidraw-app/collab/RoomDialog.tsx
- src/tests/clients.test.ts
fixes https://github.com/excalidraw/excalidraw/issues/6208
> fix: don't allow blank space in collab name

- dev-docs/docusaurus.config.js
https://user-images.githubusercontent.com/11256141/218452839-7575ee9f-c0a6-4270-9497-476d577e2dd7.mp4
> docs: enable Algolia for search

- src/components/App.tsx
- src/data/blob.ts
- src/data/restore.ts
- src/excalidraw-app/collab/Collab.tsx
- src/excalidraw-app/data/index.ts
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/tests/data/restore.test.ts
fixes https://github.com/excalidraw/excalidraw/issues/6237
Will update the DOCS in next branch.
> feat: Make repair and refreshDimensions configurable in restoreElements

- dev-docs/docs/introduction/contributing.mdx
> docs: Fixed broken codesandbox link in the dev-docs

- README.md
> docs: new readme

- src/components/App.tsx
- src/element/textElement.ts
- src/element/textWysiwyg.test.tsx
- src/element/typeChecks.ts
fixes https://github.com/excalidraw/excalidraw/issues/5794
https://user-images.githubusercontent.com/11256141/219024410-e6a913b4-e32d-4c54-93d0-c5bf80b0b76b.mp4
> feat: Bind text to container if double clicked on filled shape or stroke

- src/renderer/renderElement.ts
fix https://github.com/excalidraw/excalidraw/issues/6284
> fix: svg text baseline (#6285

- src/element/textWysiwyg.test.tsx
- src/element/textWysiwyg.tsx
Regression got introduced in #6187 
https://user-images.githubusercontent.com/11256141/221545740-c69c3e4e-08c8-47ae-8a17-23066546e361.mov
> fix: text never goes beyond max width for unbound text elements

- src/components/Popover.scss
- src/components/Popover.tsx
https://user-images.githubusercontent.com/61119157/230742880-2917924d-9477-4dd6-81cf-163755a611f9.mp4
https://user-images.githubusercontent.com/61119157/230742941-288d3b31-3d04-4d55-86fa-af0b7f195e4f.mp4
> fix: fixing popover overflow on small screen

- src/actions/actionBoundText.tsx
- src/element/textElement.ts
- src/element/textWysiwyg.test.tsx
- src/tests/linearElementEditor.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/6435
TODOS
> fix: update coords when text unbinded from its container

- .github/workflows/publish-docker.yml
_Not tested_, I'm not a github CI user, this MR is here to suggest an implementation to fix #6507
> build: Add version tags to Docker build

- src/components/ColorPicker.scss
- src/components/ContextMenu.scss
- src/components/Tooltip.scss
- src/css/styles.scss
The browser default font was showing up in various locations. Fixed them to show the desired ui font.
fixes https://github.com/excalidraw/excalidraw/issues/6493
> style: fix font family inconsistencies

- src/element/newElement.ts
- src/element/resizeElements.ts
- src/element/textElement.test.ts
- src/element/textElement.ts
- src/element/textWysiwyg.tsx
- src/renderer/renderElement.ts
- src/tests/linearElementEditor.test.tsx
> fix: cleanup getMaxContainerHeight and getMaxContainerWidth

- public/index.html
- src/analytics.ts
- src/global.d.ts
- let's test those two for now.
> feat: testing simple analytics and fathom analytics for better privacy of the users

- src/clients.ts
- src/components/Avatar.tsx
- src/tests/clients.test.ts
> fix: garbled text displayed on avatars 

- src/element/resizeElements.ts
[Screencast from 2023-06-09 15-52-16.webm](https://github.com/excalidraw/excalidraw/assets/45559664/9004d234-d4fd-4e27-bc16-89a25a1688c0)
> fix: bound arrows not updated when rotating multiple elements

- src/actions/actionNavigate.tsx
- src/clients.ts
- src/components/Avatar.scss
- src/components/Avatar.tsx
- src/renderer/renderScene.ts
Updated cursors for collaborators
> feat: redesigned collab cursors

- .env.development
- .env.production
- public/index.html
- src/analytics.ts
- removed GA analytics
- replaced them with privacy & GDPR friendly simple analytics
- tracking iframe embedding as event not as page view to not skew the stats
- allow only specific events to track when we will need it
> feat: simple analitycs

- src/charts.ts
fix getChartDimentions to getChartDimensions
> fix: typo in chart.ts

- src/packages/excalidraw/.size-limit.json
to support size increase in https://github.com/excalidraw/excalidraw/pull/6759
> build: increase limit for bundle by 1kb

- src/components/App.tsx
- src/components/canvases/InteractiveCanvas.tsx
related to #6885
I am not yet able to systematically reproduce the error reported in #6885, however I believe the querySelector(".excalidraw") should be solved anyway. This solution replaces the querySelector with a forwardedRef.
> fix: scope `--color-selection` retrieval to given instance

- src/components/canvases/InteractiveCanvas.tsx
- src/components/canvases/StaticCanvas.tsx
- src/groups.ts
- src/renderer/renderScene.ts
- src/tests/__snapshots__/contextmenu.test.tsx.snap
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/tests/dragCreate.test.tsx
- src/tests/linearElementEditor.test.tsx
- src/tests/move.test.tsx
- src/tests/multiPointCreate.test.tsx
- src/tests/selection.test.tsx
- src/types.ts
fix https://github.com/excalidraw/excalidraw/issues/6884
> fix: make canvas compos memoize appState on props they declare

- src/components/App.tsx
regression from https://github.com/excalidraw/excalidraw/pull/6747
> fix: resetting deleted elements on duplication

- src/actions/actionProperties.tsx
This allows custom actions to modify the contents of `ExcalidrawElement.customData`.
> feat: export `changeProperty()` and `getFormValue()`.

- src/element/typeChecks.ts
https://github.com/excalidraw/excalidraw/issues/6899
> fix: isBindableElement to affirm frames

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/package.json
Blocked by https://github.com/excalidraw/excalidraw/pull/6879, https://github.com/excalidraw/excalidraw/pull/6976
> docs: release @excalidraw/excalidraw@0.16.0  🎉

- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/7023
regressed in https://github.com/excalidraw/excalidraw/pull/7005
> fix: frame name not editable on dbl-click

- src/components/icons.tsx
> feat: Export `iconFillColor()`

- src/components/App.tsx
> fix: regression from #6739 preventing redirect link in view mode

- src/components/Actions.scss
- src/components/FilledButton.scss
- src/components/HelpDialog.scss
- src/components/LibraryMenu.scss
- src/components/RadioGroup.scss
- src/components/Sidebar/SidebarTrigger.scss
- src/components/Switch.scss
- src/components/TextField.scss
- src/components/ToolIcon.scss
- src/components/Toolbar.scss
- src/components/dropdownMenu/DropdownMenu.scss
- src/components/live-collaboration/LiveCollaborationTrigger.scss
- src/components/main-menu/MainMenu.tsx
- src/components/welcome-screen/WelcomeScreen.scss
- src/css/styles.scss
- src/css/theme.scss
- src/css/variables.module.scss
This PR introduces a bit of a colour scheme refresh per our Figma specs. Some changes/deviations might be present due to insufficient context but it should largely follow the specs.
> feat: new dark mode theme & light theme tweaks

- src/components/Actions.tsx
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
fix https://github.com/excalidraw/excalidraw/issues/7147
TODO
> fix: double image dialog shown on insert

- src/components/App.tsx
- src/cursor.ts
- src/tests/tool.test.tsx
- src/utils.ts
> feat: support `props.locked` for `setActiveTool`

- src/element/collision.ts
fix https://github.com/excalidraw/excalidraw/issues/7191
> fix: freedraw non-solid bg hitbox not working

- src/element/embeddable.ts
tested on
```
https://giphy.com/clips/southpark-episode-1-season-7-south-park-pg66I8sglfvAUhiX0u
```
```
https://giphy.com/embed/2x0VePimPaFJDpGZ7H
```
```
<div style="width:480px"><iframe allow="fullscreen" frameBorder="0" height="270" src="https://giphy.com/embed/pg66I8sglfvAUhiX0u/video" width="480"></iframe></div>
```
> feat: support giphy.com embed domain

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/index.tsx
docs added in https://github.com/excalidraw/excalidraw/pull/7248
> feat: export getCommonBounds util

- excalidraw-app/index.tsx
- src/components/App.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/example/App.tsx
- src/packages/excalidraw/index.tsx
- src/tests/packages/events.test.tsx
- src/tests/tool.test.tsx
- src/types.ts
closes https://github.com/excalidraw/excalidraw/issues/6177
> feat: support excalidrawAPI and remove refs support

- src/scene/Shape.ts
fix https://github.com/excalidraw/excalidraw/issues/7231 
fix https://github.com/excalidraw/excalidraw/issues/7239
> feat: make adaptive-roughness less aggressive

- dev-docs/docs/@excalidraw/excalidraw/api/children-components/sidebar.mdx
- dev-docs/docs/@excalidraw/excalidraw/api/excalidraw-element-skeleton.mdx
- dev-docs/docs/@excalidraw/excalidraw/api/props/excalidraw-api.mdx
- dev-docs/docs/@excalidraw/excalidraw/api/props/props.mdx
- dev-docs/docs/@excalidraw/excalidraw/api/props/ui-options.mdx
- dev-docs/docs/@excalidraw/excalidraw/api/utils/utils-intro.md
- dev-docs/docs/@excalidraw/excalidraw/faq.mdx
- dev-docs/docs/@excalidraw/excalidraw/integration.mdx
- dev-docs/docusaurus.config.js
- dev-docs/package.json
- dev-docs/sidebars.js
- dev-docs/yarn.lock
- src/packages/excalidraw/CHANGELOG.md
> docs: Docs for v0.17.0 🚀

- excalidraw-app/collab/Portal.tsx
- excalidraw-app/data/firebase.ts
Strangely it build in the PR's CI, but not in master.
> fix: import `Socket` as type

- README.md
> docs: add steps for local development 

- packages/excalidraw/components/App.tsx
- packages/excalidraw/element/embeddable.ts
- packages/excalidraw/element/textElement.ts
- packages/excalidraw/utils.ts
- adds support to insert multiple embeds by pasting multiple urls, separated by newline(s)
- adds support for `x.com` domain
> feat: support multi-embed pasting & x.com domain

- packages/excalidraw/components/icons.tsx
- packages/excalidraw/components/main-menu/DefaultItems.tsx
- packages/excalidraw/locales/en.json
- packages/excalidraw/tests/__snapshots__/excalidraw.test.tsx.snap
> feat: update X brand logo & tweak labels

- packages/excalidraw/components/App.tsx
This PR makes sure that eraser erases groups in one go.
> feat: erase groups atomically

- packages/excalidraw/actions/actionNavigate.tsx
- packages/excalidraw/components/UserList.scss
Will fix https://github.com/excalidraw-teams/excalidraw-teams/issues/1078.
> fix: Truncate collaborator name in dropdown.

- packages/excalidraw/frame.ts
> fix: frame name editing inconvenience

- dev-docs/docs/@excalidraw/excalidraw/api/props/excalidraw-api.mdx
i thought it might be typo. there is no toggleMenu in excalidraw api.
> docs: toggleSidebar api fix

- .env.development
- .env.production
- excalidraw-app/collab/Collab.tsx
- excalidraw-app/data/index.ts
- excalidraw-app/tests/collab.test.tsx
- getting rid of portal logic, since it's no longer needed
> refactor: remove portal as it is no longer needed

- .env.development
3002 is the default port we use in https://github.com/excalidraw/excalidraw-room
> chore: change default port of collab server

- excalidraw-app/collab/RoomDialog.tsx
- packages/excalidraw/actions/manager.tsx
- packages/excalidraw/components/FilledButton.scss
- packages/excalidraw/components/FilledButton.tsx
- packages/excalidraw/components/ImageExportDialog.scss
- packages/excalidraw/components/ImageExportDialog.tsx
- packages/excalidraw/components/ShareableLinkDialog.tsx
- packages/excalidraw/components/ToolButton.tsx
- adds loading state if `onClick` returns a promise
- during loading, disables button from submit
> feat: add loading state to FilledButton

- packages/excalidraw/CHANGELOG.md
branch - https://github.com/excalidraw/excalidraw/compare/master...aakansha/v0.17.3
> docs: release patch v0.17.3

- packages/excalidraw/actions/actionClipboard.tsx
- packages/excalidraw/actions/actionDeleteSelected.tsx
- packages/excalidraw/actions/actionDuplicateSelection.tsx
- packages/excalidraw/actions/actionFinalize.tsx
- packages/excalidraw/actions/actionFlip.ts
- packages/excalidraw/actions/actionLinearEditor.ts
- packages/excalidraw/actions/actionSelectAll.ts
- packages/excalidraw/components/App.tsx
- packages/excalidraw/data/transform.ts
- packages/excalidraw/element/binding.ts
- packages/excalidraw/element/linearElementEditor.ts
- packages/excalidraw/renderer/renderScene.ts
- packages/excalidraw/tests/move.test.tsx
> fix: make LinearElementEditor independent of scene

- packages/excalidraw/clipboard.ts
- packages/excalidraw/components/App.tsx
- packages/excalidraw/frame.ts
- packages/excalidraw/renderer/renderElement.ts
- packages/excalidraw/scene/Scene.ts
- packages/excalidraw/scene/export.ts
- packages/excalidraw/scene/selection.ts
> fix: remove scene hack from export.ts & remove pass elementsMap to getContainingFrame

- packages/utils/global.d.ts
- packages/utils/package.json
- packages/utils/tsconfig.json
try here - https://codesandbox.io/p/sandbox/excalidraw-esm-djfq22?file=%2Fsrc%2FApp.tsx%3A31%2C1
or if you want to test try `@excalidraw/utils@0.1.3-test7`
> build: export types for @excalidraw/utils

- packages/excalidraw/element/textElement.ts
fix https://github.com/excalidraw/excalidraw/issues/7751
> fix: add missing font metrics for Assistant

- packages/excalidraw/components/App.tsx
- packages/utils/geometry/shape.ts
> fix: hit test for closed sharp curves

- packages/excalidraw/element/embeddable.ts
fix https://github.com/excalidraw/excalidraw/issues/7888
I've also removed dddice.com because it seems the embed isn't working correctly anymore even despite `allow-same-origin` (though we'd also likely not want to allow that flag for this domain, going forward). /cc @FilBot3
> fix: allow same origin for all necessary domains

- excalidraw-app/App.tsx
- excalidraw-app/collab/Collab.tsx
- excalidraw-app/data/firebase.ts
- packages/excalidraw/index.tsx
> feat: export reconciliation

- packages/excalidraw/components/SVGLayer.scss
- packages/excalidraw/css/styles.scss
- increased z-index of SVG layer, so laser pointer can used on embeds and such
> fix: z-index for laser pointer to be able to draw on embeds and such

- packages/excalidraw/components/Actions.tsx
- packages/excalidraw/components/ButtonIconSelect.tsx
- packages/excalidraw/components/CheckboxItem.tsx
- packages/excalidraw/components/ContextMenu.tsx
- packages/excalidraw/components/Dialog.tsx
- packages/excalidraw/components/FollowMode/FollowMode.tsx
- packages/excalidraw/components/IconPicker.tsx
- packages/excalidraw/components/LayerUI.tsx
- packages/excalidraw/components/MobileMenu.tsx
- packages/excalidraw/components/PasteChartDialog.tsx
fix https://github.com/excalidraw/excalidraw/issues/8029
> feat: add missing `type="button"`

- packages/excalidraw/package.json
- yarn.lock
Release notes - https://github.com/excalidraw/mermaid-to-excalidraw/blob/e378ae217d90a26ad2a8c3296629e3a65ce2a977/CHANGELOG.md
> feat: upgrade to mermaid-to-excalidraw v1 🚀

- packages/excalidraw/data/restore.ts
- packages/excalidraw/element/binding.ts
- packages/excalidraw/element/typeChecks.ts
fix https://github.com/excalidraw/excalidraw/issues/8131
> fix: repair invalid binding on restore & fix type check

- packages/excalidraw/data/restore.ts
- packages/excalidraw/element/binding.ts
> fix: only bind arrow

- packages/excalidraw/element/mutateElement.ts
- packages/excalidraw/scene/Fonts.ts
fix https://github.com/excalidraw/excalidraw/issues/8190
> fix: stop updating text versions on init

- excalidraw-app/App.tsx
- excalidraw-app/app-language/LanguageList.tsx
- excalidraw-app/app-language/language-detector.ts
- excalidraw-app/app-language/language-state.ts
- excalidraw-app/components/AppMainMenu.tsx
fix https://github.com/excalidraw/excalidraw/issues/8202
plus some refactor
> feat: smarter preferred lang detection

- .env.production
typo from https://github.com/excalidraw/excalidraw/pull/8224
> fix: messed up env variable

- packages/excalidraw/components/App.tsx
- packages/excalidraw/components/FontPicker/FontPickerList.tsx
- packages/excalidraw/fonts/index.ts
- packages/excalidraw/scene/export.ts
> fix: load fonts for `exportToCanvas`

- packages/excalidraw/element/linearElementEditor.ts
> fix: Point duplication in LEE on ALT+click

- packages/excalidraw/element/binding.ts
- packages/excalidraw/element/linearElementEditor.ts
Add additional heuristics to patch over the line/element intersection code issue
> fix: Patch over intersection calculation issue

- packages/excalidraw/element/binding.ts
- packages/excalidraw/tests/__snapshots__/history.test.tsx.snap
- packages/excalidraw/tests/rotate.test.tsx
- packages/utils/geometry/geometry.ts
Quickfix for faulty rectangular shape <-> segment intersection calculation
> fix: Reimplement rectangle intersection

- packages/excalidraw/actions/actionCanvas.tsx
- packages/excalidraw/components/App.tsx
- packages/excalidraw/element/bounds.ts
- packages/excalidraw/element/sizeHelpers.ts
Not fully tested and quite sure not fully correct, but there's no time. We live or we die. We all serve the Omnissiah!
> feat: improve zoom-to-content when creating flowchart

- packages/excalidraw/components/App.tsx
- packages/excalidraw/components/HintViewer.tsx
- packages/excalidraw/components/Stats/index.tsx
- packages/excalidraw/snapping.ts
fix https://github.com/excalidraw/excalidraw/issues/8380
> fix: object snapping not working

- packages/excalidraw/components/App.tsx
- packages/excalidraw/components/Stats/DragInput.tsx
> fix: context menu does not work after after dragging on StatsDragInput

- packages/excalidraw/components/App.tsx
Fixes: #8451 
Regression #8437
> fix: View mode wheel zooming does not work

- packages/excalidraw/components/ColorPicker/ColorPicker.tsx
- packages/excalidraw/css/styles.scss
> fix: PropertiesPopover maxWidth changing fixed units to relative units

- dev-docs/docs/@excalidraw/excalidraw/api/children-components/main-menu.mdx
Update dead link in page "api/children-components/main-menu"
> docs: update dead link on main-menu page

- excalidraw-app/data/LocalData.ts
- packages/excalidraw/components/SearchMenu.tsx
- do not persist search sidebar to LS
- plus naming change 
(I messed up git staging so everything is in one commit ☹)
> feat: smarter zooming when scrolling to match & only match on search/switch

- packages/excalidraw/data/encode.ts
- packages/excalidraw/fonts/ExcalidrawFont.ts
- packages/excalidraw/utils.ts
> fix: Buffer dependency

- vitest.config.mts
we're not meeting the threshold atm and are pressed for time. Will increase later.
> test: decrease min coverage thresholds

- packages/excalidraw/renderer/renderElement.ts
fix https://github.com/excalidraw/excalidraw/issues/8692
> fix: image render perf

- .github/workflows/locales-coverage.yml
> fix: usage of `node12 which is deprecated`

- packages/excalidraw/package.json
- yarn.lock
fix https://github.com/advisories/GHSA-m4gq-x24j-jpmf
> chore: bump `@excalidraw/mermaid-to-excalidraw`

- packages/excalidraw/components/App.tsx
Also solves issue reported with too many state changes in one render.
> fix: Optimize frameToHighlight state change and snapLines state change

- packages/excalidraw/package.json
- yarn.lock
> chore: Remove @tldraw/vec

- packages/excalidraw/components/App.tsx
> fix: regression on dragging a selected frame by its name

- packages/excalidraw/data/library.ts
- BREAKING CHANGE: only allow `*.excalidraw.com` base domain library install urls by default, for safety reasons.
- new API for `useHandleLibrary()` hook: `opts.validateLibraryUrl(libraryUrl: string): boolean`. If supplied, the `libraryUrl` is allowed only if returned `true`
> feat: validate library install urls

- packages/excalidraw/element/binding.ts
Fixes regression introduced in #8927
Closes issue: #8964
> fix: elbow arrows do not work within frames (issue: #8964)

- packages/excalidraw/element/flowchart.ts
#8575 
https://github.com/user-attachments/assets/517d35de-4423-4e68-9c37-03f2f90edfc7
> fix: #8575 , Flowchart clones the current arrowhead

- packages/excalidraw/components/IconPicker.tsx
> fix: library item checkbox style regression

- packages/excalidraw/actions/actionProperties.tsx
- packages/excalidraw/components/App.tsx
- packages/excalidraw/element/binding.ts
- packages/excalidraw/element/elbowArrow.ts
- packages/excalidraw/element/linearElementEditor.ts
- packages/excalidraw/element/mutateElement.ts
- packages/excalidraw/scene/comparisons.ts
- packages/excalidraw/utils.ts
fix https://github.com/excalidraw/excalidraw/issues/9077
> fix: Elbow arrow z-index binding

- packages/excalidraw/components/icons.tsx
fix https://github.com/excalidraw/excalidraw/issues/8948
> feat: change empty arrowhead icon

- packages/excalidraw/element/binding.ts
- packages/excalidraw/scene/comparisons.ts
- packages/excalidraw/scene/index.ts
Fixes the issue where with a special iframe no matter where you want to create the elbow arrow, it always get attached to the iframe:
> fix: IFrame and elbow arrow interaction fix

- packages/excalidraw/actions/actionDuplicateSelection.tsx
- packages/excalidraw/components/App.tsx
- packages/excalidraw/index.tsx
- packages/excalidraw/types.ts
```tsx
<Excalidraw
onDuplicate={(elements, prevElements) => {
const prevElementsMap = arrayToMap(prevElements);
return elements.map((el) => ({
...el,
backgroundColor: !prevElementsMap.has(el.id)
? el.backgroundColor === "red"
? "yellow"
: "red"
: el.backgroundColor,
}));
}}
/>
```
> feat: add `props.onDuplicate`

- excalidraw-app/sentry.ts
- packages/excalidraw/data/restore.ts
- packages/excalidraw/element/elbowArrow.ts
- packages/excalidraw/element/newElement.ts
- packages/excalidraw/element/resizeElements.ts
Reverted PR (for now): https://github.com/excalidraw/excalidraw/pull/9116
> chore: Revert aspect ratio fix with element size limits and chk

- packages/excalidraw/components/App.tsx
- packages/excalidraw/components/LayerUI.tsx
- packages/excalidraw/components/Sidebar/Sidebar.tsx
regressed in https://github.com/excalidraw/excalidraw/pull/9127
> fix: docked sidebar width

- packages/element/src/linearElementEditor.ts
- packages/excalidraw/data/__snapshots__/transform.test.ts.snap
- packages/excalidraw/data/transform.test.ts
- packages/excalidraw/data/transform.ts
- packages/excalidraw/tests/linearElementEditor.test.tsx
> fix: Linear element is not normalized

- packages/common/src/utils.ts
- packages/element/src/binding.ts
- packages/element/src/collision.ts
- packages/element/src/cropElement.ts
- packages/element/src/distance.ts
- packages/element/src/shapes.ts
- packages/element/src/utils.ts
- packages/excalidraw/tests/helpers/ui.ts
Refactor of center calc realted to this issue: https://github.com/excalidraw/excalidraw/issues/9296
> chore: Element center point util

- packages/excalidraw/components/App.tsx
- packages/excalidraw/eraser/index.ts
- packages/excalidraw/lasso/utils.ts
- packages/excalidraw/tests/lasso.test.tsx
- packages/math/src/types.ts
Reuse the structure and logic from lasso to make eraser performant.
> perf: make eraser great again

- packages/element/src/bounds.ts
- packages/excalidraw/renderer/helpers.ts
- packages/excalidraw/renderer/interactiveScene.ts
- packages/math/src/curve.ts
- packages/math/src/vector.ts
Highlights when you try to bind now pixel-perfect sized.
> feat: Precise highlights for bindings

- packages/common/src/constants.ts
- packages/common/src/font-metadata.ts
- packages/element/src/frame.ts
- packages/excalidraw/actions/actionToggleSearchMenu.ts
- packages/excalidraw/appState.ts
- packages/excalidraw/components/App.tsx
- packages/excalidraw/components/FontPicker/FontPickerList.tsx
- packages/excalidraw/components/HintViewer.tsx
- packages/excalidraw/components/SearchMenu.scss
- packages/excalidraw/components/SearchMenu.tsx
- packages/excalidraw/components/Stats/Collapsible.tsx
- packages/excalidraw/locales/en.json
- packages/excalidraw/renderer/interactiveScene.ts
- packages/excalidraw/tests/__snapshots__/contextmenu.test.tsx.snap
- packages/excalidraw/tests/__snapshots__/history.test.tsx.snap
- packages/excalidraw/tests/__snapshots__/regressionTests.test.tsx.snap
- packages/excalidraw/tests/search.test.tsx
- packages/excalidraw/types.ts
- packages/utils/tests/__snapshots__/export.test.ts.snap
> feat: include frame names in canvas searches

- packages/excalidraw/lasso/index.ts
> fix: update cached segments when visible area changes

- packages/element/src/linearElementEditor.ts
- packages/excalidraw/actions/actionProperties.tsx
> fix: Elbow arrow conversion labels mixed up

- packages/element/src/elbowArrow.ts
- packages/excalidraw/components/ConvertElementTypePopup.tsx
fix https://github.com/excalidraw/excalidraw/issues/9558
> fix: Linear to elbow conversion crash

- packages/element/tests/binding.test.tsx
- packages/element/tests/linearElementEditor.test.tsx
- packages/excalidraw/components/Stats/stats.test.tsx
- packages/excalidraw/tests/MermaidToExcalidraw.test.tsx
- packages/excalidraw/tests/elementLocking.test.tsx
- packages/excalidraw/tests/flip.test.tsx
- packages/excalidraw/tests/helpers/ui.ts
- packages/excalidraw/tests/queries/dom.ts
- packages/excalidraw/tests/test-utils.ts
- packages/excalidraw/wysiwyg/textWysiwyg.test.tsx
drying out and improving the reporter
> test: improve getTextEditor test helper

- packages/element/src/binding.ts
- packages/element/src/linearElementEditor.ts
- packages/excalidraw/actions/actionFinalize.tsx
- packages/excalidraw/components/App.tsx
- packages/excalidraw/tests/__snapshots__/history.test.tsx.snap
> fix: Bindings at partially overlapping binding areas

- packages/excalidraw/components/App.tsx
fixes #9654
fixes #9720
There probably needs to be a better way for accessing state in handlers.
> fix: Remove flushSync from alt-lasso and elbow dragging

- packages/excalidraw/snapping.ts
> feat: allow a frame to snap to its children

- packages/excalidraw/clipboard.ts
fixes mime type detection. Regression from https://github.com/excalidraw/excalidraw/pull/9947
> fix: normalize file on paste/drop

- excalidraw-app/App.tsx
- excalidraw-app/data/LocalData.ts
- excalidraw-app/index.scss
- packages/excalidraw/locales/en.json
Closes #9941
My attempt at solving issue where local storage quota is exceeded but user is not notified. Toasts user with an appropriate message.
https://github.com/user-attachments/assets/4bb386d1-a0c3-408f-9f50-737878192916
This is my first PR here so please do not hesitate to criticize, I appreciate any feedback or suggestions for improvement!
> fix: display error message when local storage quota is exceeded
