excalidraw/excalidraw

- src/index.js
- src/styles.css
Added basic PNG export. Manually tested on Chrome & FF (not sure if Safari works).
Closes https://github.com/vjeux/excalibur/issues/23
Changes:
1. Support export to PNG (Selection is cleared before export. Also allow to clip canvas to visible area only + padding).
2. ensure `Backspace` isn't prevented in input fields.
3. (forgot to remove): added support to setting `width`/`height` to `newElement` factory (useful for testing).
> add PNG export

- src/index.tsx
There's been a few commits that touched this but the behavior was still weird. I think that it is now good.
If you have elements already selected:
-  you click on one of them, it does nothing. It will let you drag the entire pack.
- you click on an unselected one, it selects it and unless shift is pressed, unselect everything else. This way you can select a new element.
- you click somewhere outside of elements, it unselects everything so you can start a new selection.
> Better selection click detection

- src/index.tsx
- src/styles.css
#54 by @Fausto95 had two small issues:
- The color for input needs to be of the exact format 6 lowercase hexadecimal (`#ffffff`) for it to work
- Arrows didn't receive the stroke color
After that change, the top UI becomes pretty cluttered and hard to parse. I moved all the options into fieldsets and moved the non-essential ones below the fold. We'll need to have a proper structure there but at least it should get us going for a bit more time :)
> Random fixes

- src/index.tsx
Fixes #14 
- I don't like the frame rate of updates caused by `setState`. Maybe we shall try request animation frame loop to draw and update canvas instead of using `setState` and redrawing on `componentDidUpdate` phase
> [WIP] Scroll with mouse wheel

- src/index.tsx
- src/styles.css
Right now, since we auto-save to localStorage, there's no way to easily start a new canvas. This PR adds support for clearing it.
Technically, one could select all elements and hit `delete`, but suppose the elements are all over the place (some out of visible area), or there's a bug like the one that didn't clear selections.
> add support for clearing canvas

- public/index.html
We don't have one and it causes an error in Chrome
> Remove manifest.json

- src/index.tsx
This adds two buttons, one to save the diagram as a JSON file, and one to load an existing file.
The DOM APIs for this stuff are kind of ancient so the code is a bit sloppy, but it works!
Fixes #143
> Add save/load functionality from file

- src/index.tsx
fixes #153 
`actualBoundingBoxAscent` and -descent are only supported by Chrome and Safari.
https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics
This falls back to simply using the font size, which is probably not as precise but seems to work fine. The value is hardcoded like the font size (a few lines above). If someone adds support for changing the font-size, this will have to be applied to this measure as well.
> fallback if TextMeasure.actualBoundingBox* unavailable

- src/index.tsx
Added quick and dirty tooltips using `title` attributes with shape keyboard shortcuts.
> Add titles to shape buttons with key shortcuts

- src/index.tsx
Some fixes proposed by @vjeux in #179 
1. Element's properties all on top
2. Remove comments
3. Rename `someElementIsSelectedIsRectangleOrEllipseOrDiamondOrArrow` to `hasStroke`
4. Some backwards compatibility when restore elements without new properties
> Styles fix

- src/index.tsx
- src/styles.scss
Bunch of small changes:
- Implement `<ButtonSelect>` for a select made of a bunch of buttons
- Used this new select element for a bunch of properties
- Reduced the number of options dramatically. This way there's no choice paralysis
- For fill, just "Solid", "Hashure", "Cross-hatch"
- For stroke width, just "Thin", "Bold", "Extra Bold"
- For Sloppiness, just "Draftsman", "Artist", "Cartoonist"
- Properly handle when multiple selected elements don't have the same value, we don't highlight anything, but changing it will set it to all the elements.
> Improve selection view

- src/element/collision.ts
Ellipse hit test function is not working properly if width or height of ellipse is negative
> Fixed ellipse hit test if sizes are negative

- src/index.tsx
As mentioned in https://github.com/excalidraw/excalidraw/pull/141#issuecomment-570899194, the `⌘ Cmd` keyboard shortcuts don't work on Windows/Linux/others. We can use the `Ctrl` key for these devices.
> Use Ctrl instead of Cmd for keyboard shortcuts on Windows

- src/element/bounds.test.ts
- src/element/bounds.ts
- src/element/collision.ts
- src/element/index.ts
- src/element/newElement.ts
- src/history.ts
- src/index.tsx
- src/renderer/index.ts
- src/renderer/renderElement.ts
- src/renderer/renderScene.ts
- src/scene/data.ts
- src/scene/index.ts
- src/scene/scrollbars.ts
- src/scene/selection.ts
Note: To be honest, I did not understand the reasoning behind adding a function to render the element. Based on my basic experience with game development, typically, the actual rendering stuff (e.g `fillRect` in context2d) are rendered by the renderer. If we compare this functionality to React, this is also how React works. In other words, React returns JS objects during the `render` function while the actual rendering happens in ReactDOM, which is the renderer.
I am not familiar with roughjs; so, if you want to move the shapes within the element, I can move the `shape` object into the element and let the renderer only do the context calls etc.
> Refactor Element Functions

- src/components/ColorPicker.tsx
Reduces initial bundle size by 25%
Before 
After
> Async loading of TwitterPicker

- src/index.tsx
Issue #165 
By pressing the alt key while clicking an element it duplicates it.
Here is how it behaves:
> feat(duplicate_element): duplicate element by alt dragging

- src/index.tsx
> alt+drag should duplicate all selected elems

- src/element/index.ts
- src/element/newElement.ts
- src/index.tsx
Ok, making this PR a draft to ensure this one is done right :).
I've made a helper for duplicating elements. Technically, object spread won't be enough in case we add non-primitive members to elements in the future, so not sure about using that one.
> fix for duplicating elements

- package.json
- src/index.tsx
Made pre-commit hook to fail on eslint warnings. WTBS, we still lint and prettify only staged lines, which means it won't catch stuff like "unused variables" --- shouldn't we move to lint & prettify whole codebase?
> prevent commit on eslint warnings & fix lint

- src/element/handlerRectangles.ts
- src/element/resizeTest.ts
- src/index.tsx
- src/scene/types.ts
Fixes #250 
Now, the cursor should change accordingly if the user hovers over the elements without having any mouse button depressed.
Additionally:
* Refactors the resizing test logic so that `resizeTest` is not invoked again after the selected element has been found.
* Adds a `viewportCoordsToSceneCoords` to replace the proper `x` and `y` coords calculation relative to the drawing canvas that was done in most event handlers.
> Show move and resize cursors on hover

- src/element/resizeTest.ts
- src/history.ts
- src/index.tsx
- src/renderer/renderScene.ts
- src/scene/comparisons.ts
- src/scene/createScene.ts
- src/scene/data.ts
- src/scene/scrollbars.ts
- src/scene/selection.ts
- src/zindex.ts
In this PR, I am making all the operations on elements array (not the actual elements within them) immutable. Now, all the functions return values instead of mutating the array directly. Some of the functions to mutate the array directly but currently, those functions accept a copy of the elements array instead of the actual array (`[...elements]`). Those functions are:
- clearSelection
- setSelection
- moveAllLeft / Right
- moveOneLeft / Right
We can also slowly make these functions immutable.
After this PR, I am planning on moving elements array into state as nothing is really dependent on it except for the App component.
> Make all operations on elements array immutable

- src/components/panels/PanelExport.tsx
- src/components/panels/panelExport.scss
- src/global.d.ts
- src/index.tsx
- src/scene/data.ts
- src/scene/index.ts
- src/scene/types.ts
Adds support to export canvas to clipboard, for browsers that support it (Chrome, Edge...).
This allows to copy/paste the canvas into apps such as:
- many desktop apps
- websites (GitHub, Trello, StackOverflow etc.)
- Electron Apps (Slack, Skype...)
Potentially very useful feature, but lacking wide support so far, and sometimes buggy, so maybe this is ahead of its time.
**Problems:**
- Browser support. For browsers that (likely) don't support it, the button isn't shown at all.
- Even Chrome is buggy (the bg is sometimes black, at least for alpha pngs).
Uses [`navigator.clipboard.write`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write) and `ClipboardItem`. See https://web.dev/image-support-for-async-clipboard/#images for intro.
> support copy canvas to clipboard

- src/components/panels/PanelExport.tsx
For some reason `navigator.clipboard` object is `undefined` in Safari; so, `"write" in navigator.clipboard` throws error. I have added another check to see if `navigator.clipboard` object exists.
EDIT: It is not supported in [Safari](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard)
> Fix a bug where clipboard object doesn't exist in Safari

- src/index.tsx
Fix for #290 
Moving `history.resumeRecording();` to `onMouseUp` from `componentDidUpdate`. 
`skipRecording` is called in `onMouseDown` and `onMouseMove`. However, component is being updated a number of times which causes componentDidUpdate to call `resumeRecording` before being skipped again.
> Fix history saving for resizing/dragging element

- src/utils.ts
Use `innerText` instead of `innerHTML` when measuring text
> Fix text measurement when HTML is added as content

- src/actions/actionZindex.tsx
Now that they are in the context menu, we don't need to have them in the panel anymore.
Fixes #242
> Remove zindex options from panel

- src/components/ColorPicker.tsx
- src/components/SidePanel.tsx
- src/components/panels/PanelCanvas.tsx
- src/components/panels/PanelColor.tsx
Covers https://github.com/excalidraw/excalidraw/issues/262.
Thinking about the comment by @vjeux about using different color palettes for each type of color in the app, I thought it would make great sense to use one same palette with different levels of lightness to reinforce their role.
So I took the `schemeTableau10` color palette from [d3 palettes](https://github.com/d3/d3-scale-chromatic#api-reference) as @pshihn suggested and modified it based on lightness to have light pastel-like colors for the canvas background (so we easily add on top with contrast), saturated and clean colors for the elements background (so they catch eyes as they are the main elements) and dark colors for strokes (so they highlight elements more effectively).
Canvas background:
Element background:
Element …
> Improve color suggestions

- src/components/ContextMenu.css
- Move the context menu right next to the mouse so it's not so far away. But 1px out so that nothing is selected until you move your mouse
- Change the colors to be closer to the macos one. Unfortunately, macos has a 0.5px border that I'm not able to reproduce without some annoying hacks, 1px it'll be.
Fixes #269
> Tweak context menu style

- src/actions/actionProperties.tsx
- src/actions/actionStyles.ts
- src/element/newElement.ts
- src/history.ts
- src/index.tsx
- src/renderer/renderElement.ts
- src/scene/data.ts
It adds back the performance optimization of regenerating the shapes only when element properties change.
Do not merge it yet! I need to check out export etc afterwards.
> Regenerate roughjs shape only when the item is updated

- src/index.tsx
We need to quit if we have either elements OR appState, not both.
Test plan:
- Cmd-a
- Observe that it selects elements
- Observe that it doesn't enable arrow creation
Fixes #319
> Fix cmd-a drawing arrows

- package-lock.json
- package.json
- src/components/ColorPicker.css
- src/components/ColorPicker.tsx
- src/renderer/renderElement.ts
Unfortunately, react-color has a bug where transparent color doesn't trigger onChange. I've been annoyed by the huge dependency anyway so decided to take the generated html (which is awesome) and reimplement a specific component for it.
I also made sure that we don't actually render anything when the background is transparent on rough (I looked at the generated path and made sure it didn't have the commands for the background)
> Support transparent background + inline picker

- src/element/newElement.ts
- src/index.tsx
We need to unselect all the previous elements and select all the new ones. Also made sure that the shape is regenerated when the element is duplicated
> Fix alt-duplicate

- src/index.tsx
I keep adding empty rectangles because I reload with cmd-r which enables rectangle :p Let's only make the shortcut work if there's no modifier enabled
> Prevent cmd-r from selecting rectangle

- src/index.tsx
- src/utils.ts
I profiled dragging and it looks like it takes ~3ms to save to localStorage a smallish scene and we're doing it twice per mousemove. Let's debounce so we don't pay that cost on every mouse move.
Stole the implementation from #220 which got reverted.
> Debounce localstorage save

- src/index.tsx
If the input is active, we shouldn't override copy paste behavior
Fixes #254
> Fix copy-paste on input

- src/index.tsx
Fixes #252
Test plan:
- Click on text icon
- Click anywhere to start entering text
- Add a letter
- Make sure the cursor is selection and not text
- Click anywhere else, make sure it completes the text and not create a new one
> Reset to selection after creating a text

- src/scene/data.ts
This is a bug from shape generator optimization. The generator shapes were being saved into local storage which was causing any changes to the rendering etc to be saved. Now, it is removed.
> Remove element shape object from local storage save

- src/history.ts
- src/index.tsx
Following up https://github.com/excalidraw/excalidraw/issues/307.
Covers:
- Simplify `redoOnce` function to match `undoOnce` shape.
- Move `clearRedoStack` call to `pushEntry` (we might be erasing the redo stack when we haven't created any new entry in the history if the generated current entry is equal to last history entry).
- Remove `skipRecording` call from `restoreEntry` because we already make sure to don't loop by checking that the history entry we want to push is not equal to the last one. If we want to optimize the number of calls to `pushEntry` in `componentDidUpdate`, we should do it via external mechanism (same way we only call `pushEntry` if `isRecording`). The history itself should not be aware of this recording thing. 
cc @vjeux as he was in the context 👍
> History improvements

- src/index.tsx
Fixes #123 
**Before:**
There's a jump when we start resizing the element
**After:**
Resizing has no jump
> Use cursor delta to resize shape

- src/index.tsx
Fixes #351 
Only show the resize handlers on hover if a single element is selected
> Don't show resize cursor if multiple elements are selected

- src/components/ContextMenu.tsx
- src/components/Popover.tsx
This PR positions contextMenu to ensure it doesn't overflow viewport.
Before change:
After change:
> ensure contextMenu doesn't overflow viewport

- src/index.tsx
Implemented canvas panning on wheel button drag, since there's currently no way for non-touchpad users to pan horizontally.
This has potential (well, actual) bad performance on more complex scenes. Unfortunately, I have no idea how to improve that (debounce/throttle wouldn't help here), apart from actually improving render performance. Or, is it possible to translate canvas without fully rerendering it?
WTBS, performance-wise, this shouldn't be different from what we're currently doing on scrolling via high-resolution mouse wheel, or touchpad.
Made the `mousemove` event `passive`, whatever good it's gonna do here. Possibly none?
> pan canvas on wheel button drag

- src/actions/actionExport.tsx
- src/scene/data.ts
Adds AppState to the json created when clicking "Save as...". This fixes a few bugs:
* #306 - Now the scroll position will be the same as it was when the user saved the file. This is how we treat loading from local storage, so we should be treating loading from a file the same way.
* #357 - By adding the AppState to the exported json, we also keep the background color, which previously was not stored in the file, so all drawings that were imported would have a blank background
Before:
After:
> Add AppState to export json to fix various import bugs

- public/index.html
We thought #400 would resolve #379 but unfortunately, the `og:image` doesn't seem to be working as @Fausto95 noted. 
I believe this is because we were using a relative path to the image, instead of an absolute path (which makes sense I guess). 
We'll test this using the deploy preview link to make sure.
> fix: use full url for og:image

- src/actions/actionProperties.tsx
This changes the label "Draftsman" with "Architect" to be more inclusive. 
Suggestion via Twitter:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">hi! I&#39;m not savvy enough to submit a PR myself — so instead you get a tweet! <br><br>It would be really great to change the label for &#39;Sloppiness&#39; from Craftsman to Craftsperson. Craftsman is unnecessarily exclusionary language! <a href="https://t.co/Raz2EykNzt">pic.twitter.com/Raz2EykNzt</a></p>&mdash; Jason Crabtree (@jasontcrabtree) <a href="https://twitter.com/jasontcrabtree/status/1218186980275650560?ref_src=twsrc%5Etfw">January 17, 2020</a></blockquote>
> fix: replace Draftsman with Architect

- src/index.tsx
Fixes #429
I have one question. We can use shortcuts for choosing a shape(e.g. `R` key for rectangle) while dragging a shape. Is it intentional?
> Disable shortcuts for shapes while dragging the selection

- src/element/textWysiwyg.tsx
When we are inputting Japanese(and probably Chinese, Korean, and more...), need to input Enter key for committing IME conversion. But now, when we input Enter key, `textWysiwyg` always submit and blurs. So I modified to ignore Enter `keydown` events that are part of composition.
ref: https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event
***
@vjeux and contributors, thank you for developing such a great tool!
> Ignore enter `keydown` events that are part of composition

- src/actions/actionProperties.tsx
- src/index.tsx
As proposed in https://github.com/excalidraw/excalidraw/issues/398, it'd be cool to render the shape actions panel right when a shape tool is selected
> Render shape action on tool selected

- src/element/textWysiwyg.tsx
Fixes https://github.com/excalidraw/excalidraw/issues/417
> Trim wysiwyg text to avoid misalignment on Firefox

- src/scene/data.ts
Previously the type used for the data URI when saving was text/plain. On iPad Safari, this caused the file to automatically have a .txt extension added (so files ended up with names like "drawing-xyz.json.txt"). This meant that the files couldn't be loaded by the tool, which expects only files with a .json extension.
Now, the type used is application/json, which means that the files get reliably saved with the correct extension and can be successfully loaded by the tool later.
> Adjust type of data URI when saving

- package-lock.json
- package.json
- scripts/build-node.js
- src/actions/actionSelectAll.ts
- src/actions/actionStyles.ts
- src/actions/actionZindex.tsx
- src/components/ExportDialog.tsx
- src/index-node.ts
- src/index.tsx
- src/keys.ts
- src/scene/data.ts
- src/scene/getExportCanvasPreview.ts
We can use the [node-canvas](https://github.com/Automattic/node-canvas) project to render the scenes on the server without a browser. The annoying part is that it requires the native dependency Cairo which needs to be installed separately and has different ways for each platform. But, once installed, it worked on my mac!
I used rewire in order to edit the webpack config that create-react-app is using to output a node-compatible bundle.
I also had to do some minor refactoring to be able to get the code without any browser dependencies on the critical path.
I'm going to check this in as is. There will be more work as follow-up to be done to make it useful:
- Create a proper library function and publish to npm
- Create a small command line script that reads a json file and outputs …
> Pure node rendering

- src/components/ColorPicker.css
- src/components/ColorPicker.tsx
Fixes #434, #418.
This PR refactors `Picker` and `ColorPicker` so that they share the same input field and logic to handle manual typing of hex color values.
1. External input uses the appearance from inner input:
**Before**:
**After**:
2. This keeps previous valid value while a new one is being typed and thus an invalid one is present:
3. Inner color picker now allows **#RRGGBBAA** format
> Add ColorInput component

- src/index.tsx
Small change to remove one level of nesting to the already deeply nested `onMouseMove` logic.
> Remove not needed nesting for resize

- src/index.tsx
Followup to #447 - disallowing shape selection (via hotkey) even during element creation.
/cc @sosukesuzuki is there a reason why you included this line:
https://github.com/sosukesuzuki/excalidraw/blob/3efa673fe80128f88b620b98af251fd1ff33e940/src/index.tsx#L302
> disallow shape selection during creation

- src/actions/actionProperties.tsx
We have to change the logic to:
Because in the future we might change some fonts but not their meanings.
> Change the font family names

- src/components/ColorPicker.css
- src/components/ContextMenu.css
- src/components/EditableText.css
- src/components/ExportDialog.css
- src/components/FixedSideContainer.css
- src/components/ToolIcon.scss
- src/styles.scss
- src/theme.css
Closes #458 
This improves accessibility for users that override their default user agent settings to allow text to be rendered at a bigger size.
Before for client font size set at 20px:
After for client font size set at 20px:
> Use relative CSS units

- public/locales/en/translation.json
- src/actions/actionProperties.tsx
https://en.wikipedia.org/wiki/Opacity_(optics)
I left the variable/key as-is, it's not visible to users anyway.
> Fix typo in "Opacity"

- src/renderer/renderScene.ts
Fixes #457 . Covers the accepted input in src/components/ColorPicker.tsx and 4-digit rgba, but it will have to be revised if rgb/hsl/color names are accepted.
> fix: Transparent backgrounds result in bleed

- src/scene/getExportCanvasPreview.ts
Fixes #490. Preserves the ratio of the preview image when width / height reaches max-width/max-height.
> fix: Preview image is being stretched when the proportions are wrong

- package-lock.json
- package.json
- src/scene/browser-native.d.ts
- src/scene/data.ts
- Instead of doing the feature detection inline, this is now outsourced to [browser-nativefs](https://github.com/tomayac/browser-nativefs), which makes the code a lot easier to read. This new library dynamically imports only the relevant code path (legacy or Native File System API), albeit this advantage is down-transpiled at the moment.
- Add two missing fields to `package.json`.
> Move file system operations to separate module

- .eslintignore
- .lintstagedrc.js
- package-lock.json
- package.json
- src/index-node.ts
- Adds `.eslintignore` list, which is then reused for prettier ignore list
- Adds linting for JSON files (useful for translation files, to ensure we don't include duplicate keys...). I've used [eslint-plugin-json-format](https://github.com/Bkucera/eslint-plugin-json-format) because out of the three packages I've found, this is one that I can vouch for (made by a guy in the Cypress team).
- Adds linting against `console.log`
- :warning: I've gotten lots of lint errors until (I think) I got the settings right, but it may still turn out it will break linting in some scenarios. In that case we'll need to revert this PR.
- requires separate config of `lint-staged` plugin via `.lintstagedrc.js` to fix an eslint issue: see https://github.com/okonet/lint-staged#how-can-i-ignore-files-from-eslintig …
> Lint tweaks

- src/element/index.ts
- src/element/resizeTest.ts
- src/element/sizeHelpers.ts
- src/index.tsx
- src/scene/getExportCanvasPreview.ts
- src/utils.ts
fixes #505
I decided to do another take on normalizing dimensions, because fixing #505 without it would be a pain. On top of it, I still believe that not-normalizing will result (and already has) in lots of lost time, and hacks on top of hacks. Without it, we need to account for negative dimensions (`width`/`height`), handles reported e.g. as `w` when in reality user holds `e` etc.
This PR doesn't yet normalize `arrow` & `line` elem. It works without it, but we should normalize every element. Will fix tomorrow or in another PR.
Note: while functioning, I'm not sure if it doesn't break unrelated things. Also, tomorrow I plan to refactor the codebase to remove the hacks which are no longer necessary.
(I haven't in fact checked #342, so not sure what I'm doing differently, and what I haven't …
> Normalize dimensions

- src/element/textWysiwyg.tsx
- src/index.tsx
Closes #507 . 
When the text is empty, the `textWysiwyg onSubmit` was never triggered thus `editingElement` was never flushed leading to the buggy behavior.
`onCancel` callback was added to `textWysiwyg` that is triggered when an empty text is submitted. We can now flush the text element from state when submitting an empty text.
> Fix #507 - Add onCancel callback to textWysiwyg for cleanup

- src/index.tsx
Storing it in state causes a full re-render. The only time we use the cursor position is for pasting. This halves the number of renders on drag.
Before:
After:
> Do not store cursor position in state

- src/scene/data.ts
It turns out the only thing we need to save in the appState is the background color. All the rest is transient data.
I added `"type": "excalidraw"` at the beginning to explain where it was.
I removed `"source": "http://localhost:3000/"`. I don't think we want to leak on which webpage it was saved from.
I removed `isSelected` from the json
I added indentation so it's easier to read the content. I'm not 100% sure on this one, but I figure filesize doesn't matter too much those days. And if we want to shrink it, there are more effective ways than json.
> Cleanup saved json file

- src/index.tsx
Problem:
- Select arrow
- Mouse down somewhere
- Mouse move somewhere to create an arrow
- Press escape
- Now you're in a weird situation where the shape is now "selection" but you're still dragging the arrow. If you mouse up, the arrow disappears
In order to solve this problem, we can avoid making escape do anything if you're currently dragging an element
> Disable escape when creating element

- public/index.html
- src/index-node.ts
- src/styles.scss
This updates the way fonts are handled to not have to download the font from the internet.
If you do `./public/font.ttf` in the .scss file, unfortunately the bundle packages them somewhere that's different from the public folder that is used by the index.html to preload them.
The fix I used is to use absolute path `/font.ttf` so that both work. Unfortunately, this means that the website will only work if at the root of the domain. That's the case so far so it's okay but still annoying if we want to embed it somewhere.
> Use local fonts

- src/index.tsx
- src/scene/getExportCanvasPreview.ts
- src/scene/scrollbars.ts
If you scroll and draw to the left of the origin, when you export the scene, there's a weird whitespace on the right. This is because we do the min() computation starting at 0 and not -Infinity
This also fixes pasted elements and scrollbars.
> Fix exported size when drawing to the left

- src/scene/data.ts
The description is the name of the file type in the dialog. This shouldn't be Excalidraw but the default one for a png.
> Remove image type description when saving to png

- src/actions/actionProperties.tsx
If you have two elements selected that have a different value (eg: a green line and a red line), the value of the color picker should be undefined, not the default value.
> Fix value when multiple elements are selected

- src/index.tsx
A common workflow I have is to enable the lock, draw a bunch of things, unlock to be able to select stuff. However, after I unlock, the last shape is still enabled, so I end up drawing yet another of the same shape :(
This PR resets to selection instead!
> Set selection when unlocking

- src/index.tsx
- src/scene/comparisons.ts
The logic to display which settings when nothing was selected was incorrect. This PR ensures that they are in sync.
I also removed all the `<hr />` which after the redesigned just looked like weird empty spaces
> Only show correct settings

- src/actions/actionProperties.tsx
Some PR made the settings UI show up even though nothing is selected. However, you couldn't actually change any of those settings except for the colors. This PR pipes through the rest of the properties so everything works now!
> Fix global settings

- src/actions/actionProperties.tsx
The cartoonist roughness is IMO too sloppy (it goes from `0` → `1` → `3`). I think it's often unusable for anything useful. I propose changing it to `2`.
Come to think of it, I should have first created an issue for this. Feel free to close if you think it's not a good idea.
> change cartoonist roughness

- src/components/ToolButton.tsx
#534 broke tooltips of shape icons because it moved it to the `<input>` which is not full size of the `<label>`.
/cc @voluntadpear should we move the aria labels, too?
> move title to label

- public/index.html
- public/locales/en/translation.json
- public/locales/es/translation.json
- src/components/LanguageList.tsx
- src/components/LockIcon.tsx
- src/index.tsx
This PR uses HTML semantic elements to set the landmarks of the page.
This is helpful for assistive technologies to determine the different regions of content. In our case it's useful for jumping between the different islands that we use to group the form controls.
**Note:** The diff looks large because the `<canvas>` is now wrapped in a `<main>` element and I included [fallback text](http://pauljadam.com/demos/canvas.html) to describe it. No logic change was made in this PR.
> Add page landmarks

- package-lock.json
- package.json
In reply to https://github.com/tomayac/browser-nativefs/issues/2.
> Bump browser-nativefs version to v0.2.0

- src/actions/manager.tsx
- src/actions/types.ts
- src/index.tsx
- src/utils.ts
Fixes issues where copy/paste event's weren't triggered due to focus being on `.ToolIcon`.
Note: this doesn't resolve #386.
> improve clipboard handling

- src/index.tsx
There are several cases where we pause recording and don't resume it. Apart from history, this also results in UI not updating correctly.
The way we do it now is brittle and very error prone (hence this issue).
> fix not resuming recording

- src/index.tsx
Fixes issue where `state.draggingElement` wasn't reset when tools locked. This caused an issue where you couldn't `esc` to reset to `selection` after creating an element (among possible other bugs).
Steps to repro:
1. lock tools
2. create rectangle
3. press `esc`
4. tool is not reset to selection
> ensure we reset draggingElement when tool locked

- src/index.tsx
Instead of finding all the places where we want to resume recording, we should do it after every componentDidUpdate(). The idea is that we just want to disable the history for certain setState, for which we call directly before skipHistory.
> Different call of resumeRecording()

- src/index.tsx
Pressing 1 would change the cursor to a + instead of normal cursor
> Fix wrong cursor for selection keyboard shortcut

- src/styles.scss
It's unclear otherwise when using the keyboard
> Add outline to button list

- src/index.tsx
- src/utils.ts
This is the only way to navigate using the keyboard and was prevented by #596. Now it works fine.
Test Plan:
- Click on selection icon
- Use left/right arrow keys to move between tool icons, that works.
- Click on a shape, cmd+c
- Click on the selection icon
- Cmd+v, it pastes correctly
> Fix ability to use arrow keys to navigate between shapes

- src/element/textWysiwyg.tsx
By using position: fixed like the rest of the UI components, it will no longer make the body change size and have bad side effects like scrolling.
Fixes #365
> Fix wysiwyg text overflow

- public/fonts.css
- public/index.html
- src/styles.scss
Thanks to this stack overflow answer ( https://stackoverflow.com/a/41678350/232122 ) I was able to fix the font preloading!
If we put fonts.css in the public/folder and include it with normal html, we can avoid going through the build pipeline!
Test Plan:
- Go to http://localhost:3000/?id=6309590945759232
- See that the font loads by default
- See that there's no warning in the console saying that we preload a font we don't use
Fixes #637
> Fix font preloading

- src/element/textWysiwyg.tsx
- src/utils.ts
We did some hackery to prevent copy pasting when we didn't support multilines. But we do now so we can remove it.
Interestingly, newlines are actually <br /> elements. So we need to tweak the isInputLike logic a bit
Fixed #396
> Allow copy pasting inside of wysiwyg element

- src/element/textWysiwyg.tsx
- src/styles.scss
There's a bug where the carret doesn't show up when the text is first focused on Chrome with the previous combination of CSS. I tweaked it and now it seems to work (don't ask me why!).
Unfortunately on Safari, ever since we moved to contentEditable on #274, the carret disappeared the first time. I unsuccessfully tried to repro in a smaller codebase ( https://jsfiddle.net/u2mjs90y/1/ ) but it does work in Safari...
I'm not exactly sure what's going on, there are bunch of issues opened against this bug when googling against all the browsers...
> Fixed wysiwyg caret disappearing on Chrome

- src/element/textWysiwyg.tsx
- src/styles.scss
Turns out the root cause was the outline. For some reason, doing "transparent" doesn't work but doing "1px solid transparent" does. Don't know why but I'll take it!
> Fix caret for real!

- src/appState.ts
- src/index.tsx
- src/locales/en.json
- src/renderer/renderScene.ts
- src/scene/data.ts
- src/scene/index.ts
- src/styles.scss
- src/types.ts
With the infinite scroll behavior, it's easy to scroll super far away from where the content is and have a hard time getting back. This PR adds a button to refocus on the center of the scene when no elements are visible anymore.
Fixes #491
> Add button when scrolled outside of visible area

- src/components/ToolButton.tsx
- src/components/ToolIcon.scss
- src/index.tsx
I'm not 100% sure about this one. I feel like it's going to help people be a lot more productive to display the key bindings at all time. But it also clutters the UI...
I tried putting both the letter and number but it looked really terrible. I feel like using the numbers is going to be more predictable anyway.
> Add keybindings for shapes

- .lintstagedrc.js
- src/clipboard.ts
- src/components/ExportDialog.tsx
- src/index.tsx
- src/scene/data.ts
- src/utils.ts
fixes #386, #397
As "discussed" in #386 (it was mostly a monologue), I've moved away from system clipboard when copying elements. The reason is mainly because of browser support when trying to paste using contextMenu (FF/safari doesn't support `navigator.clipboard.readText`).
As a side-effect, users should no longer be asked for permissions (this isn't 100% guaranteed, as I'm still using `clipboard.writeText()` as a preferred method to clear system clip, but AFAIK it doesn't require permissions if called within a user-triggered event callback).
System clipboard is also used when copying backend link to clip, and when exporting PNG to clipboard (in which case, async clipboard API is still required).
Note, to implement #397 I have to clear system clip when user copies scene elements, …
> rewrite clipboard handling

- src/components/ColorPicker.tsx
Fixes #688 
This PR fixes typing into a color picker popup text field that causes color selection via a hotkey. Also, another change I made,  text in the text field is selected/highlighted on the first click. This might be something that needs to be discussed because people might have different preferences. In my opinion, selecting all text makes deleting/removing easier.
Action: selecting  color picker, clicking on the color text field and  typing `"d"`
Before:
After:
> Fix typing into color picker popup text field

- src/components/StoredScenesList.tsx
- src/index.tsx
- src/scene/data.ts
- src/scene/types.ts
In order to avoid the server being able to read the content of the scene, this PR implements local encryption and decryption. This implements the algorithm described in #610.
Right now the server doesn't support uploading binary files. I mocked the server with comments. @lipis, could you add support on the server and update this PR? I added a bunch of TODO: that tell you where to comment/uncomment in order to get the server flow going.
To test locally right now:
- Import: Open http://localhost:3000/#json=1234,5oYVOnGpWYPPTz19-PMYYw and see a square
- Export: Click the export link and see the right url with the private key + the encrypted binary in the console
Fixes #610
> Add encryption

- .lintstagedrc.js
- package.json
- src/clipboard.ts
- ~Remove `no-else-return` (was unnecessarily strict rule that needed manual refactors).~
- Make eslint styleguide rules from `error` → `warn` so that you can distinguish between syntax/type errors when writing code.
- Reintroduce `max-warnings=0` due to the above (not sure why it was removed in #626).
> Eslint tweaks

- src/scene/data.ts
fixes https://github.com/excalidraw/excalidraw/issues/721
Backward compat should be free because the TextEncoder we're currently using for encoding is by default already in `utf8`.
> fix decoding imported data from backend

- .npmrc
https://docs.npmjs.com/misc/config#save-exact
When installing new packages, it will save the exact version instead of rage (`^`)
> Add npmrc to have pinned deps

- src/clipboard.ts
- src/element/textWysiwyg.tsx
- src/index.tsx
- src/shapes.tsx
- src/types.ts
Fixes 3 issues:
- Reset to `selection` tool on paste (fixes https://github.com/excalidraw/excalidraw/issues/712).
- Ensure pasting via contextMenu and via event (`cmd+v`) is aligned. Fixes the case where pasting. via hotkey would paste text from the clipboard, but via contextMenu would paste element.
In order to implement this I had to use `navigator.clipboard.readText` again, which means no support for non-chromium browsers, and it'll ask for permissions again (but unlike old clipboard implem, it will work).
- Ensure pasting into wysiwyg editor allows for plaintext only. Which means I had to revert https://github.com/excalidraw/excalidraw/pull/651/files and reimplement `onpaste`.
before:
after:
> Improve pasting

- src/actions/manager.tsx
- src/actions/types.ts
- src/appState.ts
- src/index.tsx
- src/scene/data.ts
- src/scene/index.ts
- src/types.ts
A refactor and some tweaks:
- Move `footer` to `<LayerUI>`.
- Scrap `state.lng` (from https://github.com/excalidraw/excalidraw/pull/726) in favor of passing it as a prop to `LayerUI` because we weren't using `state.lng` anywhere so it seemed weird to introduce it just to fix a stale state issue.
- Moved history resuming from ActionManager up to `updater` passed from upstream (`asyncActionResult`), which is now passed `commitToHistory: boolean` (defaults to `true`). This is in preparation for making ActionManager usable across the app as a way to sync state.
- Made `loadScene` readonly and factored out.
- Few other tweaks and refactor.
Make sure to review without whitespace changes:
> move footer into layerUI & refactor ActionManager

- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/nb-no.json
- src/locales/pl.json
- src/locales/pt.json
- src/locales/ru.json
- src/scene/data.ts
This PR updates the url upload description to mention that it is end to end encrypted. I used a very similar message as whatsapp so that it is familar to people.
I also removed the automatic copying and turned the alert into prompt. This should be less awkward than the current implementation.
> End to end encryption description

- src/index.tsx
- src/scene/scrollbars.ts
The computation was not correct. I'm not really sure how it used to work but it was not taking into account the dimensions of the scene so it was wrong.
The new algorithm is computing the scrollbar such that it's the position of the viewport in relationship to the bounding box of the viewport and all the elements.
Fixes #680
> Fix scrollbar

- src/actions/actionZindex.tsx
- src/index.tsx
- src/locales/en.json
- src/styles.scss
Fixes #679 by adding the z-index buttons (Send to Back, Bring to Front, Send Backward, Bring Forward) back to the left panel. Improves visibility of the feature for new users.
> Add zindex to panel

- src/actions/actionZindex.tsx
- src/components/ToolIcon.scss
- src/styles.scss
1. fix svg jsx attributes, and remove unnecessary ones
2. center & make active elem orange so it's obvious which is which
before:
after:
> z-index button fixes

- src/element/newElement.ts
fixes #739
I wanted to go for `JSON.parse(JSON.stringify(element))` altogether, to guard against future regressions, but it could cause regressions on other fronts (e.g. when we expected some functions to be kept). We should migrate to a structured cloning algorithm, later.
> ensure duplicateElement does deep copy of points

- src/actions/actionDeleteSelected.tsx
- src/actions/actionProperties.tsx
- src/clipboard.ts
- src/components/ExportDialog.tsx
- src/components/HintViewer.tsx
- src/index.tsx
- src/renderer/renderScene.ts
- src/scene/index.ts
- src/scene/selection.ts
Fixes https://github.com/excalidraw/excalidraw/issues/671.
I also refactored some code related to getting selected elements.
> Resize handler detection should not be active when moving multiple elements

- public/index.html
- src/actions/actionDeleteSelected.tsx
- src/actions/actionFinalize.tsx
- src/components/HintViewer.css
- src/gesture.ts
- src/index.tsx
- src/is-mobile.tsx
- src/locales/en.json
- src/styles.scss
- src/tests/dragCreate.test.tsx
- src/tests/move.test.tsx
- src/tests/multiPointCreate.test.tsx
- src/tests/resize.test.tsx
- src/tests/selection.test.tsx
- src/types.ts
> Add touch support

- src/components/ProjectName.tsx
- src/element/textWysiwyg.tsx
I didn’t realize this would throw an error if it was unsupported, but it should be fixed. cc @nc-rasel. Fixes #802.
> Fix error with contentEditable

- src/index.tsx
- src/scene/data.ts
Fixes #804. `pointerleave` is called after `pointercancel`, but also when the mouse leaves the window.
> Fix zoom being set to NaN

- src/components/ToolIcon.scss
- src/styles.scss
When hovering buttons with hidden radio buttons inside, there's a small part(the hidden radio button) where mouse returns to normal when it should be pointer.
This PR adds `cursor: pointer;` style to radio buttons so the mouse stays consistent.
> Add cursor pointer style to hidden radio buttons

- package-lock.json
- package.json
- src/index.tsx
fixes https://github.com/excalidraw/excalidraw/issues/498
- Improves the output of localStorage (gets rid of double escapes).
- Tries to map error stack trace using source maps (using https://github.com/stacktracejs/stacktrace.js). ~~No clue if this is going to work in production -- depends whether we deploy source maps. We'll see.~~ looks like it does on preview:
Repro:
1. load https://excalidraw-git-improveerrorhandling.vjeux.now.sh//?id=5142238724096000
2. click on the text element
> improve error handling & map stack trace

- src/actions/actionStyles.ts
Fixes: #814 second part(I missed it in the first PR #832 )
```
If it is a text elment or a multielement the app crashes. 
Otherwise, it pastes empty styles. Trying to change the background color of the element freezes the tab.
```
> Fix pasting styles on text elements

- package.json
- public/index.html
Related: https://github.com/excalidraw/excalidraw-desktop/pull/24
```html
<script src="/static/js/2.2a62696b.chunk.js"></script>
<script src="/static/js/main.b098d13e.chunk.js"></script>
```
Does anyone know how to remove the leading slash?
> Use relative path for static files

- src/actions/actionDeleteSelected.tsx
- src/components/App.tsx
- src/scene/selection.ts
Fixes one of the issues with the last PR. We kept previously deleted element IDs in the `selectedElementIds` map, this diff resets them after the deletion occurs.
> Reset selectedElementIds when deleting selected elements

- src/components/App.tsx
- src/gesture.ts
- src/types.ts
@lissitz debugged the selection issue here: https://github.com/excalidraw/excalidraw/issues/871#issuecomment-596258622. It jives with my sense of what the bug might be too.
Since it's a race condition it's hard to know if it's conclusively solved but I haven't been able to repro it since this patch.
> Make gesture.pointers a Map instead of an array of pointers

- src/renderer/renderElement.ts
D'oh! We should probably actually *populate* the canvas cache :)
Test plan:
* Load large scene and drag shape around with devtools open.
* Without patch: very slow
* With patch: buttery smooth
> Fix perf regression

- docs/shortcuts.md
Let's keep track of this document that could be later used as a base for #408 or possible documentation page somewhere like excalidraw.com/docs/shortcuts
Preview: https://github.com/excalidraw/excalidraw/blob/shortcutdocs/docs/shortcuts.md
> Add a doc with all the current shortcuts

- src/data/restore.ts
fixes https://github.com/excalidraw/excalidraw/issues/900
~~before merge, I'll quickly check whether we want to also remove it from `appState` where we stored selection for a while IIRC.~~ nvm, we still do that :).
> filter out selection elements on restore

- src/actions/actionFinalize.tsx
- src/actions/actionProperties.tsx
- src/actions/actionStyles.ts
- src/components/App.tsx
- src/data/restore.ts
- src/element/mutateElement.ts
- src/element/sizeHelpers.ts
- src/element/textElement.ts
- src/element/types.ts
- src/history.ts
I'm still not satisfied with how things are but this makes things a bit better :)
#898 merged in a few changes that I had made that I wasn't quite ready to commit to master :) There were two issues:
* `mutateElement` was a little awkward to use and allocated an extra closure which was wasteful (though probably didn't cause noticeable perf issues)
* We often clone elements and change their properties by doing `{...element, someProp: someValue}`. The issue with this is the `id` of the element will stay the same, but despite the element changing, `version` is not automatically updated. I added a new function to abstract away this pattern.
I do think we'd be better off at this point having ExcalidrawElement as a class, but I'm not 100% certain of it. Looking for feedback!
Test plan: 
* …
> Clean up `mutateElement`

- src/components/App.tsx
Partially helps with https://github.com/excalidraw/excalidraw/issues/740.
In the case of arrow/line, when you doubleclick with that shape selected it creates both, and the arrow/line ends up in some undefined state that throws.
This PR prevents creating text via doubleclick when in `multiElement` mode, which fixes this.
Test plan:
1. select `arrow` shape
2. double-click
3. create another arrow point
3. check console
> cancel text via doubleclick when in multiElement mode

- src/components/App.tsx
- src/data/index.ts
- src/data/types.ts
- src/types.ts
Hotfix for https://github.com/excalidraw/excalidraw/issues/906
No satisfied. Definitely missed major cases, and this may introduce some subtle (or not so subtle) race conditions. As a hotfix it should probably work.
What I'm doing is
1. Not syncing elements being edited (e.g. arrows until they're finalized, or elements during drag etc.)
2. When syncing from remote, prefer local version if the element is currently being edited.
> Fix multiplayer concurrency

- src/actions/actionSelectAll.ts
- src/components/App.tsx
- src/element/newElement.ts
fixes https://github.com/excalidraw/excalidraw/issues/931
This bug occurs in browsers we probably don't officially support, but `Object.fromEntries` is ES2020, so it's rather new. That said, replacing it with `Array#reduce` will arguably improve perf for little cost, so I say let's fix this.
> remove object.fromEntries

- src/appState.ts
- src/components/App.tsx
- src/data/index.ts
- src/data/restore.ts
- src/scene/selection.ts
- src/types.ts
Moved to semi-tombstone architecture for syncing deletions: a map of deleted ids and version at time of deletion. Element is removed on local only if remote deletion has same or newer version than local version. For this reason I removed the `version` incrementing during restore, because that would break this (I also don't see why we did that to begin with).
Also, from now on we're syncing only selected props from `AppState` because we won't want to use any other. Currently I'm sending some props but not doing anything with them yet. Will do so later, and also refactor it a bit.
Don't merge yet. I'm not confident this is correct + I want to make some refactor.
> use deletedIds map to sync deletions

- src/renderer/renderScene.ts
I opted to use transparency to indicate that the pointer is out of screen. It seems to be working relatively well.
Fixes #935
> Render pointers out of screen

- src/element/textWysiwyg.tsx
This was added when we were computing the width without adding "pre" behavior. Now it is no longer an issue
Test plan:
- Create a text with `"&nbsp;&nbsp;a&nbsp;&nbsp;a&nbsp;&nbsp;&nbsp;"`
- Commit the text, make sure it looks the same
- Edit the text, make sure it still has the spaces
> Remove text trim

- src/renderer/renderScene.ts
They shouldn't really change when zooming in or out.
Before:
After:
> Make selection handle resolution independent

- src/components/App.tsx
- src/renderer/renderElement.ts
- src/renderer/renderScene.ts
- src/scene/export.ts
- src/scene/index.ts
- src/scene/zoom.ts
Fixes #861
The original motivation behind this is to make it work with Firefox. But it also helped make the code more intentional.
Test Plan:
- Create one square, select it, zoom in repeatedly, make sure that it zooms centered in the screen and everything looks good
- Scroll at various zoom levels, things look good
- Export a small scene at 1x and 3x, make sure the background is properly set and look good
> Stop using getTransform

- .gitignore
- src/actions/actionCanvas.tsx
- src/actions/actionHistory.tsx
- src/appState.ts
- src/components/App.tsx
- src/data/index.ts
- src/data/restore.ts
- src/element/index.ts
- src/element/mutateElement.ts
- src/element/newElement.ts
- src/history.ts
- src/renderer/renderScene.ts
- src/scene/comparisons.ts
- src/scene/selection.ts
- src/types.ts
* move to using an `isDeleted` field on the element rather than `deletedIds`. this simplified a bunch of the code as we can use the same reconciliation algorithm for every type of modification.
* fix undo to propagate changes to other peers. reset the undo stack when we receive an update from someone else. this behavior is still surprising, and it's possible to lose your redo stack mid-operation if someone else makes a change.
* fix issue where cursors would get lost sometimes
* show real-time resizing of elements
fixes #946 and some of #937
> Fix many syncing issues

- src/actions/actionFinalize.tsx
- src/actions/actionProperties.tsx
- src/actions/actionStyles.ts
- src/components/App.tsx
- src/data/json.ts
- src/data/localStorage.ts
- src/data/restore.ts
- src/element/bounds.ts
- src/element/collision.ts
- src/element/mutateElement.ts
- src/element/newElement.ts
- src/element/sizeHelpers.ts
- src/element/textElement.ts
- src/math.ts
- src/renderer/renderElement.ts
- src/scene/createScene.ts
- src/types.ts
This diff does a few things to clean up how we deal with ExcalidrawElements.
* Wraps all rebinding of the `elements` array with `replaceElements()`. This means you don't have to remember to call `setState({})` after updating the array itself (note that you still need to remember to call it if you call `mutateElement()`)
* `mutateElement()` now knows when to invalidate the shape cache. Gone are the days of manually remembering to `invalidateShapeForElement()`.
* You don't reference `elements` directly anymore. You do it via a function call `getAllElements()`. I'll probably make this function skip deleted Elements in the future, and provide a second function to get the list including the deleted Elements.
* `mutateElement()` and `newElementWith()` now work for `ExcalidrawTextElements`
* I …
> Abstract away or eliminate most of the mutation of the Elements array

- src/components/App.tsx
- src/renderer/renderElement.ts
- src/renderer/renderScene.ts
- src/scene/export.ts
- src/scene/zoom.ts
- src/utils.ts
My original hack to put the scale when we create the canvas element doesn't make much sense. It should be done when we are rendering the scene. I moved it there in this PR.
The rest was all about forwarding the scale to where it's needed.
Fixes #861
> Remove last get/setTransform

- src/element/collision.ts
- src/tests/selection.test.tsx
- The bounding box was not correctly extended to take into account the threshold. It was only for y axis but not x.
- The bezier threshold was using 20 instead of 10 and not taking into account zoom level.
Both those issues are fixed and now the behavior looks good on all the shapes I can test.
Fixes #706
Before:
After:
> Fix hit testing threshold

- src/components/App.tsx
After accidentally closing a multiplayer session, my natural reaction is to just reopen the page. However, if I was the last or only user in the session, the reopened page will be empty. The reopened page overwrites my local history so https://excalidraw.com/ is empty too.
I know there's already a "if all of you disconnect, you will loose the data" warning when I start a multiplayer session, but... the warning doesn't stop me from fat-fingering the close button. So I think it'd be useful to show a confirmation before the user closes or refreshes the page.
NOTE: ideally this prompt is only shown when there has been changes since the last save/export, but I can't seem to find a clean way to do this (marking the app state as "dirty"). But I think this could still be a good start?
Test Plan:
> Show confirmation dialog before the user closes a collaborative session

- src/components/App.tsx
- src/data/index.ts
- src/renderer/renderScene.ts
- src/scene/export.ts
- src/scene/types.ts
- src/types.ts
Reverts excalidraw/excalidraw#971
Some of the words can be interpreted in a negative way: obedient, rat, cow, monkey...
Right now we don’t have a way to see what name we’ve been attributed nor actually change it.
I feel like I merged it too fast. Let’s build the view/edit flow and then merge it back in.
Reverting for now.
> Revert "[RFC] Randomized names next to mouse pointers."

- package-lock.json
- package.json
The enums of the Native File System API have changed ([details](https://github.com/WICG/native-file-system/issues/147)). Version 0.4.0 of [browser-nativefs](https://www.npmjs.com/package/browser-nativefs) deals with this. It's [ugly](https://github.com/GoogleChromeLabs/browser-nativefs/commit/a6ab5c3e93d1c22c38827dbf5aae14b607a38fad) since it involves nested `try {} catch (err) {}`, but will only be necessary until usage of Chrome 80 has died as the last browser to *not* support the new dash-separated enums.
> Update to browser-nativefs 0.4.0

- src/components/App.tsx
- src/components/Popover.tsx
- src/element/mutateElement.ts
I made the faulty assumption that we always called `mutateElement()` from within a React event handler (which is wrapped in `batchedUpdates()`). This isn't true -- we add and remove regular listeners from the `window` also. I wrapped all the event handlers in `unstable_batchedUpdates()` which fixed the performance issue.
> Fix performance regression (#977)

- src/components/App.tsx
The problem is that syncActionResult wasn't using batching.
Test plan:
- Add console.log("update") on componentDidMount
- Reload the page
- Observe a single update log (instead of 3 before this fix)
> Fix three rendering when loading

- src/components/App.tsx
- src/element/mutateElement.ts
- src/points.ts
Fixes #973 and some additional bugs introduced sometime before #955.
Tests:
* Draw and resize every shape
* Draw and resize and rotate an arrow and line (2 point)
* Draw and resize mutielement lines and arrows
* Export preview
* Save file
* Reload file, resize curves
* Resize mutielement line in multiplayer
* Load the 1000 square json, draw a curve, UX is smooth
* Alt-drag works. Shift click works.
The UX isn't perfect -- I think we should flip the element if you switch to negative width -- but it's better than the previous behavior.
> Fix multielements

- src/actions/actionDuplicateSelection.ts
- src/components/App.tsx
- src/components/HintViewer.tsx
- src/data/restore.ts
- src/element/bounds.test.ts
- src/element/bounds.ts
- src/element/collision.ts
- src/element/index.ts
- src/element/mutateElement.ts
- src/element/newElement.test.ts
- src/element/newElement.ts
- src/element/resizeTest.ts
- src/element/sizeHelpers.ts
- src/element/typeChecks.ts
- src/element/types.ts
- src/global.d.ts
- src/history.ts
- src/renderer/renderElement.ts
- src/tests/dragCreate.test.tsx
- src/tests/multiPointCreate.test.tsx
- src/types.ts
In short, this PR adds more type safety.
- Add `ExcalidrawLinearElement` type, and make `points` only specific to that type. This is in expectation of followup https://github.com/excalidraw/excalidraw/pull/949 where I'll be adding another, arrow-specific property.
- Rewrite Element type-specific constructors (move away from parameter list to object; move away from nested constructors when creating text elements).
- Ensure `element.type` narrows down the element type when possible (i.e. make it into a union discriminant). For now, I haven't split `rectangle`/`ellipse`/`diamond` shapes into their own constructors because they all share the same props.
- Don't create generic element on every `pointerdown`. Instead, create specific elements when needed.
- Make APIs that mutate elements …
> improve & granularize ExcalidrawElement types

- src/components/App.tsx
Fixes #993. I probably broke this in #874. Now that we aren't mutating `selectedElementIds` in place we need to keep track of which elements are selected for alt-drag. Fortunately we were already doing this, so I gave the variable a bit of a more descriptive name and started using it in the alt-drag code.
> Fix alt drag

- src/components/App.tsx
Hey Excalidraw! This is a really awesome tool first of all and thanks for making this great!
Totally new-comer here but think I got a fix for https://github.com/excalidraw/excalidraw/issues/994.
From my understanding, double clicking to insert text node into canvas should de-select all the elements that are currently selected. So re-initializing the `selectedElementIds` seemed to be a no brainer.
But since I'm new to this land, I could be totally wrong (very likely)! Appreciate it in advance if anyone catches something that I'd missed.
Other than that, here's the test screenshot I used:
Forgot to screenshot the case where it's a background filled rectangle but it works with that, too.
> Deselect all elements when inserting text with double click

- src/element/textWysiwyg.tsx
- fix regression for https://github.com/excalidraw/excalidraw/pull/454 introduced in https://github.com/excalidraw/excalidraw/pull/947 (by trimming trailing newlines which have no usefulness and mess up bounding box `height` calculation, and they're also added on FF by default for multiline texts)
- also I'm trimming whitespace-only texts which would result in invisible text elements
> Trim trailing newlines

- src/components/App.tsx
https://github.com/excalidraw/excalidraw/pull/987 disabled negative resize even for non-multipoint elements which isn't necessary, hence this fix.
> fix negative resize for non-multipoint elements

- docs/shortcuts.md
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/LockIcon.tsx
Resolves #997 
I think there might be a mistake in accidentally closing the window by pressing `⌘ + Q` while working. To prevent this, ``` ` ```(backquote/backtick) or other keys may be a better option. Please give me feedback.
> Add a Shortcut for Toggling Shape Lock

- src/components/App.tsx
- src/tests/dragCreate.test.tsx
- src/tests/move.test.tsx
- src/tests/multiPointCreate.test.tsx
- src/tests/resize.test.tsx
- src/tests/selection.test.tsx
partial implementation of https://github.com/excalidraw/excalidraw/issues/968 --- I'm  not gonna close it yet.
Exposes `elements`, `appState`, & `history` under `window.h`. Also used in tests.
> expose a few state props for debugging

- src/actions/actionCanvas.tsx
- src/actions/actionDeleteSelected.tsx
- src/actions/actionDuplicateSelection.ts
- src/actions/actionExport.tsx
- src/actions/actionFinalize.tsx
- src/actions/actionHistory.tsx
- src/actions/actionMenu.tsx
- src/actions/actionProperties.tsx
- src/actions/actionSelectAll.ts
- src/actions/actionStyles.ts
- src/actions/actionZindex.tsx
- src/actions/manager.tsx
- src/actions/types.ts
- src/components/App.tsx
- src/data/index.ts
- src/history.ts
fixes https://github.com/excalidraw/excalidraw/issues/988
The main issue was `withBatchedUpdates` allowing to pass functions with higher arity, while swallowing extra arguments, which resulted in `syncActionResult`'s 2nd argument `commitToHistory` always defaulting to `true`.
I've also changed how `commitToHistory` is set. Instead of making it an optional function on `Action` objects, I made it a required property on `ActionResult` object returned from `Action`'s `perform()` method. This way it's explicit, and we'll never forget to set it (which we've already done --- now fixed).
For now, I kept scene loading not being saved to history, but we can later do that, too.
Also, it seems we're always populating history with an initial entry, so I made `undoOnce` bail on `length === 1`. Before, …
> fix history

- src/components/App.tsx
- src/element/index.ts
- src/element/mutateElement.ts
- src/history.ts
- previously, before pushing entry to history we were piping each element through `newElementWith()` which regenerates `versionNonce`. This resulted in every single change going through, effectively skipping the bail-on-no-change check, and thus we were adding changes to history e.g. just on clicking on an element.
I've made it so that we don't update `versionNonce` on this occasion. Note that we're still incrementing `version` of each element. In this case it doesn't cause an immediate issue because when checking against the currently-stored-in-history elements, those already have `version` incremented from last push. WTBS, I think this is brittle and will result in some issue down the line. @petehunt was there a reason why you were doing this (both `version`, and `versionNonce`)?
- …
> Fix history - the 2nd installment

- src/components/App.tsx
Fix for https://github.com/excalidraw/excalidraw/issues/927
The issue is, in the `handleCanvasPointerDown` event handler, we're always setting the `state.draggingElement` to a newly instantiated element:
https://github.com/excalidraw/excalidraw/blob/master/src/components/App.tsx#L1614-L1630
And later it gets added to the selected elements unconditionally
https://github.com/excalidraw/excalidraw/blob/master/src/components/App.tsx#L2152
The fix I'm proposing is that in the pointer down event handler, and if we have a `hitElement`, we're gonna set the `draggingElement` to the `hitElement` (which makes sense) instead of creating a new one. So that later when we set the `selectedElement`, the draggingElement already exists in the selected element and we don't mistakenly create a new "selected …
> Fix adding incorrect dragging element when handleCanvasPointerDown

- package-lock.json
- package.json
- Use `npm audit fix` to upgrade high severity security vulnerabilities [CVE-2020-7598](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7598) in two ESLint dependencies: `acorn` and `minimist`.
- Bump `react-scripts` to version ``3.4.1`` which uses a newer babel version without these security vulnerabilities
`npm audit fix` now only shows 2 vulnerabilities as opposed to 900 before this upgrade.
> Bump react-scripts to version 3.4.1

- src/styles.scss
Also put Arial after Helvetica. I hate Arial.
Apparently there’s `system-ui` which was supposed to make this much simpler but if you use Windows 7 with an East Asian language the system font for Latin letters is truly awful.
> Use system fonts where possible.

- package-lock.json
```
found 501 vulnerabilities (498 low, 3 moderate)
run `npm audit fix` to fix them, or `npm audit` for details
```
> npm-audit-fix

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/LockIcon.tsx
- src/components/MobileMenu.tsx
- src/components/ToolIcon.scss
Resolves #819 
- As discussed in #819, I added different lock button style for small screens. I found 360px to be a suitable breakpoint and handled it via media query. 
- Rename the event handler that I added in #1005
> Add the shape lock button for mobile

- src/components/App.tsx
reverts https://github.com/excalidraw/excalidraw/pull/1036 to fix https://github.com/excalidraw/excalidraw/issues/1072
We can decide later what we want to do. For now I think this should be merged asap because it has the tendency to leak user's private scene to remote rooms.
Explanation: https://github.com/excalidraw/excalidraw/issues/1072#issuecomment-603364309
> load from localStorage only if not in multiplayer

- package.json
- tsconfig.json
- Safari < 12 don’t support `.flat()`, which we use.
- KaiOS doesn’t support async functions, and runs on a lot of feature phones which I hope we don’t target.
- Trident-based Edge (12–18) don’t support `.flat()`.
- Chrome < 70 doesn’t support Grid or `.flat()`
- Samsung Internet < 10 and UC Browser < 13 don’t support `.flat()`.
Note: to get the build script to take the new values, you have to `rm -rf node_modules/.cache`.
It also adds a smaller set of supported browsers for dev mode. I’m happy to revert this if someone on the team is deving on an older browser.
> Remove support for some older browsers that probably didn’t work anyway

- src/components/App.tsx
Resolves #285 
`this.startTextEditing` method has been extracted to reuse the `handleCanvasDoubleClick` handler.
> Add Enter key handler that can start text editing

- src/actions/actionZindex.tsx
- src/components/App.tsx
- src/scene/index.ts
- src/scene/selection.ts
- src/tests/zindex.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/989
Implementation follows @vjeux [suggestion](https://github.com/excalidraw/excalidraw/issues/1069#issuecomment-603064630) of auto-selecting neighboring deleted elements.
Comments & tests tomorrow, and merge then. Pushed as RFC.
> fix z-index action to account for deleted elems

- src/styles.scss
Fixes #1082 
'Scroll back to content' button is not visible only on the desktop. Changes have been made in [this work](https://github.com/excalidraw/excalidraw/pull/1002/files#diff-6a2256f44598ec970b4bd034962e011eR376). I modified the z-index because it should be applied only to mobile.
> Apply scroll-back-to-content's z-index only for mobile

- public/index.html
- src/appState.ts
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/LoadingMessage.tsx
- src/components/MobileMenu.tsx
- src/global.d.ts
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/types.ts
Added loading state to the app, useful for 3 main cases:
1. During initial app load so that users with slow connection (or when Netlify is slow) know something is happening.
2. When loading hefty scenes, or importing them.
3. When initializing a collaboration session.
> Add loading state

- src/components/App.tsx
This wasn't taking into account zoom properly.
The logic should probably get refactored a bit, it's not ideal that we're passing canvas, state and scale as different arguments. Also it's weird that the function that returns the center is computing the viewport translation. But I'm not motivated enough to fix it right now...
Also the small jump at the end is annoying!
Fixes #1100
> Fix wysiwyg center

- src/components/Actions.tsx
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
This work continues #1146 
The current action button is hidden by `visibility`, so it is still clickable and the tooltip is visible.
To fix this, I modified the button to show after editing is complete. and also reflected [this suggestion](https://github.com/excalidraw/excalidraw/pull/1146#issuecomment-607097265).
> Modify action buttons visibility for desktop

- src/i18n.ts
As per #1183 I fixed the arabic language name by changing it from عربي to العربية as the existing one عربي is an adjective not the language name which is العربية.
> Change arabic language name

- src/element/textWysiwyg.tsx
fix https://github.com/excalidraw/excalidraw/pull/1185 not using `ctrl` for windows.
Before merging this, we should also decide whether we want to keep `shift+enter` to enter newline despite the default for that being `enter` without shift. /cc @vjeux
> make text committing cross-platform

- src/components/ToolButton.tsx
- src/components/ToolIcon.scss
As per #1183 this fixes the alignment of the ToolButton Label in RTL mode as mentioned per this screenshot:
> Align ToolButton Label in RTL mode

- src/components/Island.tsx
- src/components/LayerUI.tsx
- src/styles.scss
Fixes #1127 
- Modify markup to move the zoom button to left menus
- Add some styles for left center menu
- Remove unused menu related classes
> Make left panel height flexible to avoid overflow

- now.json
- public/index.html
Fixes #1192
- We should allow websites to embed Excalidraw in an `iFrame`
- [**Preview**](https://excalidraw-git-headers.excalidraw.now.sh)
- [Test Before](https://securityheaders.com/?q=https%3A%2F%2Fexcalidraw.com%2F&followRedirects=on): **D**
- [Test After](https://securityheaders.com/?q=https%3A%2F%2Fexcalidraw-git-headers.excalidraw.now.sh&followRedirects=on): **A**
- https://www.cspisawesome.com
> Add Security Headers

- src/actions/actionSelectAll.ts
While I was developing #1193, I found a weird behavior.
It was because selectAll selects deleted elements.
Unless it is intentional, this should fix it.
(Otherwise, I can do a workaround.)
> do not select deleted elements

- src/components/App.tsx
- src/data/index.ts
- src/renderer/renderScene.ts
- src/scene/export.ts
- src/scene/types.ts
- src/types.ts
Fixes https://github.com/excalidraw/excalidraw/issues/1109
First take. Will refactor tomorrow.
(The stroke rendering courtesy of @vjeux)
Related: I think we should use a subset of bright colors for remote users. I often get gray/dark-blue/purple remote color which is hardly distinguishable from local color (black).
> sync remote selection

- src/element/bounds.ts
- src/scene/scroll.ts
test plan:
1. create empty-scene collab room
2. join in another tab
3. try to draw in the 2nd tab
> fix scrollToCenter when no elements supplied

- src/appState.ts
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/Modal.tsx
- src/components/ShortcutsDialog.tsx
- src/keys.ts
- src/locales/en.json
- src/styles.scss
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/types.ts
- src/utils.ts
> Show shortcuts dialog when pressing `?`

- src/element/textWysiwyg.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1247
I messed up when I removed those handler removals, because it turns out they weren't there for memory leak problems :)
> fix wysiwyg event cleanup

- src/clipboard.ts
- src/components/App.tsx
- src/data/index.ts
- src/locales/en.json
- src/scene/types.ts
Fixes https://github.com/excalidraw/excalidraw/issues/860.
Added support to copy to clipboard as SVG by copying the whole SVG as text.
Tested by pasting the content into Figma - which is able to detect that it's an SVG content and pastes the image.
> Adding ability to copy to clipboard as SVG

- src/clipboard.ts
- src/scene/export.ts
fixes https://github.com/excalidraw/excalidraw/issues/1252
- added excalidraw tag comment to export & clipboard (not sure if there's is normative `<svg>` attribute for this, but I didn't find it)
> prevent pasting svg copied from excalidraw

- src/components/Dialog.tsx
- src/components/ExportDialog.tsx
- src/components/Modal.tsx
- src/components/ShortcutsDialog.tsx
Currently `Escape` key does not work on `ShortcutsDialog`. This is an issue due to focus management, so some generalized focus handling is added to `Dialog` like [`ExportDialog`](https://github.com/excalidraw/excalidraw/blob/master/src/components/ExportDialog.tsx#L88-L90). And a prop type warning related to `key` has been fixed.
> Fix 'Dialog' keydown event and prop type warning

- src/element/textWysiwyg.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1322
This aligns our wysiwyg editor with Figma & Affinity, where newline can be added both via `enter` & `shift+enter`.
Committing remains via `Cmd/Ctrl+Enter`.
> support newline on shift+enter

- src/components/Island.css
- src/components/ShortcutsDialog.tsx
1. Fix Chinese display unnecessary line breaks.
2. Keep all row heights consistent.
Before:
After:
> Optimize ShortcutsDialog style

- src/components/App.tsx
Hoping that it will improve #1310 
I tried testing it with the browser throttled connection and it seemed to perform a bit better, though it's hard to tell if events actually get dropped. In any case, not a full solution to the problem.
> Make the mouse location broadcast volatile

- src/components/App.tsx
- src/element/index.ts
- src/element/resizeElements.ts
- src/element/types.ts
I'm not sure if it's only for me, but the following syntax is causing [codesandbox](https://codesandbox.io/s/github/excalidraw/excalidraw) parsing error. It seems to be an issue due to the syntax supported by typescript [v3.8.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-exports). To solve this, the type was moved to the `element/types.ts` file according to the existing convention.
```ts
export type { ResizeArrowFnType } from "./resizeElements";
```
> Refactor ResizeArrowFnType to resolve Codesandbox parsing error

- package-lock.json
- package.json
Updated with browser-nativefs v0.5.0.
https://wicg.github.io/native-file-system/#ref-for-dom-filesystemfilehandle-createwritable①:~:text=In%20the%20Origin%20Trial%20as%20available%20in%20Chrome%2082%2C%20createWritable%20replaces%20the%20createWriter%20method.
> createWriter is now createWritable

- src/utils.ts
> Update shortcut display for enter on Mac

- package.json
- src/components/LoadingMessage.tsx
This helps prompt people to use `t()` instead. You can work around the rule bu wrapping the text in `{""}`.
> Add rule banning literal text in JSX

- src/data/restore.ts
The `textAlign` property of text object was not read when reloading a scene or opening a saved file.
> Restore textAlign property

- src/element/bounds.ts
Close #1303
For diamonds and ellipses, the calculation should be fast.
For curved lines, it may require some computations. (There's probably room for improvement, but I'm not sure how.)
> Calculate rotated element bounds properly

- src/actions/actionProperties.tsx
- src/appState.ts
- src/components/App.tsx
- src/element/index.ts
- src/element/textWysiwyg.tsx
- src/element/types.ts
- src/renderer/renderScene.ts
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/types.ts
Re: #1325 , the `blur` handler on the editable is causing the active editing element to become a normal element, whenever a click happens outside that element, including the choosing of a style on the toolbox.
This PR is a PoC, to expose the wysiwyg element so we can finalize it on demand, thus allowing us to do in-place style changes while it is still on editing mode.
I can see how this could potentially pave the way for tackling https://github.com/excalidraw/excalidraw/pull/1213 and https://github.com/excalidraw/excalidraw/issues/1126. Let me know if I'm wrong on this.
> PoC: Expose wysiwyg element to manipulate from outside

- src/renderer/renderElement.ts
The exported SVG file did not reflect the `textAlign` property setting of the text object.
> Fix to reflect `textAlign` property to SVG export

- src/components/App.tsx
I think this should fix #903 
However, might want to test it with the deployed commit since not sure how to test this on local. I wasn't able to connect to the same collaboration session on my local server.
> Fix flickering mouse tracking when using two touches on mobile

- src/element/bounds.ts
Fix #1393.
It was a silly mistype.
> fix calc diamond bounds

- src/renderer/renderElement.ts
Fill of looping lines is not worked expectedly in exported SVG file.
On canvas:
Exported SVG:
In accordance with #1315, apply the evenodd rule to SVG fills as well.
(This will need to be fixed If we want to merge changes like #1341.)
And the following is the behavior after fix:
On canvas:
Exported SVG:
> Fix fill of looping lines in exported SVG

- src/renderer/renderElement.ts
https://github.com/excalidraw/excalidraw/pull/1396#discussion_r407142052
When exporting the SVG contains a line element, all line elements had `fill-rule` attribute.
But this is useless, so fixed it to only set it when necessary.
> Suppresses unnecessary fill-rule attribute in SVG

- public/index.html
Fixes https://github.com/excalidraw/excalidraw/issues/1385 and https://github.com/excalidraw/excalidraw/issues/1386
@dwelle I think this should fix the issue. It looks like the connect-src implementation isn't as consistent across browsers. Would it be possible for us to check this on Safari also, before this PR is merged. I run a linux system and cannot test that out currently. But I can confirm that it works alright on Firefox, Chromium, Brave on Linux.
> Support http: ws: for self in connect-src csp

- public/index.html
- src/appState.ts
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/constants.ts
- src/element/textWysiwyg.tsx
- src/element/types.ts
- src/renderer/renderScene.ts
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/types.ts
So, at first I started making a few fixes which then turned into a full rewrite :smile:.
First, I wanted to fix problems with previous solution that discarded wysiwyg's `blur` event altogether. Problem with finalizing wysiwyg on explicit `pointerDown` on canvas is that we don't finalize when e.g. changing tools (which we should), or zooming in/out (which resulted in visual bugs) and who knows what else.
So instead I used a different workaround: when clicking inside the menu, temporarily remove the `blur` event, and re-enable it on `pointerup` (plus some logic on top to handle edge-cases).
I've also fixed a case when you click on the same property which doesn't result in update, so on previous solution the wysiwyg wasn't focused.
Another bug this PR fixes is trying to type into color …
> rewrite wysiwyg property updating

- now.json
- public/index.html
After internal discussion, we decided to remove CSP directives for now, as it was still causing issues.
We can try to introduce it again when we're more mature, and when there's an actual use case (attack vector) we want to guard against. Right now it's only causing issues when we develop new features.
/cc @lipis @Shriram-Balaji
> Remove CSP

- src/index.tsx
For https://github.com/excalidraw/excalidraw/issues/1372
> Ignore `undefined is not an object (evaluating 'window.__pad.performLoop')` error

- public/index.html
The `meta[name="theme-color"]` was declared twice, with contradictory values (black, white). This PR removes one of them and sets the theme color to white.
> Remove superfluous meta tag

- src/components/App.tsx
fixes case when wheel-dragging, and the callback accesses the event asynchronously.
https://reactjs.org/docs/events.html#event-pooling
> persist pointerDown event

- src/components/Island.css
- src/components/Modal.scss
- src/css/theme.scss
Removed transparency from modals, and tweaked menus for better legibility.
menu before:
menu after:
> tweak blurry bg for legibility & remove from modals

- src/index.tsx
It does nothing once the app is installed, so don't load it.
> Only load PWACompat when we really need it

- src/components/Island.css
- src/components/Island.tsx
- src/components/LayerUI.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1444
Since the `backdrop-filter` on `.Island` introduced in https://github.com/excalidraw/excalidraw/issues/1444 creates a local stacking context, the nested color picker is stacked relative to the `.Island`. And since shape actions menu is rendered 2nd in the DOM, it has higher local stacking order.
This PR makes the 1st menu have higher stacking order by first making all `.Island` elements positioned so that `z-index` takes effect, and second making the 1st menu have higher `z-index` value than the shape menu.
> fix bg color picker rendered behind shape menu

- src/components/App.tsx
Ensures that `Ctrl/Cmd+Shift+C` works when devTools is not focued. I do this so often that it's about time we fix this.
> don't prevent select-element devTools action

- src/actions/actionStyles.ts
When pasting a style on text element, the value of `textAlign` is not reflected.
> Reflect `textAlign` when pasting a style

- package-lock.json
- package.json
- src/element/collision.ts
This came into light because of dependabot's PR for bumping roughjs version failed. https://github.com/excalidraw/excalidraw/pull/1458
I had refactored some of roughjs' geometry code into a separate npm package  (`points-on-curve`) without thinking of consequences. (This function was not documented and only used in excalidraw)
This PR bumps the version and uses the `points-on-curve` package which was refactored out of roughjs.
> Bump roughjs and resolve breaking change in roughjs refactoring. (sorry)

- src/components/LayerUI.scss
- src/components/LayerUI.tsx
It’s bad to use `*-left` and `*-right` because it doesn’t translate properly when using an RTL layout. Instead, `*-inline-start` and `*-inline-end` should be used.
> RTL for the security badge, add an arrow to the tooltip

- src/element/resizeTest.ts
This is something I gave up in #1099, because creating arbitrary cursors is not trivial.
However, rotating existing cursors is not hard, and this is it.
We might want a custom cursor for rotation, though.
> Better resize cursors on rotated elements

- src/locales/en.json
I think it's pretty obvious that it's clickable since we are changing the pointer. 
I don't like it when have to point the obvious, especially with `click here`, etc..
> Update shield's tooltip

- src/components/ColorPicker.tsx
- src/renderer/renderScene.ts
Fixes:
- inability to input HEX colors without `#` (fixes https://github.com/excalidraw/excalidraw/issues/1485)
- in many cases, colors being normalized to HEX while you're typing
Adds:
- keep colors in the form user typed them
- ability to use rgba/hsla
> rewrite picker color handling

- src/components/App.tsx
- src/components/Portal.tsx
The goal is eventually to have all the socket-y code in Portal so App doesn't know anything about how collaboration is implemented.
> Begin moving socket listeners to Portal

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- package.json
Hi,
I've been searching for a good whiteboard tool and Excalidraw looks very prominent for that.
I would, however, like to self-host this so in this PR I added necessary files to build a Docker image and test it locally. The resulting image is as small as **23.3 MB** 🎉 
If this satisfies the needs, this also fixes #1078 
Eventually, it might be wise to add a new Github Action for pushing this image to Docker Hub using e.g. this [official action](https://github.com/docker/build-push-action).
To get up and running, I've added instructions into README. Let me know if you require more information.
> Add option for self-hosting via Docker

- src/components/LayerUI.scss
- src/components/LayerUI.tsx
- src/components/LockIcon.tsx
- src/components/Stack.tsx
fixes https://github.com/excalidraw/excalidraw/issues/1510
(anyone also has problems figuring out which div corresponds to which menu in our `LayerUI.tsx`?)
> disable pointer events on hidden menus in zen mode

- src/shapes.tsx
FIxes issue #1532
For ease of understanding I'll use an example
The user wants to use the text tool and uses the keyboard to select it:
Before to select the text tool **t** would work but **T** wouldn't work
Now using **t** or **T** will select the text tool
> Make tools shortcuts case insensitive

- src/data/index.ts
`crypto.subtle.importKey` returns a promise, so there's no need to `await`
edit: tsc complained, the WebCrypto interface currently returns `PromiseLike`... it looks like the issue was recently resolved (see: https://github.com/microsoft/TSJS-lib-generator/pull/193) but hasn't made it into typescript release yet (see: https://github.com/microsoft/TSJS-lib-generator/pull/843)
in lieu of changing the return type to `PromiseLike` i'll revert it to async function so it's wrapped in a vanilla promise, once these PRs land in ts, can remove async wrapper
this PR will reduce `getImportedKey` from 3 to 2 promises
> fix(data): removes unnecessary await

- src/components/App.tsx
- src/global.d.ts
- src/time_constants.ts
fixes https://github.com/excalidraw/excalidraw/issues/1553
It seems, at least in FF, that fonts are being (re)loaded on init when we join remote scene. Instead of waiting on font load twice (once in init after component mount, and once after we initialize remote scene), or potentially more (in the future), I've added a listener for font loading which should fix all the cases.
I removed the initial wait for font load in compo mount to simplify things. This will likely result in initial FOUT for non-remote scenes, but IMO it's not drastic.
> fix incorrect font rendered on late load

- src/components/RoomDialog.tsx
- src/locales/ar-SA.json
- src/locales/bg-BG.json
- src/locales/de-DE.json
- src/locales/el-GR.json
- src/locales/en.json
- src/locales/es-ES.json
- src/locales/fi-FI.json
- src/locales/fr-FR.json
- src/locales/he-IL.json
- src/locales/hi-IN.json
- src/locales/hu-HU.json
- src/locales/id-ID.json
- src/locales/it-IT.json
- src/locales/ja-JP.json
- src/locales/ko-KR.json
- src/locales/nl-NL.json
- src/locales/no-NO.json
- src/locales/pl-PL.json
- src/locales/pt-PT.json
- src/locales/ru-RU.json
- src/locales/tr-TR.json
- src/locales/zh-CN.json
- src/locales/zh-TW.json
Small wording change. I was confused by the room dialog, thinking 'Name' was asking me to assign a label to the live collaboration session. 
Changing the label to 'Your name' eliminates that ambiguity. 
I added a new label `labels.yourName`, and set it to 'Your name' in English. For the rest of the languages I duplicated the existing `labels.name`, so that it falls back on the existing localized text rather than reverting to English. Let me know if there's a better approach.
> Room dialog: Change 'Name' to 'Your name'

- src/components/App.tsx
- src/element/index.ts
- src/element/resizeElements.ts
- src/element/types.ts
Close #1339
This is just to refactor code without changing the behavior.
(I wasn't able to come up with a simple fix for https://github.com/excalidraw/excalidraw/issues/1339#issuecomment-611969579)
> Refactor: resize two-point lines/arrows

- src/components/ShortcutsDialog.tsx
- src/utils.ts
fixes https://github.com/excalidraw/excalidraw/issues/1557
I used `Cmd` instead of `Command` because the long form is not used very often, and takes too much space.
> don't use unicode characters for shortcut help

- public/index.html
The origin trial ran out on May 13.
> Remove no longer needed Native File System API v1 origin trial token

- src/actions/actionFinalize.tsx
- src/components/App.tsx
https://github.com/excalidraw/excalidraw/pull/1594 was merged a bit too fast. While correct, we should use `commitToHistory` prop in actions.
/cc @kbariotis @lusingander
> use commitToHistory prop for handling draw history

- src/components/ShortcutsDialog.tsx
As with the other shortcut keys in help modal, Alt should be labeled as Option on Mac.
> Alt should be labeled as Option on Mac

- src/element/bounds.ts
- src/element/resizeElements.ts
- src/points.ts
For part of #1218. This was tricky regardless of the small diff. Even with two-point lines, element.width/height are different from the absolute coords.
> feat: resize multiple elements including two-point lines

- Dockerfile
Declaring
`ENV NODE_ENV=production` before `npm install` will not install devDependencies and the build will fail with a TypeScript error, see issue #1593 
Move the declaration before `RUN npm run build:app` so the build succeed.
> docker build : install devDependencies so the build succeed

- src/scene/globalScene.ts
This PR caches nonDeleted elements on each replacement so that `globalSceneState.getElements()` 1) doesn't renew array reference unnecessarily (used in `LayerUI` memoization), and 2) makes it `O(1)` instead of `O(n)` operation.
This kinda hinges on the fact that we call `replaceAllElements()` when we delete them, which we seem to be doing now.
This gets us back to 60FPS for regular scenes (for a subset of operations).
Here's element dragging on the 256 scene:
Before:
After:
> cache nonDeleted elements

- README.md
Without the www, it makes firefox mad, because of a CERT error.
[Broken](https://typescriptlang.org)
[Fixed](https://www.typescriptlang.org)
> fix typescript link

- src/element/newElement.ts
- src/history.ts
Rather than serialize/deserialize all the elements, instead only store the elements that have changed.
Tested by making changes in a large scene and manually inspecting the history object.
I also took a look at the staged version of this PR vs production excalidraw.com. When I load up a 2mb scene, force GC, drag an element 10 times, and force GC again, the production version uses 28mb of RAM, and this diff drops it down to 17mb.
When you take a look at the memory usage after loading and rendering the scene the difference is much more pronounced: the production version stores 14mb of history, and this version stores only 3.
Fixes #1258
Probably fixes #1246 and #1357
> Optimize undo history

- src/actions/actionDeleteSelected.tsx
- src/components/App.tsx
- src/element/mutateElement.ts
- src/element/newElement.ts
- src/element/types.ts
- src/groups.ts
- src/history.ts
- src/scene/index.ts
- src/scene/selection.ts
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/types.ts
Mainly, this fixes (in 2nd to last commit) the case where you edit a group and remove all except the last element in group. Afterwards, if you selected that element, it would show as a group, which it shouldn't.
We could either 1) automatically ungroup on removing penultimate element from group 2) ignore group selection for N=1 groups.
I went with (2) because if/when we later introduce layers, we don't want to remove groups when removing sibling elements. This is what Figma et al does. It also doesn't really hurt to retain the group, and just ignore it (it's also much simpler, and shows the group model we chose was the right call).
---
In the remaining commits, I do:
- Persist `editingGroupId` to history. This takes care of the case where you edit stuff within a group, and undo/redo. You …
> Fix group element removing

- src/data/index.ts
- src/renderer/renderElement.ts
- src/scene/export.ts
- src/utils.ts
This fixes a bug on the text direction when the RTL text is mixed with LTR or non-directional characters, which causes a visual inconsistency between how it shows on the Textfield and how it shows on the Canvas 
I first went with `CanvasRenderingContext2D.direction` but it's still experimental and it's not very supported.
Then I switch to setting the `dir` attribute on the canvas directly. But for some reason it only works if the canvas is mounted to the DOM. hence, doing the "dirty" `appendChild` + `removeChild`.
while trying to implement RTL support on the SVG export I noticed a miscalculated offset, and I fixed it
> Fix RTL text direction rendering

- src/element/linearElementEditor.ts
Undo line editing works as expected when I hold down the alt key and move the cursor.
However, if I hold down the alt key and clicking without moving the cursor, it will not work as expected.
It works as shown in the following image:
I expect it to work like the image below.
I suppose that if we call `createPointAt`, we also need to call `resumeRecording`.
> Fix undo with line editing

- src/charts.ts
- src/clipboard.ts
- src/components/App.tsx
- src/locales/en.json
Copy some cells from excel, paste them into excalidraw, and get an editable bar chart.
In the future we may want to add something to the toolbar or more chart types. This is an MVP optimized for a small implementation size and for making Excalidraw an option for creating presentations.
> Excalicharts MVP

- public/app.css
- public/index.html
- src/components/App.tsx
- src/css/styles.scss
* Rename container to excalidraw as container is a very generic class
* Moved the CSS from index.html to app.css so it can be included in the upstream app as well
cc @dwelle
> rename container class to excalidraw and move css from index.html to app.css

- src/components/ColorPicker.scss
Here's a fix for the issue #1675 . It was a small change for a z-index. The colour picker hash div does not conflict with any other elements and should be on the base.
**Screenshots**
_Issue_
_Fix_
> Tune down z-index for the color-picker-hash div

- src/renderer/renderElement.ts
fix https://github.com/excalidraw/excalidraw/issues/1739
The regression was caused in https://github.com/excalidraw/excalidraw/pull/1687/files#diff-680b22eac5b0928191cad6f83fdadda9R398-R402 which I didn't notice because we're depending on side-effects of that function. Thus I split it to make it more obvious.
> fix not always generating shape on render

- Dockerfile
- package.json
- src/index.tsx
Disables Sentry inside the Docker container (also disables Gtag as previously an env var was being overridden).
https://github.com/excalidraw/excalidraw/issues/1768
> Disable Sentry inside Docker

- src/components/App.tsx
close #1816 
This is exactly what I concerned in https://github.com/excalidraw/excalidraw/pull/1788#discussion_r443167541 but wasn't sure the specific case to fail.
This PR should fix the case reported. Note the code is not very ideal, and it feels like we do duplicated things. Glad if someone could take a look to refactor. cc @petehunt
> fix: start dragging grouped elements

- src/components/Modal.tsx
> Fix flickering outline on the dialogs while clicking

- src/components/App.tsx
- src/data/localStorage.ts
After merging https://github.com/excalidraw/excalidraw/commit/9351b2821c1d6a96f384d7fb2d92a006b9fc056e
the height/width if changed when you open excalidraw, takes the older height/width until resized instead of the current one since it's saved in local storage.
> use width,height from current appstate when initializing scene

- src/actions/actionStyles.ts
- src/components/ShortcutsDialog.tsx
- src/keys.ts
fix https://github.com/excalidraw/excalidraw/issues/1688
Moved to `Cmd/Ctrl+Opt/Alt+C/V` for copy/paste styles, because previous shortcuts collided with browser default.
overrides Mac's "inspect element", but that shortcut is only an alias for cross-platform `Cmd+Shift+C`, and Figma uses this also, so it should be fine.
> change copy/paste styles shortcuts

- src/components/App.tsx
- src/constants.ts
- src/data/index.ts
- src/locales/en.json
fixes https://github.com/excalidraw/excalidraw/issues/1861
- prompts only if local scene contains elements (appState overriding is low-profile, so let's limit the prompting when not absolutely necessary)
Suboptimal behavior:
- reloading page during collab will prompt for confirmation, too
- ditto for loading identical collab link
> prompt when loading external scene before overriding local one

- src/components/App.tsx
- src/constants.ts
It's annoying that when you paste a scene link to url bar it doesn't reload until 2nd confirm (at least on Win Chrome). This PR fixes that by listening on `hashchange`.
> reload scene on hashchange

- .dockerignore
As I began working on the Docker image, I realised that the environment variables defined in https://github.com/excalidraw/excalidraw/blob/8621ddb/.env were being ignored. This fixes a regression introduced in #1848.
> Restore missing env vars in Docker image

- src/appState.ts
We're [getting errors](https://sentry.io/organizations/excalidraw/issues/1778894364/?environment=production&project=5179260&query=is%3Aunresolved) (me included) while clearing appState for storage. Happened to me several times during init load. Not sure how/why (it'd make sense for old schemas, but I'm on latest so it shouldn't be happening), so I added an extra log so we can diagnose.
> fix accessing nonexisting config property during appState clearing

- package.json
This was bugging me. Before: 
After:
`¯\_(ツ)_/¯ `
> Add name field to package.json

- src/constants.ts
- src/utils.ts
In many Windows browsers (Chrome, Firefox, Edge), certain older emoji (pre-2012) render in monochrome using the Segoe UI Symbols font. Newer emoji are rendered in the Segoe UI Emoji font. 
If the css `fontFamily` string for an element includes `Segoe UI Emoji` as a final fallback, all emoji are rendered correctly. 
This PR appends the fallback font in the `getFontFamilyString` utility function. So for example if the user's selected font is `Cascadia`, the result will be `Cascadia,Segoe UI Emoji`.
> Fix display of some emoji on Windows

- src/components/LayerUI.tsx
Not sure when it regressed, but since we are disregarding `isResizing` when comparing states in LayerUI memo resolver, it resulted in the hint not being shown.
I've also removed discarding other props that we either consider in HintViewer, or may do in the near future. Not sure why those props were being ignored ITFP since they shouldn't result in degrading the performance much.
> fix resize hints not showing due to LayerUI bailing on updates

- src/components/Actions.tsx
- src/components/App.tsx
- src/components/ShortcutsDialog.tsx
- src/shapes.tsx
Changed the defaults for these tools to align either with standards (`selection`, `line`), or Figma (`draw`). Kept previous shortcuts on top, for now.
- `selection` default changed to `V`
- `line` default changed to `P`
- `draw` default changed to `Shift+P` (Photoshop uses `P P`, that's why Figma probably went with `Shift+P` and I concur. It's an awkward shortcut, but we display numbers as primary shortcuts anyway)
> change selection/line/draw shortcut defaults

- src/actions/actionGroup.tsx
- src/components/Actions.tsx
- src/components/icons.tsx
- src/tests/regressionTests.test.tsx
Add group and ungroup icons to the action icons
fix for issue:[#1827](https://github.com/excalidraw/excalidraw/issues/1827)
I do my very best creating both icons  - unfortunately I'm not a designer. But I think it's looks usable.
> Issues/1827 group-ungroup icons

- src/components/App.tsx
- src/element/handlerRectangles.ts
- src/element/resizeElements.ts
- src/renderer/renderScene.ts
> feat: rotating multiple elements

- src/components/App.tsx
This was an oversight to enable it for all the shapes. I don't believe that we want to be able to insert text on double click when drawing a rectangle for example. And it's definitely a broken experience when doing so for free draw.
Fixes part of #1935
> Only insert text on double click when selection is enabled

- src/components/App.tsx
- src/element/linearElementEditor.ts
/cc @dai-shi 
Also fixes a case where if you start dragging the whole line and during the drag the cursor happens to mover over an point (happens when moving mouse really fast), it started to drag the point instead.
> simplify by replacing draggingElementPointIndex with isDragging

- src/index.tsx
We're effectively preventing `touchmove` on ~~non-safari~~ browsers that do not support `event.scale`. This manifests in scrolling (of overflowing containers) not working on mobile.
> do not prevent UI scrolling on mobile

- src/components/App.tsx
Implements #1981
The distance used in the iterative end-point fit algorithm to
determine if points can be removed no longer ignores the
zoom. As the zoom gets larger this distance will get smaller
and fewer points will be removed, thus making for finer grain
control over the drawing. As the zoom gets smaller the drawing
will get more coarse as more points are removed.
> update simplifier distance to reflect zoom

- src/components/ShortcutsDialog.tsx
- src/locales/en.json
Follow up to #1899.
Adds last item in Shapes
> Add prevent binding keyboard shortcut to shortcuts dialog

- src/components/RoomDialog.scss
- src/components/RoomDialog.tsx
In the Collaboration dialog, there are 2 emojis in paragraphs. The 🔒 one was always correctly displayed on macOS because the system font defaults to Emoji Presentation mode for this emoji, whereas the ⚠️ one rendered gray-scale because the system font defaults to Text Presentation mode for this emoji.
It may differ a lot based on the systems, so the most consistent way to have Emoji Presentation seems to be `font-family: sans-serif`. Even Variation Selector-16 didn't work here.
> 🐛 Fix emoji rendering

- src/components/Avatar.tsx
It's unused and serialized to `undefined`.
> 🐛 Remove unnecessary class name props

- src/components/App.tsx
- src/css/theme.scss
Before (note the bottom):
After (note the bottom):
> Make iOS "safe area" respect dark mode

- src/components/LayerUI.tsx
Mainly to have all the top icons on the same level.. plus we have more real estate by removing the extra padding.
> Reduce the padding of the left 'Islands'

- src/element/textWysiwyg.tsx
Looks like event.stopPropagation() is not enough to stop Chrome from handling the pinch zoom event when the cursor is over the <textarea> for the wysiwg text.
On this PR, I added `event.preventDefault()` so that the Chrome browser does not handle the pinch zoom.
I tested this on:
- Chrome 84 ✅ 
- Brave 1.12 (Chromium 84) ✅ 
- Firefox (was not affected by the problem and still works the same way) ✅ 
- Safari (zoom and panning on wysiwg is still broken) 🔴
> Fix #2075 - Pinch zooming while typing text breaks the UI on Chrome Mac OS X

- src/components/HintViewer.scss
Fixes #2063
I decided to go with this variant, just add background for the whole Hint block, because otherwise padding looks ugly anyway (see issue)
There is another issue with hint, it does not look great with small screens, I think I'll look into that with different PR
> Fix multiline hint text cropping

- public/index.html
hack-fix https://github.com/excalidraw/excalidraw/issues/2061 until https://github.com/excalidraw/excalidraw/issues/2083 is fixed
@lipis to answer your previous question as for why we have shape-tools and other menu labels: I think it was added for screen readers.
> reintroduce index CSS as interim solution to SW caching issues

- src/tests/helpers/api.ts
- src/tests/helpers/ui.ts
- src/tests/regressionTests.test.tsx
- src/tests/test-utils.ts
First part of major test refactoring.
In this PR, I've focused on making helpers from `regressionTests.test.tsx` be able to be used elsewhere.
In doing so, I've namespaced most of the helpers under respective classes (as static methods): `Keyboard`, `Pointer` (remains from previous), `UI` (for manipulating the app via UI), `API` (for manipulating the app via API) --- those categories are not without flaws, but we can iterate on it later.
The reason why I namespaced them is so that 1) we don't mistake them for helpers from the actual app (such as `getSelectedElements()`), and 2) it's clear whether each helper is E2E (via UI/eventing) or whether it's programmatic.
In order for the helpers to access apis such as currently rendered `canvas`, or `renderResult`, I've introduced …
> factor out test helpers

- src/components/App.tsx
- src/element/index.ts
- src/element/resizeElements.ts
- src/element/transformHandles.ts
We had a discussion in #1994 about various ideas and ended up with just fix the issue at first.
Previously, we only allowed and assumed `angle=0` for two-point lines and arrows, because there is no notation of angle for 1-d lines. This PR changes that assumption and support `angle` for two-point lines, because otherwise we can't fix #1994. close #1994 
Now, we can rotate two-point lines. close #1673 and close #1663 
Furthermore, group rotation with two-point lines are much nicer with stable bounding box.
> Support rotating two-point lines (angle can be non-zero)

- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/2094
We've unfortunately changed naming of the MOUSE_LOCATION payload prop from `socketID` → `socketId`. I've missed this would cause issues due to SW caching.
> fix collab MOUSE_LOCATION payload naming for legacy versions

- src/components/App.tsx
- src/element/binding.ts
- src/tests/binding.test.tsx
Follow up to #2096
The #2096 PR started binding on mouse move, which I have always avoided to prevent a perf regression. This PR fixes the two places that needed fixing: 1) to check for rotation in the keyboard up handler, 2) specifically to the test, the logic around when we can bind simple arrows didn't account for swapping start and end bound elements; and reverts the changes from that PR.
This also fixes the CMD disabling when taking screenshots on a mac (this perhaps deserves its own PR but I'm lazy).
> Fix arrow rebinding on rotation (take 2)

- src/components/App.tsx
If the Native File System API is supported, dropped files are now assigned a file handle, which makes them save-able immediately like a native app. Before this, you had to go through the "save" or "save as" flow to associate the currently edited file with the file that was dropped.
> Assign file handle to dropped files 

- src/components/HintViewer.scss
- src/components/LayerUI.tsx
So I've tried to fix some positioning issues with HintViewer
Also no more magic numbers stuff in css, like `calc(-50% - 16px)` (16px is half of lock icon) or `top: 54px;` (54px is height of Shapes menu)
**Before:**
**After:**
> Fix HintViewer positioning

- src/components/App.tsx
- src/element/binding.ts
- src/tests/__snapshots__/regressionTests.test.tsx.snap
Before this PR if you took a screenshot on macOS with CMD+SHIFT+4 et al, it would disable binding until the next CMD press. Now we check that CMD is pressed during pointer move, and if its state doesn't match the app state we update it.
Closes #2112 
In #2112 we discussed moving the state altogether to pointerDownState. That doesn't work (easily) for a few reasons:
1) We want to react to key press even if there is no pointer move
2) When editing multi-point elements we finish the binding from componentDidUpdate, which doesn't have access to pointerDownState (a module-level variable would be needed for this)
3) The code is currently simplified by not checking binding enabled/disabled when suggesting, instead checking it in renderScene - this would have to be reworked, complicating all the …
> Fix binding disabling when taking screenshots on macOS

- src/components/App.tsx
- src/element/resizeElements.ts
- src/element/textWysiwyg.tsx
This PR fixes the small bug with textbox bindings not automatically updating until you move one of the connected elements.
- Bug seems to occur when:
- The text input is changed
- The textbox is resized
Before:
After:
closes #2134
> Fix textbox element bindings on size changes

- src/actions/actionExport.tsx
- src/components/App.tsx
- src/element/newElement.test.ts
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/tests/helpers/api.ts
- src/tests/helpers/ui.ts
- src/tests/history.test.tsx
- src/tests/regressionTests.test.tsx
- src/tests/zindex.test.tsx
This PR fixes history when initialiazing scene (local/remote, except collab where we still keep history disabled) so that the first history entry contains the initialized state.
Previously if you loaded a scene and hit `Cmd-Z` you ended up with empty scene (similarly if you made an edit and undoed it).
I've also made loading from blob to push to history entries to make it undoable --- previously it was undoable but suffered from similar problems as described above. From backend we could in theory do that too, but since it involves re-init (user pastes it to url bar), and often a full-page refresh, I thought we might don't want to.
> Fix history initialization

- src/components/App.tsx
- src/element/dragElements.ts
- src/element/resizeElements.ts
- src/tests/__snapshots__/resize.test.tsx.snap
- src/tests/resize.test.tsx
This feature allows you to lock the direction you are moving/dragging a selection in, as inspired by @Andarius #1844 
Implemented as follows:
- Original coordinates are saved when starting dragging
- If `shift` is pressed (can also happen after a while) it will see if you are moving more into the x or y direction
- It then does not modify the opposing property
This is my first contribution to Excalidraw (actually my first OSS contrib ever 😊 ) as I wanted to support in any way. Help and feedback is welcome.
Closes #1844
> Lock drag direction using `Shift`

- public/index.html
The [Origin Trial](https://developers.chrome.com/origintrials/#/view_trial/4019462667428167681) ends on September 30 anyway; given the recent hiccups let's just make the removal of the token final, so only users with Chrome >=86 use the API.
> Remove Native File System OT token for good

- docker-compose.yml
I saw issue #2136  and decided to fix it 🙂 
changed the line 23 from
```yml
- ./package-lock.lock:/opt/node_app/package-lock.lock
```
to
```yml
- ./package-lock.json:/opt/node_app/package-lock.json
```
> Fix package-lock.json typo in volumes

- src/components/App.tsx
The middle mouse panning on Windows resulted in the canvas jumping the wrong direction.
Test plan:
* Test middle mouse behavior on windows. Before it's broken. Now it works.
* Test two finger pan on mac desktop touchpad. No regression.
> Fix middle mouse panning on windows

- src/components/App.tsx
Pinch-to-zoom is pretty unusable on large drawings using Chrome on my MacBook Pro. This introduces the debounced cache busting that is used in other parts of the codebase.
Test plan: pinched to zoom on a large drawing. Before, it was slow. Now it's fast (and blurry for up to 300ms before it rerenders).
> Fix pinch-to-zoom performance

- public/manifest.json
- src/actions/actionExport.tsx
- src/components/App.tsx
- src/data/blob.ts
- src/data/index.ts
- src/data/json.ts
- src/index.tsx
Follow-up from #1736. 
Test this with the [`#file-handling-api`](chrome://flags/#file-handling-api) flag set. Note that the app needs to be installed. If it doesn't work immediately and the app already was installed, uninstall and then re-install for the file handler to be picked up by the OS.
1. <img width="800" alt="Screen Shot 2020-09-22 at 15 06 25" src="https://user-images.githubusercontent.com/145676/93886153-5d39c980-fce5-11ea-8d04-998d3ba73b4d.png">
1. <img width="244" alt="Screen Shot 2020-09-22 at 15 06 37" src="https://user-images.githubusercontent.com/145676/93886160-5f9c2380-fce5-11ea-9b65-e2714753319a.png">
1. <img width="800" alt="Screen Shot 2020-09-22 at 15 06 47" src="https://user-images.githubusercontent.com/145676/93886162-5f9c2380-fce5-11ea-9eba-1f1cefd6e2b7.png">
> Make File Handling actually work 🎉

- src/components/App.tsx
- src/data/json.ts
- src/locales/en.json
This introduces a lightweight way of sharing libraries. Library authors can put their libraries up as static file somewhere (github gists work just great) and share clickable links for users to install them.
If this is accepted, I think we should create a wiki page where the community can add their own shape libraries.
To try it, click this link: https://excalidraw-git-fork-petehunt-add-to-library-link.excalidraw.vercel.app/?addLibrary=https://gist.githubusercontent.com/petehunt/cf25a65e1e343ecdedd68cf1cdaedced/raw/8f2d943481b898c62a42e2a20e7bde973d494e83/library.excalidrawlib
This is a v0. I think there are a few ways we could expand on it, but for now, this is an v0 that will enable library authors to easily share their work.
> One-click installable libraries

- src/element/textWysiwyg.tsx
Hi, I noticed that on dark mode, the text element was changing color back to its light mode variant while being edited (white turns back to black, etc...).
Upon looking, I saw that --appearance-filter was not being applied to the floating textarea. It was only applied to the .excalidraw class while the floating textarea is being appended to the body which put it outside of .excalidraw.
This PR adds `.excalidraw` class to the floating textarea and also adds `.Appearance_dark` to it while the dark mode is on.
> fix text color on dark mode changing to light mode color while its being edited.

- src/components/App.tsx
When joining a room, we don't want the local scene to be potentially merged into the remote one.
This PR clears the scene before joining the room (not when creating one).
> clear scene when joining a room

- src/element/collision.ts
- src/renderer/renderScene.ts
Collisions were being detected around corners and the binding was overdrawing.
> Fix collision check for rectangles and rendering of binding area

- src/components/App.tsx
- src/data/blob.ts
- src/data/index.ts
- src/data/json.ts
- src/data/localStorage.ts
- src/data/restore.ts
- src/tests/appState.test.tsx
- src/tests/helpers/api.ts
- src/tests/history.test.tsx
Somewhere along the way we've started overwriting local appState props which are not persisted to file/backend with default values on import. This PR fixes it, and makes restoring more type-safe.
> retain local appState props on restore

- src/components/ExportDialog.tsx
- src/data/blob.ts
- src/data/index.ts
- src/data/png.ts
fix https://github.com/excalidraw/excalidraw/issues/2234
- unrelated: move input below `export only selected` input
> Fix embedding scene to PNG on Safari

- src/data/index.ts
- src/locales/en.json
[#1257](https://github.com/excalidraw/excalidraw/issues/1257)
[old overkill merge request](https://github.com/excalidraw/excalidraw/pull/2231)
feat: check if error_class in server reponse is RequestTooLargeError and display a proper error message. 
P-S: In dev env the server isn't responding with error_class -> RequestTooLargeError
> feat: add a proper error message when file is too big

- src/data/firebase.ts
- src/data/restore.ts
Made importing from firebase go through `restore()`. As such, needed to make `restoreElements()` not reset `element.isDeleted` to `false`.
> restore elements on load from firebase

- src/components/App.tsx
- src/tests/collab.test.tsx
This PR ensures that deleted elements currently in memory won't be carried over & persisted on server when creating a collab room.
I'm not clearing history at the moment, but this could be considered as well.
> clear deleted elements on room create

- src/data/index.ts
- src/scene/export.ts
The SVG root element has no width/height, so they end up drawn at unspecified size
Includes "width" and "height" attributes in root SVG element, including 1x/2x/3x scaling.
Fixes #2291
> SVG export: add image size

- .eslintrc.json
- src/components/ContextMenu.tsx
- src/global.d.ts
- for the `@typescript-eslint/no-redeclare` I could have renamed the type, but in this case it's not really necessary to make the item into its own component.
- The `@typescript-eslint/no-unused-vars` is a false positive, but rather than disable the rule completely, let's just disable that one line.
- kept `import/no-anonymous-default-export` for now as it's not a high-profile rule.
> remove eslint two disabled rules & fix

- src/components/ColorPicker.tsx
- src/components/Island.tsx
- src/components/LayerUI.tsx
- src/components/Modal.tsx
- src/components/Stack.tsx
- src/css.d.ts
> Fix padding in the library loading buttons

- src/service-worker.js
Cache relevant font files for offline usage.
Fixes #2276
> BTW: No problem in Firefox
> fix: fonts not cached by Service Worker

- .dockerignore
- .github/workflows/build-docker.yml
- Dockerfile
- package-lock.json
The Docker build seems to be broken since https://github.com/excalidraw/excalidraw/commit/9de6c947ef1cf5f2b7be4349f3c6a81ca9f7043f (https://github.com/excalidraw/excalidraw/actions/runs/334032101).
I removed the "deps" step, I think it's more reliable and (potentially) faster to install dependencies in the "build" step.
I also updated the `package-lock.json` and added `.eslintrc.json` (as it seems to be required by `react-scripts`).
To avoid regression, I've added a GitHub Actions that will build the docker image on every pull request.
> Fix docker build

- src/components/Portal.tsx
We weren't properly resetting portal state on `portal.close()` which resulted in issues on reconnecting or connecting to new rooms.
Making it as a separate PR from https://github.com/excalidraw/excalidraw/pull/2313 — the sooner this lands to production the better.
> fix portal teardown

- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/2372
hacked via Proxy instead of custom handling on each site where we check `event.key`. I'm pretty sure it'll break some case I'm not aware of, but as a temp workaround (until we rewrite key handling, if we do) I guess it's ok (it affects only CapsLock events).
~~Note: this will break `instanceof event` and similar checks.~~ actually, it doesn't. Proxy FTW.
> ignore CapsLock when handling keyDown event

- public/index.html
For now we'll support two properties, during the transition.. starting from 1st of January we'll switch only to the newest one.
- https://developers.google.com/analytics/devguides/collection/gtagjs
- https://support.google.com/analytics/answer/9744165?hl=en&utm_id=ad
> Update to Analytics 4

- src/data/blob.ts
- src/data/json.ts
- src/data/localStorage.ts
- src/element/index.ts
clearElementsForExport()  and clearElementsForLocalStorage() to remove ```lastComittedPoint``` from (liniear) elements. Use it on importing / saving.
That fixes #1353
> Remove last committed point json

- public/index.html
On my iPhone, the "Copy | Loop Up" native context menu still shows up on both Safari and Chrome. Add a `-webkit-` prefix to the user-select fixes it.
> Fix "Copy | Look Up"  popup issue on mobile device

- src/disitrubte.ts
This PR adds a backup strategy to use when the total span of the selected items is larger than the extent of the selection box, as in the example below. 
In the previous implementation, certain arrangements could produce an "unstable" distribution that would change with multiple iterations. 
As it turns out, this isn't a rare issue—several other design tools have the same problem.
See [this issue](https://github.com/excalidraw/excalidraw/issues/2411) for more on what was going wrong.
In the original implementation, I used a "distribute by gaps" strategy that would attempt to position the selected items such that the space between between item was equal. In this PR's implementation, I've added a second backup strategy to use in cases where that first strategy would not work as expected. …
> Improves distribute algorithm

- src/components/Actions.tsx
- src/components/LayerUI.scss
- src/components/RoomDialog.scss
- src/components/ShortcutsDialog.tsx
- src/components/icons.tsx
- src/css/styles.scss
- updates to mirroring for a few icons, including a mistake I initially made after misreading the guidelines
- spacing fixes across the app, including major ones for zen mode.
- preserve the order of the horizontal alignment buttons in RTL mode so their positions match their actions.
Zen mode (before/after):
Collaboration (before/after):
Editing (before/after):
> RTL updates

- src/components/Actions.tsx
- src/components/LayerUI.tsx
When clicking on the library icon,  LibraryMenu's `onClickOutside` callback should not try to set `isLibraryOpen`  to `false`.
> click on library icon should toggle the LibraryMenu

- src/components/App.tsx
gesture.pointers are empty which leads NaN values of coords when `gesture.pointers` is triggered.
We should move away from [GestureEvent Api](https://developer.mozilla.org/en-US/docs/Web/API/GestureEvent) soon as its an unstable API
fixes https://github.com/excalidraw/excalidraw/issues/2347
>  use cursorx, cursory in onGestureChange

- src/components/App.tsx
We were processing both the touch move and gesture on iOS which was first firing twice as many set state, but also caused issues:
- The gesture implementation didn't support zooming on the center
- Touching down on a circle and then on the bottom chrome would freak out because initialScale was null
Touching down on the menu still isn't perfect as it shifts the shape around but doesn't completly break the zoom
> Remove native gesture "support" from iOS

- src/element/transformHandles.ts
- src/renderer/renderScene.ts
For rendering we always use mouse in order to check which handles to display but when doing the hit test, we used pointer which has a different size. So we couldn't use the middle handles for small shapes. This is now fixed.
cc @j-f1 as you added it in #790
> Fix middle handles on mobile

- src/actions/actionMenu.tsx
F is full screen but we shouldn't override cmd/ctrl-f for search. It's useful for searching in the list of key bindings
> Do not override cmd/ctrl-f for search

- src/components/DarkModeToggle.tsx
- src/components/ToolIcon.scss
> show lockicon on a second row on mobile

- src/scene/scrollbars.ts
I already fixed this but a special case for no elements was added in getCommonBounds to return 0 and reintroduce this bug. I'm not exactly sure where to put this check tbh. Fixing it here so that I'm not annoyed anymore at least.
I checked some of the callsites, some of them related to selection will never pass an empty array, some to export will break if we remove the 0, 0, 0, 0 fix.
Fixes #2064
> Fix scrollbars when no elements

- src/components/App.tsx
Fix https://github.com/excalidraw/excalidraw/issues/2482
@bx10f can you please double check this indeed fixes the issue? https://excalidraw-ltub5law3.vercel.app/
> Revert "Remove native gesture "support" from iOS (#2457)"

- src/packages/excalidraw/webpack.prod.config.js
remove excalidraw-assets from publicPath as its not needed
This will help users to copy the folder `excalidraw-assets` as it is to serve the assets 
Check [here](https://codesandbox.io/s/excalidraw-ehlz3)
> move all chunks inside excalidraw-assets folder when bundling

- src/packages/excalidraw/webpack.prod.config.js
Though combining the entry points was combining the CSS files correctly but it's messing up the exports in the JS bundle which is breaking rendering.
Tried removing the `MiniCssExtractPlugin` so CSS is combined with js but in the build, it is not working out well so will have to check more as the bundle seems to get messed up.
Will look more into these more after the initial release.
>  add separate entry point for fonts as its messing up the js bundle

- src/components/App.tsx
- src/excalidraw-app/index.tsx
- src/global.d.ts
- src/types.ts
If host app doesn't want to use `readyPromise` or uses `createRef` then the App will break so added safe check,
> fix(app.tsx): add safe check for readyPromise

- .gitignore
- src/analytics.ts
- src/charts.ts
- src/clipboard.ts
- src/components/App.tsx
- src/element/newElement.ts
- src/element/types.ts
- src/locales/en.json
- src/types.ts
------
-------
```
Month,Accounts
Jan,98
Feb,769
Mar,263
Apr,356
May,431
Jun,985
Jul,548
Aug,738
Sep,748
Oct,69
Nov,376
Dec,424
```
| Month | Accounts |
| ----- | -------- |
| Jan   | 653      |
| Feb   | 751      |
| Mar   | 941      |
| Apr   | 116      |
| May   | 828      |
| Jun   | 85       |
| Jul   | 169      |
| Aug   | 666      |
| Sep   | 127      |
| Oct   | 484      |
| Nov   | 288      |
| Dec   | 687      |
```
Day	Commits
Sun	143
Mon	167
Tue	92
Wed	114
Thu	128
Fri	155
Sat	193
```
The following issues are currently on master as well.
- Doesn't work for negative numbers
- Only works for one or two columns (maybe later we can paste multiple charts.. or a combination. Not something for this PR)
> Support CSV graphs and improve the look and feel

- src/components/ColorPicker.scss
- src/components/IconPicker.scss
> Hide shortcuts on pickers for mobile

- src/components/MobileMenu.tsx
- src/components/Stats.tsx
This was bothering me since forever and I never got around to fix it :)
> hide stats and scrollToContent-button when mobile menus open

- src/components/App.tsx
- src/components/ShortcutsDialog.tsx
- src/locales/en.json
- src/tests/regressionTests.test.tsx
Adds "Cut" to the shortcuts menu (when you right click) and the keyboard shortcuts list (when you click the keyboard icon in the corner)
Responds to: [Missing "Cut" from list of keybindings and right click menu](https://github.com/excalidraw/excalidraw/issues/2510)
**TODO**: Add "Cut" to the other translation files!!
Didn't _add_ any tests, but changed a few existing ones to expect "Cut" in the menus
> Add Cut to menus

- src/renderer/renderElement.ts
When we render an element, we draw that element onto a canvas. The size of this canvas is based on the size of the element, plus an extra 20px of padding just to be sure. This padding can sometimes be insufficient to catch certain arrowheads, causing them to appear clipped. The problem is most noticeable when zoomed in.
The underlying problem is that arrowheads are ignored when calculating the bounds of the line. This is perhaps correct for the shape's bounding box; however, we should take them into account when calculating the size of the element's canvas. 
This PR does not solve the underlying problem. Instead, this PR:
- expands the canvas padding from `20` to `28`
- makes the canvas padding width change with the canvas zoom. At 200% zoom, the shape will receive 56px padding (2 * …
> Expand canvas padding based on zoom.

- src/components/App.tsx
Right now, clicking on a library item inserts it **right under the cursor** (this works out ok, since the library menu is in the middle of the screen). 
We should insert it in the middle of the screen instead! (no matter where the library menu is)
> Insert Library items in the middle of the screen

- src/charts.ts
- src/packages/excalidraw/CHANGELOG.MD
Fixes #2585 
Even though the created line should do that automatically.
> fix: Add width/height for the lines in charts

- .github/workflows/changelog-check.yml
- src/actions/actionAlign.tsx
Revert the changelog check of excluding the branches since the changelog stopped running for all pull requests now
I will check more on this and push a proper fix
> Revert the changelog check of excluding the branches 

- .github/workflows/changelog-check.yml
- src/actions/actionAlign.tsx
* Since `pull_request` was removed in https://github.com/excalidraw/excalidraw/commit/bfeb3c7dfd2486f6734de8a6f90f7208a07f731e the changelog checks stopped running for all pull requests which are made against forked branches example https://github.com/excalidraw/excalidraw/pull/2596 so I have added that again and it runs for forked pr's now https://github.com/excalidraw/excalidraw/pull/2603
* I digged into the workflows and looks like there is no way to stop running the actions for some particular head branches when pull request is made so added a condition for that to skip changelog check.
* tested its skipping the check for matched branches( notice the name of this branch)
* ~~I am not sure why the checks are running twice https://github.com/excalidraw/excalidraw/pull/2604/checks coz in …
>  Fix changelog workflow

- .github/workflows/locales-coverage.yml
Fixes #2587.
Adds a bunch of GH actions to
- find the PR of the commit (only on specific branch)
- construct MD body of the comment
- find if there is a comment already
- create or update comment
Example: https://github.com/excalidraw/excalidraw/pull/2592#issuecomment-748466838
> feat(translations): Commenting on translations PRs

- src/analytics.ts
- src/charts.ts
- src/packages/excalidraw/CHANGELOG.MD
- src/tests/__snapshots__/charts.test.tsx.snap
- src/tests/charts.test.tsx
I tried to paste weekly active users from excel but isNumeric didn't recognize "10,000" as number and wouldn't recognize the data as a chart. This PR fixes it.
> improvement: Support numbers with commas in them

- src/components/App.tsx
- src/packages/excalidraw/CHANGELOG.md
If you start the gesture on the chrome, gesture is not defined and the zoom will be set to NaN and you will have to refresh.
Typescript was actually right and we shouldn't have overridden the bang ;)
Repro:
- On iPhone touch down on a shape, touch down on the chrome, start moving around
- See that the selection is off, but the zoom is not being modified like crazy.
- 
https://user-images.githubusercontent.com/197597/102722206-6c182400-42b4-11eb-9865-6ae1cd0af9be.MP4
> fix: Don't break zoom when zooming in on UI

- src/components/App.tsx
My last attempt removed the gesture handler altogether but broke macbooks. This one keeps it working on macbook but makes sure it zooms properly on iPhone and iPad.
Test plan:
For macbook:
> fix: Center zoom on iPhone and iPad

- src/components/ContextMenu.scss
change the css for context-menu to look the shortcut text a little bit better. It was not perfect, because the font-size of the shortcut is reduced.
Fixes #2641
> fix: align items in context menu

- src/components/HintViewer.tsx
- src/locales/en.json
- src/packages/excalidraw/CHANGELOG.md
- src/tests/regressionTests.test.tsx
- src/utils.ts
Turns out we don't to split the label, because 2-point lines need a different label altogether :).
> improvement: change hint for 2-point lines on resize

- src/components/ColorPicker.scss
- src/components/ContextMenu.scss
- src/components/Dialog.scss
- src/components/ExportDialog.scss
- src/components/HintViewer.scss
- src/components/IconPicker.scss
- src/components/Modal.scss
- src/components/ToolIcon.scss
- src/css/_variables.scss
- src/css/styles.scss
- src/is-mobile.tsx
> refactor: Media queries

- src/components/App.tsx
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- fixes a regression introduced during rewrite for npm package: by moving to promise-based initialization, we've been mistakenly been early-resolving in late-initialization scenarios which ended up not initializing the scene properly
- also fixed an issue where late initialization wasn't prompting due to `onChange` callback being called early and overriding localStorage with empty data
> fix: scene not initialized properly when tab not focused

- src/components/LayerUI.scss
- src/components/LayerUI.tsx
I did some stylings changes in order to fix the "Brose Libraries" link button when the scrollbar appears.
The 17px padding is because of windows scroll width, so when the user see the scroll, its not on top of the link button.
You can appreciate in the gif below that when scrollbar expands in Mac OS, then the scrollbar is not on top of the link button.
> feat: browse libraries styles fixed

- src/components/Dialog.scss
- src/components/Dialog.tsx
- src/components/Island.scss
- src/components/Modal.scss
- src/components/Modal.tsx
- src/css/theme.scss
> improvement: Make dialogs look more like dialogs

- src/components/IconPicker.scss
> improvement: Make arrowheads keybinds color accessible on dark mode

- src/actions/shortcuts.ts
- src/components/App.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/tests/regressionTests.test.tsx
Pros of this change:
I believe that more people will use zenmode if it's easier to find.  In addition, the keyboard binding is pretty awkward and can conflict with other global system bindings in certain environments.
Cons of this change:
Makes the action menu longer, however since we only show these "global options" when the user right clicks on the background it seems that the additional option is not too much.
Resolves: #1581
> improvement: adding zen mode to context menu

- .github/workflows/cancel.yml
Runs on:
1. build-docker.yml
1. build-packages.yml 
1. lint.yml
1. locales-coverage.yml
1. publish-docker.yml
1. sentry-production.yml
1. test.yml
To check workflow ids, go to https://api.github.com/repos/excalidraw/excalidraw/actions/workflows
Resolves #2437
> chore(actions): Use cancel workflow action

- src/excalidraw-app/index.tsx
- src/utils.ts
- Tried to tie it into the SW thing, but it was too complex, so ended up with a simple timeout.
- Also made it so we don't log same version multiple times on repeated visits from the same device.
> fix: delay version logging & prevent duplicates

- src/charts.ts
- src/components/PasteChartDialog.tsx
It was always tracking twice for each render in the paste chart dialog.
> fix: Track the chart type correctly

- src/components/App.tsx
- src/packages/excalidraw/CHANGELOG.md
fix #2778
Quick fix I had stashed for ages — wanted to fix more of these errors (tracked in #2738), but didn't have time.
> fix: don't render due to zoom after unmount

- src/components/ContextMenu.scss
- src/components/ContextMenu.tsx
- src/components/ShortcutsDialog.scss
- src/components/ShortcutsDialog.tsx
1. kbd tag is used to keyboard shortcuts
2. converting span to kbd tag to be more semtantic
NA
1. checkout the branch
2. view keyboard shortcut modal it should use kbd tag instead of span nothing else should have changed
* With the way keybard shortcut is now rendered it uses single tag for rendering a combination. For example **ctrl + c** gets rendered inside a single tag it would be better if **ctrl** and **c** gets rendered as a separate tag
* This is more of a preference than an actual accessibility concerns
There were no existing snapshot covering this I was not sure if I should add one
> refactor: Converting span to kbd tag

- src/components/Dialog.scss
- src/packages/excalidraw/CHANGELOG.md
1. Enable text selection in keyboard modal
2. Convert cursor inside modal from crosshair to text
> fix: allow text-selecting in dialogs & reset cursor

- package.json
On Vercel `NOW_GITHUB_COMMIT_SHA` are legacy system environment variables and we can update them to the new `VERCEL_GITHUB_COMMIT_SHA`.
To make it work, the "Automatically expose System Environment Variables" option should also be enabled in the Project, like described here: https://vercel.com/docs/environment-variables#system-environment-variables.
> fix: Use `VERCEL_GIT_COMMIT_SHA` env variable

- src/packages/excalidraw/entry.js
- src/packages/excalidraw/webpack.prod.config.js
no more importing CSS files seperately now as its bundled with js
pushed [here](https://codesandbox.io/s/excalidraw-v02-no-css-xggy7)
**Pros**
Host will no more have to import the css files and just importing the package would work
**Cons**
The bundle size would increase (~10 KiB)  since now the CSS is injected into DOM via js.
> build(webpack): bundle css files with js

- src/actions/actionHistory.tsx
- src/components/HelpDialog.tsx
- src/keys.ts
- src/packages/excalidraw/CHANGELOG.md
On Windows, we use `Ctrl-Y` instead of `Ctrl-Shift-Z` to redo.
Should we allow this only on Windows machines? Mac and Linux seems to only use `Cmd/Ctrl-Shift-Z`.
> feat: add ctrl-y to redo

- src/components/App.tsx
- src/components/Dialog.tsx
- src/createInverseContext.tsx
- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/collab/Portal.tsx
- src/excalidraw-app/index.tsx
- src/hooks/useCallbackRefState.ts
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/tests/dragCreate.test.tsx
- src/tests/move.test.tsx
- src/tests/multiPointCreate.test.tsx
- src/tests/selection.test.tsx
- src/tests/test-utils.ts
- src/types.ts
Promised refactor of Collab to make the code more predictable and easier to reason about, and removing the "TDZs" (see https://github.com/excalidraw/excalidraw/pull/2313#issuecomment-734378460).
Review by commits.
- Made `<CollabWrapper/>` to not wrap the `<ExcalidrawWrapper/>` component, and instead render it conditionally as a sibling of `<Excalidraw/>` (we should probably rename the component then). This is so that the `ExcalidrawAPI` TDZ is removed. Updates are now handled by an inverse-Provider (it's the same as a regular `Context`, but inverts how the value is provided and consumed), which wraps the `<ExcalidrawWrapper/>` in `CollabWrapper`'s stead.
- Replaced `excalidrawRef` MutableRefObject with a callbackRef, which simplifies consumption and allows reading it directly without …
> refactor: rewrite collabWrapper to remove TDZs and simplify

- src/actions/actionAddToLibrary.ts
- src/actions/actionClipboard.tsx
- src/actions/actionDeleteSelected.tsx
- src/actions/actionGroup.tsx
- src/actions/actionStyles.ts
- src/actions/actionToggleGridMode.tsx
- src/actions/actionToggleStats.tsx
- src/actions/actionToggleZenMode.tsx
- src/actions/index.ts
- src/actions/manager.tsx
- src/actions/shortcuts.ts
- src/actions/types.ts
- src/components/App.tsx
- src/components/ContextMenu.scss
- src/components/ContextMenu.tsx
- src/is-mobile.tsx
- src/keys.ts
- src/tests/regressionTests.test.tsx
Fixes #2506 - Check the [**preview**](https://excalidraw-git-fork-kartik1397-addseparatorsoncontextmenu.excalidraw.vercel.app/).
This is my first try toward implementing separators in context menu.
One thing which I can improve in this implementation is to use constant varible instead of hard coded numerical value for order and group.
If there is a more clever way to implement this, please suggest me.
> feat: Add separators on context menu

- src/components/Avatar.scss
- src/components/CollabButton.scss
- src/components/ColorPicker.scss
- src/components/ContextMenu.scss
- src/components/Dialog.scss
- src/components/ExportDialog.scss
- src/components/HelpDialog.scss
- src/components/HintViewer.scss
- src/components/IconPicker.scss
- src/components/Modal.scss
- src/components/PasteChartDialog.scss
- src/components/Stats.scss
- src/components/TextInput.scss
- src/components/Toast.scss
- src/components/ToolIcon.scss
- src/components/Tooltip.scss
- src/css/styles.scss
- src/css/variables.module.scss
- src/excalidraw-app/collab/RoomDialog.scss
- src/is-mobile.tsx
Import SCSS variables into JS so that we don't duplicate values which leads to regressions.
Had to suffix the `variables.scss` file with `.module` due to https://github.com/facebook/create-react-app/issues/10047#issuecomment-724227353
> refactor: reuse scss variables in js for SSOT

- src/components/App.tsx
- src/is-mobile.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/tests/regressionTests.test.tsx
- src/utils.ts
> feat: Remove copy & paste from context menu on desktop

- src/actions/actionToggleGridMode.tsx
- src/actions/actionToggleStats.tsx
- src/actions/actionToggleZenMode.tsx
- src/actions/types.ts
- src/components/App.tsx
- src/components/ContextMenu.tsx
> fix: apply initialData appState for zenmode and grid stats and refactor check param for actions

- src/actions/actionClipboard.tsx
- src/components/App.tsx
This deduping has a tiny behavior change in that it shows the toast message for copyAsPng even if you do it via contextmenu, but I think it's fine.
If not desired, we can fix it later. If desired, we can also add the toast to copyAsSvg (contextmenu).
> refactor: remove duplicate key handling

- src/actions/actionCanvas.tsx
- src/components/App.tsx
- src/constants.ts
- src/scene/zoom.ts
fix https://github.com/excalidraw/excalidraw/issues/2081
- max zoom is now 1000%
- wheel-scrolling step is get progressively larger the more you're zoomed in. Haven't made it adapt to wheel-scroll speed because that'd be more involved, plus I'd have to have access to continuous-scroll wheels to be confident I got it right.
- haven't changed touch zooming nor UI zooming speed. Touch zooming should be fine as is.
Lemme know if the current algo feels ok.
> feat: increase max zoom

- src/appState.ts
- src/components/App.tsx
- src/gesture.ts
- src/scene/export.ts
- src/scene/index.ts
- src/scene/scroll.ts
- src/scene/scrollbars.ts
- src/scene/types.ts
- src/tests/__snapshots__/regressionTests.test.tsx.snap
- src/types.ts
The experiment of flooring scroll numbers didn't pan out (pun intended). The recent support for 1000% zoom revealed how problematic it is (try zooming to max and panning canvas via mouse-wheel). It also caused this https://github.com/excalidraw/excalidraw/issues/782.
It was implemented to combat canvas blurriness but it didn't help much on that front.
fixes https://github.com/excalidraw/excalidraw/issues/782
> fix: stop flooring scroll positions

- src/components/LayerUI.tsx
- src/components/Tooltip.scss
- src/css/styles.scss
- src/packages/excalidraw/CHANGELOG.md
Fixes (among other things) this issue:
- when you drag element in collab session and you drag the element underneath a UI, the remote pointer gets stuck because the `handleCanvasPointerMove` callback is not called.
This fix is somewhat of a hack, but we're already hacking it in one place (the privacy shield icon — this hack can now be removed).
It could be fixed in other ways, such as not handling `canvas` `pointermove` and instead use the `document` event handler, but it'd introduce other issues. And ultimately, we still want to disable menu pointer-events when drawing on canvas (so that cursor doesn't change, the drag isn't stuck on `input` elements etc.).
AFAIK the only problematic thing about this hack is if the `pointerup` isn't called (which we track in separate issue …
> fix: disable UI pointer-events on canvas drag

- src/actions/actionToggleGridMode.tsx
- src/actions/actionToggleZenMode.tsx
Since it isn't feat so kept fix however fix is also not suitable here. Any better suggestion?
> fix: track zenmode & grid mode usage

- .github/workflows/cancel.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
It seems that the actions are not running only on push when from other repositories.. #2916 
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#example-using-a-single-event
> chore: Run actions on pull requests as well

- src/components/App.tsx
Cf https://github.com/excalidraw/excalidraw/issues/2915#issuecomment-772807009
Today when setting offsetLeft or offsetRight when using the package library, scrollbars will display, but can't be dragged. This is an attempt to fix it.
> fix: make scrollbars draggable when offsets are set

- src/components/App.tsx
- src/components/Stats.tsx
- src/locales/en.json
- src/utils.ts
Not sure if needed.. but sometime it's good to know when filing an issue for example.. thoughts?
> feat: Show version in the stats dialog

- src/components/App.tsx
- src/element/textWysiwyg.tsx
fix https://github.com/excalidraw/excalidraw/issues/2913
> fix: incorrect z-index of text editor

- src/packages/utils.ts
- src/scene/export.ts
I didn't notice that we've forgot to integrate `scale` when supplying custom `getDimensions` during canvas export. This PR is technically a breaking change of the API, but since we haven't yet documented `getDimensions()`, we don't need a changelog for this.
> feat: support supplying custom scale when exporting canvas

- src/components/LayerUI.scss
- src/components/MobileMenu.tsx
- src/css/styles.scss
- src/element/textWysiwyg.tsx
fix https://github.com/excalidraw/excalidraw/issues/2919
Took me a while to figure that in darkMode, the canvas creates a stacking context due having `filter` property, which made its z-index higher than the textarea.
> fix: text editor not visible in dark mode

- src/components/MobileMenu.tsx
- src/css/styles.scss
Fixes toolbar on mobile making the canvas around it unusable due to being unnecessarily wide.
> fix: toolbar unnecessarily eats too much width

- src/excalidraw-app/index.tsx
fix https://github.com/excalidraw/excalidraw/issues/2935
Turns out the `shouldForceLoadScene()` we removed was needed after all. I just inlined the empty-scene check. This fix aligns it with previous behavior.
Long-term we can also check for identical-scene, but that will require a little more work.
> fix: don't prompt on empty scenes

- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
before/after
also, for non-mobile, we're now rendering only if non-empty as well (perf-optim).
> fix: hide collaborator list on mobile if empty

- src/css/styles.scss
fixing a regression caused in recent PR:
> fix: mobile toolbar tooltip regression

- src/renderer/renderScene.ts
- src/utils.ts
As discussed on chat, at least some Windows 7 users can't display emoji. This PR deals with this fact by providing a textual fallback for 💤 ("idle") and ⚫️ ("away"). The default state, 🟢, is ignored on purpose.
> chore: [Idle detection] Deal with users on systems that don't handle emoji

- src/actions/actionExport.tsx
- src/locales/en.json
shows toast when saving to an existing file via `save` button or via `ctrl+s`.
> feat: show toast when saving to existing file

- src/i18n.ts
Currently, when changing the app language, the `lang` attribute still in `en`.
> fix: Update the `lang` attribute with the current lang.

- src/components/LayerUI.tsx
- src/locales/en.json
> feat: Add the ability to clear library

- README.md
Adding link to the main readme to increase the visibility of the package since it resides in the same repo
> docs(readme): link to @excalidraw/excalidraw npm package to give more visibility

- package-lock.json
- package.json
- src/components/App.tsx
- src/element/textWysiwyg.tsx
Replaced `resize` with `ResizeObserver`. This will ensure that wysiwyg position is refreshed when canvas is resized via other means, such as updating dimensions or offsets from the host app.
fix https://github.com/excalidraw/excalidraw/issues/2921 (kinda)
> fix: refresh wysiwyg position on canvas resize

- src/components/App.tsx
Given it's followed by qualified import - unqualified import looks redundant, unless I'm missing some tricky edge case.
> refactor: Removed redundant import from `App.tsx`

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/Modal.scss
- src/components/Modal.tsx
- src/components/Popover.scss
- src/components/Stats.scss
- src/components/Toast.scss
- src/constants.ts
- src/css/styles.scss
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/package-lock.json
- src/packages/excalidraw/package.json
fixes #3011 &  #2737 
For host check it out [here](https://k1xx5.csb.app)
TODOS
> fix: Support Excalidraw inside scrollable container

- src/actions/actionFinalize.tsx
- src/components/App.tsx
- src/constants.ts
- src/element/linearElementEditor.ts
- src/math.ts
The line confirmation threshold that we also use for auto-closing of start/end points should account for zoom. If zoomed in a lot, the threshold should be smaller and vice versa.
I haven't applied this to shape filling, which still uses the threshold verbatim. It feels ok. The idea is so that you can create points close together without the line being confirmed, so that you can continue creating more points.
The formulas are a bit crazy. I came up with it by first coming up with a few reasonable values at given zoom values, and then fitting a curve through those points using a [calculator](https://mycurvefit.com/). Well, it was a bit harder than that because I also wanted to guarantee that the line threshold constant stays constant at 100% zoom.
> feat: adjust line-confirm-threshold based on zoom

- src/components/App.tsx
- src/renderer/renderScene.ts
There seems to be another issue. On Firefox, The scrollbars render by default (mobile & desktop) even on an empty canvas. Is this known?
Resolves:
#2923
> fix: Hide scrollbars on mobile

- public/index.html
- src/global.d.ts
- src/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/index.tsx
- src/packages/excalidraw/package.json
- src/packages/excalidraw/publicPath.js
- src/packages/excalidraw/webpack.prod.config.js
CSB is also working now, no more chunk errors 🎉 [try here](https://i86kx.csb.app/)
No more __webpack_public_path__ needed explicitly in the host and it will default to unpkg CDN if window.EXCALIDRAW_ASSET_PATH is not defined.
for #3061, #3013, #3060
I had tried this approach earlier but unfortunately, I was assigning __webpack_public_path__ at the wrong place in `entry.js` :/. 
This will make hosting the excalidraw assets for the host much easier as its now scoped down to just Excalidraw.
TODOS
> feat: expose variable window.EXCALIDRAW_ASSET_PATH to allow host define the path for excalidraw assets

- .github/dependabot.yml
- .github/workflows/build-docker.yml
- .github/workflows/build-packages.yml
- .github/workflows/semantic-pr-title.yml
- .github/workflows/sentry-production.yml
The `main` was confusing in the required checks
> chore: Consistent job names in GH actions

- src/actions/actionFinalize.tsx
- src/components/Actions.tsx
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
- src/components/TopErrorBoundary.tsx
- src/element/resizeElements.ts
- src/utils.ts
fix https://github.com/excalidraw/excalidraw/issues/3160
- moved cursor from `document` to `canvas`. This way it won't ever affect DOM outside the component, but it'll also fix cases where we forget to update the cursor when mousing over the UI, so it's a win-win.
- moved the cursor updating to helper — not sure if the extra function will meaningfully impact perf in tight loops (such as `pointermove` events), but it doesn't look like it
> fix: cursor being leaked outside of canvas

- src/element/binding.ts
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/package.json
fixes #3164 
fixes https://github.com/excalidraw/excalidraw/issues/3153
[spreadArrays](https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#more-accurate-array-spread) introduced in 3.6 only supports arrays by default. We can enable the flag `downlevelIteration` to make it work with other types but it increases bundle size by `~20kb`which is unnecessary so using `Array.from` instead.
Try it out [here](https://y0ld3.csb.app/)
TODOS
> fix: Use Array.from when spreading over set so that typescript transpiles correctly in the umd build

- package.json
- yarn.lock
fix https://github.com/excalidraw/excalidraw/issues/3155 until https://github.com/GoogleChromeLabs/browser-fs-access/pull/37 is merged and released
> fix: temporarily downgrade browser-fs-access to fix legacy FS API

- src/components/App.tsx
- src/constants.ts
- src/packages/excalidraw/CHANGELOG.md
fixes #3175 
This can go into the patch version release along with #3174 
try it out [here](https://3scmb.csb.app/)
> fix: Reduce the scroll debounce timeout to 100ms and update only if offset changes

- src/components/icons.tsx
- src/excalidraw-app/collab/RoomDialog.tsx
- src/locales/en.json
As discussed in the issue, share button will replace the copy button if the browser supports it. Since Safari web also supports this, the behavior is same there. Is that fine?
Closes
#3213
> feat: Implement the Web Share API for the collaboration dialog

- src/element/textWysiwyg.tsx
> fix: Apply correct translation when text editor overflows when zoom not 100%

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/index.tsx
- src/types.ts
for https://github.com/excalidraw/excalidraw-libraries/pull/74 (this PR must be merged first due to the URI decoding)
- use `referrer` when loading libs. This isn't necessary as our origin is the default, but it's useful in development
- decode URI component
---
/cc @zsviczian
> feat: support `libraryReturnUrl` when installing libraries

- public/index.html
- src/components/App.tsx
- src/css/styles.scss
- src/element/textWysiwyg.tsx
Attempt to fix https://github.com/excalidraw/excalidraw/issues/3151
~~Also, this fixes a case where clicking on canvas doesn't deselect selection outside Excalidraw component.~~
> fix: stop preventing canvas pointerdown/tapend events

- src/components/App.tsx
- src/data/types.ts
- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/tests/scroll.test.tsx
> refactor: Rename prop scrollToCenter and setScrollToCenter to scrollToContent and setScrollToContent respectively

- src/actions/actionClipboard.tsx
- src/components/App.tsx
Take 2. See https://github.com/excalidraw/excalidraw/pull/3269 for details.
We'll perf-optimize this after we decide whether this is the right way to go or not.
> fix: allow copying text outside the component

- src/components/ExportDialog.scss
> fix: overflow in textinput in export dialog

- src/components/LayerUI.tsx
> fix: Don't show export and delete when library is empty

- public/index.html
- src/components/LayerUI.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
set window.name in excalidraw app so library installation always opens on same tab & also support target for excalidraw libraries
upstream PR: https://github.com/excalidraw/excalidraw-libraries/pull/79
> feat: set window.name in excalidraw app & also support target for excalidraw libraries

- src/excalidraw-app/collab/CollabWrapper.tsx
If you load a shared scene with at least another person on the scene, you can start seeing the content via the firebase response. If you scroll and you receive the response from the websocket INIT, then it scrolls you back to the center which is jarring.
This PR removes the scroll to content for that use case.
> fix: Don't scroll to content on INIT websocket message

- src/excalidraw-app/data/index.ts
This change introduces random IV (Initialization Vector) for link-sharing feature, as described in #2829, in order to improve end-to-end encryption. Generated IV is being concatenated with encrypted content and sent to the backend on export. Since IV has a fixed length, when importing from the backend we can simply retrieve it based on its length. 
The assumption here is that after introducing change, there won't be a need for supporting previously-generated links (without IV being exported). If such backward compatibility is required, the approach would have to be adjusted a bit.
Since this is my first PR to the Excalidraw, please try to forgive me if something would be missing or wrong.
> fix: use random IV for link-sharing encryption (#2829)

- src/components/LayerUI.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
Usually the host apps will not want to be redirect to the root when installing libs.
> feat: use `origin + pathname` as `libraryReturnUrl` default

- package.json
- yarn.lock
This should make Brave users, Firefox users, and Safari users universally happy. Background: https://github.com/GoogleChromeLabs/browser-fs-access/issues/41.
> chore: Update to browser-fs-access v0.16.0

- src/utils.ts
In my previous "fix" (https://github.com/excalidraw/excalidraw/pull/3281) I actually broke it even more (I've unthinkingly adapted a thing I had in a fork).
That said, the previous solution (checking for `lastArgs`) wasn't entirely correct because we weren't unsetting  them when should have. This PR should account for that. This fixes a case where your function would be invoked on `flush` even if it was previously cancelled, and potentially with stale args.
We may wanna add tests, or better yet, use the `debounce` from lodash :). (though, it's [quite big](https://bundlephobia.com/result?p=lodash.debounce@4.0.8))
> fix: `debounce.flush` invokes func even if never queued before

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/constants.ts
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- prefer `#` when importing libraries (upstream PR https://github.com/excalidraw/excalidraw-libraries/pull/82) — this will improve UX in that it won't reload the page + we can retain whatever hash was set previously (e.g. collab room id)
- export `importLibrary` from excalidrawAPI
---
Due to compat reasons we need to pass `useHash` flag when opening the libraries page, and also keep a migration path for query `?addLibrary`. We can drop these after some time has passed.
> feat: prefer hash when importing libraries & expose `importLibrary`

- src/components/App.tsx
- src/components/LayerUI.tsx
- src/data/library.ts
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
fix https://github.com/excalidraw/excalidraw/issues/3327
This is relevant only when the tab is reused (https://github.com/excalidraw/excalidraw/pull/3320).
Upstream PR: https://github.com/excalidraw/excalidraw-libraries/pull/84
> feat: don't unnecessarily prompt when installing libraries

- src/components/Stats.tsx
Stats dialog positions for linear elements weren't correct. Fixed by using commonBounds, and simplified in the process.
> fix: positions stats for linear elements

- src/components/App.tsx
- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/collab/Portal.tsx
- src/excalidraw-app/collab/types.ts
- src/excalidraw-app/data/index.ts
- src/renderer/renderScene.ts
- src/tests/collab.test.tsx
- src/tests/test-utils.ts
- src/types.ts
This is needed so that core and excalidraw-app is decoupled and also when we export types, the collab types are not exported in #3337
> fix: Don't share collab types with core

- src/actions/actionCanvas.tsx
- src/actions/actionExport.tsx
- src/components/Actions.tsx
- src/components/ButtonIconCycle.tsx
- src/components/CollabButton.tsx
- src/components/Dialog.tsx
- src/components/ExportDialog.tsx
- src/components/LayerUI.tsx
- src/components/LibraryUnit.tsx
- src/components/Stats.tsx
- src/excalidraw-app/index.tsx
- src/is-mobile.tsx
- src/renderer/renderElement.ts
- src/tests/resize.test.tsx
- Arrow functions
- No default export in `is-mobile`
> refactor: Use arrow function where possible

- src/components/App.tsx
- src/components/Stats.tsx
- src/excalidraw-app/CustomStats.tsx
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
- src/types.ts
Add renderCustomStats prop to render extra stats & move storage & version to renderCustomStats
Expose Api to update toast message so single instance of toast is used
fixes https://github.com/excalidraw/excalidraw/issues/3354
> feat: Add renderCustomStats prop and expose setToastMessage API to update toast

- .gitignore
- src/global.d.ts
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/package.json
- src/packages/excalidraw/yarn.lock
- tsconfig-types.json
- tsconfig.json
fixes https://github.com/excalidraw/excalidraw/issues/2514
pushed [here](https://codesandbox.io/s/excalidraw-types-9h2dm)
> feat: export types for package @excalidraw/excalidraw 🎉 

- src/excalidraw-app/data/localStorage.ts
Removing  `JSON.stringify` since the data is already stringified and will also give wrong value
> fix: remove JSON.stringify when calculating storage as its not needed

- package.json
- yarn.lock
fix https://github.com/excalidraw/excalidraw/issues/3370 — thanks @tomayac!
> chore: bump browser-fs-access to 0.16.2

- src/clipboard.ts
- src/components/App.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
- src/types.ts
- src/utils.ts
Add `onPasteFromClipboard` props to `@excalidraw/excalidraw`.
A simple example to add a custom element when the text `"special"` is pasted in the scene.
```tsx
import React, { useCallback, useRef } from "react";
import Excalidraw from "@excalidraw/excalidraw";
import {
ExcalidrawAPIRefValue,
ExcalidrawProps,
} from "@excalidraw/excalidraw/types/types";
export const App = () => {
const ref = useRef<ExcalidrawAPIRefValue>(null);
const onPasteFromClipboard = useCallback<Required<ExcalidrawProps>["onPasteFromClipboard"]>(
(data) => {
if (ref.current?.ready && data.text === "special") {
/* do something special */
const prev = ref.current.getSceneElementsIncludingDeleted();
ref.current.updateScene({elements: [...prev, /* my special element */]})
return true; // Prevent default paste action
} …
```
> feat: Add onPaste prop to customise clipboard paste event

- src/components/App.tsx
- src/constants.ts
- src/data/blob.ts
- src/data/json.ts
- src/data/restore.ts
- src/data/types.ts
- src/excalidraw-app/data/index.ts
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- tsconfig.json
There was a bit of mess around imported `DataState` and created `DataState` + we weren't type checking the latter.
We should also rename the `DataState` to something more descriptive, like `SceneState`, but we'd also need to rename the `SceneState` type we use in `renderScene()` so I left it for now.
> refactor: improve types around dataState and libraryData

- src/actions/actionFinalize.tsx
- src/actions/actionMenu.tsx
- src/actions/manager.tsx
- src/actions/types.ts
- src/components/App.tsx
- src/components/ColorPicker.tsx
- src/components/Dialog.tsx
- src/components/ErrorDialog.tsx
- src/components/IconPicker.tsx
- src/components/LayerUI.tsx
- src/components/Modal.scss
- src/components/Modal.tsx
- src/components/ProjectName.tsx
- src/css/styles.scss
- src/data/library.ts
- src/element/textWysiwyg.tsx
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
- src/tests/__snapshots__/dragCreate.test.tsx.snap
- src/tests/dragCreate.test.tsx
- src/tests/helpers/ui.ts
- src/tests/multiPointCreate.test.tsx
- src/tests/regressionTests.test.tsx
- src/tests/selection.test.tsx
- src/types.ts
- src/utils.ts
fixes https://github.com/excalidraw/excalidraw/issues/3405
Also fixes handling keyboard events for individual excalidraw container when [multiple excalidraw](https://github.com/excalidraw/excalidraw/issues/3043) rendered
> feat: Bind keyboard events to the current  excalidraw container and add handleKeyboardGlobally prop to allow host to bind to document

- src/components/App.tsx
- src/components/Dialog.tsx
- src/components/Modal.tsx
- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/collab/RoomDialog.tsx
- src/packages/excalidraw/CHANGELOG.md
Make sure theme is only applied to the active Excalidraw component when  [multiple excalidraw](https://github.com/excalidraw/excalidraw/issues/3043)  rendered
Exposed a hook that gives access to the current instance, this will be useful when focusing the current instance as well(ex after dialog close, we can expose focus function as well for the same)
Since collab dialog is not in the hierarchy of App.tsx hence had to add a new prop theme so it can be used to add a `theme` to custom dialogs as well.
Try [here](https://k1xx5.csb.app/)
> fix: Apply theme to only to active excalidraw component

- src/actions/actionAddToLibrary.ts
- src/actions/manager.tsx
- src/actions/types.ts
- src/components/App.tsx
- src/components/LayerUI.tsx
- src/data/json.ts
- src/data/library.ts
- src/data/types.ts
- src/excalidraw-app/index.tsx
- src/locales/en.json
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
- src/packages/excalidraw/package.json
- src/tests/library.test.tsx
- src/types.ts
An attempt to attach the library to each excalidraw instance so each instance has its own library when [multiple excalidraw](https://github.com/excalidraw/excalidraw/issues/3043) rendered.
fixes https://github.com/excalidraw/excalidraw/issues/3400
Try [here](https://k1xx5.csb.app/#token=Kc18ngwqu2Pf7ZuRuLG0o)
1. `onLibraryChange` which will get triggered on every library change.
2. `initialData.libraryItems` with which host can load excalidraw with existing library items.
3. Add unique id to excalidraw component which will be available to host via ref.
> feat: Make library local to given excalidraw instance and allow consumer to control it

- src/element/index.ts
- src/excalidraw-app/collab/CollabWrapper.tsx
- src/excalidraw-app/collab/Portal.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
Moved `getSyncableElements` util to CollabWrapper. Not sure why we were exporting it from the package since it's an implementation detail tightly coupled to excalidraw.com collab implementation.
> refactor: move getSyncableElements to CollabWrapper & expose isInvisiblySmallElement helper

- src/components/App.tsx
- src/element/textWysiwyg.tsx
- src/packages/excalidraw/CHANGELOG.md
fix text editing was not working when you have [multiple excalidraw](https://github.com/excalidraw/excalidraw/issues/3043) components on the same page
try [here](https://k1xx5.csb.app/)
> fix: use active Excalidraw component when editing text

- public/index.html
- src/css/app.scss
attempt to fix https://github.com/excalidraw/excalidraw/issues/3468
> fix: prevent selecting `.visually-hidden` elements

- src/components/Island.scss
- src/components/Modal.scss
- src/css/theme.scss
fix https://github.com/excalidraw/excalidraw/issues/3505
Kept transparency (and also added it to dark mode `.Island` bg which previously wasn't there).
before:
after:
> feat: remove `backdrop-filter` to improve perf

- public/index.html
On mobile and tablet devices, user experience suffers as the footer
controls are below the viewport height, becoming unreachable due to
scrolling being blocked by pinch-to-zoom.
Additionally, using the contextual menus on long touch causes the menu
items text to be selected.
This commit fixes both issues by improving the page css,
disabling user selection on touch as well as finxing the
html and body height to 100%.
> fix: improve mobile user experience

- src/renderer/renderElement.ts
- src/renderer/renderScene.ts
Instead of muting the errors I'm catching the render calls, because we may not want to mute errors for render calls across the board as that would not be nice for upstream consumers using those util methods directly.
> fix: handle render errors

- src/data/restore.ts
- src/element/collision.ts
- src/element/types.ts
- src/renderer/renderElement.ts
Removing `draw` type (replaced by `freedraw`) from codebase. It should be dead code and migrations should take care of it.
Also introduces migration for `appState.elementType`.
> fix: remove `draw` element from codebase

- src/renderer/renderElement.ts
This PR fixes the bug reported here: https://github.com/excalidraw/excalidraw/issues/3561
The SVG export for freedraw elements was setting the path's `fill` to `strokeStyle` rather than `strokeColor`.
(Note that with freedraw lines, because the line is actually a polygon shape, we use the element's strokeColor as its fill. This fact is unrelated to the above bug but is worth mentioning somewhere.)
> fix: Exporting freedraw with color to svg 

- src/actions/actionClipboard.tsx
- src/clipboard.ts
- src/components/LayerUI.tsx
- src/data/index.ts
This is the first tiny-thin-slice refactor that I've extracted from #3516. I thought I'd start with something tiny to get the merge-train going.
There will be a couple more refactor PRs after this, to clean up `src/data/index.ts` and `src/scene/export.ts. After that is done, I will make a (hopefully tiny) `feat:` PR which uses the refactored export functions for re-saving to png/svg.
The general plan is to clean up and unify the arguments to export helper functions, and make all of the export functions return `Blob`. This PR takes a couple of baby-steps in that direction.
> refactor: reduce passing-around of canvas in export code

- src/components/LayerUI.scss
- src/components/LayerUI.tsx
- src/components/MobileMenu.tsx
- src/css/styles.scss
- src/excalidraw-app/index.scss
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/types.ts
An attempt to fix https://github.com/excalidraw/excalidraw/issues/2899
When restoring zenmode the encrypted icon since now is rendered from excal-app via `renderFooter` prop hence gets pushed from right (due to translate) which might look jerky.
> fix: move encrypted icon to excalidraw-app

- vercel.json
Live demo: https://excalidraw-d2qs5vtbq-excalidraw.vercel.app/_src
This helps people verify that the code they’re downloading from `excalidraw.com` matches the `master` branch on GitHub:
<sup><a href="https://mobile.twitter.com/agentofuser/status/1393972173350576133">source</a></sup>
> chore: Make deploy source and logs public

- src/components/App.tsx
- src/groups.ts
- src/tests/helpers/api.ts
- src/tests/helpers/ui.ts
- src/tests/selection.test.tsx
- src/tests/zindex.test.tsx
fix https://github.com/excalidraw/excalidraw/issues/3601
Draft because it will likely contain bugs + will need a lot of tests.
---
Aligns the drag-select behavior with Figma. When you drag-select while pressing cmd/ctrl it disables dragging of selected elements (elements under cursor); instead it acts as regular box selection.
Below I drag-select while pressing cmd/ctrl:
The behavior where it first immediately selects the element under cursor (gray) is correct, because you may want to use `cmd/ctrl` as a drill-select modifier (i.e. `cmd/ctrl-click` to select specific element). If you then box-select a nested element (or any element) it deselects the original element you initially clicked on.
Note for the future: this isn't aligned 1:1 Figma in that Figma keeps selection of hitElement even …
> feat: allow inner-drag-selecting with cmd/ctrl

- .github/workflows/autorelease-excalidraw.yml
- package.json
- scripts/autorelease.js
- src/packages/excalidraw/README.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/package.json
If the commit needs a release, this GitHub action will update the package name to `@excalidraw/excalidraw-next` and append commit hash to the release name and then publish the package.
Here is the [auto released version](https://www.npmjs.com/package/@excalidraw/excalidraw-next).
TODOS before merge
> feat: Auto release @excalidraw/excalidraw-next on every change

- src/components/LayerUI.scss
- src/css/styles.scss
When we split footer into 3 containers we've inadvertently re-enabled pointer events on the center footer which prevents interacting with the canvas at the bottom.
> fix: disable pointer-events on footer-center container

- src/data/restore.ts
- src/element/linearElementEditor.ts
It may happen that linear element's points get denormalized in the course of the app. This shouldn't happen but apparently it can https://github.com/excalidraw/excalidraw/issues/3632. This PR normalizes the points during restore if needed.
This may also be useful if someone creates the arrows programmatically and don't adhere to the `[0,0]` invariant.
> fix: normalize linear element points on restore

- src/actions/actionExport.tsx
- src/components/Tooltip.scss
- src/components/Tooltip.tsx
- src/excalidraw-app/index.tsx
- tooltip is now autopositioned, ensuring it doesn't overflow viewport (thus, dropped `position` prop)
- tooltip is now rendered into an absolutely-positioned div in `body` which allows it to overflow containers which have `overflow: hidden`
- for now I dropped these two things:
- the tooltip triangle. Can be reintroduced at any time, I just thought it's not worth the effort right now (it looks fine without it)
- not auto-hiding the tooltip when you managed to mouseover it. Again, it can be reintroduced, but even in production it was nearly useless as you had to carefully navigate the mouse across the triangle
@ad1992 I'd like to export this compo so it can be reused by host apps. Thoughts?
> feat: auto-position tooltip and suport overflowing container

- src/actions/actionExport.tsx
- src/actions/index.ts
- src/actions/types.ts
- src/components/App.tsx
- src/components/JSONExportDialog.tsx
- src/components/LayerUI.tsx
- src/constants.ts
- src/excalidraw-app/index.tsx
- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README_NEXT.md
- src/packages/excalidraw/index.tsx
- src/tests/excalidrawPackage.test.tsx
- src/types.ts
> feat: customise export dialog with UIOptions.canvasActions.export prop

- public/index.html
Previously, swiping up and down on an Island would cause the page to rubberband. Adding `overflow: hidden` fixes this.
> fix: overscroll on touch devices

- src/components/App.tsx
- src/tests/__snapshots__/contextmenu.test.tsx.snap
- src/tests/contextmenu.test.tsx
- src/tests/helpers/api.ts
Opening contextMenu when clicking on a selected element(s) should retain the selection regardless of whether there's a non-selected element with a higher z-index under the cursor (covering the one selected) when right-clicking.
Aligns with Affinity, Figma et al.
Test plan:
- create two elements, one covering the other, select the one beneath, and rightclick on the element that's covering it (but still so that you're clicking on both effectively)
> fix: on contextMenu, use selected element regardless of z-index

- src/components/ExportDialog.scss
fix https://github.com/excalidraw/excalidraw/issues/3687
I must have used chrome to copy them from, where it forces you to use the new shorthand syntax.
> fix: use rgba instead of shorthand alpha

- src/packages/excalidraw/README.md
- src/packages/excalidraw/README_NEXT.md
Hi there, thanks for Excalidraw! Really amazing editor, enables so many things 🙌 
Just a quick PR to improve the grammar and make the `useEffect` with the import run only once (which I believe should be fine)
> docs: improve grammar, import + render only once

- src/components/App.tsx
In React v17, `persist` is no longer required.
I thought `event.persist()` could be removed.
Reference:
> As of v17, e.persist() doesn’t do anything because the SyntheticEvent is no longer pooled.
https://reactjs.org/docs/events.html#overview
> refactor: Delete React SyntheticEvent persist

- src/components/LayerUI.scss
Disable zen mode is broken in prod since https://github.com/excalidraw/excalidraw/pull/3629 was merged as pointer events were disabed
> fix: allow pointer events for disable zen mode button

- src/components/App.tsx
- src/tests/library.test.tsx
- fixes #3765
- I see that there's a test file for library (library.test.tsx) but not quite sure how to use it. Will definitely work on a test if I can get guidance/pointers!
- attached a video showing tests before and after change
https://user-images.githubusercontent.com/37394743/123556943-0b364080-d75c-11eb-96f5-39cf9307a553.mov
> feat: switch to selection tool on library item insert

- .gitignore
- src/components/App.tsx
- src/shapes.tsx
fix #2649
> Why the s and g shortcut doesn't work to change the selected color while a tool is active and nothing is selected? Instead pressing s goes back to the Selection tool and pressing g does nothing.
cc @dwelle https://github.com/excalidraw/excalidraw/issues/2649#issuecomment-873642610
- also drops `S` shortcut for `selection` tool (legacy)
> fix: ensure `s` and `g` shortcuts work on no selection

- src/components/App.tsx
I made a mistake in https://github.com/excalidraw/excalidraw/pull/3797, not passing deleted elements to the restore 😊
> fix: include deleted elements when passing to restore

- .gitignore
- README.md
got some errors with yarn v2, so had to downgrade
to even start working, I think it's a good idea
to put it in the README
> docs: specify to use yarn v1 not v2

- src/packages/excalidraw/CHANGELOG.md
- src/renderer/renderElement.ts
- src/renderer/renderScene.ts
This should resolve the issues observed in https://github.com/excalidraw/excalidraw/issues/3798 where the cursor becomes misaligned with the canvas. This appears to be caused by small rounding errors in the transform matrix accumulating over time.
This PR contains two fixes for this.
1. Reset the canvas's transform matrix to the identity matrix at the beginning of `renderScene`. This ensures that any accumulated error from previous frames is irrelevant.
2. Instead of manually restoring the drawing context's state, use the built-in `context.save()` and `context.restore()`. This ensures that rounding errors can't accumulate in between elements. This change is obviously somewhat more involved and therefore more risky. It could be left out of this PR and while the underlying issue wouldn't be …
> fix: Prevent gradual canvas misalignment

- src/actions/actionCanvas.tsx
- src/actions/actionExport.tsx
- src/actions/actionHistory.tsx
- src/actions/actionNavigate.tsx
- src/actions/manager.tsx
- src/actions/types.ts
- src/components/Actions.tsx
- src/components/CheckboxItem.scss
- src/components/LayerUI.scss
- src/components/LayerUI.tsx
- src/components/LibraryButton.tsx
- src/components/LockButton.tsx
- src/components/MobileMenu.tsx
- src/components/ToolButton.tsx
- src/components/ToolIcon.scss
- src/components/Tooltip.scss
- src/components/Tooltip.tsx
- src/css/styles.scss
- src/excalidraw-app/components/LanguageList.tsx
- src/excalidraw-app/index.scss
- src/excalidraw-app/index.tsx
- src/tests/flip.test.tsx
- src/tests/packages/__snapshots__/excalidraw.test.tsx.snap
- src/tests/resize.test.tsx
fix https://github.com/excalidraw/excalidraw/issues/3162
Moved encryption icon to the right because it didn't look good next to the undo buttons. Also made footer smaller, and removed absolute positioning of help icon.
Initially I wrapped the resetZoom button in a Tooltip, but removed it in [`ff790b9` (#3832)](https://github.com/excalidraw/excalidraw/pull/3832/commits/ff790b9779c1f635d8f6ed631a29a58774ad9623) because it made tests fail for unknown reason (https://github.com/excalidraw/excalidraw/runs/3060724910).
> feat: add undo/redo buttons & tweak footer

- src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/3553
In specific cases (such as when starting to edit text), `pointerup` event may not be fired on `<cavas>` which results in not removing it from the `gesture.pointers` cache, which then results in buggy behavior.
> fix: permanent zoom mode

- src/css/styles.scss
fix https://github.com/excalidraw/excalidraw/issues/3938
> fix: help-icon now visible on Safari

- src/packages/excalidraw/CHANGELOG.md
- src/packages/excalidraw/README.md
- src/packages/excalidraw/README_NEXT.md
This was something I ran into when integrating the component. I'm using it here and it doesn't work with the documented name: https://github.com/alkem-io/client-web/blob/whiteboard-806-embedded/src/components/Opportunity/ActorWhiteboard.tsx#L129
> docs: correct exportToBackend to onExportToBackend in README

- package.json
- src/renderer/renderElement.ts
- yarn.lock
This PR bumps perfect-freehand to the latest version and tweaks the code used to generate an SVG path from the stroke points. There have been a few bug fixes since the previously used versions, which may solve the missing strokes issues reported here: https://github.com/excalidraw/excalidraw/issues/3564
.
fix https://github.com/excalidraw/excalidraw/issues/3564
> feat: improve freedraw shape
