README.md
This small change improves our current README doc by adding a note to point out the requirement of 22 characters for encryption key parameter. As brought up in #3994 🙂
=> docs: Added note on encryption key length

src/excalidraw-app/data/index.ts, src/locales/en.json
The changes in this PR resolves #3994 by adding a check to ensure that the encryption key is of 22 characters, and alerts the user + disables live collaboration mode if that's not the case.  🙂
=> fix: Added alert for bad encryption key

src/components/App.tsx
Closes #3732 
Fixes the positioning of the context menu which gets hidden when right clicked on to the rightmost or bottomost part of the viewport which is caused due to re-rendering of the context menu.
Fixes the re-rendering of ContextMenu which is caused due to poor control flow logic which fails when the `this.state.viewModeEnabled` is false.
=> fix: context menu positioning

src/components/App.tsx, src/components/LayerUI.tsx, src/excalidraw-app/collab/CollabWrapper.tsx, src/excalidraw-app/collab/Portal.tsx, src/excalidraw-app/components/ExportToExcalidrawPlus.tsx, src/excalidraw-app/data/FileManager.ts, src/excalidraw-app/index.tsx
fix https://github.com/excalidraw/excalidraw/issues/4108
Among major issues fixed:
- we weren't checking `files` object when resolving `LayerUI` compo. We should write an abstraction for this because it's not being type checked at all.
- stop mutating image elements when updating `status`, particularly when closing collab room — this was causing a race condition where a `pending` status update leaked into the last server update on room close (the updater function awaits stuff before the elements are finally serialized).
=> fix: image-related fixes

src/components/App.tsx, src/excalidraw-app/data/firebase.ts, src/excalidraw-app/index.tsx
fix https://github.com/excalidraw/excalidraw/issues/4154
Due to not mutating image elements anymore, which caused `appState.pendingImageElement` not pointing to the latest element. Regression from https://github.com/excalidraw/excalidraw/pull/4147 😊 
Also fixed two related issues with (not) updating status correctly.
=> fix: images not initialized correctly

src/components/HintViewer.tsx, src/components/LayerUI.tsx, src/components/MobileMenu.tsx, src/locales/en.json
Many users don't know how to pan canvas. While we will add a separate pan tool shortly, we should nevertheless teach people how to move canvas in a more efficient way.
Added a hint around canvas panning, when a `selection` tool is active, but nothing is selected — the reasoning for the latter is we show specific hints when certain elements are selected (arrow, line...) or when doing some action while selection tool is active (resizing...). So it's best we don't show the canvas panning hint all the time as it'd not be consistent and to ensure the hint doesn't appear as related to selecting.
Not showing on Mobile. This will still show on tablets. We will need a better way to discern devices that don't have a keyboard or mouse attached. One way is to detect in which way the selection tool …
=> feat: add hint around canvas panning

package.json, src/renderer/renderElement.ts, yarn.lock
fix https://github.com/excalidraw/excalidraw/issues/4046
Removing decimal points when rendering rough elements on Canvas seem to have fixed #4046. There's minimal difference in render output.
PR: https://excalidraw-git-fixskiarendering-excalidraw.vercel.app/#json=5629239709663232,-x6WJuEA3TsAz3vIjZmgtQ
prod: https://excalidraw.com/#json=5629239709663232,-x6WJuEA3TsAz3vIjZmgtQ
PR/prod: (or was it the other way round? :p)
=> fix: Skia rendering issues

public/index.html, public/manifest.json
- The origin trial for File Handling is over.
- The declarative link capturing feature will launch in a different shape.
=> chore: Remove outdated origin trial info

src/actions/actionExport.tsx, src/components/App.tsx, src/components/ToolButton.tsx, src/utils.ts
We tend to get a lot of bugs related to FS abort errors. To make debugging easier, let's always log them to the console (`console.warn` to not log to Sentry).
=> feat: log FS abortError to console

src/data/filesystem.ts, src/data/index.ts
fix https://github.com/excalidraw/excalidraw/issues/4271
On Linux, using the new FS API requires passing `description` argument 🤷‍♂️
=> fix: new FS API not working on Linux

src/actions/actionCanvas.tsx, src/components/Tooltip.scss, src/components/Tooltip.tsx
reverting [`cefa6f5` (#3832)](https://github.com/excalidraw/excalidraw/pull/3832/commits/cefa6f5b566fd7a78b3a50276673f33210f614f6) to fix:
=> fix: remove `100%` height from tooltip container to fix layout issues

src/components/App.tsx, src/renderer/renderElement.ts, src/renderer/renderScene.ts, src/scene/export.ts, src/scene/types.ts
When we shipped the image PR I've mistakenly enabled render optimizations during export which we shouldn't do. One of the main issues with it is broke scaling.
In this PR I've reverted the change, which required accounting for this when rendering images (so we correctly reset the canvas filter).
At the same time, I've removed the `renderOptimizations` option, merging it into `isExport` (renamed to `isExporting`), because it was currently 1:1 coupled.
----
Second, unrelated commit: merge `SceneState` and render options config, and rename to `RenderConfig`.
**Review by commits**
=> fix: export scale quality regression

src/components/App.tsx, src/components/PublishLibrary.tsx, src/data/blob.ts, src/global.d.ts, src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README_NEXT.md, src/packages/utils.ts, src/utils.ts
⚠️ REMOTE PR MUST BE MERGED FIRST: https://github.com/excalidraw/excalidraw-libraries-automation/pull/15 ⚠️ 
Max 6 items per row, all items are 160px squares (the PNG is larger for better quality when we later support zooming).
Also, we're now compressing into JPG, which fixes https://github.com/excalidraw/excalidraw-libraries/issues/280
---
https://github.com/excalidraw/excalidraw-libraries/pull/281 (preview https://excalidraw-libraries-llr7un0rd-excalidraw.vercel.app) (png: https://excalidraw-libraries-llr7un0rd-excalidraw.vercel.app/libraries/test/test.png)
=> feat: improve library preview image generation on publish

src/renderer/renderElement.ts
Previously, we've been dropping floating points to improve render output (make sharper), but it didn't really improve much on average (if at all), and on large zoom levels (and small elements) it drastically worsened UX & rendering precision.
before/after:
before:
=> feat: stop discarding precision when rendering

src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/package.json, src/packages/excalidraw/webpack.prod.config.js, src/packages/tsconfig.prod.json
- remove `dist/` before build because it seems webpack simply merges the build output, not removing the old chunks/assets generated from previous builds
- move to `es2017` build target. We don't support browsers that don't support it anyway. Solves a recent regression where transpiling async/wait to regenerators was causing typeError issues. Haven't dug super deep to figure out what was the exact cause, but it just seems a compiler issue.
=> feat: set package build target to `es2017`

src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/package.json, src/packages/excalidraw/webpack.dev.config.js, src/packages/excalidraw/webpack.prod.config.js, src/packages/excalidraw/yarn.lock
fixes  https://github.com/excalidraw/excalidraw/issues/4313
This started happening since https://github.com/excalidraw/excalidraw/pull/4122 was merged as `css-loader` was compatible with webpack 5 which led to duplication of assets and started pointing to the new urls due to which fonts stopped working
Using asset modules as suggested in [webpack docs](https://webpack.js.org/guides/asset-modules/)
Try [here](https://1m7pt.csb.app/)
=> build: remove file loader and migrate to asset modules webpack for font assets

src/actions/actionDeleteSelected.tsx, src/actions/actionDuplicateSelection.tsx, src/actions/actionFlip.ts, src/components/App.tsx, src/components/HintViewer.tsx, src/element/binding.ts, src/element/collision.ts, src/element/linearElementEditor.ts, src/locales/en.json, src/renderer/renderScene.ts, src/tests/binding.test.tsx, src/types.ts
- Added support for selecting multiple points (via Shift-click) when inside line editor.
- Second commit adds support for box-selection of points (drag, Shift-drag, Cmd-drag)
(Reviewable by commits.)
=> feat: support selecting multiple points when editing line

src/components/Card.tsx, src/components/IconPicker.scss, src/components/Island.scss, src/components/LayerUI.tsx, src/components/LibraryButton.tsx, src/components/LockButton.tsx, src/components/MobileMenu.tsx, src/components/ToolIcon.scss, src/components/Toolbar.scss, src/components/icons.tsx, src/css/styles.scss, src/css/theme.scss, src/excalidraw-app/components/ExportToExcalidrawPlus.tsx, src/excalidraw-app/index.scss, src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README_NEXT.md
Several smaller design changes, most notably the toolbar. And using our new brand color, _Muscari Royale_. 🚀
Also tweaked what is/isn't shown in zen mode:
- hide toolbar keybindings
- hide  hints
- show lock and library buttons
(reviewable by commits)
=> feat: redesign toolbar & tweaks

src/element/textWysiwyg.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4409
=> fix: use word-break break-word and update text editor height only when binded to container

src/tests/helpers/api.ts, src/tests/zindex.test.tsx, src/zindex.ts
fixes https://github.com/excalidraw/excalidraw/issues/4407
=> fix: bound text not atomic with container when changing z-index

src/element/textWysiwyg.tsx
This has been an existing issue for text editor 
Before
Now
=> fix: support updating stroke color for text by typing in color picker input

src/element/textWysiwyg.tsx, src/packages/excalidraw/package.json
Earlier: 
Now
Also fixes https://github.com/excalidraw/excalidraw/issues/4421, https://github.com/excalidraw/excalidraw/issues/4418
try https://1m7pt.csb.app/
=> fix: vertically center align the bounded text correctly when zoomed

src/components/App.tsx
=> fix: switch cursor to center of container when adding text when dimensions are too small

src/element/textWysiwyg.tsx
=> fix: vertically center the first line as user starts typing in container

src/element/textWysiwyg.tsx
Previous
Now
introduced as regression in https://github.com/excalidraw/excalidraw/pull/4444
=> fix: vertically center align text when text deleted

src/components/LibraryUnit.scss
=> fix: align library item previews to center

src/components/App.tsx
=> fix: move binded text when moving container using keyboard

src/align.ts, src/disitrubte.ts, src/element/bounds.ts, src/groups.ts
Previous
Now
fixes https://github.com/excalidraw/excalidraw/issues/4467
=> fix: align and distribute binded text in container and cleanup

src/actions/actionProperties.tsx, src/actions/actionStyles.ts, src/constants.ts, src/element/newElement.ts, src/element/textElement.ts, src/element/textWysiwyg.tsx
Prev
Now
fixes https://github.com/excalidraw/excalidraw/issues/4461
This only happens for first time since text editor width is not yet set
=> fix: set height correctly when text properties updated while editing in container until first submit

src/components/App.tsx
Previous
Now
fixes https://github.com/excalidraw/excalidraw/issues/4471
=> fix: pasted elements except binded text once paste action is complete

src/components/App.tsx, src/packages/excalidraw/CHANGELOG.md
When the component is inside a scrollable container, panning via `space-drag` or `wheel-drag` causes the container to scroll.
=> fix: prevent browser from scrolling when panning

src/element/newElement.ts, src/random.ts, src/utils.ts
Introduced in https://github.com/excalidraw/excalidraw/pull/4495, since `process?.env?.NODE_ENV` breaks in browser as `process` is not defined hence package breaks hence adding a safe check to make sure its defined before using it
=> fix: check if process is defined before using so it works in browser

src/components/App.tsx
Adding text inside a container who's part of a group(s) doesn't set the `groupIds` on the new text element.
=> fix: bound text doesn't inherit container

src/element/textElement.ts
fixes https://github.com/excalidraw/excalidraw/issues/4500
Previous
Now
There is still one issue, you need to undo twice  for first time, and thats coz the data gets pushed twice to the stack when editing in https://github.com/excalidraw/excalidraw/blob/master/src/components/App.tsx#L1970
=> fix: undo should work when selecting bounded text

src/element/textWysiwyg.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4474
Previou
Now
There are still few bugs related to rotation which I will fix in future PR's
=> fix: rotate bounded text when container is rotated before typing

src/actions/actionProperties.tsx, src/element/textElement.ts
=> fix: show text properties button states correctly for bounded text

src/components/HelpDialog.tsx
It's not SHIFT+P anymore but just "X".
=> fix: wrong shortcut for Draw tool in help dialog

src/components/App.tsx
Pasting spreadsheet data from MS Office/Libre Office also puts an image fine into the clipboard, which is currently preferred. This PR makes sure the spreadsheet data takes priority.
=> fix: prefer spreadsheet data over image

.github/workflows/test.yml, package.json, src/components/App.tsx, src/element/newElement.ts, src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx
Attempt fix the "undo twice for first time when bounded text properties updated by selecting text explicitly" mentioned in https://github.com/excalidraw/excalidraw/pull/4537
Previous
Now
=> fix: don't mutate the bounded text if not updated when submitted

src/actions/actionClipboard.tsx, src/actions/register.ts, src/components/App.tsx, src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx, src/tests/resize.test.tsx
fix https://github.com/excalidraw/excalidraw/issues/4587. The regression was caused in https://github.com/excalidraw/excalidraw/pull/4553, where I didn't realize that if we let our keyboard handler handle the `cmd`/`ctrl` events, it'll block actions like `cmd-a` or `cmd-delete` in inputs.
This PR reverts that and tests for the font decreasing/increasing actions in place, and executes them directly when applicable.
=> fix: cmd/ctrl native browser behavior blocked in inputs

src/element/textWysiwyg.tsx
fix https://github.com/excalidraw/excalidraw/issues/4680
=> fix: typing `_+` in wysiwyg not working

src/components/App.tsx, src/packages/excalidraw/CHANGELOG.md
When Excalidraw is used as a dynamic component with useEffects it gets unmounted and mounted back multiple times. `componentWillUnmount` sets `this.unmounted` to `true` which breaks the functionality because it blocks `syncActionResult`. This fix ensures that `this.unmounted` is reseted to false
=> fix: reset unmounted state for the component

src/components/App.tsx, src/components/Toolbar.scss
[for-obsidian #411](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/411)
=> fix: Disable three finger pinch zoom in penMode

src/components/App.tsx
Freedraw, when drawing with a pen slowly (aiming for precision) generates a jittery line. Performance of freedraw also degrades after a long stretch of "precision" drawing.
This is because freedraw captures every point, even if it has the exact same coordinates. True, these points might have different pressures, however this additional pressure information, since all the points are on top of one another, is anyway wasteful.
The change will only add the next point to the points array if it has at least one different coordinate. This drastically reduces the size of freedraw objects and decreases the jitter on the line. 
The noise could be further decreased by increasing the minimum distance between points.
After applying the fix:
=> fix: freedraw slow movement jittery lines

src/components/App.tsx, src/types.ts, src/utils.ts
I've noticed that iPad Pen (but likely Safari, and maybe other browsers, in general) emits too many events when drawing. This PR throttles most (but not all) `pointermove` handlers to be called at most one per animation frame.
This will cause some events to be dropped (it always takes the last one), but I haven't noticed any visual/behavioral issues. I've left the handler that takes care about cursor changes unthrottled, but if we don't notice any issues we should throttle that one as well.
Doing this __significantly__ improves drawing performance on iPad Pen, especially the `freedraw`.
---
Read [this article](https://nolanlawson.com/2019/08/11/high-performance-input-handling-on-the-web/) for explanation. We may later want to introduce other perf improvements mentioned there as well.
=> feat: throttle `pointermove` events per framerate

src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4704
=> fix: make link icon clickable in mobile

src/components/App.tsx, src/element/Hyperlink.tsx
https://user-images.githubusercontent.com/11256141/152760117-96491123-71fd-4f49-a4f2-42cdbb38c4d6.mp4
=> feat: Make whole element clickable in view mode when it has hyperlink

src/components/App.tsx, src/constants.ts
fix https://github.com/excalidraw/excalidraw/issues/4674
=> fix: disable contextmenu on non-secondary `pen` events or `touch`

src/actions/actionCanvas.tsx
Something that annoyed me is when you're drawing and want to clear canvas, it resets the selected tool.
=> feat: keep selected tool on canvas reset

src/actions/actionProperties.tsx, src/components/ButtonIconSelect.tsx, src/tests/appState.test.tsx
=> fix: changing font size when text is not selected or edited

src/element/Hyperlink.tsx
fixes https://github.com/excalidraw/excalidraw/issues/4748
=> fix: use absolute coords when rendering link popover

src/components/App.tsx
Unclear why we're reimplementing `event.touches` list in the first place (maybe there's a valid reason), but that's for another day.
=> fix: contextMenu timer & pointers not correctly reset on iOS

src/components/App.tsx
I no longer think it is either necessary (https://github.com/excalidraw/excalidraw/pull/4089/files) or desired to bump element versions when you're simply updating `app.files`.
For excalidraw.com it makes it hard to figure out what constitutes an actual change (for collaboration versioning purposes).
@zsviczian
=> fix: don't bump element version when adding files data

src/element/textWysiwyg.tsx
Attempt to fix https://github.com/excalidraw/excalidraw/issues/4617
https://user-images.githubusercontent.com/11256141/155104144-e86301af-b27a-4735-9264-d657a4c931b8.mp4
=> fix: restore cursor position after bound text container value updated

src/actions/actionFlip.ts, src/element/resizeElements.ts
https://user-images.githubusercontent.com/11256141/154973540-5e9b6f04-1548-4226-acca-d6c442c97ab5.mp4
=> feat: Scale font size when bound text containers resized with shift pressed

src/components/Actions.tsx
=> fix: Don't show align icons for single bound container element

src/components/Actions.tsx
fix https://github.com/excalidraw/excalidraw/issues/4859
I've also changed this from `every` to `some` to align with what we do with other props.
=> fix: ensure verticalAlign properties not shown when no element selected

src/packages/utils/README.md, src/packages/utils/package.json, src/packages/utils/webpack.prod.config.js, src/packages/utils/yarn.lock
fixes https://github.com/excalidraw/excalidraw/issues/4865
[Try here](https://codesandbox.io/s/excalidraw-utils-76dwne)
This is a temp solution to make the utils work, however we will want to remove the dependency of React/ReactDom completely before officially releasing the version since this package should be pure Javascript
Will set up the `autorelease` for `@excalidraw/utils` as well so its up to date with the codebase
=> build: support runtime React Jsx in @excalidraw/utils

src/excalidraw-app/collab/CollabWrapper.tsx, src/excalidraw-app/collab/Portal.tsx
When another client connects to an existing room, we were awaiting firebase data which caused socket subscriptions to be delayed, in particular the `SCENE_INIT` which resulted in the portal not being initialized and falling back on the 5sec timeout.
This PR makes sure the firebase data are fetched only when first in the room (or on fallback).
=> fix: collab room initialization

.env.development, .env.production, public/index.html, src/excalidraw-app/collab/CollabWrapper.tsx, src/excalidraw-app/data/index.ts, src/global.d.ts, src/locales/en.json, src/tests/collab.test.tsx
- Switched to a new collab server
- Connecting to a collab server is done in two steps now:
1. get collab server connection details by querying `portal.excalidraw.com`
2. connect to the server using the data from step (1) 
This allows us to switch servers etc. more-or-less immediately without having to push things and waiting for all clients to update to latest ServiceWorker (which in many cases takes months or even more).
- disabled `polling` socketIO transport (all the browser we support have support for WS)
- removed preconnecting to our WS server. The optim is not worth the downsides (increasing load on our servers). If needed, we can optimize differently.
=> feat: rewrite collab server connecting 

src/excalidraw-app/app_constants.ts, src/excalidraw-app/collab/CollabWrapper.tsx
Throttle pointer syncing to reduce the amount of messages (it's a bottleneck for both the collab server and render loop)
=> fix: improve pointer syncing performance

src/renderer/renderElement.ts
The drawing:
export using [exportToSvg](https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw#exporttosvg) before the fix:
export using [exportToSvg](https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw#exporttosvg) after the fix:
Zip file with the two sample SVG files:
[sample.svg.zip](https://github.com/excalidraw/excalidraw/files/8191516/sample.svg.zip)
=> fix: freedraw element's background fill color missing from SVG when exporting with package API exportToSvg()

src/components/App.tsx, src/tests/helpers/api.ts
Closes #3971 
Adds a missing check for if a file is present on drop. This is required manually due a typescript `as any` cast further inside the code block. Also manually adds a couple of type annotations to make clear that file may not be provided.
The behaviour is now to take no action, if a file is not found (rather than showing an error modal).
=> fix: don't crash on drop highlighted text onto canvas

src/actions/actionCanvas.tsx, src/components/HelpDialog.tsx, src/keys.ts, src/locales/en.json, src/shapes.tsx, src/tests/__snapshots__/regressionTests.test.tsx.snap, src/tests/regressionTests.test.tsx
https://user-images.githubusercontent.com/11256141/158551603-496f3f0e-5e54-47d9-a125-7f90a52b54cf.mp4
=> feat: Map shortcut O to ellipse and Add eraser shortcut E

src/components/App.tsx, src/element/Hyperlink.tsx
this is for _top-right corner hitbox issue #4966_
I've added a check to ensure there's actually a link for the element to do the early return. From what I can tell there's no need to return early if there's no link to actually go to. 
I'm checking for `length > 0` instead of just checking `not equals null ` because as soon as you open the hyperlink box, `link` is not null (even after closing hyperlink box).
_edge case this fix doesn't handle_ – if you open up the hyperlink box and start typing in a link, we don't satisfy this check anymore, so you'd not be able to drag the element from the top right corner with an open hyperlink editor with some contents for the link
=> fix: adding check for link length to prevent early return 

src/data/restore.ts
Resetting `penDetected` on reload if penMode isn't active. Currently, the button is never hidden if you ever enter penMode.
If `localAppState` passed to restore, we don't reset. This accounts for a case where you restore the appState during the same session for some reason.
=> feat: hide penMode button on reload if not enabled

src/data/json.ts, src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README.md, src/packages/excalidraw/README_NEXT.md, src/packages/utils.ts
This PR add an `serializeLibraryAsJSON` helper.
Example usecase in the VSCode extension: https://github.com/pomdtr/vscode-excalidraw-editor/issues/16
=> feat: create and expose serializeLibraryAsJSON

src/actions/actionClipboard.tsx, src/actions/index.ts, src/actions/types.ts, src/components/App.tsx, src/locales/en.json
=> feat: Copy to clipboard all text nodes as text

src/actions/actionClipboard.tsx, src/components/App.tsx
fixes bugs introduced by https://github.com/excalidraw/excalidraw/pull/5013
=> fix: Copy to clipboard all text nodes as text

src/clipboard.ts, src/data/index.ts, src/locales/en.json, src/utils.ts
fix https://github.com/excalidraw/excalidraw/issues/4967
Safari doesn't like when the ClipboardItem is created in a different frame than the user-triggered event. https://bugs.webkit.org/show_bug.cgi?id=222262 (via https://web.dev/async-clipboard/). ~~And chrome doesn't support the `Promise` in `ClipboardItem` constructor.~~ EDIT: not anymore, but I'm still handling the case where promise ClipboardItem constructor isn't supported to be safe (future FF may not support it).
=> fix: support copying PNG to clipboard on Safari

src/packages/excalidraw/index.tsx
=> fix: export serializeLibraryAsJSON in the excalidraw package

src/excalidraw-app/collab/CollabWrapper.tsx, src/excalidraw-app/collab/Portal.tsx, src/excalidraw-app/data/LocalData.ts, src/excalidraw-app/data/Locker.ts, src/excalidraw-app/data/localStorage.ts, src/excalidraw-app/index.tsx
- first commit just factors out the LS/IDB handling into `LocalData` class. It also makes it explicit that we're disabling saving when collaborating.
- second commit fixes a race condition in a multi-tab scenario when a new release is made and Service Workers are updated, reloading all tabs. In this case, users could lose data by the old tabs overwriting them just in time for the new tab to initialize from it. Refer to the diagram below for specifics.
The fix consists of disabling saving when the document is hidden.
=> feat: refactor local persistence & fix race condition on SW reload

src/components/App.tsx
Pinch zoom in currently does not work when `viewModeEnabled===true`. This PR fixes this issue. 
https://user-images.githubusercontent.com/14358394/161367999-2dd9d290-503b-4030-9a58-7e278b051c38.MOV
=> fix: Pinch zoom in view mode

src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README_NEXT.md, src/packages/excalidraw/entry.js, src/packages/excalidraw/example/App.js, src/packages/excalidraw/webpack.dev.config.js, src/packages/excalidraw/webpack.prod.config.js
fixes https://github.com/excalidraw/excalidraw/issues/5035
Try [here](https://stackblitz.com/edit/vitejs-vite-yahyqr?file=src%2FApp.jsx&terminal=serve)
=> build: export only named exports from the package

.env.development, public/index.html, src/excalidraw-app/index.scss, src/excalidraw-app/index.tsx
https://user-images.githubusercontent.com/11256141/163429110-4ca8633d-7228-45cd-b80c-51963b6158d1.mp4
=> feat: hide trash button during collaboration

src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README_NEXT.md, src/packages/excalidraw/example/App.js, src/packages/utils.ts
This will be helpful to allow users to edit png files directly in the vscode extension (https://github.com/excalidraw/excalidraw-vscode/issues/10)
=> feat: embed scene support for png export in npm package

firebase-project/storage.rules
Updates our Firebase storage rules. This is just for docs for self-hosting purposes. The Storage rules aren't deployed from source, and our actual rules differ slightly. For example, this PR removes the `match /{migrations}` rule as it's excalidraw.com/E+ specific and doesn't serve any purpose for host apps.
=> fix: update `storage.rules`

public/index.html, src/components/LayerUI.tsx, src/components/LoadingMessage.tsx, src/css/app.scss
- Changed the initial loading message to be delayed by 250ms. This removes a flicker for most cases as the initial load is pretty fast. And since we're now delaying, there's no need for also adding the loading message to `index.html` outside of the react flow.
- I've also tweaked the design as the text on gray rectangle wasn't looking that great.
Sadly you can't really test this in preview, it's too fast :).
=> feat: delay initial loading message & tweak design

src/data/image.ts
Example file triggering an error: https://gist.github.com/pomdtr/53af6d4170a8682b7f944e32c8ca499b which can be reproduced when prettifying the SVG file
=> fix: SVG metadata extraction regex on multiline elements

src/components/App.tsx
In the vscode extension, the updateScene helper is used to sync deleted items from the library between webviews.
The behavior since of the `updateScene` method since cd942c3 break this, since the deleted items from the library will still be present after the merge.
The `updateScene` method does not attempt to merge the appState or the elements, so I feel like this is not the expected behavior.
=> fix: don't merge libraryItems on updateScene

src/element/binding.ts
fixes https://github.com/excalidraw/excalidraw/issues/5008
=> fix: boundElementIds when arrows bound to elements are deleted

src/packages/excalidraw/entry.js, src/packages/excalidraw/index.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5080
check [preview](https://excalidraw-package-example-git-aakansha-fix-webpack-excalidraw.vercel.app/)
=> fix: setting webpack public path

src/components/ToolIcon.scss
fixes vscode extension floating buttons not being round
=> fix: toolIcon height not using rem

public/index.html, src/constants.ts, src/global.d.ts, src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README_NEXT.md
=> feat: Expose `window.EXCALIDRAW_EXPORT_SOURCE` which host can use to overwrite the source field in exports

src/components/App.tsx, src/element/textWysiwyg.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5000
=> fix: don't bind text to container if double clicked else where instead of center

src/actions/actionProperties.tsx
So currently the scroll wheel interaction on the opacity slider can cause some really jarring stuff to happen when you need to scroll down the action bar.
You mouse over to the action bar, your mouse happens to be hovering over the opacity bar, you scroll down.. and what happens is the opacity is dropped to zero at the same time as the action panel is scrolled down.
This means you don't notice that the opacity got changed, just that your element is suddenly invisible.
The problem stems from the fact that React just doesn't handle wheel event properly, you cant just `event.stopPropagation()`. It doesn't stop the scroll behaviour from propagating to the parent element.
https://github.com/facebook/react/issues/14856
Rather than pursuing some hacky solution involving binding an event listener …
=> fix: remove opacity scroll wheel interaction

src/actions/actionClipboard.tsx, src/clipboard.ts, src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README_NEXT.md, src/packages/excalidraw/example/App.js, src/packages/excalidraw/index.tsx, src/packages/utils.ts
https://user-images.githubusercontent.com/11256141/165487436-7f7a1fc3-9746-4c3f-9f38-a1d63ed82df3.mp4
~Do we want to introduce `type`  (svg, png, text) ?~ done
=> feat: export exportToClipboard util from package

src/charts.test.ts, src/charts.ts
Fixes https://github.com/excalidraw/excalidraw/issues/5149
Parse
- `10%`
- numbers with leading or trailing `.`'s
- Currency with `-` after leading currency symbol
as a number in a chart
Treat the first column as labels if both columns in a chart are numeric.
=> fix: Chart display fix

src/components/LibraryMenu.tsx, src/components/LibraryMenuItems.tsx
Currently, the multi-select support in library menu doesn't work properly across published/unpublished section because it accesses selected items from the original, unsorted array (hence the index offsets are read incorrectly).
This PR fixes this by looking up items from a concatenated array of unpublished & published section in the right order.
=> fix: library multiselect not accounting for published state

src/components/ColorPicker.tsx
Fixes #5151
Fixes the crash, I think we can talk about the undo/redo correctly applying in a seperate issue.
=> fix: Handle `ColorPicker` parentSelector being undefined

src/components/App.tsx, src/element/binding.ts, src/scene/Scene.ts
- first commit: fix https://github.com/excalidraw/excalidraw/issues/5153
- second commit: rename `scene.getElements` → `scene.getNonDeletedElements` (the original naming was a footgun), and move 
the original `getNonDeletedElements ` method from `Scene` to `binding.ts` (was too specific)
=> fix: eraser removed deleted elements

src/components/App.tsx
Playing around with the wheel zoom normalization to try and get it to behave nicely on trackpads.
It seems the go-to logic for getting some kinds of normalization between different browsers / devices is some hand-me-down facebook code. https://github.com/basilfx/normalize-wheel
I've tried this in firefox and chrome with both a mouse wheel and trackpad, and it seems to behave fine.
The only thing that could be slightly better is the velocity when very zoomed in, currently it moves at bit fast. Would just be a question of tweaking the maths a little..
https://www.loom.com/share/dff08cfe53d04719bcf7da624b4d6149
Fixes #4385
I think the normalize-wheel repo is just a copy of what's on npm with types added? In that case it might be better to use the NPM version and just add the types locally?
=> fix: wheel zoom normalization

src/components/App.tsx
Current behaviour is quite erratic when zooming, with the selection rapidly showing and hiding.
This PR stops deselecting elements when zooming via wheel/trackpad (basically, anything except touchscreen pinch gestures).
=> fix: do not deselect when not zooming using touchscreen pinch

src/components/LibraryMenuItems.tsx
=> fix: Library load button does not work

src/components/App.tsx, src/element/textWysiwyg.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5300
https://user-images.githubusercontent.com/11256141/173784757-a59d6e42-f87d-46a6-aab6-b618c9b55afe.mp4
=> fix: bind text to correct container when nested

src/components/App.tsx, src/components/ColorPicker.tsx
fix https://github.com/excalidraw/excalidraw/issues/5314 
Stopped preventing cmd/ctrl-modified keydown events even in inputs, if they're not arrow keys. Not really a general fix (and who knows if it doesn't break some cases), for that we'll need to rewrite the keyboard handling.
An unrelated fix https://github.com/excalidraw/excalidraw/pull/5316/commits/68c7d789e6d0394eb4999f9afd344ad00dbcb865 for unsafe children access.
=> fix: non-letter shortcuts being swallowed by color picker

src/components/App.tsx
fixes regression from https://github.com/excalidraw/excalidraw/pull/5316
turns out (again?) that not bailing on using `cmd/ctrl`-modified keypresses within inputs is breaking too many things to easily catch. So let's go the other way and fix cases where specific app shortcuts don't work (and should) in inputs.
Later we'll move to a different way to handle shortcuts altogether.
=> fix: unable to use cmd/ctrl-delete/backspace in inputs

vercel.json
this might not work without setting up a dns redirect first (though I'm not sure how that would work either). Also don't think we can test this without deploying to prod first.
https://vercel.com/docs/project-configuration#project-configuration/redirects
https://vercel.com/support/articles/can-i-redirect-from-a-subdomain-to-a-subpath
=> feat: redirect vscode.excalidraw.com to vscode marketplace

src/components/App.tsx, src/renderer/index.ts, src/renderer/renderScene.ts, src/tests/contextmenu.test.tsx, src/tests/dragCreate.test.tsx, src/tests/move.test.tsx, src/tests/multiPointCreate.test.tsx, src/tests/regressionTests.test.tsx, src/tests/resize.test.tsx, src/tests/selection.test.tsx, src/utils.ts
fix https://github.com/excalidraw/excalidraw/issues/5385
The main scene render loop is now throttled to animation framerate. Trailing invocation is enabled to ensure that potentially significant calls are not lost, such as when selecting where we need to ensure the last render removing the box-selection is made.
May break things. I suppose we'll find out once we ship.
=> feat: throttle scene rendering to animation framerate

src/components/App.tsx
Regression introduced in https://github.com/excalidraw/excalidraw/pull/5426 which broke scrolling for host apps
=> fix: attach wheel event to exscalidraw container only

src/components/App.tsx, src/excalidraw-app/index.tsx, src/global.d.ts, src/renderer/renderScene.ts, src/tests/contextmenu.test.tsx, src/tests/dragCreate.test.tsx, src/tests/move.test.tsx, src/tests/multiPointCreate.test.tsx, src/tests/regressionTests.test.tsx, src/tests/resize.test.tsx, src/tests/selection.test.tsx
Check https://github.com/excalidraw/excalidraw/issues/5439 for details on the resize throttling issues.
And since the throttling seems pretty unstable still, we're putting it under a flag for now.
=> fix: disable render throttling by default & during resize

src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5458
https://user-images.githubusercontent.com/11256141/179467759-bfd03de4-a3b2-4e97-84bf-56d79f7962c3.mp4
Looked into different heuristics eg checking `event.deltaY` to fix this but `browser` setting `ctrl` event to true when pinch zooming is interesting, got to know about this when looking into how Miro code of preventing pinch zoom but still allow scrolling :p.
This works well, lemme know if you find any issues when testing it out.
=> fix: check for ctrl key when wheel event triggered to only disable zooming

src/components/ImageExportDialog.tsx
Hi,
I found a missing translation for the word "Scale" in the export dialog.
I have reused the "button.scale" entry. Is it right for you?
Or it's better to create a new entry?
=> fix: missing translation for "Scale" to Export Dialog

src/components/Modal.tsx
Error
Due to this types couldn't be generated and hence package couldn't be [released](https://github.com/excalidraw/excalidraw/runs/7462925431?check_suite_focus=true)
=> fix: Use React.FC as react-dom is not able to infer types of Modal

src/renderer/renderElement.ts
We've had freedraw render branches switched, where in editor we used a branch for export, and vice versa. This resulted in worse perf during editing (no canvas caching), and blurry freedraw shapes when exporting on higher scale.
=> fix: incorrectly rendering freedraw elements

src/components/PasteChartDialog.tsx
In React 18 the effects run twice mount -> unmount -> mount in strict mode (only for dev to cleanup any unsafe side effects and ensure [reusable state](https://github.com/reactwg/react-18/discussions/19) for future API's) hence due to this the charts was broken as mentioned in https://github.com/excalidraw/excalidraw/issues/5503 in dev mode only
Due to this the component was being unmounted even before `svg` generate leading to the error in dev mode. So I am cleaning up the children of the DOM node before appending the new child.
=> fix: useLayout effect cleanup in dev mode for charts

src/components/App.tsx
Since React 18 batches the states between event handlers - This was happening before as well but there was a minor difference for class Components -> You still can read values of previous state in class components as it use to render the updates synchronously which is not possible now with React 18 where it doesn't render until the next browser tick.
Due to this the line editor behaviour was breaking once you start adding points as we compare the current and previous values and in React 18 this comparison is not working as its not synchronous anymore and hence leads to continuously adding points once alt is pressed and excessive state updates of course as points get added (notice the logs in video)
https://user-images.githubusercontent.com/11256141/181766843-c56c85ba-af29-461d-b6f4-6f326a2 …
=> fix: use flushSync when moving line editor since we need to read previous value after setting state

scripts/prebuild.js
=> fix: resolve paths in prebuild.js script

src/element/dragElements.ts
fixes https://github.com/excalidraw/excalidraw/issues/5513
=> feat: cursor alignment when creating generic elements

src/components/App.tsx, src/element/index.ts, src/element/sizeHelpers.ts
1. work out the angle θ
2. find out which locked angle θ is closet to
3. express the locked angle line and the line through the point at cursor that is also perpendicular to the locked angle line
4. find out the perpendicular intersection
=> feat: cursor alignment when creating linear elements with shift pressed

src/element/dragElements.ts
Disabled aspect ration locking for box-selection. Other apps don't do it, and it fixes this regression we shipped recently:
=> fix: disable locking aspect ratio for box-selection

src/scene/Scene.ts
fix https://github.com/excalidraw/excalidraw/issues/5541
When caching elements for later Scene lookup, we were mapping `Scene -> ExcalidrawElement` only, but we also have `Scene -> ExcalidrawElementId` when we need to lookup by id alone.
This PR makes sure we populate both maps when caching.
=> fix: Scene lookup failing when looking up by id

src/element/bounds.ts, src/element/resizeElements.ts, src/packages/excalidraw/CHANGELOG.md, src/points.ts
fix https://github.com/excalidraw/excalidraw/issues/3989 fix https://github.com/excalidraw/excalidraw/issues/4001 fix https://github.com/excalidraw/excalidraw/issues/2896
Hi! This is my first attempt making a meaningful oss contribution, feedback would be appreciated.
I was trying to fix #4009 and ended up rewriting the whole `resizeMultipleElements` function 😅. Now it updates selected elements based on their state at resize start. I manually tested it with:
- generic & text elements
- attached linear elements
- rotated
- with bound text inside
There's an issue with resizing multiple linear & free draw elements, but I think this is existing problem and I didn't cause it:
<details><summary>gif</summary>
</details>
Currently a selection doesn't flip, maybe will add this in the futute.
So …
=> fix: resize multiple elements from center

src/packages/excalidraw/README.md
I believe this type for theme should be THEME.LIGHT | THEME.DARK
It's currently this:
=> docs: correct readme type typo

src/components/App.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5577
=> fix: deselect linear element when clicked inside bounding box outside editor

src/element/bounds.ts, src/element/newElement.ts, src/element/resizeElements.ts, src/points.ts
#5560 stopped normalizing points on resize which introduced a buggy behavior such as the one shown below. This PR "fixes" it by reintroducing the normalization when resizing single elements. For multiple elements it shouldn't be needed as we don't yet allow resizing to the negative.
/cc @alex-kim-dev 
```
{"type":"excalidraw/clipboard","elements":[{"type":"freedraw","version":2875,"versionNonce":879128633,"isDeleted":false,"id":"Pjd86HppQGL0FhjcFqNPl","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":921.6778895758034,"y":476.80697591987155,"strokeColor":"#5c940d","backgroundColor":"#fa5252","width":45.86902273164816,"height":46.94255062652051,"seed":146528458,"groupIds":[],"strokeSharpness":"round","boundElements":[],"updated":1660677471 …
```
=> fix: points not being normalized on single-elem resize

src/components/LayerUI.tsx, src/components/MobileMenu.tsx, src/components/Stats.tsx, src/excalidraw-app/CustomStats.tsx, src/excalidraw-app/index.tsx
=> refactor: Stats component

src/element/bounds.ts
=> fix: add random tiny offsets to avoid linear elements from being clipped

src/element/bounds.ts
closes #5617 
When we have two consecutive points lined up vertically, rough.js has the two control points lined up vertically as well. This means that in `solveQuadratic`, we would have `a = 0`, which makes the calculation of `t1` and `t2` undefined, leading to `[s1, s2] = [null, null]`, which then leads to `getCubicBezierCurveBound` taking the max of starting and ending points' `x` as the max `x` bound, resulting in clipping as shown in #5585. 
Since we're trying to solve the derivative of the cubic bezier curve, which is a quadratic equation, when `a = 0`, we are really just solving a linear equation. The adjustment in `solveQuadratic` does exactly this.
=> fix: improve solveQuadratic when a = 0

src/components/LayerUI.tsx
Introduced as a regression in https://github.com/excalidraw/excalidraw/pull/5611
=> fix: don't render library menu twice for mobile

.codesandbox/tasks.json, README.md
Hello team!
In this PR I update the link for contributing to CodeSandbox to the new version of CodeSandbox. This is a more smooth experience, and should also work faster and more consistently with the local environment. I've also added a configuration so it works more smooth when you link to https://codesandbox.io/p/github/excalidraw/excalidraw/master.
Also, if you're interested you could install the GitHub App, this would ensure that every PR also has a running dev environment you can open to review like we have here:
(For this PR for instance, it would link to https://codesandbox.io/p/github/excalidraw/excalidraw/csb-1zdutz/draft/cold-sun)
=> chore: update CodeSandbox links and add a config

src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README.md, src/packages/utils.ts
Setting the expoertPadding is possible using `exportToSVG()` but not with `exportToBlob()` and `exportToCanvas()`. This change adds the optional exportPadding input variable to the latter two.
=> feat: added exportPadding to PNG (blob) export in @excalidraw/utils

src/excalidraw-app/index.tsx
- ❌ prevent newly initialized state to override theme preferences.
- 🔧 fix for [#5622](https://github.com/excalidraw/excalidraw/issues/5622)
=> fix: #5622 - prevent session theme reset during collaboration

src/components/MobileMenu.tsx
Buttons jump around because the eraser is rendered as an extra button if no element is selected. When elements are selected 6 buttons are rendered (no eraser), but when no element is selected, then 7 buttons (or their empty place) are rendered, resulting in the jumping.
The eraser is mutually exclusive with the finalize or duplicateSelection button. If these 3 buttons are displayed in the same spot depending on scene state, then buttons will stay in place.
Checking viewModeEnabled for the eraser is superfluous because a different app-toolbar-content is returned by renderAppToolbar if viewModeEnabled. Thus I recommend removing this condition from showEraser. 
Before the fix:
https://user-images.githubusercontent.com/14358394/188264037-35217cf3-2644-4aa6-b5c4-152df0e5d3ae.mp4
After the fix: …
=> fix: buttons jump around on the mobile menu

src/actions/manager.tsx, src/components/App.tsx, src/components/BackgroundPickerAndDarkModeToggle.tsx, src/components/InitializeApp.tsx, src/components/LayerUI.tsx, src/components/LoadingMessage.tsx, src/components/MobileMenu.tsx, src/constants.ts, src/css/app.scss, src/excalidraw-app/app_constants.ts, src/excalidraw-app/index.tsx, src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/README.md, src/packages/excalidraw/index.tsx, src/tests/packages/excalidraw.test.tsx, src/types.ts
- 🔧 fixed loading screen and default theme always set to light
resulting in white screen splash before switching to dark mode
<hr />
the explanation below assumes the case when the user has previously selected `dark` theme and its value is stored in the local storage. But the changes are compatible with both themes.
- app loads and shows the white loading screen `<LoadingMessage />` while the language is being set (the app is being initialized - `initializeApp.ts`).
- the canvas renders with the default app state assuming the theme to be `light`.
- the app state from local storage resolved [`initialData`] prop and the theme is then set to `dark` as previously set by the user.
Splash of white screen
👇
https://www.loom.com/share/6ac6615a26a44125b8b04080f20936bf …
=> fix: default light theme splash 🔧

public/index.html, src/css/app.scss, src/excalidraw-app/index.tsx
follow-up to https://github.com/excalidraw/excalidraw/pull/5660. Turns out there is still several frames before we render the init container (message) that sets the dark mode.
This PR tries to set basic dark theme as soon as we possibly can (I think). Still doesn't fix it 100% (when accessing excalidraw from a new tab), but let's as close as we can!
Not much of a difference on Chrome, but on Safari during reloading the tab it does.
/cc @mabdullahadeel @ad1992
=> feat: further reduce darkmode init flash

src/components/App.tsx
See #5703 for details
This solution feels like a sticking plaster. I do not have the patience to dig deeper to understand why this
https://github.com/excalidraw/excalidraw/blob/9cccac1458c8ff6b79452305cbbed7032522f18b/src/components/App.tsx#L1150-L1158
is called twice, but if I abort the second time, the issue is resolved.
=> fix: double state update incorrectly resetting state

src/constants.ts, src/data/restore.ts, src/excalidraw-app/collab/Portal.tsx, src/excalidraw-app/collab/reconciliation.ts, src/tests/reconciliation.test.ts
This bug causes invalid reconciliation during collaboration.
Here is a demo with buggy behavior:
https://user-images.githubusercontent.com/3718145/194401588-33aae198-546a-4867-840f-9fb7b5eb9ab5.mov
=> fix: restoreElementWithProperties drops "parent" property

package.json, yarn.lock
#5717
As mentioned by @YIRU69 the bug still exist in excalidraw, this is due to the usage of version of [steveruizok/perfect-freehand](https://github.com/steveruizok/perfect-freehand) that still has the bug.
Upgrading to 1.2.0 make things better 🧙‍♀️, however, seems like if there still exist some cases when the dot appear.
=> fix: update perfect freehand library to fix extra dot

src/constants.ts
I've received various requests for image formats, most recently a request to support webp [#820](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/820).
This seems like a no-brainer simple change. I don't see any downside. I've tested with sample files and it seems to work as expected.
=> feat: additional drag and drop image format support (webp, bmp, ico)

src/actions/actionFlip.ts, src/tests/flip.test.tsx
Fixed #5750 freedraw flip by correctly calculating transform handle final point, to avoid scaling issues
=> fix: free draw flip not scaling correctly

src/element/bounds.test.ts, src/element/bounds.ts, src/element/resizeElements.ts
=> fix: multiple elements resizing regressions

src/actions/actionCanvas.tsx, src/components/App.tsx, src/constants.ts, src/scene/zoom.ts
I changed ZOOM_STEP in Obsidian to 0.05 only to find a few unintended consequences and inconsistent behaviors:
- ZOOM_STEP was honored when using the `+` & `-` buttons, but not using CTRL+Wheel
- ZOOM_STEP changed the minimum zoom level used when ZoomToFitElements (Shift+1). This results in inconsistent behavior because zoom to fit can decrease the zoom to 5% but using the zoom controls one can only get to 10%. More importantly, this had a weird side effect in that a phantom copy of the drawing appeared on the canvas when there were many elements and the zoom level was below 10% [#850](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/850).
I couldn't figure out the root cause of the phantom duplicate, but introducing MIN_ZOOM and consistent use of ZOOM_STEP solved my issues …
=> fix: consistent use of ZOOM_STEP

src/actions/shortcuts.ts
Exactly what it sounds like - the word `shift` was missing a letter.
=> fix: Corrected typo in toggle theme shortcut

src/actions/actionDeleteSelected.tsx
When deleting the last point and confirming, it correctly deletes the line element since 1-point lines do not make sense. But, there's a bug where it syncs the 1-line element to remote clients, because we were removing it from the array altogether instead marking it as `isDeleted`.
=> fix: syncing 1-point lines to remote clients

src/renderer/renderScene.ts, src/tests/linearElementEditor.test.tsx
fixes:
The addedd test case doesn't test for this case (which would need a image-comparison test), but it's a regression test for this general case.
=> fix: line editor points rendering below elements

src/components/App.tsx, src/excalidraw-app/data/FileManager.ts, src/excalidraw-app/data/LocalData.ts, src/excalidraw-app/data/firebase.ts, src/packages/excalidraw/example/App.tsx, src/tests/export.test.tsx, src/types.ts
The exact case is not fully known, but there is a potential race condition where the locally stored images are removed from storage as unused, even though they actually are being used. There were reports around tab syncing / collab.
This PR makes it so that "unused" images are only cleared after 24hrs. For this purpose we set up a new flag `lastRetrieved` which we update on each retrieval from storage, and save it back.
@ad1992 thinking of factoring out the `lastRetrieved` attribute into host app (but the types may be annoying) since it has no editor behavior on its own. We can decide later. Merging for now to get this into prod.
=> feat: clean unused images only after 24hrs (local-only)

src/components/Actions.tsx, src/components/App.tsx, src/components/HelpDialog.tsx, src/components/LibraryButton.tsx, src/keys.ts, src/shapes.tsx, src/tests/__snapshots__/regressionTests.test.tsx.snap, src/tests/regressionTests.test.tsx
- freedraw: remove `X` shortcut, and change `Shift-P` to `P`. While `Shift-P` for freedraw is used in vector editors (where `P` is used for the vector pen tool), for low-precision, freedraw editors like Excalidraw it makes more sense to use just the `P` shortcut.
- remove `0` shortcut for toggling the library, as there would now be conflict with the eraser tool
Still unsure of showing the letter labels instead of numbers in the toolbar, so kept as is.
=> feat: tweak toolbar shortcuts & remove library shortcut

src/shapes.tsx
reintroducing the `x` shortcut for freedraw because it [breaks people's workflows](https://github.com/excalidraw/excalidraw/pull/5832#issuecomment-1304899745). Keeping it as undocumented so we don't onboard new users on it.
=> feat: reintroduce `x` shortcut for `freedraw`

.dockerignore
* this fixes the issue where Browse Libraries button link was broken in docker/self-hosted versions of excalidraw
Fixes #5802 and fixes #5662
=> build: stops ignoring .env files from docker context so env variables get set during react app build.

src/element/newElement.ts, src/element/textElement.ts, src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5834
https://user-images.githubusercontent.com/11256141/200546741-49962628-679b-4306-b51c-90192ebf712f.mov
=> fix: compute dimensions of container correctly when text pasted on container

.env.development
Submitted an issue https://github.com/facebook/create-react-app/issues/12843 but disabling "FAST_REFRESH" fixes the live reload which broke recently
=> fix: disable FAST_REFRESH to fix live reload

src/clipboard.test.ts, src/clipboard.ts, src/element/textWysiwyg.test.tsx
Fixes #5867.  Clipboard contents parsed as `number` types did not throw an exception, thus an empty `appClipboardData` was being returned.
=> fix: Correctly paste contents parsed by `JSON.parse()` as text.

src/components/App.tsx, src/components/LibraryUnit.tsx, src/components/PasteChartDialog.tsx, src/scene/Scene.ts, src/scene/export.ts, src/tests/__snapshots__/export.test.tsx.snap, src/tests/scene/__snapshots__/export.test.ts.snap
When we render elements as SVG, we render a `<style>` with font faces (Virgil, Cascadia...) which, upon adding the SVG to DOM, results in the the font `loadingdone` event firing again. On this event we then recalculate font dimensions and update the state, which, in some cases can result in a loop (case: library item previews).
This is a hotfix. We'll want to come up with a better flow for this, and potentially safeguard against `loadingdone` event firing for duplicate fonts.
=> fix: stop font `loadingdone` loop when rendering element SVGs

package.json, yarn.lock
None of the breaking changes should be affecting us: https://github.com/facebook/create-react-app/releases/tag/v5.0.0
This enables node >= v17
=> chore: bump create-react-app to 5.0.1 (from 4.0.3)

src/components/App.tsx, src/global.d.ts, src/scene/Fonts.ts
On some browsers (Safari, though we may have reports from some mobile Chromium browsers as well), the [FontFaceSet `loadingdone`](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/loadingdone_event) is not being fired, which results in the fonts not being rendered correctly on init until after all text shapes are invalidated (which may be never unless manually edited).
- This PR fixes that by manually loading fonts for existing text elements on init.
- On top of that, we're now checking if the font has not been already loaded so that we don't invalidate elements and rerender the scene unnecessarily (fixes a potential infinite loop https://github.com/excalidraw/excalidraw/pull/5883).
=> fix: fonts not rendered on init if `loadingdone` not fired

src/components/App.tsx, src/element/textElement.ts, src/element/textWysiwyg.test.tsx, src/scene/Scene.ts, src/scene/comparisons.ts, src/scene/index.ts, src/tests/elementLocking.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/5860
=> fix: Always bind to container selected by user

src/element/newElement.ts, src/element/textWysiwyg.test.tsx
https://github.com/excalidraw/excalidraw/pull/5938 actually broke history, because we're resetting the `boundElements` on the wrong level. Instead of resetting in the `deepCopyElement()` (which should always clone verbatim, where applicable), we should be doing it in `duplicateElement()`.
=> fix: bindings do not survive history serialization

src/element/types.ts
I found this while merging `excalidraw:master` into #2993.
=> fix: `ExcalidrawArrowElement` rather than `ExcalidrawArrowEleement`

scripts/locales-coverage-description.js
I was digging through the files and this caught my eye.
Sorry if it's not supposed to be updated manually.
=> fix: Galego and Kurdî missing in languages plus two locale typos

src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx
fix https://github.com/excalidraw/excalidraw/issues/5848
context: PR https://github.com/excalidraw/excalidraw/pull/5845 that was fixing https://github.com/excalidraw/excalidraw/issues/5834 ended up breaking native paste behavior, and instead of reimplementing it, we decided to fix the original issue in other ways.
=> fix: remove editor onpaste handler

src/actions/actionStyles.ts, src/element/typeChecks.ts
Since diamonds only use proportional radius for now, we shouldn't copy adaptive radius from rectangles to diamonds, which unfortunately it does in production at the moment. 
While we don't wanna copy adaptive radius roundness from rectangles to diamonds, we do want the target diamonds to be rounded if styles are copied from a rounded rectangle.
So, what we are doing in this fix is to first check if the given source roundness type can be applied to the target element. If not, we provide a default roundness for the target element, so that the target element is rounded also.
=> fix: apply the right type of roundness when pasting styles

src/components/Avatar.scss, src/components/UserList.scss
- fix outline on Safari:
(below, before fix)
- center vertically:
(below, fixed)
=> fix: Avatar outline on safari & center

src/element/resizeElements.ts
fix https://github.com/excalidraw/excalidraw/issues/6009
Not quite fully fixed. We have a race condition in resizing where the resize handler holds onto an object that's no longer in the Scene elements array by the time it tries to retrieve the scene using the element.
But, it turns out this bug is not really an edge case and affects any sticky notes that are part of a group. As such it affects large swathes of libraries and user shapes, so we need to fix this asap.
This fix also seems to not exhibit and UX issues. That said, we need to figure out the root cause and fix it properly.
Also, how many times have we been burned by doing unnecessary type assertions? Let's stop doing that unless we're 99% certain it's safe. /cc @ad1992
=> fix: resize sometimes throwing on missing null-checks

src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/6007 (or at least it addresses the UX issue communicating the action improperly through the wrong cursor)
=> fix: showing `grabbing` cursor when holding `spacebar`

src/components/ColorPicker.tsx
I encountered a strange error in the Obsidian Electron browser.
A six-digit hex color string e.g. "ba5f36" was recognized as a valid color by `isValidColor` even though it did not have a leading `#`. In debugger `style.color` had a valid value. As such `getColor` returned the six-digit value without leading `#`, however, the excalidraw canvas did not recognize the value as a color and the resulting stroke color was black.
By switching the sequence of testing in getColor, and first testing for ```isValidColor(`#${color}`)``` a correct color is returned even in the Electron browser, without impacting the original logic of the getColor function.
```typescript
const isValidColor = (color: string) => {
const style = new Option().style;
style.color = color;
return !!style.color;
};
const …
```
=> fix: ColorPicker getColor

src/element/textElement.test.ts, src/element/textElement.ts, src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx, src/tests/data/__snapshots__/restore.test.ts.snap, src/tests/linearElementEditor.test.tsx
A bug got introduced in https://github.com/excalidraw/excalidraw/pull/5996 when adding text to arrows
Before
Now
Pending tasks for next PR
1. open https://excalidraw-hzs43vab7-excalidraw.vercel.app/#json=V8IuuHiLiBN8Tz78LfHFV,O5phO7_M7NSG3kFPpGDZgA
2. edit
3. select all
4. delete
5. undo
=> fix: use canvas measureText to calculate width in measureText

src/element/textWysiwyg.tsx, src/tests/__snapshots__/linearElementEditor.test.tsx.snap, src/tests/linearElementEditor.test.tsx
fix https://github.com/excalidraw/excalidraw/issues/6032
=> fix: remove background from wysiwyg when editing arrow label

src/utils.ts
Got introduced when `displayName` was changed to `name` in https://github.com/excalidraw/excalidraw/pull/5970
Before
Now
=> fix: use displayName since name gets stripped off when uglifying/minifiyng in production

src/components/HelpDialog.tsx
The help menu shortcuts weren't updated: i.e., it currently says "Shift + P" for pencil, and 'p' for line when it's actually lowercase 'L' for line and lowercase 'P' for pencil.
=> fix: HelpDialog

src/components/LayerUI.tsx, src/packages/excalidraw/index.tsx, src/utils.ts
In LayerUI we were not considering `props.children` and other props. Rewritten to simplify and safeproof against (most) regressions.
=> fix: React.memo resolvers not accounting for all props

src/components/Button.scss, src/components/Button.tsx, src/components/CollabButton.scss, src/components/CollabButton.tsx, src/components/dropdownMenu/DropdownMenu.scss, src/css/styles.scss, src/css/theme.scss, src/css/variables.module.scss, src/packages/excalidraw/example/CustomFooter.tsx, src/packages/excalidraw/index.tsx
The motivation for this PR is that host applications have had to resort to manually implementing/mimicking Excalidraw's button styling if they wanted to stay visually consistent when implementing custom buttons. This PR exports a generic button component that follows Excalidraw's design system. Usage is really quite straightforward but an example has been added in the examples section as well. If we need anything else here, please add your feedback below.
=> feat: generic button export

src/components/Button.scss
Introduced in https://github.com/excalidraw/excalidraw/pull/6092 which was breaking collaborator count.
Before
Now
=> fix: remove overflow hidden from button

.husky/pre-commit
fix https://github.com/excalidraw/excalidraw/issues/6094
Until we fix the eslint CLIEngine issue. What's also on the table is removing precommit hooks altogether.
=> build: temporarily disable pre-commit

src/actions/actionHistory.tsx, src/actions/actionZindex.tsx, src/actions/shortcuts.ts, src/clipboard.ts, src/components/App.tsx, src/components/HelpDialog.tsx, src/components/ImageExportDialog.tsx, src/constants.ts, src/data/index.ts, src/keys.ts, src/locales/en.json, src/utils.ts
fix #6118
On firefox, the `clipboard.write()` API is enabled either in the context of a user action, or when a flag is enabled. We might fall under the former category, but we also rely on `ClipboardItem` API which works _only_ under a flag.
This PR enables the copy-as-png button in the export dialog despite it not working by default on Firefox, and if it inevitable throws, the error message will contain steps to enable it:
This way Firefox users will at least be aware that the functionality exists and will be able to do something if they want it.
Suggested by @orlp
=> feat: show copy-as-png export button on firefox and show steps how to enable it

src/css/variables.module.scss
- svg size doesn't work on safari
- bg fallback fix:
before:
after:
=> fix: button background and svg sizes

public/index.html, src/css/styles.scss
Introduced in [editor redesign](https://github.com/excalidraw/excalidraw/pull/5780/files)
Will do a patch release post merge
=> fix: declare css variable for font in excalidraw so its available in host

src/element/textElement.test.ts, src/element/textElement.ts, src/element/textWysiwyg.tsx
Try adding a a letter in https://excalidraw.com/#json=8aAL_CLsjuwOKV4zLrCN0,p5reRLoF7GtLfj3etsol9g, it will add a new line in prod.
=> fix: set the width correctly using measureText in editor

Dockerfile
I'm building a docker image on an Oracle ARM A1 instance that supports multiple system architectures, it includes linux/arm64/v8, linux/arm/v7, linux/arm/v6, linux/amd64, when build linux/amd64 image a error will occur causing the build to break.
```bash
$ sudo docker buildx build -t dejavumoe/excalidraw:master --platform=linux/arm/v7,linux/arm64,linux/arm/v6,linux/amd64 .
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
[+] Building 444.6s (42/45)
=> [internal] load build definition from Dockerfile                                                                                                     0.0s
=> => transferring dockerfile: 361B …
```
=> fix: docker build architecture:linux/amd64 error occur on linux/arm64 instance

src/components/App.tsx, src/element/newElement.ts, src/element/resizeElements.ts, src/element/textElement.test.ts, src/element/textElement.ts, src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx, src/tests/linearElementEditor.test.tsx
Currently Stacked on top of https://github.com/excalidraw/excalidraw/pull/6172
Partially fixes https://github.com/excalidraw/excalidraw/issues/5671
Since the rhombus has 4 sides equal, the largest rectangle will be formed by joining the midpoints of each side of the rhombus and the rectangle sides will be parallel to the diagonals of a rhombus.
The dimensions of the rectangle will be 
```
width = rhombus.width/2 - BOUND_TEXT_PADDING *2
height = rhombus.height/2 -  BOUND_TEXT_PADDING *2
```
https://user-images.githubusercontent.com/11256141/220093480-29dc129d-67e5-47ed-b36c-b4e775750f6c.mp4
=> fix: improve text wrapping inside rhombus and more fixes

src/element/textWysiwyg.tsx
ref: Japanese text input with tab key doesn't work properly #6218
Enter Japanese and press the tab key.
When the tab key is pressed and auto correct by the IME is performed, the word entered remains and the input result is [the word entered] + [the auto correct word].
- ~~This phenomenon seemed to occur when the outdent or indent method was executed, so I changed it so that the outdent or indent method is not executed if the current language code is "ja-JP"
I don't think it is necessary to adjust indentation with tabs for Japanese input IMO.~~
- check event.isComposing and if it is true, it will not adjust indentation.
=> fix: indenting via `tab` clashing with IME compositor

src/element/textElement.test.ts, src/element/textElement.ts, src/tests/clipboard.test.tsx
Pasting an older version of element (Rhombus and Ellipse) before text wrapping was fixed led to one extra edit to fix.
Try pasting below in the prod vs this PR. It was due to height being incorrectly computed (padding wasn't considered hence the extra edit).
```
{"type":"excalidraw/clipboard","elements":[{"id":"zrR8vTKGuH_E7uEOkF2pF","type":"ellipse","x":555.23046875,"y":196.0234375,"width":166,"height":187.01953125,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"roundness":{"type":2},"seed":733356165,"version":38,"versionNonce":1100933963,"isDeleted":false,"boundElements":[{"type":"text","id":"6_ZlMG6ID0xNDNkjanOuw"}],"updated":1677139260395,"link":null,"locked":false}, …
```
=> fix: compute container height from bound text correctly

src/components/App.tsx, src/element/typeChecks.test.ts, src/element/typeChecks.ts
Unfortunately, till now we were not checking `arrow` when using the function `hasBoundTextElement` due to which some of the functionalities were not working for the arrow as mentioned below
* If the arrow has a label then clicking on the arrow using the text tool should go to the label similar to other bound containers
* The link icon was not being shown for the arrow
*  `copyStyles` was not considering the label styles
*  `unibind text` was not being shown in context menu for arrow labels
https://user-images.githubusercontent.com/11256141/221875837-d1a31e86-a243-4c86-a4ff-702c19dbc026.mov
=> fix: consider arrow for bound text element

src/components/ActiveConfirmDialog.tsx, src/components/LibraryMenuHeaderContent.tsx, src/tests/shortcuts.test.tsx
fixes a regression where imperatively updating these atoms no longer workeds
=> fix: use jotai scope for editor-specific atoms

src/element/resizeElements.ts
fixes https://github.com/excalidraw/excalidraw/issues/6306
=> fix: compute bounding box correctly for text element when multiple element resizing

src/actions/actionBoundText.tsx, src/actions/types.ts, src/components/App.tsx, src/element/textElement.test.ts, src/element/textElement.ts, src/element/textWysiwyg.test.tsx, src/global.d.ts, src/locales/en.json, src/tests/__snapshots__/contextmenu.test.tsx.snap
closes https://github.com/excalidraw/excalidraw/issues/5670
https://user-images.githubusercontent.com/11256141/222403703-6bc4f5b2-826f-43ce-a683-41823e7f43c8.mp4
eg max width of container = 100
The text is "Hello world there"
Width of world + there = 100 still it will split it was splitting it to `Hello\nWorld\nthere`
=> feat: create bound container from text

src/components/HelpButton.tsx, src/components/footer/Footer.tsx
Before:
After:
`helpDialog.title` locale attribute seemed to be used when the word "Help" was used, so I didn't create a new attribute.
=> fix: provide HelpButton title prop

src/components/ConfirmDialog.tsx, src/components/Dialog.tsx, src/components/main-menu/DefaultItems.tsx
fix https://github.com/excalidraw/excalidraw/issues/6312
I forgot we also use `useSetAtom` and `useAtomValue` which I didn't account for in the previous PR https://github.com/excalidraw/excalidraw/pull/6308
=> fix: more jotai scopes missing

src/element/textWysiwyg.tsx, src/tests/__snapshots__/linearElementEditor.test.tsx.snap
An attempt to fix https://github.com/excalidraw/excalidraw/issues/6318
In chrome, the below test case breaks due to diff in measurements of canvas vs DOM hence I am adding `0.5px` to the text editor irrespective of the browser
```
{"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":330,"versionNonce":2052614281,"isDeleted":false,"id":"31vXnfdx8kajVSVVIfvCP","fillStyle":"hachure","strokeWidth":4,"strokeStyle":"solid","roughness":2,"opacity":100,"angle":0,"x":565.0773024358487,"y":797.405287044643,"strokeColor":"#c92a2a","backgroundColor":"transparent","width":416.63022605391654,"height":326.8,"seed":317114057,"groupIds":[],"roundness":{"type":3},"boundElements":[{"type":"text","id":"Tw9ge3wKmBk2-lojWy5Ps"}],"updated":1678186715202,"link":null,"locked":false},{"type":"te …
```
=> fix: add an offset of 0.5px for text editor in containers

src/data/blob.ts, src/excalidraw-app/data/index.ts
try opening https://excalidraw-git-aakansha-refresh-dims-on-json-load-excalidraw.vercel.app/#json=-DV4Cph-GwtrlhYpHZ-d5,Mq55Gk1Z99mCPwtNPEPrLQ vs in prod with same keys
When loaded from `LS` its not needed since `onFontLoad` takes care of it.
=> fix: refresh dimensions when elements loaded from shareable link and blob

src/element/textElement.test.ts, src/element/textElement.ts
`wrapText` now has 100% coverage
=> perf: break early if the line width <= max width of the container

src/actions/actionProperties.tsx, src/components/Actions.tsx, src/element/textElement.ts, src/tests/linearElementEditor.test.tsx
`Text align` is not really useful for labelled arrows hence I am proposing to hide it instead.
fixes #6316
=> fix: hide text align for labelled arrows

src/element/collision.ts, src/element/textElement.test.ts, src/element/textElement.ts
[#1054](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1054) 
I was not able to reproduce the issue with the same file on Excalidraw.com, but that is likely because the issue was triggered by the Obsidian plugin updating container sizes while loading a drawing. The container size update is there because text transclusions might change the length of text in container-bound text elements. In this drawing, an arrow was pointing from a rectangle to an ellipse and the arrow had a label. All the stars were aligned and Excalidraw froze...
The user had the gird enabled, therefore coordinates of the ellipse and arrow were all round numbers. When the rectangle gets resized during the Obsidian load process, this triggers an update of all its bound elements, including the arrow, which …
=> fix: division by zero in findFocusPointForEllipse leads to infinite loop in wrapText freezing Excalidraw

src/data/index.ts
fix https://github.com/excalidraw/excalidraw/issues/6349
Saving with compound file extensions completely crashes Chrome 111.0.5563.64 (arm64).
Already fixed in 111.0.5563.65, but it doesn't seem to be shipped on arm platform yet (or the autoupdate doesn't update at least). Tracking bug https://bugs.chromium.org/p/chromium/issues/detail?id=1426358&q=111.0.5563.64%20crash&can=2
=> fix: chrome crashing when embedding scene on chrome arm

src/renderer/renderElement.ts
this is a hack that only slightly improves https://github.com/excalidraw/excalidraw/issues/6380. Proper fix will have to be implemented through either reintroducing baseline, or reverting other parts of https://github.com/excalidraw/excalidraw/pull/6187 responsible for this regression
=> fix: use `ideographic` textBaseline to improve layout shift when editing text

src/renderer/renderElement.ts
Reverts excalidraw/excalidraw#6384
=> fix: Revert use `ideographic` textBaseline to improve layout shift when editing text"

src/element/textElement.test.ts, src/element/textElement.ts
fix: `getDefaultLineHeight` always returns a default
The reason why I want to fix the `getDefaultLineHeight`'s return value is that after syncing with the latest `origin/master`, my forked excalidraw with my custom fonts app lost all text elements XD.
After doing some research, I found the `lineHeight` of the custom fonts is missing. Therefore, I prefer that `getDefaultLineHeight` always returns a value.
BTW: I forked the **AMAZING** excalidraw and added some custom fonts which is implemented at my [branch](https://github.com/CoyoteWaltz/excalidraw/tree/feat-addFonts/src/fork_by_coyote).
ALSO I wonder if there exists an elegant way to extend custom fonts with **minimal changes** and **better adoption with upcoming upper stream features**.
Thanks!
=> fix: getDefaultLineHeight should return default font family line height for unknown font

src/element/textWysiwyg.tsx
https://user-images.githubusercontent.com/11256141/229852137-73ba75f4-1a66-4ba5-b57f-4a8409eb9930.mov
=> fix: don't jump text to end when out of viewport in safari

src/actions/actionBoundText.tsx
Closes #6418
Updated `actionCreateContainerFromText` action to take multiple text elements.
Iterated over each element and adding containers to them
https://user-images.githubusercontent.com/51131670/230577307-4a6a56af-94c1-4ec5-ac6a-9fa515fea2f7.mov
=> feat: add container to multiple text elements

README.md
I've noticed that the opening tag is `<h2>` but the closing tag is `</h3>`
=> docs: fix closing tag in readme (#6424

src/actions/actionBoundText.tsx, src/element/textWysiwyg.test.tsx, src/tests/binding.test.tsx
=> fix: center align text when bind to container via context menu

src/components/App.tsx
See also: [#1065](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1065) 
Placing a second finger on the canvas while drawing a freedraw shape results in a spike and the termination of the freedraw editing. Under normal conditions (i.e. drawing with your finger) this should not happen. This typically happens when using a pen, clicking the pen tool for the first time, and touching the canvas with your palm before touching it with the pen. In this scenario penMode does not activate before receiving the multi-touch input, resulting in the unwanted line.
The easiest way to simulate this situation is by touching the freedraw tool (i.e. not in penMode), then touching the canvas with one finger, and then, while the first finger stays on touching the canvas, touching the canvas with …
=> fix: abort freedraw line if second touch is detected

src/components/LibraryMenuItems.tsx
fix https://github.com/excalidraw/excalidraw/issues/6465
haven't written tests for this because it'd super hard to test this behavior (it happens at a level really hard to drill down into)
=> fix: library ids cross-contamination on multiple insert

src/components/App.tsx, src/data/restore.ts, src/element/newElement.ts, src/tests/__snapshots__/regressionTests.test.tsx.snap, src/tests/helpers/api.ts, src/tests/library.test.tsx
Pasting/inserting library currently breaks arrow bindings in some cases. Replaced the ad-hoc duplicating with our new `duplicateElements()` helper.
=> fix: incorrectly duplicating items on paste/library insert (#6467

src/renderer/renderElement.ts
fix https://github.com/excalidraw/excalidraw/issues/6472
=> fix: improperly cache-busting on canvas scale instead of zoom

src/components/ImageExportDialog.tsx, src/packages/utils.ts
partially addresses https://github.com/excalidraw/excalidraw/issues/5846
We're unnecessarily rendering the full canvas size when displaying the export preview. This PR limits the preview canvas size to that of the preview DOM size, which can massively improve performance for large canvases.
=> feat: constrain export dialog preview size

scripts/release.js, src/packages/excalidraw/CHANGELOG.md
Since the note for unstable readme is no longer there hence removing this script to update readme - due to this the package version `0.15.0` was released without any readme
=> fix: add readme back to npm package which was mistakenly removed

src/components/App.tsx, src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx
=> fix: rotate the text element when binding to a rotated container

src/components/App.tsx, src/constants.ts, src/data/blob.ts, src/data/filesystem.ts, src/types.ts
fix https://github.com/excalidraw/excalidraw/issues/6478
(the `bmp`/`ico` was already allowed through paste/drag&drop https://github.com/excalidraw/excalidraw/pull/5749, but not via file picker).
=> feat: allow `avif`, `jfif`, `webp`, `bmp`, `ico` image types (#6500

src/components/App.tsx, src/element/textWysiwyg.tsx
solves #6469
Seems for some reason Excalidraw registers an element drag - that is why the text jumps.  Debouncing the call to dragSelectedElement() when `this.state.editingElement` solves the problem.
=> fix: text jumps when editing on Android Chrome

src/data/blob.ts, src/excalidraw-app/data/index.ts, src/scene/Fonts.ts
To test  try opening [https://excalidraw-git-aakansha-no-refresh-text-containers-excalidraw.vercel.app/#json=Soy3LkNbWr9H9ghDWSUOY,8Bc7JZUTrT0p4SqOlZ-YzQ](https://excalidraw-git-aakansha-no-refresh-text-containers-excalidraw.vercel.app/#json=Soy3LkNbWr9H9ghDWSUOY,8Bc7JZUTrT0p4SqOlZ-YzQ) and reload - the diagrams should remain the same as it was before unless you try to edit it
=> fix: don't refresh dimensions for text containers on font load

.github/workflows/publish-docker.yml
Reverts excalidraw/excalidraw#6508
The docker build is breaking hence reverting this PR. We will push it again once a proper fix is pushed and tested.
=> fix: Revert add version tags to Docker build

src/components/BraveMeasureTextError.tsx, src/components/Trans.test.tsx, src/components/Trans.tsx, src/components/__snapshots__/App.test.tsx.snap, src/locales/en.json
Fixes https://github.com/excalidraw/excalidraw/issues/6351
This is a proof of concept PR that shows a possible solution to #6351 (this already works, you can quickly test it by applying the diff at the bottom and removing `if (isBrave() && !isMeasureTextSupported()) {` in `App.tsx`).
`Trans` component make it possible to use JSX for translations.
Examples:
```json
{
"example1": "Hello {{audience}}",
"example2": "Please <link>click the button</link> to continue.",
"example3": "Please <link>click {{location}}</link> to continue.",
"example4": "Please <link>click <bold>{{location}}</bold></link> to continue.",
}
```
```jsx
<Trans i18nKey="example1" audience="world" />
<Trans
i18nKey="example2"
connectLink={(el) => <a href="https://example.com">{el}</a>}
/>
<Trans
i18nKey="example3" …
```
=> feat: Add Trans component for interpolating JSX in translations

src/element/textWysiwyg.tsx
Fixes https://github.com/excalidraw/excalidraw/issues/6576, https://github.com/excalidraw/excalidraw/issues/5837
=> fix: assign the original text to text editor only during init

src/components/dropdownMenu/DropdownMenu.scss
Fixed: #6611
Issue: Dropdown items were not visible on mobile devices.
Before
After
Cause
Display flex for mobile devices was causing the issue.
=> fix: Library dropdown visibility issue for mobile

src/components/LibraryMenu.tsx, src/components/LibraryMenuItems.tsx, src/components/LibraryMenuSection.tsx, src/components/LibraryUnit.scss, src/components/LibraryUnit.tsx, src/components/Spinner.scss, src/components/Spinner.tsx, src/hooks/useLibraryItemSvg.ts
This is proof of concept of speeding up of rending of the Library and its content when it contains hundreds or thousands of items and what will be the performance of rendering them in batches (by row) rather than all in one go.
Currently, it doesn't handle any callbacks or edge cases, ale when there is more than one section; they are rendered in parallel (there is no actual added value in moving this into a separate component).
=> perf: improve rendering performance for Library

src/components/LibraryMenu.tsx, src/components/LibraryMenuItems.scss, src/components/LibraryMenuItems.tsx, src/components/LibraryMenuSection.tsx, src/components/LibraryUnit.scss, src/components/LibraryUnit.tsx, src/hooks/useLibraryItemSvg.ts
The Target of this PR is to minimize the number of unnecessary renders of the items in the library and the library itself.
There is an issue, when the user clicks on the canvas, a random item is added into `appState.selectedElementIds`. This will cause a new render of the personal part of the library (but items are memorized) and the first item with selected content (if there is any).
This may cause some conflicts when #6621 is merged.
=> perf: memoize rendering of library

src/components/ColorPicker/ColorPicker.tsx
fix #6595.
`updateData` was passed to `ColorPickerPopupContent` but never used anywhere and hence there the `appState.openPopup` is not reset.
Invoked `updateData` inside `onCloseAutoFocus` in `Popover.Content`.
=> fix: color picker input closing problem

src/element/newElement.ts, src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx
1. Removed all code related to updating `editor.style.width/editor.style.height` in `updateWysiwygStyle` as we are updating measurements in `updateTextElement` and that gets reflected on the text element as `updateWysiwygStyle`  due to `informMutation` when replacing scene elements
2. Removed all code related to updating container dimensions as thats not needed since we are updating container dimensions in `getAdjustedDimensions` which gets called due to `informMutation` after text element dimensions are updated.
3. using `computeBoundTextPosition` to update `y` coord as you type instead of having duplicate checks in `updateWysiwygStyle`
4. I had to update one test because there is one issue in test from the begining - when `updateWysiwygStyle` is triggered it doesn't have the `text` …
=> fix: cleanup textWysiwyg and getAdjustedDimensions

src/components/App.tsx, src/components/ColorPicker/ColorPicker.tsx, src/element/textWysiwyg.test.tsx, src/utils.ts
Confluence of factors resulted in creating text while color picker open not being possible.
The issues were:
1. refocusing editor container on color picker open. This was done _after_ entering the text editor which then blurred the `textarea`, terminating the wysiwyg... except:
2. there was (still is) a state update race condition where the color picker state update of `{ openPopup: null }` is updating with a stale appState state because the action's `updateData()` is using the original `appState` being passed to it on color picker open, and our action updates still set the complete state. The state appState was overriding the update on the wysiwyg close which is called before the color picker close (or more specifically, color picker focus change where we call the `updateData()`).
For …
=> fix: creating text while color picker open

src/renderer/renderScene.ts, src/renderer/roundRect.polyfill.ts
polyfill `CanvasRenderingContext2D.roundRect` & `Path2D.roundRect`. Via https://github.com/Kaiido/roundRect/tree/main, but rewritten to remove nullish coalescing assignment operator and `globalThis`.
=> feat: polyfill `CanvasRenderingContext2D.roundRect`

src/components/HelpDialog.tsx
Updated the link for documentation page under help section 
from - [https://github.com/excalidraw/excalidraw#documentation](https://github.com/excalidraw/excalidraw#documentation) 
to - [https://docs-excalidraw.vercel.app](https://docs-excalidraw.vercel.app) 
Issue - #6616
=> fix: updated link for documentation page under help section

src/components/App.tsx, src/element/textWysiwyg.test.tsx
When using text tool we don't switch to already bound text like we do when using "Enter" or "Double Click" unless trying to add a text to center of container.
Due to this what was happening is if a text container has a text which isn't aligned to center vertically and horizontally, then text tool tries to bind the text to the container
https://github.com/excalidraw/excalidraw/assets/11256141/f29f6735-d854-4efe-9770-78c4531953bb
=> fix: do not bind text to container using text tool when it has text already

src/components/App.tsx, src/css/styles.scss, src/css/theme.scss, src/renderer/renderScene.ts, src/scene/scrollbars.ts
we've had scrollbar rendering broken for quite some time. This PR fixes it. But, it also disables rendering of scrollbars by default because no one complained and it looks better without it.
That said, I kept the logic in place and we should expose the scrollbar rendering as public API later. https://github.com/excalidraw/excalidraw/issues/6707
=> fix: scrollbars renders but disable

src/data/restore.ts, src/frame.ts, src/zindex.ts
fix issue reported https://discord.com/channels/723672430744174682/723672430744174685/1121405542435409982
description:
- elements that are in a non-existing frame will be removed when other elements are moved
- as can be reproduced here https://excalidraw.com/#json=P2C3bNY_tUguLfBlA88Tf,xBgX6-gB3mWWGY7X4EsidA
root cause
- `removeElementsFromFrame` depends on `shift` in `zindex.ts`
- which assumes that if an element has `frameId`, the frame must be present
- when the frame is non-existent, then all elements with the `frameId` will not be removed whenever `shift` is called
TODOs:
=> fix: elements in non-existing frame getting removed

src/components/LayerUI.tsx
=> fix: UI disappears when pressing the eyedropper shortcut on mobile

src/components/App.tsx
fixing case where you override the `<DefaultSidebar/>` and force its `docked` state to `true`, it shouldn't close the sidebar on library insert.
=> fix: use actual dock state to not close docked library on insert

.github/workflows/size-limit.yml, src/components/main-menu/DefaultItems.tsx, src/packages/excalidraw/example/App.tsx, src/tests/packages/__snapshots__/excalidraw.test.tsx.snap, src/tests/packages/excalidraw.test.tsx
closes https://github.com/excalidraw/excalidraw/issues/6738
=> fix: don't show `canvasBackground` label when `UIOptions.canvasActions.changeViewBackgroundColor` is false

.github/workflows/semantic-pr-title.yml
Here is a nice article on how `pull_request_target` differs from `pull_request` https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
As per `semantic-pr-title` it shouldn't need a write permission hence changing to `pull_request`
=> fix: use pull request in semantic workflow for better security

src/components/App.tsx, src/tests/selection.test.tsx
fixes https://github.com/excalidraw/excalidraw/issues/6806, regression introduced in https://github.com/excalidraw/excalidraw/pull/6745 ([commit](https://github.com/excalidraw/excalidraw/pull/6745/files#diff-86963609bec6fda3d34233676d5ae33f6aa4b9bbe2758a10cd4863b704b37093)).
Not a great fix. That whole part needs to be rewritten to fix other cases (though not regressions).
=> fix: adding to selection via shift box-select

src/renderer/renderScene.ts
This PR turns moves calculation of the `offsetX` and `offsetY` inside the `strokeGrid` function. Also changes color of every 5th line to darker grey (`rgba(0, 0, 0, 0.4)`) to make grid clearer and more appealing (imho).
Darker lines are related to app coordinates and not to the users viewport, so they stay in the same position when user is moving across the scene. The position of the darker lines is calculated so that they meet at 0, 0.
Here is the screenshot:
=> feat: render bold lines in grid

src/element/embeddable.ts
Make it possible to embed vals in excalidraw drawings.
> Val Town is a social website to write and run code. 
> 
> You write JavaScript/TypeScript on our website and we run it on our servers. Create APIs, scheduled functions, email yourself, and persist small pieces of data — all from the browser and instantly deployed.
=> feat: add support for val.town embeds

src/packages/excalidraw/webpack.dev.config.js, src/packages/excalidraw/webpack.prod.config.js
I modified the exclude statement in `webpack.config` to work on Windows.
The rest of the changes are simply to align the order of declarations between .prod.js and .dev.js. These add nothing to functionality and only serve my OCD.
=> fix: webpack config exclude statement to system agnostic

dev-docs/docs/introduction/contributing.mdx
- add a note admonition that species tests that require aproval before they are run to the contributing documentation.
=> docs: add note for tests that have requisites

src/components/App.tsx
Enhancing #6262
Limiting the suggested  binding to fix performance issue, for now to 50
Root cause problem :  on selection of multiple shapes containing  arrows, on movement it starts comparing for binding with each arrows to shapes, leads to performance issue; which we here limit it to 50 
Fix : when more than 50 shapes selected we skip binding comparing
=> perf: Limiting the suggested binding to fix performance issue

src/element/bounds.ts, src/renderer/renderElement.ts, src/scene/Shape.ts, src/scene/ShapeCache.ts, src/scene/types.ts
Further cleanup of `renderElement.ts`.
- `generateElementShape` now returns the generated shape and doesn't handle any caching at all, which is moved solely to `ShapeCache`.
- `generateElementShape` is now more typesafe.
- related to the above, when rendering elements we retrieve the shape from `ShapeCache.generateElementShape` (hybrid cache getter / generator) instead of generating + retrieving from cache in two separate, type-unsafe steps.
- moved `generateElementShape` out of `renderElement.ts` (further refactor and decoupling TBD).
=> refactor: factor out shape generation from `renderElement.ts` pt 2

src/renderer/renderScene.ts
fixes #6934
I don't understand the intended purpose of 
```typescript
-Math.ceil(appState.zoom.value / appState.gridSize) * appState.gridSize +
(appState.scrollX % appState.gridSize),
-Math.ceil(appState.zoom.value / appState.gridSize) * appState.gridSize +
(appState.scrollY % appState.gridSize),
```
replacing it with code similar to code before #6759 seems to fix the issue
=> fix: grid jittery after partition PR

src/components/canvases/StaticCanvas.tsx
fix https://github.com/excalidraw/excalidraw/issues/6951
https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-set-bitmap-dimensions
=> fix: canvas flickering due to resetting canvas on skipped frames

src/element/textWysiwyg.test.tsx, src/element/textWysiwyg.tsx
=> fix: stale labeled arrow bounds cache after editing the label

src/components/App.tsx, src/frame.test.tsx, src/frame.ts, src/renderer/renderScene.ts
Fixed the re-ordering issues for "adding element/s to frame" by re-implementing the algorithm (introduced in #6123) to a more correct, resilient and performant version (also due to "downgrade" in #6904). Added number of test cases so these won't regress in the future, specifically for:
* Resizing frame over elements - all at once, one by one, with elements in between, with or without bounded element
* Dragging elements into the frame - all at once, one by one, with elements in between
* Resizing frame down - addition of elements followed by removal
* Duplicating an element inside the frame, while keeping it inside or dragging it outside the frame
* For most of the above, covered cases when the frame is in a bottom, middle or top layer
---
Addition/deletion in frames leads to weird z-index …
=> fix: z-index inconsistencies during addition / deletion in frames

src/components/ColorPicker/ColorInput.tsx, src/components/ColorPicker/ColorPicker.tsx, src/components/EyeDropper.scss, src/components/EyeDropper.tsx, src/css/styles.scss, src/types.ts
Tried to write a test for it, but we'd have to mock too many things including `getImageData`.
- fix eyeDropper not working due to its backdrop having lower z-index than interactive canvas https://github.com/excalidraw/excalidraw/pull/7002/commits/fd7382d0e8779c62b1e65d136e82d4ae4a1e7365
- potential fix for mobile (right now, tablets) so we always pick current color on click instead of relying on `pointermove` https://github.com/excalidraw/excalidraw/pull/7002/commits/22cca0aa8d69ad1d6544567a80af86dd333a10ee
- fix eyedropper preview picking incorrect color on alt when picking from color-picker (as opposed to `I`/`Shift-S`/`Shift-G`) https://github.com/excalidraw/excalidraw/pull/7002/commits/ffdff280b5bf4df8dbfbaa308f4e55ec2b6ed4db
=> fix: several eyeDropper fixes

src/actions/actionFlip.ts, src/tests/flip.test.tsx
Most likely a regression after #6789
=> fix: generic element's labels not flipping with them

src/components/App.tsx, src/components/ColorPicker/ColorInput.tsx, src/components/ColorPicker/ColorPicker.tsx, src/components/EyeDropper.tsx, src/components/LayerUI.tsx, src/hooks/useStable.ts
- fix canvas bg color picker not opening (regressed in [`ffdff28` (#7002)](https://github.com/excalidraw/excalidraw/pull/7002/commits/ffdff280b5bf4df8dbfbaa308f4e55ec2b6ed4db))
- fix not storing color changes to history when using shift-I/shift-G shortcuts
- fix not updating color in some cases when dragging pointer with eyedropper (bg left preview on purpose because it was too distracting)
- move updating element color for "preview" on drag up from `EyeDropper` to `LayerUI` (as prop) to make `EyeDropper` more dumb
=> fix: more eye-droper fixes

src/polyfill.ts
fix https://github.com/excalidraw/excalidraw/issues/7033
turns out `replaceChildren` is not yet that [widely supported](https://caniuse.com/?search=replaceChildren)
=> fix: polyfill `Element.replaceChildren`

src/frame.test.tsx, src/frame.ts
regressed in https://github.com/excalidraw/excalidraw/pull/6914
hotfix. Z-indexes again not retained correctly which the above PR was trying to fix, but at least we shouldn't be deleting/duplicating elements now. 
Proper fix soon.
No time for tests.
=> fix: elements being dropped/duplicated when added to frame

dev-docs/src/components/Homepage/index.js
I found a fairly prominent typo on the homepage of the developer docs and raised an issue about it.
Currently, the problematic sentence reads: "Want to build your own app powered by Excalidraw **by** don't know where to start?"
I have fixed it to say: ""Want to build your own app powered by Excalidraw **but** don't know where to start?"
Here is an image of the current state of the developer docs with the typo.
Here is the only line in the source code that I changed in order to solve the issue.
This is my first PR here and I'm eager to explore the codebase further! Thanks for maintaining this great piece of software, and please let me know if I failed to follow the contributing guidelines in any way.
=> docs: fix typo on homepage of developer docs

public/manifest.json, vite.config.ts
https://excalidraw.com/apple-touch-icon.png is 180x180, not 256x256.
=> fix: Icon size in manifest

README.md, dev-docs/docs/@excalidraw/excalidraw/faq.mdx
**PR Summary**:
PR updates links to the excalidraw-app which was moved in PR #6987 from `src/excalidraw-app` to `excalidraw-app`. PR also contains a small type fix (same file).
=> fix: update links to excalidraw-app

src/frame.ts
While we're finding ways to move away from relying on `selectedElementIds`, this simple check avoid unnecessary geometry calls to check if the given element is in a frame, which actually improves the perf quite significantly.
=> perf: improve element in frame check

src/data/blob.ts, src/data/index.ts
Turns out we're still awaiting canvas creation when exporting to clipboard as PNG, which makes it fail on Safari in some specific cases (e.g. when exporting canvas containing an image). It's unclear why it was previously working in Safari at all.
=> fix: ensure `ClipboardItem` created in the same tick to fix safari

dev-docs/docs/codebase/frames.mdx, src/actions/actionDuplicateSelection.tsx, src/components/App.tsx, src/data/restore.ts, src/element/binding.ts, src/frame.ts, src/renderer/renderScene.ts
fix https://github.com/excalidraw/excalidraw/issues/6749
The idea is that we want arrows to be able to cross frames. Investigating that, it seems better if bound arrows (either start/end binding is set) to not be part of frames at all.
I'm sure I've skipped some cases.
New rules:
> An arrow can be a child of a frame only if it has no binding (either start or end) to any other element, regardless of whether the bound element is inside the frame or not.
>
> This ensures that when an arrow is bound to an element outside the frame, it's rendered and behaves correctly.
> 
> Therefore, when an arrow (that's a child of a frame) gets bound to an element, it's automatically removed from the frame.
> 
> Bound-arrow is duplicated alongside a frame only if the arrow start is bound to an element …
=> feat: remove bound-arrows from frames

excalidraw-app/components/ExportToExcalidrawPlus.tsx, excalidraw-app/index.tsx, src/actions/actionExport.tsx, src/components/JSONExportDialog.tsx, src/components/ToolButton.tsx
**Description:**
This pull request addresses a user flow issue by adding functionality to close the dialog box when the "Save to Disk" action is performed. 
**Issue:**
More information about the issue can be found on the following GitHub issue created by [@starlove54](https://github.com/starlove54): [excalidraw/excalidraw#7156](https://github.com/excalidraw/excalidraw/issues/7156)
**Changes Made:**
I have made this PR in accordance with the issue mentioned above. Prior to this change, when a user clicked the "Save to Disk" button, the dialog box for "Save to" was not disappearing, resulting in a suboptimal user experience. This pull request resolves this issue by adding the functionality to close the dialog box upon clicking the "Save to Disk" button.
**How to Test:**
To test this change, …
=> feat: Closing of "Save to.." Dialog on Save To Disk

dev-docs/docs/codebase/frames.mdx, src/actions/actionDuplicateSelection.tsx, src/components/App.tsx, src/data/restore.ts, src/element/binding.ts, src/frame.ts, src/renderer/renderScene.ts
Reverts excalidraw/excalidraw#7157
fix https://github.com/excalidraw/excalidraw/issues/7182
Introduced too many breaking changes for frames. We'll need to redesign.
=> revert: remove bound-arrows from frames

src/data/__snapshots__/transform.test.ts.snap, src/data/transform.test.ts, src/data/transform.ts, src/packages/excalidraw/.size-limit.json, src/packages/excalidraw/CHANGELOG.md
Pull out the transform api related changes in https://github.com/excalidraw/excalidraw/pull/6920 to this PR
=> feat: regenerate ids by default when using transform api and also update bindings by 0.5px to avoid possible overlapping

src/actions/actionClipboard.tsx, src/actions/manager.tsx, src/clipboard.test.ts, src/clipboard.ts, src/components/App.tsx, src/components/ContextMenu.tsx, src/constants.ts, src/locales/en.json, src/scene/export.ts, src/setupTests.ts, src/tests/__snapshots__/contextmenu.test.tsx.snap, src/tests/clipboard.test.tsx, src/tests/contextmenu.test.tsx, src/tests/flip.test.tsx, src/tests/helpers/polyfills.ts, src/tests/test-utils.ts, src/utils.ts
- prefer `text/plain` over `text/html` for JSON and text-only HTML pastes
- fix parsing spreadsheets (regressed)
- made parsing clipboard event and copying to system clipboard more robust
- as such, removed the in-memory clipboard hack as it's low likelihood we'll need it
- reintroduced copy/cut/paste actions to contextmenu on all platforms and browsers. Firefox still has problems with `paste`, but users can enable through a flag (they'll be notified).
=> feat: make clipboard more robust and reintroduce contextmenu actions

src/element/textWysiwyg.test.tsx
this test case was a sibling of `describe()` block that also rendered `<App/>`. Maybe that's the issue, maybe not :).
EDIT: guess not
=> test: disable flaky test

src/hooks/useCreatePortalContainer.ts
Technically not a remount, but it trashed any imperatively rendered DOM nodes we do inside modals, and  this also fixes the annoying animation restarting e.g. when changing theme while modal is open.
=> fix: dialog remounting on className updates

src/components/Dialog.scss, src/components/Dialog.tsx, src/components/Modal.scss
fix https://github.com/excalidraw/excalidraw/issues/7232
Modal/Dialog components are fullscreen so they need to use viewport instead of editor breakpoints.
=> fix: make modal use viewport breakpoints

src/actions/actionCanvas.tsx
#7188 
The shortcut `H` for Hand tools doesn't filter out the `ALT` key presses.
This PR adds the filter on the Hand tools shorcut.
* Other shortcuts from `actionCanvas.tsx`  doesn't exclude the `ALT`  and might also need this filter
* The `CTRL` key press should probably also be filtered out
=> fix: Fixes the shortcut collision between "toggleHandTool" and "distributeHorizontally"

src/actions/actionGroup.tsx
factored out from https://github.com/excalidraw/excalidraw/pull/7256 and slightly modified
=> fix: perf issue when ungrouping elements within frame

src/components/App.tsx, src/components/LayerUI.tsx, src/components/MobileMenu.tsx
If you activate pen mode by touching the screen with a pen, currently there is no way to disable it because onPenModeToggle calls the function with an event argument which is interpreted as a force true.
=> fix: Can't toggle penMode off due to missing typecheck in togglePenMode

src/scene/export.ts
Before this fix, if appState.frameRendering.endabled is set to false the export will omit the frame but include the frame name.
=> fix: exportToSvg to honor frameRendering also for name not only for frame itself

src/components/App.tsx, src/cursor.ts
Fixes:
- when inserting image using the image file picker, the image-preview cursor was being reset 
- in the same flow, the image was being added to frame that was currently in the center of viewport at time of file picker open. This is incorrect, and it should add the to frame on pointerdown only.
=> fix: image insertion bugs

excalidraw-app/index.tsx, src/components/Actions.tsx, src/components/App.tsx, src/components/LayerUI.tsx, src/components/MobileMenu.tsx, src/constants.ts, src/data/blob.ts, src/errors.ts, src/locales/en.json, src/packages/excalidraw/CHANGELOG.md, src/packages/excalidraw/example/App.tsx, src/packages/excalidraw/index.tsx, src/types.ts
fix https://github.com/excalidraw/excalidraw/issues/4831
Disables `image` tool/image insertion when `props.UIOptions.tools.image = false`.
Non-goals:
- doesn't affect tool keyboard shortcuts -> if image tool is disabled, there'll be a hole in the numeric shortcuts:
- does not disable importing `.excalidraw` files that contain images. We may add support for disabling later after we decide on API and what should happen.
=> feat: support disabling image tool

dev-docs/docs/@excalidraw/excalidraw/development.mdx, package.json
The `prerelease` script was conflicting with `release` hence I have updated the scripts so going forward these scripts can be used directly
=> chore: update release scripts

package.json
Additionally, vercel was also warning about using `>=18.0.0` for node version so that would also be gone with this.
=> build: use caret for specifying node version to avoid major upgrades automatically

src/components/App.tsx
fix https://github.com/excalidraw/excalidraw/issues/7233
=> feat: change frame resizing behavior

src/actions/actionCanvas.tsx
This PR slightly improves the behaviour of the `zoomToFit` function when called with the `fitToViewport` flag. It now accounts for the presence of the sidebar when it is open.
One particular issue it addresses is in E+ when clicking on a slide preview in the presentation/frames sidebar. Right now, clicking on a slide/frame preview does centre the frame on the scene but it does not account for the sidebar being open so the centering happens relative to the appWidth and not appWidth - sidebarWidth.
With this PR, the centering will now happen relative to the actually visible canvas area. (The PR should also account for RTL orientation too when the sidebar is on the left.)
=> fix: make zoomToFit fitToViewport account for sidebar

src/element/bounds.ts
Since we've recently stopped updating arrow labels, we don't invalidate Bounds cache for labels when container is moved. This is causing bugs when checking for visibility and such.
This PR is a hotfix to ignore cache for bound text. Proper fix after proper analysis.
=> fix: disable caching bounds for arrow labels

dev-docs/docs/introduction/contributing.mdx
This closes issue #7388.
Removed changelog instructions as they are not needed anymore. The changelog is automatically updated and doesn't need to be updated manually. 
Regards,
Vaibhav Shukla
=> docs: changelog instruction removed from docs

packages/excalidraw/components/App.tsx, packages/excalidraw/tests/__snapshots__/move.test.tsx.snap, packages/excalidraw/tests/__snapshots__/multiPointCreate.test.tsx.snap, packages/excalidraw/tests/linearElementEditor.test.tsx, packages/excalidraw/tests/move.test.tsx, packages/excalidraw/tests/multiPointCreate.test.tsx, packages/excalidraw/utils.ts
When moving the mouse on the canvas, the interactive canvas will re-render because `isShallowEqual` return `false` as the `snapLines` are two empty arrays. 
It's unnecessary to re-render just because mouse moves, so I added a condition to filter out this condition.
=> fix: empty snapLines arrays would cause re-render

packages/excalidraw/components/App.tsx, packages/excalidraw/emitter.ts, packages/excalidraw/global.d.ts, packages/excalidraw/types.ts, packages/excalidraw/utils.ts
Refactored setting/tearing down of event listeners to use an emitter with the a combination of a thin wrapper for removing the listeners to allows us to do both in the same step => simpler and more robust.
- Allows us to not implement stable callbacks in order to be able to remove the listener later.
- Fixed a case where we forgot to unsub one listener (`document.fonts`).
=> refactor: editor events sub/unsub refactor

packages/excalidraw/components/App.tsx, packages/excalidraw/constants.ts
On `touchstart` we were preventing the default for non-android devices, which prevented focus on drawing-tablet devices (Wacom) when touching canvas with stylus in pen mode.
This PR now prevents the default only on iOS devices.
Needs testing on Android tablets. /cc @zsviczian
=> fix: drawing-tablet stylus touch events being prevented

packages/excalidraw/components/App.tsx
This PR makes embeddables render lazily, not rendering them until they first appear in viewport.
Pros:
- faster init load and less traffic in cases where you don't land on canvas where all embeds are immediately visible, or you never even scroll to all the embeds on canvas in a session
Cons:
- Slower initially-visible-to-rendered transition
- in cases where preloading all embeds if desirable (e.g. presentations), this is a deoptimization
If the cons prove too bad, we could investigate hybrid solution to improve both the above while keeping (some of) the benefits.
/cc @zsviczian
=> feat: render embeds lazily

excalidraw-app/collab/Collab.tsx, packages/excalidraw/components/App.tsx, packages/excalidraw/components/canvases/InteractiveCanvas.tsx, packages/excalidraw/components/canvases/StaticCanvas.tsx, packages/excalidraw/example/App.tsx, packages/excalidraw/reactUtils.ts, packages/excalidraw/utils.ts
Decouple the `react` and `react dom` imports from utils.ts which led to importing `React` and `ReactDom` into utils package - more details [here](https://keybu.com/l/69d3c20bfdfd76ae6b42/creating-esm-bundle-for-excalidraw-utils)
for #7500
=> fix: decouple react and react-dom imports from utils and make it treeshakeable

dev-docs/docs/@excalidraw/excalidraw/api/props/ui-options.mdx
Remove extra space after "prop".
=> docs: fix extra space in UIOptions/tools

packages/excalidraw/element/dragElements.ts
fixes a bug where if a text container (non-arrow) is part of a group that's a member of a frame and you translate the frame, it won't translate the bound text.
=> fix: translating frames containing grouped text containers

packages/excalidraw/package.json
`nextjs` build fails as it expects the default export should be last one
=> fix: move default to last so its compatible with nextjs

dev-docs/docs/@excalidraw/excalidraw/api/props/props.mdx
The "canvas actions" is linked to nonexistent anchor "canvasactions".
The UIOptions page has the anchor, so I changed the link target to the UIOptions page.
=> docs: fix "canvas actions" link in Props page

packages/excalidraw/components/Sidebar/SidebarTrigger.scss
In some language and some component width, characters in the upper right "library" label become overlapped and they look bad.
I added `white-space: nowrap;` style to prevent this and make the full word be shown.
=> fix: Prevent the library label from being collapsed

packages/excalidraw/components/App.tsx, packages/excalidraw/data/index.ts, packages/excalidraw/frame.ts, packages/excalidraw/scene/export.ts, packages/excalidraw/tests/scene/export.test.ts
if you export a single frame that has other-frame children overlapping with it, it used to incorrectly export those as well.
=> fix: exporting frame-overlapping elements belonging to other frames

packages/excalidraw/scene/export.ts
inexplicably removed in https://github.com/excalidraw/excalidraw/pull/7577
=> fix: revert `mapElementIds` flag removal

packages/excalidraw/constants.ts, packages/excalidraw/element/transformHandles.ts, packages/excalidraw/renderer/renderScene.ts
`tranformHandles` is a pure JS file but its importing a constant `DEFAULT_SPACING` which leads to importing `react-dom` so we can move this constant to a `constants.ts` instead - that way it would be semantically more correct as well.
=> fix: don't bundle react-dom when importing from transformHandles

packages/excalidraw/actions/actionBoundText.tsx, packages/excalidraw/element/containerCache.ts, packages/excalidraw/element/textElement.ts, packages/excalidraw/element/textWysiwyg.test.tsx, packages/excalidraw/element/textWysiwyg.tsx
The cache can be improved by creating closure but I am not sure we should be doing it now since we might end up refactoring textWysWyg hence I left it as is.
For context the below import leads to importing `react-dom`👇
```js
import { getElementBounds } from "../excalidraw/element/bounds";
```
`textElement` uses the below imports from `textWysWyg`
```
import {
resetOriginalContainerCache,
updateOriginalContainerCache,
} from "./textWysiwyg";
```
which ultimately leads to importing `react-dom` hence breaking the chain at `textElement` and moving the caching logic so decoupled the caching to `containerCache.ts`
=> fix: decouple container cache logic to containerCache.

packages/excalidraw/CHANGELOG.md, packages/excalidraw/components/App.tsx, packages/excalidraw/index.tsx, packages/excalidraw/types.ts
closes https://github.com/excalidraw/excalidraw/issues/7617
So the doc mentioned the prop `onPointerUp` but it was never added in the package hence adding it now.
Thanks @Soliden-96 for the report
=> feat: support onPointerUp prop

packages/excalidraw/components/App.tsx, packages/excalidraw/element/Hyperlink.tsx, packages/excalidraw/element/embeddable.ts, packages/excalidraw/element/types.ts
for #7500 
```js
import {getEmbedLink} from "../element/embeddable";
```
The above import results in :point_down: 
So `getEmbedLink` uses `t` function which results in importing `react`, `jotai` and all the locales. Since its a pure JS util, it shouldn't be dependent on `t`, instead the function should just return whether to show warning and the caller will be responsible to show the warning. 
Hence I have moved the responsibility of showing `warning` to caller and instead just return `warning` as a boolean. Should `warning` be renamed to `showWarning` so its more semantic ?
=> fix: make getEmbedLink independent of t function

packages/excalidraw/data/filesystem.ts, packages/excalidraw/data/index.ts
New filesystem API requires to be called within ~5 second of user action. This results in failure on permissions when the canvas is large enough that the export takes longer.
Can be worked around by passing a promise into the filesystem API instead of awaiting it first.
fix https://github.com/excalidraw/excalidraw/issues/7277
fix https://github.com/excalidraw/excalidraw/issues/7456
fix https://github.com/excalidraw/excalidraw/issues/7646
tested on Chrome, Safari (legacy fs), Brave (legacy fs), Firefox (legacy fs)
=> fix: file save timing out with big file sizes

packages/excalidraw/components/App.tsx
When cursor is inside the editor container we don't want browsers to interpret panning gestures as "go back/forward in history". This is often happening a lot on MacOS Chrome.
Disabling `gesture-behavior-x` when pointer inside editor container seems to fix it for Chrome. Safari seems to ignore it, but it doesn't manifest the same buggy behavior (though you can still trigger the history gesture when over editor UI, which is annoying).
=> fix: prevent panning to trigger history on macos chrome

excalidraw-app/App.tsx, excalidraw-app/components/ExportToExcalidrawPlus.tsx, packages/excalidraw/actions/actionClipboard.tsx, packages/excalidraw/actions/actionExport.tsx, packages/excalidraw/appState.ts, packages/excalidraw/components/App.tsx, packages/excalidraw/components/ImageExportDialog.tsx, packages/excalidraw/components/LayerUI.tsx, packages/excalidraw/components/ProjectName.tsx, packages/excalidraw/constants.ts, packages/excalidraw/data/index.ts, packages/excalidraw/data/json.ts, packages/excalidraw/data/resave.ts, packages/excalidraw/tests/excalidraw.test.tsx, packages/excalidraw/types.ts
for #7500 
```js
import { getDefaultAppState } from "../appState";
```
The above import results in 👇
Since `getDefaultAppState` is using `t` for computing default value of `name`, it ends up importing all `locales`, `react` and `jotai` as well. 
This is a default state and should be independent of `t`. So we can stop using `t` in `getDefaultAppState`. Allowing `t` to be `nullable` and created a function `getAppName` in `App.tsx` which is used through out the app to get the ap  name and exposed via the `excalidrawAPI` as well so host can use it as well.
This way the code stays simple and less error prone compared to just allowing the `t` to be `empty string` and the dependency of `t` is also removed from `getDefaultState`
=> fix: remove t from getDefaultAppState and allow name to be nullable

packages/excalidraw/components/App.tsx, packages/excalidraw/components/ImageExportDialog.tsx, packages/excalidraw/components/TTDDialog/common.ts, packages/excalidraw/data/blob.ts, packages/excalidraw/data/index.ts
for #7500 
Removing the dependency of `t` in the functions in `blob.ts` so that locales don't get bundled. 
I am handling the error messages in caller where needed.
=> fix: remove dependency of t in blob.ts

dev-docs/docs/@excalidraw/excalidraw/integration.mdx
docs: type error in integration documentation.
=> docs: type mistake in integration of excalidraw

dev-docs/docs/@excalidraw/excalidraw/integration.mdx
A closing angle bracket was missing in a code sample.
```javascript 
<div style={{height:"500px", width:"500px"}}
<Excalidraw />
</div>
```
```javascript 
<div style={{height:"500px", width:"500px"}}>
<Excalidraw />
</div>
```
=> docs: add missing closing angle bracket in integration.mdx 

.gitignore, packages/utils/package.json, scripts/buildUtils.js
Here are my rough notes - https://keybu.com/l/69d3c20bfdfd76ae6b42/esm-bundle-for-excalidraw-utils
working example - https://djfq22.csb.app/, if you want to test use `@excalidraw/utils@0.1.3-test4`
First lets look at how the **UMD** build was as well  **~5mb**👇
Lets look at how the **ESM** build would have looked prior to refactorings **~4mb**👇
The below is the **browser production ESM build** with **dependencies** bundled **~200kb**
The below is the **raw ESM production build** without any **dependencies** bundled - **~110kb**
So overall the bundle size has reduced from **5mb to 200kb** when dependencies are bundled and reduced by more **100kb** when dependencies are not bundled
=> build: create ESM build for utils package 🥳

packages/excalidraw/CHANGELOG.md, packages/excalidraw/element/textElement.ts
- Changed Assistant metrics to the corrrect ones from OS/2 table
- Adding more information about font metrics
- Adding branded types to avoid future mistakes
=> fix: correcting Assistant metrics

excalidraw-app/App.tsx, excalidraw-app/app_constants.ts, excalidraw-app/data/LocalData.ts, excalidraw-app/data/localStorage.ts, packages/excalidraw/CHANGELOG.md, packages/excalidraw/components/App.tsx, packages/excalidraw/data/library.ts, packages/excalidraw/element/index.ts, packages/excalidraw/index.tsx, packages/excalidraw/locales/en.json, packages/excalidraw/queue.test.ts, packages/excalidraw/queue.ts, packages/excalidraw/types.ts, packages/excalidraw/utility-types.ts, packages/excalidraw/utils.ts
- change library data source from LocalStorage to IndexedDB (to get around the 5MB limit. We could compress instead, but it might be a better idea to future proof this).
- support `useHandleLibrary(opts.adapter)` adapter that handles both loads and saves. Saves are now safer by only adding/removing actually inserted/deleted elements.
- support `useHandleLibrary(opts.migrationAdapter)` to migrate between stores during init.
- on persisting updates to storage, library items are now added/removed individually. This makes data persistence much safer in case of race conditions or initialization issues.
- saves/loads are queued to reduce race conditions.
unrelated:
- initial library load is now using the `merge` strategy so that there aren't race conditions when installing libraries
```ts
const …
```
=> feat: store library to IndexedDB & support storage adapters

packages/excalidraw/package.json, yarn.lock
Upgrading the package has the below fixes/features 👇🏻 , Ref - https://github.com/excalidraw/mermaid-to-excalidraw/pull/46
=> feat: upgrade mermaid-to-excalidraw to 0.3.0

excalidraw-app/index.html, excalidraw-app/package.json, excalidraw-app/vite.config.mts, yarn.lock
Regressed since Vite migration.
Note that unlike previously (Webpack) we need to:
- not interpolate the variable using `%var%` when checking inside conditionals (and not check against string values, at least for true/false 🤷‍♂️)
- typecheck its existence using `typeof` operator first
=> fix: ejs support in html files

packages/excalidraw/components/App.tsx
fixes: #7858 
....
problem was when using "noopener noreferrer", window.open returns null
...
according to this: https://mathiasbynens.github.io/rel-noopener
doing newWindow.opener = null; should do same as adding "noopener noreferrer"
or maybe we can do window.open(url, target, "noopener noreferrer");
=> fix: external link not opening

packages/excalidraw/renderer/staticScene.ts
fix https://github.com/excalidraw/excalidraw/issues/7897
The issue was while we're pre-filtering out the text element being editing, I was retrieving the current container's bound text from the scene elements map, not the filtered elements map, which resulted in always returning the text even if it was not meant to be rendered.
=> fix: double text rendering on edit

excalidraw-app/App.tsx, excalidraw-app/collab/Collab.tsx, excalidraw-app/collab/Portal.tsx, excalidraw-app/data/FileManager.ts, excalidraw-app/data/index.ts, excalidraw-app/tests/collab.test.tsx, packages/excalidraw/CHANGELOG.md, packages/excalidraw/actions/actionHistory.tsx, packages/excalidraw/actions/types.ts, packages/excalidraw/components/App.tsx, packages/excalidraw/element/linearElementEditor.ts, packages/excalidraw/index.tsx, packages/excalidraw/store.ts, packages/excalidraw/tests/history.test.tsx, packages/excalidraw/tests/packages/events.test.tsx, packages/excalidraw/types.ts
Introduced breaking change in `updateScene` API due to the added `Store` component as part of the #7348. Specifically, `sceneData` property `commitToHistory: boolean` was replaced with `storeAction: StoreActionType`.
Additional small improvements:
* Stabilises `Store` methods, internal API & public API (i.e. introduced `commit`)
* Avoids potential concurrency issues due to `updateScene` modifying store before already scheduled store actions execute
* Fixes slight issues with `AppState` in shared scenes (collab)
=> feat: expose `StoreAction` in relation to multiplayer history

packages/excalidraw/actions/actionFlip.ts, packages/excalidraw/components/App.tsx, packages/excalidraw/element/binding.ts, packages/excalidraw/tests/binding.test.tsx
fix https://github.com/excalidraw/excalidraw/issues/6459
This PR fixes not just #6459 but also addresses the related issue of CTRL/CMD & dragging arrow drag points disconnect ALL arrows in the scene.
Create two diamonds and two boxes, then connect one diamond to the other diamond via an arrow, followed by connecting one box to the other via another arrow.
1) Press the CTRL/CMD key and drag the end marker of the arrow connecting the boxes somewhere ✅ 
2) The box previously connected to the end of the arrow is now disconnected ✅ 
3) When the box connected with the start of the arrow is drag moved, it can be seen that the arrow did not remain connected ❌ 
4) When any of the diamonds are drag moved, the arrow connected to them did not remain connected to either of them ❌ 
1) Press the …
=> fix: CTRL/CMD & arrow point drag unbinds both sides (#6459)

packages/excalidraw/store.ts
Use a more stable Reflect API (since 2016 in major browsers) for handling `observedAppState`, instead of `Object.hasOwn` (since 2021 in major browsers).
The next step is possibly polyfilling the APIs (such as Reflect) through `@vitejs/plugin-legacy` and it's specifiers https://www.npmjs.com/package/@vitejs/plugin-legacy#polyfill-specifiers.
Can I use Reflect? https://caniuse.com/mdn-javascript_builtins_reflect
Fixes #7957
=> fix: use Reflect API (2016) instead of Object.hasOwn (2021)

packages/excalidraw/components/App.tsx, packages/excalidraw/tests/__snapshots__/history.test.tsx.snap, packages/excalidraw/tests/__snapshots__/regressionTests.test.tsx.snap, packages/excalidraw/tests/history.test.tsx
Selecting freedraw tool is recorded, so that undo does not select previously selected elements, for details check #5437.
fix https://github.com/excalidraw/excalidraw/issues/5437
=> feat: record freedraw tool selection to history

package.json, yarn.lock
Using the vitest testrunner extension allows quick test debugging and running for VSCode users, but it requires a vitest version higher than 1.2.
=> chore: Bump vitest to 1.5.3 to support VSCode vitest Extension

vitest.config.mts
This addition would allow code coverage plugins in most IDEs to pick up the results. Having a visual indicator in IDEs should nudge people toward covering their code with tests.
=> chore: Add lcov coverage output to vitest

packages/excalidraw/components/CommandPalette/CommandPalette.tsx
- wrong regex character set
- make explicitly case insensitive (though currently unnecessary)
=> fix: command palette filter

excalidraw-app/App.tsx, packages/excalidraw/locales/en.json
Adds "Install Excalidraw locally (PWA)" command to the command palette for better discoveribility.
Docs: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeinstallprompt_event
Note that the command will appear to users only if certain PWA install criteria are met (see https://web.dev/articles/install-criteria).
=> feat: add install-PWA to command palette

packages/excalidraw/components/App.tsx, packages/excalidraw/components/LayerUI.tsx, packages/excalidraw/components/canvases/InteractiveCanvas.tsx, packages/excalidraw/components/canvases/StaticCanvas.tsx, packages/excalidraw/element/mutateElement.ts, packages/excalidraw/element/resizeElements.ts, packages/excalidraw/element/textWysiwyg.tsx, packages/excalidraw/scene/Fonts.ts, packages/excalidraw/scene/Renderer.ts, packages/excalidraw/scene/Scene.ts
The main issue was that we were not guaranteeing the text element object got a renewed reference, which then didn't update the scene, not renewing the `versionNonce` or the elements array, so the `renderStaticScene` didn't run (also the canvas cache would likely not get invalidated).
=> fix: font not rendered correctly on init

packages/excalidraw/element/textWysiwyg.tsx, packages/excalidraw/tests/__snapshots__/linearElementEditor.test.tsx.snap
Regressed in https://github.com/excalidraw/excalidraw/pull/7693/files#diff-8434e9bb8c4453273416b4a429cec4cbbf022cba0ef72d05001639d2ef00dc00L231
=> fix: re-introduce wysiwyg width offset

packages/excalidraw/scene/export.ts
The property name is `VITE_PKG_VERSION` (not `PKG_VERSION`)
Resolves #7984
=> fix: correctly resolve the package version

package.json
For `corepack` https://nodejs.org/api/corepack.html.
Won't affect those not using corepack, though it should still yell at people if they try to use non-v1 yarn in a project with `packageManger` specifying v1 yarn, which is good.
We should also investigate migrating to yarn v4.
=> build: specify `packageManager` field

packages/excalidraw/actions/actionHistory.tsx, packages/excalidraw/tests/__snapshots__/history.test.tsx.snap, packages/excalidraw/tests/history.test.tsx
This PR addresses the bug: When exiting view mode the undo/redo buttons are disabled even though their stacks aren't empty.
Fixes https://github.com/excalidraw/excalidraw/issues/7948.
The default constructor is getting called which has values `isUndoStackEmpty` equal to `true` and `isRedoStackEmpty` equal to `true`.
Passing the function(from class `History`) which checks for whether the stacks are empty or not fixes the issue.
https://github.com/excalidraw/excalidraw/assets/53573748/ff57b133-8d9b-4574-8e69-e59b60177b85
https://github.com/excalidraw/excalidraw/assets/53573748/329588d3-b6bb-4eea-8fe8-d9faa6810da1
=> fix: undo/redo when exiting view mode

packages/excalidraw/components/App.tsx
Honestly not sure if this is the root cause of the problem and thus will fix it, but it makes sense to me. We'll see.
Assumption: chrome frees up memory wherever it can (they're quite aggressive lately), and one such thing is clearing the canvas context when the tab is inactive.
If true, this PR rerender the canvas on focus.
=> feat: rerender canvas on focus

packages/excalidraw/change.ts, packages/excalidraw/fractionalIndex.ts, packages/excalidraw/tests/__snapshots__/history.test.tsx.snap, packages/excalidraw/tests/__snapshots__/regressionTests.test.tsx.snap, packages/excalidraw/tests/fractionalIndex.test.ts
Re-generate fractional indices even though they could be already valid, otherwise we might end up (due to automatic fallback) modifying elements that were not moved, in cases where number of elements were moved from top to bottom.
=> fix: always re-generate index of defined moved elements

packages/excalidraw/data/restore.ts
fix https://github.com/excalidraw/excalidraw/issues/8058
https://excalidraw-git-dwelle-restore-dims-from-points-excalidraw.vercel.app#json=O9jEqYDAmq3NqgWtoy8a0,XvJyVF9uM2lhrgv7Gsbi9g
=> fix: restore linear dimensions from points

packages/excalidraw/components/App.tsx, packages/excalidraw/mermaid.ts, packages/excalidraw/tests/MermaidToExcalidraw.test.tsx, packages/excalidraw/tests/clipboard.test.tsx, packages/excalidraw/tests/helpers/mocks.ts
On paste, check if text is maybe a mermaid diagram. If so, try to parse it and insert as mermaid. Falls back to regular paste.
WIP
=> feat: paste as mermaid if applicable

packages/excalidraw/CHANGELOG.md, packages/excalidraw/components/App.tsx, packages/excalidraw/types.ts
- Allow `initialData` to be a function.
- Update `api/props/` and `api/props/initialdata` docs
The function is being called twice in development builds because of [strict mode](https://legacy.reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) but it does not impact production builds.
close: #8107
=> feat: allow props.initialData to be a function

packages/excalidraw/components/Stats/Angle.tsx, packages/excalidraw/components/Stats/Dimension.tsx, packages/excalidraw/components/Stats/DragInput.tsx, packages/excalidraw/components/Stats/FontSize.tsx, packages/excalidraw/components/Stats/MultiAngle.tsx, packages/excalidraw/components/Stats/MultiDimension.tsx, packages/excalidraw/components/Stats/MultiFontSize.tsx, packages/excalidraw/components/Stats/MultiPosition.tsx, packages/excalidraw/components/Stats/Position.tsx, packages/excalidraw/components/Stats/index.tsx, packages/excalidraw/components/Stats/stats.test.tsx, packages/excalidraw/components/Stats/utils.ts, packages/excalidraw/renderer/renderElement.ts, packages/excalidraw/scene/types.ts
This PR fixes two major issues with Stats panel:
- `blur` event fires _after_ we potentially update selected elements and rerender the Stats component with new `selectedElements` which will result in the `blur` updating incorrect elements.
Steps to repro:
1. create two differently sized rectangles
2. select rectangle A, and focus `width` input, and edit width to `100` (let's say the orig was `200`)
3. click on rectangle B to select it
4. rectangle B's width will get updated instead of rectangle A
- similar thing happens on unmount, where in special cases it can update elements even when no edit/focus has ever happened:
1. create rectangle & text (not bound to it), and deselect both
2. select rectangle
3. select text
4. click on canvas
What will happen is the text's dimensions will get …
=> fix: stats state leaking & race conds

packages/excalidraw/element/linearElementEditor.ts, packages/excalidraw/tests/linearElementEditor.test.tsx
The `LinearElementEditor.movePoints()` function incorrectly calculates the offset for local linear element points when multiple targetPoints are provided, one of those target points is index === 0 AND the other points are moved in the negative direction, and ending up with negative local coordinates.
=> fix: Incorrect point offsetting in LinearElementEditor.movePoints()

packages/excalidraw/element/binding.ts, packages/excalidraw/tests/binding.test.tsx
Using ALT/OPT + drag to clone does not transfer the bindings (or leaves the duplicates in place of the old one , which are also not bound).
=> fix: Binding after duplicating is now applied for both the old and duplicate shapes

excalidraw-app/components/LanguageList.tsx
Found a small code smell, the import of " ../../packages/excalidraw/i18n" was duplicated.
=> chore: Consolidate i18n import in LanguageList component

dev-docs/docs/@excalidraw/excalidraw/api/utils/export.mdx
In the exportToCanvas() example, there's a mistake about the prop use to store the excalidrawAPI in the state. Currently, ref is passed to the <Excalidraw /> component and it is wrong because in a bare React project, an error is fired saying you can't pass ref to a function component (React 18). Thus we want to store the excalidrawAPI in a useState object so we need to use the excalidrawAPI prop instead. Else this example won't work for someone who follows the documentation.
=> docs: fixed exportToCanvas() doc example using wrong prop

.github/workflows/test.yml
=> ci: upgrade gh actions checkout and setup-node to v4

packages/excalidraw/components/App.tsx, packages/excalidraw/components/TTDDialog/common.ts, packages/excalidraw/package.json, yarn.lock
changelog in https://github.com/excalidraw/mermaid-to-excalidraw/pull/68
To summarize
* Now the host can pass a config param to `parseMermaidToExcalidraw` which earlier only support fontSize.
* Additonally fontSize is renamed to `themeVariables.fontSize` and type is changed from `number` to `string` to keep in sync with mermaid config.
* I have removed the config since we already pass default params which are same as passed here.
=> feat: upgrade mermaid-to-excalidraw to v1.1.0

packages/excalidraw/renderer/renderElement.ts
Fixes #8234
The problematic code was introduced in #3512 to fix 'shuffle' bug. (https://github.com/excalidraw/excalidraw/pull/3512/commits/d9af6099f54587102fc57a8e069eb1797b783b21) 
At the time, the code was fine. The commit also had corresponding code in `generateElementCanvas()` that generated canvas drawing with floored x and y as base. Which was why `x1 = Math.floor(x1)` needed to be used in `drawElementFromCanvas()`,  when copying over the rendered element from that canvas.
But in #4357, the `Math.floor` code in `generatedElementCanvas()` was removed, yet it did not remove the matching code from `drawElementFromCanvas()` as well. Which resulted in the freehand drawing being rendered to a slightly wrong position.
=> fix: freedraw jittering

excalidraw-app/app-language/language-detector.ts, packages/excalidraw/fractionalIndex.ts
Thanks for PR #8205, it effectively resolved my previous issue. However, there was a minor typo. 
This PR also addresses other minor corrections I discovered over the past few days.
=> chore: Correct Typos in Code Comments

packages/excalidraw/mermaid.test.ts, packages/excalidraw/mermaid.ts
- support `graph`
- make sure text starts with mermaid type (sans inline config)
=> feat: improve mermaid detection on paste

packages/excalidraw/data/reconcile.ts, packages/excalidraw/fractionalIndex.ts, packages/excalidraw/global.d.ts, packages/excalidraw/scene/Scene.ts, packages/excalidraw/tests/fractionalIndex.test.ts
- hidden behind `window.DEBUG_FRACTIONAL_INDICES`
- disabled by default for OSS (should get enabled for E+)
=> feat: ability to debug the state of fractional indices

excalidraw-app/index.html, packages/excalidraw/components/FontPicker/FontPickerList.tsx, packages/excalidraw/fonts/ExcalidrawFont.ts, packages/excalidraw/fonts/assets/fonts.css, packages/excalidraw/fonts/index.ts, packages/excalidraw/fonts/metadata.ts, packages/excalidraw/global.d.ts, packages/excalidraw/scene/export.ts, scripts/woff2/woff2-vite-plugins.js, setupTests.ts, vercel.json
Adds the possibility to specify an array of base URLs in `EXCALIDRAW_ASSET_PATH`, so that we could register font faces for our bundled fonts with multiple fallbacks, in case of unreachable resources due to:
- network restrictions (vpns, corporate policies, firewalls etc.)
- ad blocker #8290 (only solves first-party if an appropriate filter is set to allow such fonts)
- offline mode
- unknowns
Excalidraw-app now has three font URLs for our bundled fonts:
- DO CDN
- Root domain `excalidraw.com` [_fallback_]
- UNPKG CDN [_fallback_]
Fonts are fetched in the order specified above (with automatic fallbacks), for both:
1. `window.document.fonts.load` API
- out-of-the-box fallbacks due to multiple sources specified as part of the FontFace object in a CSS familiar `@font-face#source` manner
2. …
=> feat: multiple fonts fallbacks

packages/excalidraw/components/App.tsx, packages/excalidraw/frame.ts, packages/excalidraw/scene/export.ts
Host apps might not be coupling z-index order with semantic frame order, so this automatic naming is adding confusion.
=> feat: remove automatic frame naming

packages/excalidraw/fonts/index.ts
https://github.com/excalidraw/excalidraw/pull/8286#issuecomment-2260963865
=> fix: skip registering font faces for local fonts

packages/excalidraw/data/reconcile.ts, packages/excalidraw/fractionalIndex.ts, packages/excalidraw/scene/Scene.ts, packages/excalidraw/tests/fractionalIndex.test.ts
- throttle the validation on scene updates and during reconciliation, to be performed at most once every minute (so that we could sleep a bit more calmly)
- ignore error logs when it's expected to fail (~ in `tests` and `syncMovedIndices`)
=> fix: throttle fractional indices validation

packages/excalidraw/element/binding.ts
Resolves #8315, introduced in #8185
=> fix: Duplicating arrow without bound elements throws error

package.json
- `rm:build` - removes build/dist folders from `excalidraw-app` and `packages/*`
- `rm:node_modules` - removes `node_modules` from `excalidraw-app` and `packages/*`
- `clean-install` - runs `rm:node_modules` & `yarn`
skips docs, examples etc.
Supporting non-bash compatible enviros was a non-goal.
=> build: add `rm:build`, `rm:node_modules` & `clean-install` scripts

dev-docs/docs/@excalidraw/excalidraw/api/props/props.mdx
Fixes some small typos I came across while reading the docs.
=> docs: fix typos in props.mdx

.eslintignore
to unstuck eslint checks when example apps are built
=> build: add example apps `public` and vite `dev-dist` to eslintignore

.dockerignore, Dockerfile, excalidraw-app/scripts/woff2-vite-plugins.js, excalidraw-app/vite.config.mts, scripts/woff2/woff2-vite-plugins.js, vitest.config.mts
Docker build is failing CI since the new fonts release
```
#12 0.732 ✘ [ERROR] Could not resolve "../scripts/woff2/woff2-vite-plugins"
#12 0.732 
#12 0.732     vite.config.mts:8:35:
#12 0.732       8 │ ... { woff2BrowserPlugin } from "../scripts/woff2/woff2-vite-plugins";
#12 0.732         ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#12 0.732 
#12 0.747 failed to load config from /opt/node_app/excalidraw-app/vite.config.mts
```
Solution: Moved the script imported from `excalidraw-app/vite.config.mts` into the `excalidraw-app/scripts` directory, thus making it accessible by `yarn --cwd ./excalidraw-app build:app:docker`
=> fix: Docker build in CI

.github/workflows/test.yml, packages/excalidraw/tests/MermaidToExcalidraw.test.tsx
- removes running `test.yml` in PRs as running coverage report is enough (which runs tests itself)
- fix flaky test (missed `expect` in `waitFor()`)
=> test: skip test.yml in PRs

packages/excalidraw/actions/actionDeleteSelected.tsx, packages/excalidraw/actions/actionDuplicateSelection.tsx, packages/excalidraw/actions/actionFlip.ts, packages/excalidraw/actions/actionHistory.tsx, packages/excalidraw/actions/actionProperties.tsx, packages/excalidraw/change.ts, packages/excalidraw/components/App.tsx, packages/excalidraw/components/Stats/MultiDimension.tsx, packages/excalidraw/components/Stats/utils.ts, packages/excalidraw/element/binding.ts, packages/excalidraw/element/dragElements.ts, packages/excalidraw/element/linearElementEditor.ts, packages/excalidraw/element/resizeElements.ts, packages/excalidraw/element/routing.test.tsx, packages/excalidraw/element/routing.ts, packages/excalidraw/history.ts, packages/excalidraw/tests/history.test.tsx, packages/excalidraw/tests/linearElementEditor.test.tsx
Removing scene from the entire elbow arrow feature per discussion on [history.ts and change.ts](https://github.com/excalidraw/excalidraw/pull/8299#discussion_r1698443081).
Marcel's reasoning motivating this PR:
_1. The scene contains old elements before the history increment is applied. Instead, elements here are new/next instances with already applied history increments. Thus, technically speaking, relying on the previous scene.elements (as that seems to be the only reason the scene is used here), instead of the next elements seems confusing (supposing not indented?) and could cause some unexpected issues in the future.
2. Another reason to have a change module scene-independent is its foreseen server-side usage (i.e. for versioning purposes), as server-side we won't likely have the …
=> chore: Refactor and remove scene from elbow arrow generation

packages/excalidraw/tests/zindex.test.tsx, packages/excalidraw/zindex.ts
Fix for #8295
Bug occurs because `getTargetIndexAccountingForBinding()` is able to return an index greater than the initial index even when `direction` is `left`, and similarly able to return an index smaller than the initial index even when `direction` is `right`.
This incorrect `targetIndex` causes elements to be duplicated when manipulating the `elements` array in `shiftElementsByOne()`.
First PR so I hope this is helpful and I haven't done anything wrong. Thanks!
=> fix: z-index change by one causes app to freeze

packages/excalidraw/element/flowchart.test.tsx, packages/excalidraw/tests/helpers/colorize.ts, setupTests.ts
/cc @ryan-di just a heads up on the latest API in tests
=> fix: missing `act()` in flowchart tests

packages/excalidraw/components/App.tsx
we were preventing event due to flowchart keybindings even when inside inputs (e.g. wysiwyg)
=> fix: disable flowchart keybindings inside inputs

packages/excalidraw/renderer/renderElement.ts
When trying to render from a 0-width or 0-height canvas, e.g. for small elements when zoomed out a lot. Right now happens primarily (perhaps exclusively) for container labels.
Instead of just preventing the `drawImage` call, I'm opting to not generate and populate the canvas cache at all so safe on memory and cpu.
=> fix: drawing from 0-dimension canvas

packages/excalidraw/components/Stats/Dimension.tsx
remove unused `originalElementsMap` parameter in `packages\excalidraw\components\Stats\Dimension.tsx`
=> chore: remove unused parameter

packages/excalidraw/components/App.tsx, packages/excalidraw/element/textWysiwyg.tsx
Fix #7947
There doesn't seem to be a nice way to incorporate tab stops in the Canvas API, so this replaces tab characters with spaces when editing an existing text element, and also when creating new text elements via pasting (non-Excalidraw-JSON) text.
=> fix: text content with tab characters act different in view/edit

dev-docs/docs/@excalidraw/mermaid-to-excalidraw/api.mdx
Script provided [here](https://docs.excalidraw.com/docs/@excalidraw/mermaid-to-excalidraw/installation#usage) contains an error in the function call, which was called `parseMermaid`
`parseMermaid` should be `parseMermaidToExcalidraw` as per the imported function.
=> docs: Update function call in @excalidraw/mermaid-to-excalidraw 

packages/excalidraw/components/App.tsx
Fixes: Keyboard arrow keys stop to move elements when the group includes an elbow arrow #8387
Having looked at the code I concluded that this is not a bug, but a too restrictive feature. However, we can make the restriction more targeted/relaxed even without touching the arrow move logic. The keyboard move should only be restricted if the start or end element is not part of the selection.
=> feat: improve elbow arrow keyboard move

packages/excalidraw/components/App.tsx
When passing files in `initialData` to the `@excalidraw/excalidraw` package, the images do not render the first time unless the screen is resized or a scene update is triggered by other actions.
Fixes #8419
Clone the repo and run the following command:
```bash
cd examples/excalidraw/with-script-in-browser && yarn start
```
Observe the `rocket` image not being rendered unless the window is resized or some other action is done on the image.
By creating a `clearImageShapeCache` function and calling it in 2 places: `addFiles` and `initializeScene` fixes this issue. The problem with the original code was that the image cache was not being cleared in the `addFiles` function because `this.scene.getNonDeletedElements()` was returning an empty list. Referenced code: …
=> fix: image rendering issue when passed in `initialData` 

packages/excalidraw/components/App.tsx
fixes: #8489
The solution in #8471 leads to flickering and slow performance when sequentially adding files to a scene.
=> fix: addFiles clears the whole image cache when each file is added - regression from #8471

packages/excalidraw/actions/actionCanvas.tsx, packages/excalidraw/components/App.tsx, packages/excalidraw/components/SearchMenu.tsx, packages/excalidraw/element/newElement.ts, packages/excalidraw/element/sizeHelpers.ts, packages/excalidraw/scene/scroll.ts, packages/excalidraw/types.ts, packages/math/utils.ts
Still not quite happy with the behavior, but I think it's on the right track. Feel free to tweak further.
search for `test` in https://excalidraw-git-dwelle-further-search-zooming-tweaks-excalidraw.vercel.app/#json=3byClZnjTF-kNYYeQRYGb,q5f2AP0mKotRZris1S9CrA
=> fix: improve canvas search scroll behavior further

packages/excalidraw/components/DefaultSidebar.tsx
- fix rendering of `<DefaultSidebar.Triggers/>` (broken by canvas search)
- BREAKING CHANGE: default sidebar triggers are now always merged with host app triggers (rendered through `<DefaultSidebar.Triggers/>`
- BREAKING CHANGE: `<DefaultSidebar.Triggers/>` no longer accepts any props other than `children`
=> fix: default sidebar triggers & behavior

packages/excalidraw/element/textWysiwyg.tsx
=> fix: WYSIWYG editor padding is not normalized with zoom.value

packages/excalidraw/actions/actionFinalize.tsx, packages/excalidraw/components/App.tsx
Fixes: [#2006](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/2006)
If you touch the screen with two fingers when creating a new linear element you can create a multipoint line by adding additional points. There is a complete edit button, but this is disabled during editing of the new element. On a mobile device there is simply no way to exit the line edit mode (unless by chance you find the beginning of the line and you are able to close the loop (if you know about this trick and if you can tap precisely enough). This can be an extremely frustrating UX experience when it happens.
=> fix: Linear element complete button disabled

packages/excalidraw/scene/export.ts
1. When exporting a single frame to PNG, we're effectively exporting with 0 padding, so we shouldn't clip content as it would clip the edges since the frames have a radius.
before: 
after:
2. When exporting to SVG, we were previously not adding radius at all, so we're doing that now in non-single-frame-export cases
=> fix: svg and png frame clipping cases

packages/excalidraw/actions/actionFlip.test.tsx, packages/excalidraw/actions/actionFlip.ts, packages/excalidraw/tests/helpers/api.ts
- flipping a bound (either ending or both) arrow now only flips the arrowheads
- flipping unbound arrow (or when other types are selected alongside) does a regular flip
=> feat: flip arrowheads if only arrow(s) selected

packages/excalidraw/CHANGELOG.md, packages/excalidraw/data/__snapshots__/transform.test.ts.snap, packages/excalidraw/data/transform.test.ts, packages/excalidraw/data/transform.ts
closes https://github.com/excalidraw/excalidraw/issues/8461
=> feat: prefer user defined coords and dimensions over calculated for for frame

packages/excalidraw/components/App.tsx
This PR fixes #8558 (due to race condition)
The issue was consistently happening on MacOS and safari.
I use the same strategy that is use before, with the use of `flushSync()`. We should update this in finalize action, like with via keyboard trigger
=> fix: text disappearing on edit (#8558)

packages/excalidraw/actions/actionClipboard.tsx, packages/excalidraw/actions/shortcuts.ts, packages/excalidraw/components/HelpDialog.tsx, packages/excalidraw/tests/__snapshots__/contextmenu.test.tsx.snap
(we need to reconsider this shortcut)
=> fix: remove export-to-clip-as-svg shortcut for now

packages/excalidraw/actions/actionHistory.tsx, packages/excalidraw/keys.test.ts, packages/excalidraw/keys.ts
This PR fixes #8003 
Main idea is that it is probably incorrect to use actual keys when detecting undo and redo actions, because some languages does not have `Z` or `Y` letters in their layouts. For example, in some cyrillic layouts there is letter `Я` instead of `Z`. `event.key` for it is `Я` and `event.code` is `KeyZ`. Because of this I believe key codes should be used instead of actual keys.
I'm stil figuring out how to fix tests for this change, so PR is in draft mode. I will appreciate if contributors that are more familiar with this project will look at my approach while I'm doing this.
@kirillrocks @Dementir you described this problem in the original issue. Please let me know if this PR fixes it for you
=> fix: undo/redo action for international keyboard layouts

excalidraw-app/index.html
There is already a `<meta name="description" />` tag in the upper **Primary Meta Tags** section, it seems the latter `<meta name="description" />` inside **General tags** section is duplicated.
=> chore: remove duplicated meta tag

excalidraw-app/collab/Collab.tsx, excalidraw-app/data/FileManager.ts, excalidraw-app/data/LocalData.ts, excalidraw-app/data/firebase.ts, packages/excalidraw/components/App.tsx, packages/excalidraw/data/blob.ts, packages/excalidraw/data/encode.ts, packages/excalidraw/data/image.ts, packages/excalidraw/element/image.ts, packages/excalidraw/scene/export.ts, packages/excalidraw/tests/export.test.tsx, packages/excalidraw/types.ts, packages/utils/utils.unmocked.test.ts
fix https://github.com/excalidraw/excalidraw/issues/8729
The core of the fix is rather simple: we need to normalize SVG string of images being added to the editor (`props.initialData`/`ExcalidrawAPI.addFiles`) because since image cropping (https://github.com/excalidraw/excalidraw/pull/8613) we're relying on correct image `naturalWidth`/`naturalHeight` which we parse from `<svg>` `viewBox` if it's not set natively on the `<svg>` element.
Old images stored previously weren't being normalized necessarily, or if the image added to the editor has `DataURL` encoded from a different source other than the Excalidraw editor.
---
The rest of the PR boilerplate is allowing for this restoring to take place. 
- we needed a sync version of `getDataURL()` to not change API too much.
As part of this, I …
=> fix: restore svg image DataURL dimensions

packages/excalidraw/components/App.tsx, packages/excalidraw/constants.ts, packages/excalidraw/fonts/Fonts.ts, packages/excalidraw/scene/export.ts
Safari does not always trigger "loadingdone" event (actually it rarely does) and thus in most cases we end up with unloaded fonts on init and paste. It's especially annoying when there are tons of font faces to load, such as with the recent CJK support and half or even less characters remain unloaded.
The solution is loading all the necessary font faces manually in Safari, both on init and when pasting elements.
Fixes https://github.com/excalidraw/excalidraw/issues/3229
_Other improvements_
- Consolidates font faces logic in export under the `Fonts` class
- Concurrently loads 10 font faces at a time (loading all 250 font faces at the same time likely isn't a good idea)
_TODO_
Follows #8530
=> fix: load font faces in Safari manually

packages/excalidraw/element/textElement.test.ts, packages/excalidraw/element/textElement.ts
Noticed a horizontal layout shift due to browsers not trimming all the whitespaces from the trailing line, but instead trying to fit all that fit into the set width. This PR does just that.
https://github.com/user-attachments/assets/eebab03c-311b-45d6-8d56-31d02e0bdb6a
https://excalidraw-git-mrazator-fix-trailing-line-whi-52f7d9-excalidraw.vercel.app/#json=22W0TOX7IKI0JqoWYwJ7q,efKJZCfTGt0ak8B7cTbF6g
Follows #8530
=> fix: fix trailing line whitespaces layout shift

packages/excalidraw/element/textWysiwyg.tsx, packages/excalidraw/tests/__snapshots__/linearElementEditor.test.tsx.snap
Removing the padding, as IIRC we have added it only due to overflowing cursive-like glyphs in Bangers, which we did not ship in the end.
Might re-introduce a smarter version once we have `italics`, i.e. based on `actual width - advance width`. Once there, we shall also investigate, how to keep the padding-like buffer, as we need to keep the width as advance width due to wrapping.
We could probably also just remove the padding once the text starts to overflow. However, the whole behavior of overflowing WYSIWYG is not ideal.
Fixes #8743
=> fix: text pushes UI due to padding

.env.production, excalidraw-app/vite.config.mts
The `build:preview` `start:production` scripts has been hanging recently on my machine. On further debugging I found that its the `vite build` script that hangs and thats due to the `eslint` script in the `vite-plugin-checker`
I still need to debug why the `eslint` script hangs the build, probably it takes too much time to run and eventually hangs. But nevertheless this script is for dev mode so we shouldn't be running it in production build.
This script shouldn't ideally run in production mode since it depends on an env variable `VITE_APP_ENABLE_ESLINT` which is not set in `.env.production`, however when logging the envVars this variable was logged as `true`. 
There were 2 reasons why the variable was set to `true`
1. We are loading the env vars without specifying the mode and this loads …
=> fix: load env vars correctly and set debug and linter flags to false explicitly in prod mode

packages/excalidraw/components/App.tsx, packages/excalidraw/components/Stats/MultiDimension.tsx, packages/excalidraw/components/Stats/utils.ts, packages/excalidraw/element/binding.ts, packages/excalidraw/element/resizeElements.ts, packages/excalidraw/tests/cropElement.test.tsx, packages/excalidraw/tests/linearElementEditor.test.tsx, packages/excalidraw/tests/resize.test.tsx
updateBoundElements() had a option called `oldSize` which in turn used as the `newSize` for gap calculation. This is confusing and not clear to contributors.
=> fix: Unify binding update options for `updateBoundElements()`

packages/excalidraw/components/App.tsx, packages/excalidraw/components/SearchMenu.tsx
Chrome and Firefox started to report warnings because some long-running event handlers are not explicitly marked active.
=> fix: Make some events expllicitly active to avoid console warnings

packages/excalidraw/components/ConfirmDialog.tsx
fixes #8840
**Questions**
- ~Could we do even better? (without forcing sync update). We likely don't want all functions on the DOM elements to wait for `flushSync`.~ unsure, we would need to find out what is the intermediate step causing this, but there are no usable chrome logs when running in debug
- ~Why is the container not yet fully mounted (might be non-intentional)?~ seems mounted in the DOM, but still crashes
- ~Why does it happen only on Chromium & macOS?~ might be some specific chromium bug (does not crash in newer 132.0.6796.0), though didn't find anything similar reported (weird)
- ~Why does not React automatically queue the call instead of crashing in the middle?~ likely for better granularity / control, though IMO it shouldn't just crash the tab
=> fix: Flush pending DOM updates before .focus()

packages/excalidraw/data/blob.ts
Fixes: #8792
The issue is that the `image-blob-reduce` library relies on a `pica` version that has to specify the `alpha` option to preserve the alpha channel. Specifically the `reduce.toBlob(file, options)` function, should have an `alpha: true` option.
https://github.com/excalidraw/excalidraw/blob/b5652b8e36abcc813478c65cdbe248aae774e5db/packages/excalidraw/data/blob.ts#L332.
@Mrazator
=> fix: fixed image transparency by adding alpha option to preserve image alpha channel

packages/excalidraw/clipboard.ts, packages/excalidraw/constants.ts, packages/excalidraw/data/blob.ts
This PR fixes the issue with pasting images from the clipboard using the right-click context menu. Previously, users were unable to paste copied images from the clipboard when using the right-click action, which hindered the usability of the application. While pasting with `Ctrl + V` was functioning correctly, the right-click custom paste option was not working as intended. This fix addresses that issue and improves the overall user experience.
Fixes #8826.
=> fix: right-click paste for images in clipboard (Issue #8826)

packages/excalidraw/components/App.tsx, packages/excalidraw/data/restore.ts
There was a case where `state.editingFrame` wasn't reset if you scrolled the editing frame outside of viewport. This coupled with the host app potentially persisting it to storage, and then you leaving and someone else deleting the frame itself resulted in permanent lock into frame editing state.
=> fix: robust `state.editingFrame` teardown

packages/excalidraw/element/image.ts
In the case of this example image downloaded from flaticon the current normalize function fails to identify width and height resulting in a distorted image upon import.
`viewBox="0 0 209.761 162.085"`
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 209.761 162.085" fill="#000000">
<path d="M79.779 72.857a14.494 14.494 0 0 1-.929-1.47c-1.02-1.565-2.043-3.312-2.889-5.216L68.1 94.907l25.256-3.33zm-20.536 52.945c-4.976 0-9.452-2.515-12.144-6.394L19.441 140.01c-5.425 4.042-6.547 11.717-2.506 17.143a12.234 12.234 0 0 0 9.834 4.933 12.2 12.2 0 0 0 7.309-2.427l49-36.5c.188-.14.366-.292.545-.443l-22.429 2.958c-.645.085-1.302.128-1.951.128z"/>
<circle cx="187.259" cy="27" r="22.5" transform="rotate(-34.51 187.265 26.924)"/>
<path d="m200.687 …
```
=> fix: normalizeSVG width and height from viewbox when size includes decimal points

packages/excalidraw/data/url.test.tsx, packages/excalidraw/data/url.ts, packages/excalidraw/element/embeddable.ts, packages/excalidraw/tests/utils.test.ts, packages/excalidraw/utils.ts
This change doesn't solve anything at the moment, it's just being more safe.
It's a BREAKING CHANGE in that it escapes more characters now, which carries over to element link (and related) sanitization where we use this util as well.
=> feat: make HTML attribute sanitization stricter

packages/excalidraw/data/filesystem.ts, packages/excalidraw/data/index.ts
- **when export image as png file**
→ saved as `*` file
- **so I added mimeTypes**
→ saved as `image/png` file
___
> The same goes for exporting image as svg
=> feat: add mimeTypes on file save

packages/excalidraw/data/index.ts
=> feat: reintroduce `.excalidraw.png` default when embedding scene

packages/excalidraw/components/FixedSideContainer.scss
fix https://github.com/excalidraw/excalidraw/issues/8983
Regressed in https://github.com/excalidraw/excalidraw/pull/8942 due to random CSS concatenation issue on build or something.
=> fix: z-index clash in mobile UI

scripts/buildPackage.js
- re-added top level await for each package build 
- unknown what recently caused this to fail?
=> fix: package build fails on worker chunks 

packages/excalidraw/components/App.tsx
The mouse cursor shape immediately changes when changing tools by keyboard shortcut.
resolves #8210
=> fix: change cursor by tool change immediately

packages/excalidraw/actions/actionDeleteSelected.tsx, packages/excalidraw/groups.ts, packages/excalidraw/tests/__snapshots__/regressionTests.test.tsx.snap
This PR changes how frame deletion works. Previously, we deleted the frame and its children. Now we're only deleting the frame and keeping the children, selecting them instead.
This way it's much easier to remove children from the frame instead of having to do it through context menu in two steps.
If people want to delete both the frame and its children both, they can just hit delete twice.
(Un)related, fixed (or rather, improved, as a proper fix will take more work) selection on removing the last group member when editing a group.
=> feat: do not delete frame children on frame delete

packages/excalidraw/components/ToolButton.tsx
defaultProps were [removed in React 19](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops).
=> refactor: remove `defaultProps`

packages/excalidraw/frame.ts, packages/excalidraw/renderer/staticScene.ts
Part 1 of improving frame performance.
There are two types of perf optimizations that we can make to frames:
- rendering optimizations
- operation optimizations
This PR addresses the first kind by reducing the number of unnecessary frame clippings in the render step, which is quite expensive. To elaborate,
- if an individual element is completely in a frame, there's no need to apply clipping to it
- if an element is completely outside the frame, but is part of a group that has some elements that should be clipped, then it should be clipped as well
=> perf: reduce unnecessary frame clippings

packages/excalidraw/actions/actionFrame.ts, packages/excalidraw/frame.ts
When drag creating a new frame, do not add a partial group to it.
When wrapping a selected partial group in a frame however, do add it to the wrapping frame. But we should separate it from the previous containing group. 
close #9008
=> fix: adding partial group to frame

packages/excalidraw/actions/actionProperties.tsx
- fixes the [issue](https://github.com/excalidraw/excalidraw/issues/8798) where arrows bound to text elements do not update their positions or bindings when the font size of the text elements is changed. 
- The solution ensures that the `updateBoundElements` method is called after the text elements are updated, synchronizing the arrows accordingly.
- Let me know if you’d like further refinement or if there’s anything else you’d like to add!
https://github.com/user-attachments/assets/a5518d58-18f6-4095-aa35-7c0157fc09c2
=> fix: update elbow arrow on font size change #8798

packages/excalidraw/actions/actionAlign.tsx, packages/excalidraw/align.ts
- This PR addresses the [issue](https://github.com/excalidraw/excalidraw/issues/8833) of misaligned arrows bound to elements during alignment operations. The solution involves integrating the updateBoundElements method to ensure arrows and their associated elements are aligned correctly.
- Verified alignment behavior for elements and their bound arrows in various scenarios, including grouped elements and overlapping cases.
- Let me know if you’d like further refinement or if there’s anything else you’d like to add!
https://github.com/user-attachments/assets/ae05d91a-94ce-44f0-b98f-38a30c1df27d
=> fix: align arrows bound to elements excalidraw#8833

packages/excalidraw/element/flowchart.ts
This update addresses Excalidraw issue #9045 by refining the appearance of nodes within the diagram. The changes include adjustments to the stroke style, opacity, and fill style for the new node and the subsequent nodes. These improvements enhance the visual clarity and consistency across the diagram elements.
**Screenshot:**
**Additional Note:** not only rectangle but all the nodes under `ExcalidrawFlowchartNodeElement` type will show same behaviour of consistency
thanks for the opportunity to contribute
=> fix: excalidraw issue #9045 flowcharts: align attributes of new node

packages/excalidraw/components/App.tsx
reverts `flushSync` introduced in #8763 to attempt to fix https://github.com/excalidraw/excalidraw/issues/8859
=> fix: remove flushSync to fix flickering

packages/excalidraw/data/url.test.tsx, packages/excalidraw/data/url.ts, packages/excalidraw/element/embeddable.ts, packages/excalidraw/tests/utils.test.ts, packages/excalidraw/utils.ts
fix #9051
(the overly strict sanitization of HTML entities was unnecessary)
=> fix: hyperlinks html entities

packages/excalidraw/components/App.tsx, packages/excalidraw/components/LibraryMenu.tsx, setupTests.ts
When the sidebar is docked with a sufficiently large library open, there is some perceptible lag and choppiness during canvas interaction. This PR aims to improve performance and UX in this scenario.
My first impulse + our offline discussion led me to investigate any unnecessary re-renders. Something that both `LibraryMenu` and `LibraryMenuContent` are guilty of. By memoizing both components, I managed to mitigate this. With it, I also improved the `pending elements calculation`, as in the current version, rotation and resizing do not update the preview element correctly. These optimizations helped somewhat, but did not fully resolve the performance issue.
My next thought was that it might be the large number of (potentially) complex SVGs in the sidebar that may be the culprit. One …
=> perf: Improved pointer events related performance when the sidebar is docked with a large library open

packages/excalidraw/actions/actionBoundText.tsx, packages/excalidraw/actions/actionTextAutoResize.ts, packages/excalidraw/components/App.tsx, packages/excalidraw/components/SearchMenu.tsx, packages/excalidraw/data/restore.ts, packages/excalidraw/data/transform.ts, packages/excalidraw/element/dragElements.ts, packages/excalidraw/element/newElement.ts, packages/excalidraw/element/resizeElements.ts, packages/excalidraw/element/textElement.test.ts, packages/excalidraw/element/textElement.ts, packages/excalidraw/element/textMeasurements.ts, packages/excalidraw/element/textWrapping.ts, packages/excalidraw/element/textWysiwyg.tsx, packages/excalidraw/fonts/Fonts.ts, packages/excalidraw/index.tsx, packages/excalidraw/renderer/renderElement.ts, packages/excalidraw/renderer/staticSvgScene.ts, packages/excalidraw/tests/clipboard.test.tsx
Allow custom text metrics providers, useful for overriding the width calculation algorithm when canvas API is not available / desired.
Later whole `textMeasurements` module might get treated as a separate chunk or be separated into a standalone package.
=> feat: custom text metrics provider

packages/excalidraw/element/elbowArrow.ts, packages/excalidraw/element/types.ts
`structuredClone` is [not universally supported](https://caniuse.com/?search=structuredclone) yet.
~~While stringifying and parsing JSON as a polyfill isn't quite correct, in the context we're using it for it suffices (until it won't and all hell will break lose, alas).~~
fix https://excalidraw.sentry.io/issues/6291795739/events/b61abd6a973244b9909afbe62dfdc6e0/
=> fix: stop using structuredClone

packages/excalidraw/components/MobileMenu.tsx
This PR puts the redo and undo button under the same div and fixes their position to the right in mobile view so that they look grouped together and stay on the same spot
1. Open the Excalidraw board on mobile or open the mobile view via inspector.
2. Look at the bottom bar
[✅ ] Code follows the project’s coding style.
[✅ ] Tested the feature in different scenarios.
[✅ ] No console errors or warnings.
fixes #9110
=> feat: grouped together Undo and Redo buttons on mobile

packages/excalidraw/element/binding.ts
If a `fixedPoint` binding is too close to 0.5 in some edge cases it can oscillate between positions at every frame. This PR fixes that by adding an offset to the binding points at element restore (reload)
=> fix: Fix elbow arrow fixed binding on restore

packages/excalidraw/data/restore.ts
temp fix for https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/2254
=> fix: cleanup legacy `element.rawText` (obsidian)

packages/excalidraw/components/PropertiesPopover.tsx, packages/excalidraw/package.json, yarn.lock
Fixes "Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release."
=> fix: React 18 element.ref was accessed error

package.json, yarn.lock
- bumping `vite-plugin-checker` fails on https://github.com/fi3ework/vite-plugin-checker/issues/401
- unrelated to the PR: added `@babel/preset-env` to fix CI deployment (doesn't reproduce locally)
=> chore: bump vite@6.x

packages/excalidraw/element/binding.ts, packages/excalidraw/element/elbowArrow.test.tsx, packages/excalidraw/element/elbowArrow.ts, packages/excalidraw/element/flowchart.ts, packages/excalidraw/element/mutateElement.ts, packages/excalidraw/tests/resize.test.tsx
Currently dragging elbow arrows (not start or end points!) still attempts to bind, which this PR changes to no binding in drag.
Currently elbow arrows also re-bind the opposite endpoint when the other endpoint is dragged, which can rebind to the incorrect element with overlapping binding gaps.
Also fixes #9130
=> fix: Do not rebind undragged elbow arrow endpoint

dev-docs/docs/@excalidraw/excalidraw/development.mdx, dev-docs/docs/@excalidraw/excalidraw/installation.mdx, dev-docs/docs/@excalidraw/excalidraw/integration.mdx, dev-docs/package.json, dev-docs/src/theme/ReactLiveScope/index.js, dev-docs/yarn.lock, examples/with-script-in-browser/index.html, examples/with-script-in-browser/package.json, examples/with-script-in-browser/vercel.json, packages/excalidraw/CHANGELOG.md, packages/excalidraw/README.md, packages/excalidraw/components/Actions.tsx, packages/excalidraw/components/SearchMenu.scss, packages/excalidraw/components/welcome-screen/WelcomeScreen.scss, packages/excalidraw/env.cjs, packages/excalidraw/fonts/ExcalidrawFontFace.ts, packages/excalidraw/vite-env.d.ts, yarn.lock
Test & merge after publishing 0.18.0 to npm.
**Done**
- search for "fiddle", it uses 0.18-rc version
- codesandbox is our with-script-in-browser example, which should not use rc but "*" in package.json
- there are some EXCALIDRAW_ASSETS_PATHS which point to "0.18.-rc" and they should point to latest
- the codesandbox url should be moved to master branch (currently contains `tree/mrazator/release-v18/examples/with-script-in-browser`)
**Todo**
=> chore: post publish docs & examples changes

packages/excalidraw/actions/actionDuplicateSelection.tsx, packages/excalidraw/element/dragElements.ts
fix https://github.com/excalidraw/excalidraw/issues/9272#issuecomment-2726817896
This isn't really a fix. Instead we prevent dragging if you duplicate via `ctrl-D` during drag. A proper fix would be to update `pointerDownState.originalElements` with the duplicated elements, but it's not easily doable in current implem.
I checked other apps, and they do a mix of preventing drag (figma/figjam/miro) and weird behavior (eraser, tldraw).
=> fix: elements offset incorrectly when action-duplicated during drag

packages/math/point.ts
Fix spell error 'Roate' -> 'Rotate'.
Tiny change. :)
❤️
=> fix: 'Rotate' spell error

packages/excalidraw/element/textWysiwyg.tsx
fix for - CTRL + S opens browser 'save as html webpage' if a text field is selected instead of saving as .excalidraw #9281
=> feat: add keyboard shortcut to save file in text 

.env.development, excalidraw-app/App.tsx, excalidraw-app/collab/Collab.tsx
when developing collab code, the constant preventing of unload on save is annoying, so adding a way to disable that during dev.
To do that, add this to your `.env.development.local` file:
```
VITE_APP_DISABLE_PREVENT_UNLOAD=true
```
=> feat: allow to disable preventUnload in dev

packages/excalidraw/components/Stats/DragInput.scss, packages/excalidraw/components/Stats/Stats.scss, packages/excalidraw/components/Stats/index.tsx
simplify and fix padding/margin inconsistencies
Before:
After:
=> feat: tweak stats panel input styles

packages/excalidraw/components/ColorPicker/ColorPicker.scss, packages/excalidraw/components/Range.scss, packages/excalidraw/css/styles.scss
- inactive buttons bg removed
- slightly thinner panel
- removed border from color swatches
before/after (light mode):
before/after (dark mode):
=> feat: tweak properties panel styling

packages/excalidraw/package.json, yarn.lock
bumped the version to latest stable that includes react ^19 as peerDependecy.
This fixes peerDependency issues, as reported in #9253
After updating the package in package.json -> I ran `yarn` in the projects root folder to update yarn.lock as well.
fixes #9253
=> chore: bump @radix-ui/react-tabs version to 1.1.3

packages/excalidraw/actions/actionBoundText.tsx
Closes #9334 
Updated `actionWrapTextInContainer` action's predicate, to check if **some** of the selected elements are textual
=> feat: add container to MORE multiple text elements

packages/common/src/constants.ts, packages/excalidraw/data/index.ts
SVG images exported by Excalidraw contain only the `<svg>` element representing the image, without specifying a DOCTYPE or the XML preamble for older tools to recognize and render images correctly.
This adds that preamble to increase compatibility, following recommendations from SVG 1.1: https://www.w3.org/TR/SVG11/struct.html
I tested this E2E. Exported image:
* Before:
```
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 856.1042326312408 424.0772977941177"  ...
```
* After:
```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 856.1042326312408 424.0772977941177"  ...
```
Also verified that loading the new SVG …
=> fix: Add DOCTYPE and XML preamble in exported SVG documents

packages/element/tests/duplicate.test.tsx, packages/excalidraw/tests/__snapshots__/history.test.tsx.snap, packages/excalidraw/tests/helpers/api.ts, packages/excalidraw/tests/helpers/ui.ts, packages/excalidraw/tests/test-utils.ts, setupTests.ts
When tests reuse Pointer instances (mouse), the pointer clientX/clientY position leak between tests, so `mouse.down/up` and other methods that work on deltas instead of absolute positions can work with incorrect positions.
=> fix: duplication tests pointer state leaking between tests

packages/excalidraw/components/App.tsx, packages/excalidraw/scene/scrollbars.ts, packages/excalidraw/scene/types.ts
- scrollbar rendering (width/height + x/y offsets) weren't quite correct
- when dragging the scrollbar, we need to multiply the pointer delta by a factor that accounts for how much the canvas should scroll. 
Note that the new calculation is fully correct only for when viewport is within the scene (elements) bbox. If it extends outside, there's some accumulating error that I didn't figure out, so we'll need to fix that some time later.
=> fix: scrollbar rendering and improve dragging

packages/excalidraw/animated-trail.ts
Fixes issue #9413 where the laser pointer trail disappears immediately on pointerup.
- Delay trail removal to allow smoother pointer fade-out.
=> fix: laser pointer trail disappearing on pointerup (#9413)

packages/excalidraw/components/HelpDialog.tsx, packages/excalidraw/locales/en.json
Related Issue Id: #9463 
- Document Tab and Shift+Tab usage for shape cycling
=> docs: added shape cycling shortcut in helper dialog

packages/element/src/resizeElements.ts
Fixes #9451 
In `resizeSingleElement` method, move `updateBoundElements` call after `handleBindTextResize` call, because `handleBindTextResize` might alter the element's size
=> fix: when resizing element, update bound elements after final size of element is determined

packages/excalidraw/components/Stats/utils.ts
from https://github.com/excalidraw/excalidraw/pull/9433
=> fix: do not translate bound elements twice

package.json, packages/common/package.json, packages/element/package.json, packages/excalidraw/package.json, packages/math/package.json, packages/utils/package.json, yarn.lock
fixes #9459 
Added rimraf to devDependencies
Replaced `rm -rf` with `rimraf`
=> fix: use rimraf instead of rm -rf

README.md
The tongue emoji seems kind of weird to have for Localization. This PR replaces it with "🌐".
=> docs: replace tongue emoji with globe emoji

packages/excalidraw/actions/actionProperties.tsx, packages/excalidraw/components/ColorPicker/ColorInput.tsx, packages/excalidraw/components/ColorPicker/ColorPicker.scss, packages/excalidraw/components/ColorPicker/ColorPicker.tsx, packages/excalidraw/components/ColorPicker/CustomColorList.tsx, packages/excalidraw/components/ColorPicker/Picker.tsx, packages/excalidraw/components/ColorPicker/PickerColorList.tsx, packages/excalidraw/components/ColorPicker/ShadeList.tsx, packages/excalidraw/components/ColorPicker/TopPicks.tsx, packages/excalidraw/components/ColorPicker/colorPickerUtils.ts, packages/excalidraw/components/ColorPicker/keyboardNavHandlers.ts, packages/excalidraw/components/icons.tsx, packages/excalidraw/locales/en.json
- shows empty active color when there's no common color for selected elements:
- fixed focus states so that tab and alt-color picking works in most case user would expect when the popup is open
=> feat: show empty active color if no common color

packages/excalidraw/components/App.tsx, packages/excalidraw/snapping.ts
when ctrl-alt lasso selecting:
- don't attempt to snap to objects (show snap lines)
- don't immediately select the element under cursor
=> fix: improve ctrl+alt lasso selecting

packages/element/src/embeddable.ts
I'd love to use Excalidraw+ presentations in newsletters, and would love to include surveys in my newsletters.
I have tested the form with and without adding forms.microsoft.com to `ALLOW_SAME_ORIGIN`. The form does not load without whitelisting Microsoft Forms to `ALLOW_SAME_ORIGIN`.
Need to use the embeddable link for Microsoft Forms.
Test link: https://excalidraw-okf0e5ldz-excalidraw.vercel.app/#json=5AXOAgFQjS6FxIY3n8BkX,AYzsvRPpEtBZaRmElPgwrQ
=> feat: allow forms.microsoft.com domain for embeddables

packages/element/src/renderElement.ts, packages/excalidraw/components/hyperlink/helpers.ts, packages/excalidraw/renderer/staticScene.ts
Functionally, the icons are fine—but visually, they’re a bit distracting. At low zoom levels or with non-white backgrounds, the icons remain relatively large and stand out too much.
This PR implements two minor visual improvements:
– Made the icon background transparent
– Gradually reduced icon size when zooming below 100%
sample: https://excalidraw-79ex37zp9-excalidraw.vercel.app/#json=HThLaW9fjg39IzWjMma4e,2WBzrLbSFLWoevVWy_bzzQ
Before/after with a non-white scene color:
Before / after zooming to 10%:
=> feat: transparent link background, scale link icon when zooming to below 100%

packages/excalidraw/components/App.tsx
=> fix: alt + ctrl lasso selected elements not always kept

packages/common/src/font-metadata.ts, packages/excalidraw/wysiwyg/textWysiwyg.test.tsx
- unifies line-height across default fonts into 1.25
Closes #9511
=> fix: unify line height across default fonts

packages/excalidraw/actions/actionProperties.tsx
This PR fixes the bindings for arrowheads. The key `x` was accidentally swapped with `c`.
=> fix: fix keybindings for arrowheads

README.md
Last index was on `17 April 2025`, which makes it a bit out of date now.
Adding the badge should re-index it weekly, according to this popup:
=> chore: Add DeepWiki badge

packages/element/src/linearElementEditor.ts
This updates fixes the https://github.com/excalidraw/excalidraw/issues/9500 ghost point which appear while moving the shape after dragging a point in the line editor.
What's changed :
- In linearElementEditor.ts , handlePointerUp function's return value is updated , two more properties were added to updated
linearElementEditor Element :
{ 
segmentMidPointHoveredCoords: null, 
hoverPointIndex: -1,
}
segmentMidPointHoveredCoords takes care of the all the points apart from edges , 
while hoverPointIndex takes care of the edge points
@dwelle  @ryan-di  @ad1992
=> fix: ghost point issue when moving a shape after dragging a point in the line editor

packages/element/tests/linearElementEditor.test.tsx, packages/excalidraw/components/App.tsx, packages/excalidraw/tests/selection.test.tsx
=> fix: Regression in long press context menu closure

dev-docs/docs/@excalidraw/excalidraw/integration.mdx
This is with reference to [this](https://github.com/excalidraw/excalidraw/issues/9562)
=> docs: added the correct CSS import for nextjs dynamic first import integration example

packages/element/tests/linearElementEditor.test.tsx, packages/excalidraw/components/App.tsx, packages/excalidraw/components/HintViewer.tsx, packages/excalidraw/locales/en.json
- lines (non-arrow) can now enter line editor via `enter` alone
follow-up to https://github.com/excalidraw/excalidraw/pull/9597
=> feat: use `enter` to edit line points & update hints

packages/excalidraw/renderer/helpers.ts, packages/excalidraw/renderer/interactiveScene.ts, packages/excalidraw/tests/__snapshots__/history.test.tsx.snap
window.h used in renderer `helper.ts`
=> fix: Test hook usage in production code

packages/element/src/resizeElements.ts, packages/excalidraw/components/Stats/stats.test.tsx, packages/excalidraw/components/Stats/utils.ts
Refactored & combined resizing a single text into resizing a single element, which allowed us to easily wrap & unwrap a text element in the stats panel
=> feat: wrap texts from stats panel

packages/excalidraw/components/App.tsx
This PR fixes a bug where the Toast component would re-render and reschedule its dismissal timer on every render due to an unstable inline `onClose` handler.
✅ Changes:
- Moved `onClose={() => this.setToast(null)}` to a class method `handleToastClose` to ensure a stable reference.
- Prevents unnecessary re-renders and ensures the toast closes after the intended duration.
Fixes #9714
=> fix(toast): prevent toast from re-rendering and resetting timeout  Fixes #9714

packages/element/src/delta.ts, packages/element/src/store.ts, packages/excalidraw/components/App.tsx, packages/excalidraw/wysiwyg/textWysiwyg.test.tsx
- expose `applyTo` options
- don't commit empty text element (i.e. when losing focus), as it causes redraw issues
=> feat: expose `applyTo` options, don't commit empty text element

packages/excalidraw/components/canvases/StaticCanvas.tsx
The problem was that browsers have some rounding logic when doing `canvas.style.[width|height] = ...` and `canvas.[width|height] = ...`. Hence, with some setups, conditions like [this](https://github.com/excalidraw/excalidraw/blob/d6a934ed196874e50dac498c63e9f2af7c90296d/packages/excalidraw/components/canvases/StaticCanvas.tsx#L54) always returned false. These conditions are there to prevent flickering.
The solution in this PR switches from comparing against the DOM values to comparing against previous values (via `useEffect`).
This PR should fix `flushSync` flickering issues like flickering during alt-duplication and flickering during line editor point addition.
=> fix: Fix the root cause of `flushSync` flickering

packages/common/src/constants.ts
We were breaking runtimes that don't define `navigator.platform` when loading `constants.ts`.
=> fix: calling toLowerCase on potentially undefined `navigator.*` values

packages/element/src/resizeElements.ts, packages/element/src/textElement.ts, packages/element/tests/textElement.test.ts, packages/excalidraw/tests/__snapshots__/history.test.tsx.snap, packages/excalidraw/tests/history.test.tsx, packages/excalidraw/wysiwyg/textWysiwyg.tsx
This PR was done in collaboration with @A-mundanilkunathil and fixes a bug in relation to bound text and it's associated container, where if the text is aligned in any position other than center, rotating the container caused the bound text to rotate around its own central axis instead of rotating around the central axis of the container.
The fix works by:
1. Determining the center points of both the container and the bound text.
2. Applying the container’s rotation angle to the bound text center to obtain a preliminary position.
3. Applying an offset to that preliminary position to determine the correct final placement of the bound text.  
This PR also seems to resolve #5859 where bound text that exceeded the container's maximum height caused the container to extend, but the text itself …
=> fix: bound text rotation across alignments

packages/excalidraw/tests/__snapshots__/history.test.tsx.snap, packages/math/src/curve.ts, packages/math/tests/curve.test.ts
No change in behavior, just a faster numerical method for rounded corners
=> fix: Use analytical Jacobian for curve intersection testing

packages/excalidraw/clipboard.ts, packages/excalidraw/data/blob.ts, packages/excalidraw/data/filesystem.ts, packages/excalidraw/data/json.ts
- make sure that ParsedDataTranferList `file.type` is correctly normalized
- always normalize on `fileOpen`
- support detecting `webp` when normalizing mime type
- do not normalize the same file twice
=> feat: better file normalization

packages/common/src/binary-heap.ts
Small optimization on binary heap sinkDown and bubbleUp functions. On sinkDown, caches node score before loop and only swaps the node in the last step. On bubbleUp, finds the smallest child first, then swap at the end.
Just something I noticed while exploring the repo. Probably won't make a lot of difference, but at scale it might shave a few ms :)
=> fix: small improvement on binary heap implementation

docker-compose.yml
The `version` field in **docker-compose.yml** file is not longer needed since it's deprecated, so it can be removed.
=> build: Docker compose version removed
